insert into city(name,fk_country) values('Buritizeiro (MG)',1);
insert into city(name,fk_country) values('Butiá (RS)',1);
insert into city(name,fk_country) values('Cocal do Sul (SC)',1);
insert into city(name,fk_country) values('Cocalinho (MT)',1);
insert into city(name,fk_country) values('Cocalzinho de Goiás (GO)',1);
insert into city(name,fk_country) values('Cocos (BA)',1);
insert into city(name,fk_country) values('Codajás (AM)',1);
insert into city(name,fk_country) values('Codó (MA)',1);
insert into city(name,fk_country) values('Coelho Neto (MA)',1);
insert into city(name,fk_country) values('Coimbra (MG)',1);
insert into city(name,fk_country) values('Coité do Noia (AL)',1);
insert into city(name,fk_country) values('Coivaras (PI)',1);
insert into city(name,fk_country) values('Colares (PA)',1);
insert into city(name,fk_country) values('Colatina (ES)',1);
insert into city(name,fk_country) values('Colíder (MT)',1);
insert into city(name,fk_country) values('Colina (SP)',1);
insert into city(name,fk_country) values('Colinas (MA)',1);
insert into city(name,fk_country) values('Colinas (RS)',1);
insert into city(name,fk_country) values('Colinas do Sul (GO)',1);
insert into city(name,fk_country) values('Colinas do Tocantins (TO)',1);
insert into city(name,fk_country) values('Colmeia (TO)',1);
insert into city(name,fk_country) values('Colniza (MT)',1);
insert into city(name,fk_country) values('Colômbia (SP)',1);
insert into city(name,fk_country) values('Colombo (PR)',1);
insert into city(name,fk_country) values('Colônia do Gurgueia (PI)',1);
insert into city(name,fk_country) values('Colônia do Piauí (PI)',1);
insert into city(name,fk_country) values('Colônia Leopoldina (AL)',1);
insert into city(name,fk_country) values('Colorado (PR)',1);
insert into city(name,fk_country) values('Colorado (RS)',1);
insert into city(name,fk_country) values('Colorado do Oeste (RO)',1);
insert into city(name,fk_country) values('Coluna (MG)',1);
insert into city(name,fk_country) values('Combinado (TO)',1);
insert into city(name,fk_country) values('Comendador Gomes (MG)',1);
insert into city(name,fk_country) values('Comendador Levy Gasparian (RJ)',1);
insert into city(name,fk_country) values('Comercinho (MG)',1);
insert into city(name,fk_country) values('Comodoro (MT)',1);
insert into city(name,fk_country) values('Conceição (PB)',1);
insert into city(name,fk_country) values('Conceição da Aparecida (MG)',1);
insert into city(name,fk_country) values('Conceição da Barra de Minas (MG)',1);
insert into city(name,fk_country) values('Conceição da Barra (ES)',1);
insert into city(name,fk_country) values('Conceição da Feira (BA)',1);
insert into city(name,fk_country) values('Conceição das Alagoas (MG)',1);
insert into city(name,fk_country) values('Conceição das Pedras (MG)',1);
insert into city(name,fk_country) values('Conceição de Ipanema (MG)',1);
insert into city(name,fk_country) values('Conceição de Macabu (RJ)',1);
insert into city(name,fk_country) values('Conceição do Almeida (BA)',1);
insert into city(name,fk_country) values('Conceição do Araguaia (PA)',1);
insert into city(name,fk_country) values('Conceição do Canindé (PI)',1);
insert into city(name,fk_country) values('Conceição do Castelo (ES)',1);
insert into city(name,fk_country) values('Conceição do Coité (BA)',1);
insert into city(name,fk_country) values('Conceição do Jacuípe (BA)',1);
insert into city(name,fk_country) values('Conceição do Lago Açu (MA)',1);
insert into city(name,fk_country) values('Conceição do Mato Dentro (MG)',1);
insert into city(name,fk_country) values('Conceição do Pará (MG)',1);
insert into city(name,fk_country) values('Conceição do Rio Verde (MG)',1);
insert into city(name,fk_country) values('Conceição dos Ouros (MG)',1);
insert into city(name,fk_country) values('Conceição do Tocantins (TO)',1);
insert into city(name,fk_country) values('Conchal (SP)',1);
insert into city(name,fk_country) values('Conchas (SP)',1);
insert into city(name,fk_country) values('Concórdia (SC)',1);
insert into city(name,fk_country) values('Concórdia do Pará (PA)',1);
insert into city(name,fk_country) values('Condado (PB)',1);
insert into city(name,fk_country) values('Condado (PE)',1);
insert into city(name,fk_country) values('Conde (BA)',1);
insert into city(name,fk_country) values('Conde (PB)',1);
insert into city(name,fk_country) values('Condeúba (BA)',1);
insert into city(name,fk_country) values('Condor (RS)',1);
insert into city(name,fk_country) values('Cônego Marinho (MG)',1);
insert into city(name,fk_country) values('Confins (MG)',1);
insert into city(name,fk_country) values('Confresa (MT)',1);
insert into city(name,fk_country) values('Congo (PB)',1);
insert into city(name,fk_country) values('Congonhal (MG)',1);
insert into city(name,fk_country) values('Congonhas (MG)',1);
insert into city(name,fk_country) values('Congonhas do Norte (MG)',1);
insert into city(name,fk_country) values('Congonhinhas (PR)',1);
insert into city(name,fk_country) values('Conquista (MG)',1);
insert into city(name,fk_country) values('Conquista d''Oeste (MT)',1);
insert into city(name,fk_country) values('Conselheiro Lafaiete (MG)',1);
insert into city(name,fk_country) values('Conselheiro Mairinck (PR)',1);
insert into city(name,fk_country) values('Conselheiro Pena (MG)',1);
insert into city(name,fk_country) values('Consolação (MG)',1);
insert into city(name,fk_country) values('Constantina (RS)',1);
insert into city(name,fk_country) values('Contagem (MG)',1);
insert into city(name,fk_country) values('Contenda (PR)',1);
insert into city(name,fk_country) values('Contendas do Sincorá (BA)',1);
insert into city(name,fk_country) values('Coqueiral (MG)',1);
insert into city(name,fk_country) values('Coqueiro Baixo (RS)',1);
insert into city(name,fk_country) values('Coqueiros do Sul (RS)',1);
insert into city(name,fk_country) values('Coqueiro Seco (AL)',1);
insert into city(name,fk_country) values('Coração de Jesus (MG)',1);
insert into city(name,fk_country) values('Coração de Maria (BA)',1);
insert into city(name,fk_country) values('Corbélia (PR)',1);
insert into city(name,fk_country) values('Cordeiro (RJ)',1);
insert into city(name,fk_country) values('Cordeirópolis (SP)',1);
insert into city(name,fk_country) values('Cordeiros (BA)',1);
insert into city(name,fk_country) values('Cordilheira Alta (SC)',1);
insert into city(name,fk_country) values('Cordisburgo (MG)',1);
insert into city(name,fk_country) values('Cordislândia (MG)',1);
insert into city(name,fk_country) values('Coreaú (CE)',1);
insert into city(name,fk_country) values('Coremas (PB)',1);
insert into city(name,fk_country) values('Corguinho (MS)',1);
insert into city(name,fk_country) values('Coribe (BA)',1);
insert into city(name,fk_country) values('Corinto (MG)',1);
insert into city(name,fk_country) values('Cornélio Procópio (PR)',1);
insert into city(name,fk_country) values('Coroaci (MG)',1);
insert into city(name,fk_country) values('Coroados (SP)',1);
insert into city(name,fk_country) values('Coroatá (MA)',1);
insert into city(name,fk_country) values('Coromandel (MG)',1);
insert into city(name,fk_country) values('Coronel Barros (RS)',1);
insert into city(name,fk_country) values('Coronel Bicaco (RS)',1);
insert into city(name,fk_country) values('Coronel Domingos Soares (PR)',1);
insert into city(name,fk_country) values('Coronel Ezequiel (RN)',1);
insert into city(name,fk_country) values('Coronel Fabriciano (MG)',1);
insert into city(name,fk_country) values('Coronel Freitas (SC)',1);
insert into city(name,fk_country) values('Coronel João Pessoa (RN)',1);
insert into city(name,fk_country) values('Coronel João Sá (BA)',1);
insert into city(name,fk_country) values('Coronel José Dias (PI)',1);
insert into city(name,fk_country) values('Coronel Macedo (SP)',1);
insert into city(name,fk_country) values('Coronel Martins (SC)',1);
insert into city(name,fk_country) values('Coronel Murta (MG)',1);
insert into city(name,fk_country) values('Coronel Pacheco (MG)',1);
insert into city(name,fk_country) values('Coronel Pilar (RS)',1);
insert into city(name,fk_country) values('Coronel Sapucaia (MS)',1);
insert into city(name,fk_country) values('Coronel Vivida (PR)',1);
insert into city(name,fk_country) values('Coronel Xavier Chaves (MG)',1);
insert into city(name,fk_country) values('Córrego Danta (MG)',1);
insert into city(name,fk_country) values('Córrego do Bom Jesus (MG)',1);
insert into city(name,fk_country) values('Córrego do Ouro (GO)',1);
insert into city(name,fk_country) values('Córrego Fundo (MG)',1);
insert into city(name,fk_country) values('Córrego Novo (MG)',1);
insert into city(name,fk_country) values('Correia Pinto (SC)',1);
insert into city(name,fk_country) values('Corrente (PI)',1);
insert into city(name,fk_country) values('Correntes (PE)',1);
insert into city(name,fk_country) values('Correntina (BA)',1);
insert into city(name,fk_country) values('Cortês (PE)',1);
insert into city(name,fk_country) values('Corumbá (MS)',1);
insert into city(name,fk_country) values('Corumbá de Goiás (GO)',1);
insert into city(name,fk_country) values('Corumbaíba (GO)',1);
insert into city(name,fk_country) values('Corumbataí (SP)',1);
insert into city(name,fk_country) values('Corumbataí do Sul (PR)',1);
insert into city(name,fk_country) values('Corumbiara (RO)',1);
insert into city(name,fk_country) values('Corupá (SC)',1);
insert into city(name,fk_country) values('Coruripe (AL)',1);
insert into city(name,fk_country) values('Cosmópolis (SP)',1);
insert into city(name,fk_country) values('Cosmorama (SP)',1);
insert into city(name,fk_country) values('Costa Marques (RO)',1);
insert into city(name,fk_country) values('Costa Rica (MS)',1);
insert into city(name,fk_country) values('Cotegipe (BA)',1);
insert into city(name,fk_country) values('Cotia (SP)',1);
insert into city(name,fk_country) values('Cotiporã (RS)',1);
insert into city(name,fk_country) values('Cotriguaçu (MT)',1);
insert into city(name,fk_country) values('Couto de Magalhães (TO)',1);
insert into city(name,fk_country) values('Couto de Magalhães de Minas (MG)',1);
insert into city(name,fk_country) values('Coxilha (RS)',1);
insert into city(name,fk_country) values('Coxim (MS)',1);
insert into city(name,fk_country) values('Coxixola (PB)',1);
insert into city(name,fk_country) values('Craíbas (AL)',1);
insert into city(name,fk_country) values('Crateús (CE)',1);
insert into city(name,fk_country) values('Crato (CE)',1);
insert into city(name,fk_country) values('Cravinhos (SP)',1);
insert into city(name,fk_country) values('Cravolândia (BA)',1);
insert into city(name,fk_country) values('Criciúma (SC)',1);
insert into city(name,fk_country) values('Crisólita (MG)',1);
insert into city(name,fk_country) values('Crisópolis (BA)',1);
insert into city(name,fk_country) values('Crissiumal (RS)',1);
insert into city(name,fk_country) values('Cristais (MG)',1);
insert into city(name,fk_country) values('Cristais Paulista (SP)',1);
insert into city(name,fk_country) values('Cristal (RS)',1);
insert into city(name,fk_country) values('Cristalândia (TO)',1);
insert into city(name,fk_country) values('Cristalândia do Piauí (PI)',1);
insert into city(name,fk_country) values('Cristal do Sul (RS)',1);
insert into city(name,fk_country) values('Cristália (MG)',1);
insert into city(name,fk_country) values('Cristalina (GO)',1);
insert into city(name,fk_country) values('Cristiano Otoni (MG)',1);
insert into city(name,fk_country) values('Cristianópolis (GO)',1);
insert into city(name,fk_country) values('Cristina (MG)',1);
insert into city(name,fk_country) values('Cristinápolis (SE)',1);
insert into city(name,fk_country) values('Cristino Castro (PI)',1);
insert into city(name,fk_country) values('Cristópolis (BA)',1);
insert into city(name,fk_country) values('Crixás (GO)',1);
insert into city(name,fk_country) values('Crixás do Tocantins (TO)',1);
insert into city(name,fk_country) values('Croatá (CE)',1);
insert into city(name,fk_country) values('Cromínia (GO)',1);
insert into city(name,fk_country) values('Crucilândia (MG)',1);
insert into city(name,fk_country) values('Cruz (CE)',1);
insert into city(name,fk_country) values('Cruzália (SP)',1);
insert into city(name,fk_country) values('Cruz Alta (RS)',1);
insert into city(name,fk_country) values('Cruzaltense (RS)',1);
insert into city(name,fk_country) values('Cruz das Almas (BA)',1);
insert into city(name,fk_country) values('Cruz do Espírito Santo (PB)',1);
insert into city(name,fk_country) values('Cruzeiro (SP)',1);
insert into city(name,fk_country) values('Cruzeiro da Fortaleza (MG)',1);
insert into city(name,fk_country) values('Cruzeiro do Iguaçu (PR)',1);
insert into city(name,fk_country) values('Cruzeiro do Oeste (PR)',1);
insert into city(name,fk_country) values('Cruzeiro do Sul (AC)',1);
insert into city(name,fk_country) values('Cruzeiro do Sul (PR)',1);
insert into city(name,fk_country) values('Cruzeiro do Sul (RS)',1);
insert into city(name,fk_country) values('Cruzeta (RN)',1);
insert into city(name,fk_country) values('Cruzília (MG)',1);
insert into city(name,fk_country) values('Cruz Machado (PR)',1);
insert into city(name,fk_country) values('Cruzmaltina (PR)',1);
insert into city(name,fk_country) values('Cubatão (SP)',1);
insert into city(name,fk_country) values('Cubati (PB)',1);
insert into city(name,fk_country) values('Cuiabá (MT)',1);
insert into city(name,fk_country) values('Cuité (PB)',1);
insert into city(name,fk_country) values('Cuité de Mamanguape (PB)',1);
insert into city(name,fk_country) values('Cuitegi (PB)',1);
insert into city(name,fk_country) values('Cujubim (RO)',1);
insert into city(name,fk_country) values('Cumari (GO)',1);
insert into city(name,fk_country) values('Cumaru (PE)',1);
insert into city(name,fk_country) values('Cumaru do Norte (PA)',1);
insert into city(name,fk_country) values('Cumbe (SE)',1);
insert into city(name,fk_country) values('Cunha (SP)',1);
insert into city(name,fk_country) values('Cunha Porã (SC)',1);
insert into city(name,fk_country) values('Cunhataí (SC)',1);
insert into city(name,fk_country) values('Cuparaque (MG)',1);
insert into city(name,fk_country) values('Cupira (PE)',1);
insert into city(name,fk_country) values('Curaçá (BA)',1);
insert into city(name,fk_country) values('Curimatá (PI)',1);
insert into city(name,fk_country) values('Curionópolis (PA)',1);
insert into city(name,fk_country) values('Curitiba (PR)',1);
insert into city(name,fk_country) values('Curitibanos (SC)',1);
insert into city(name,fk_country) values('Curiúva (PR)',1);
insert into city(name,fk_country) values('Currais (PI)',1);
insert into city(name,fk_country) values('Currais Novos (RN)',1);
insert into city(name,fk_country) values('Curral de Cima (PB)',1);
insert into city(name,fk_country) values('Curral de Dentro (MG)',1);
insert into city(name,fk_country) values('Curralinho (PA)',1);
insert into city(name,fk_country) values('Curralinhos (PI)',1);
insert into city(name,fk_country) values('Curral Novo do Piauí (PI)',1);
insert into city(name,fk_country) values('Curral Velho (PB)',1);
insert into city(name,fk_country) values('Curuá (PA)',1);
insert into city(name,fk_country) values('Curuçá (PA)',1);
insert into city(name,fk_country) values('Cururupu (MA)',1);
insert into city(name,fk_country) values('Curvelândia (MT)',1);
insert into city(name,fk_country) values('Curvelo (MG)',1);
insert into city(name,fk_country) values('Custódia (PE)',1);
insert into city(name,fk_country) values('Cutias (AP)',1);
insert into city(name,fk_country) values('Cocal dos Alves (PI)',1);
insert into city(name,fk_country) values('Dom Pedrito (RS)',1);
insert into city(name,fk_country) values('Dom Pedro (MA)',1);
insert into city(name,fk_country) values('Dom Pedro de Alcântara (RS)',1);
insert into city(name,fk_country) values('Dom Silvério (MG)',1);
insert into city(name,fk_country) values('Dom Viçoso (MG)',1);
insert into city(name,fk_country) values('Dona Emma (SC)',1);
insert into city(name,fk_country) values('Dona Eusébia (MG)',1);
insert into city(name,fk_country) values('Dona Francisca (RS)',1);
insert into city(name,fk_country) values('Dona Inês (PB)',1);
insert into city(name,fk_country) values('Dores de Campos (MG)',1);
insert into city(name,fk_country) values('Dores de Guanhães (MG)',1);
insert into city(name,fk_country) values('Dores do Indaiá (MG)',1);
insert into city(name,fk_country) values('Dores do Rio Preto (ES)',1);
insert into city(name,fk_country) values('Dores do Turvo (MG)',1);
insert into city(name,fk_country) values('Doresópolis (MG)',1);
insert into city(name,fk_country) values('Dormentes (PE)',1);
insert into city(name,fk_country) values('Douradina (MS)',1);
insert into city(name,fk_country) values('Douradina (PR)',1);
insert into city(name,fk_country) values('Dourado (SP)',1);
insert into city(name,fk_country) values('Douradoquara (MG)',1);
insert into city(name,fk_country) values('Dourados (MS)',1);
insert into city(name,fk_country) values('Doutor Camargo (PR)',1);
insert into city(name,fk_country) values('Doutor Maurício Cardoso (RS)',1);
insert into city(name,fk_country) values('Doutor Pedrinho (SC)',1);
insert into city(name,fk_country) values('Doutor Ricardo (RS)',1);
insert into city(name,fk_country) values('Doutor Severiano (RN)',1);
insert into city(name,fk_country) values('Doutor Ulysses (PR)',1);
insert into city(name,fk_country) values('Doverlândia (GO)',1);
insert into city(name,fk_country) values('Dracena (SP)',1);
insert into city(name,fk_country) values('Duartina (SP)',1);
insert into city(name,fk_country) values('Duas Barras (RJ)',1);
insert into city(name,fk_country) values('Duas Estradas (PB)',1);
insert into city(name,fk_country) values('Dueré (TO)',1);
insert into city(name,fk_country) values('Dumont (SP)',1);
insert into city(name,fk_country) values('Duque Bacelar (MA)',1);
insert into city(name,fk_country) values('Duque de Caxias (RJ)',1);
insert into city(name,fk_country) values('Durandé (MG)',1);
insert into city(name,fk_country) values('Espírito Santo (RN)',1);
insert into city(name,fk_country) values('Espírito Santo do Dourado (MG)',1);
insert into city(name,fk_country) values('Espírito Santo do Pinhal (SP)',1);
insert into city(name,fk_country) values('Espírito Santo do Turvo (SP)',1);
insert into city(name,fk_country) values('Esplanada (BA)',1);
insert into city(name,fk_country) values('Espumoso (RS)',1);
insert into city(name,fk_country) values('Estação (RS)',1);
insert into city(name,fk_country) values('Estância (SE)',1);
insert into city(name,fk_country) values('Estância Velha (RS)',1);
insert into city(name,fk_country) values('Esteio (RS)',1);
insert into city(name,fk_country) values('Estiva (MG)',1);
insert into city(name,fk_country) values('Estiva Gerbi (SP)',1);
insert into city(name,fk_country) values('Estreito (MA)',1);
insert into city(name,fk_country) values('Estrela (RS)',1);
insert into city(name,fk_country) values('Estrela Dalva (MG)',1);
insert into city(name,fk_country) values('Estrela de Alagoas (AL)',1);
insert into city(name,fk_country) values('Estrela d''Oeste (SP)',1);
insert into city(name,fk_country) values('Estrela do Indaiá (MG)',1);
insert into city(name,fk_country) values('Estrela do Norte (GO)',1);
insert into city(name,fk_country) values('Estrela do Norte (SP)',1);
insert into city(name,fk_country) values('Estrela do Sul (MG)',1);
insert into city(name,fk_country) values('Estrela Velha (RS)',1);
insert into city(name,fk_country) values('Euclides da Cunha (BA)',1);
insert into city(name,fk_country) values('Euclides da Cunha Paulista (SP)',1);
insert into city(name,fk_country) values('Eugênio de Castro (RS)',1);
insert into city(name,fk_country) values('Eugenópolis (MG)',1);
insert into city(name,fk_country) values('Eunápolis (BA)',1);
insert into city(name,fk_country) values('Eusébio (CE)',1);
insert into city(name,fk_country) values('Ewbank da Câmara (MG)',1);
insert into city(name,fk_country) values('Extrema (MG)',1);
insert into city(name,fk_country) values('Extremoz (RN)',1);
insert into city(name,fk_country) values('Exu (PE)',1);
insert into city(name,fk_country) values('Formoso do Araguaia (TO)',1);
insert into city(name,fk_country) values('Forquetinha (RS)',1);
insert into city(name,fk_country) values('Forquilha (CE)',1);
insert into city(name,fk_country) values('Forquilhinha (SC)',1);
insert into city(name,fk_country) values('Fortaleza (CE)',1);
insert into city(name,fk_country) values('Fortaleza de Minas (MG)',1);
insert into city(name,fk_country) values('Fortaleza dos Nogueiras (MA)',1);
insert into city(name,fk_country) values('Fortaleza dos Valos (RS)',1);
insert into city(name,fk_country) values('Fortaleza do Tabocão (TO)',1);
insert into city(name,fk_country) values('Fortim (CE)',1);
insert into city(name,fk_country) values('Fortuna (MA)',1);
insert into city(name,fk_country) values('Fortuna de Minas (MG)',1);
insert into city(name,fk_country) values('Foz do Iguaçu (PR)',1);
insert into city(name,fk_country) values('Foz do Jordão (PR)',1);
insert into city(name,fk_country) values('Fraiburgo (SC)',1);
insert into city(name,fk_country) values('Franca (SP)',1);
insert into city(name,fk_country) values('Francinópolis (PI)',1);
insert into city(name,fk_country) values('Francisco Alves (PR)',1);
insert into city(name,fk_country) values('Francisco Ayres (PI)',1);
insert into city(name,fk_country) values('Francisco Badaró (MG)',1);
insert into city(name,fk_country) values('Francisco Beltrão (PR)',1);
insert into city(name,fk_country) values('Francisco Dantas (RN)',1);
insert into city(name,fk_country) values('Francisco Dumont (MG)',1);
insert into city(name,fk_country) values('Francisco Macedo (PI)',1);
insert into city(name,fk_country) values('Francisco Morato (SP)',1);
insert into city(name,fk_country) values('Franciscópolis (MG)',1);
insert into city(name,fk_country) values('Francisco Sá (MG)',1);
insert into city(name,fk_country) values('Francisco Santos (PI)',1);
insert into city(name,fk_country) values('Franco da Rocha (SP)',1);
insert into city(name,fk_country) values('Frecheirinha (CE)',1);
insert into city(name,fk_country) values('Frederico Westphalen (RS)',1);
insert into city(name,fk_country) values('Frei Gaspar (MG)',1);
insert into city(name,fk_country) values('Frei Inocêncio (MG)',1);
insert into city(name,fk_country) values('Frei Lagonegro (MG)',1);
insert into city(name,fk_country) values('Frei Martinho (PB)',1);
insert into city(name,fk_country) values('Frei Miguelinho (PE)',1);
insert into city(name,fk_country) values('Frei Paulo (SE)',1);
insert into city(name,fk_country) values('Frei Rogério (SC)',1);
insert into city(name,fk_country) values('Fronteira (MG)',1);
insert into city(name,fk_country) values('Fronteira dos Vales (MG)',1);
insert into city(name,fk_country) values('Fronteiras (PI)',1);
insert into city(name,fk_country) values('Fruta de Leite (MG)',1);
insert into city(name,fk_country) values('Frutal (MG)',1);
insert into city(name,fk_country) values('Frutuoso Gomes (RN)',1);
insert into city(name,fk_country) values('Fundão (ES)',1);
insert into city(name,fk_country) values('Funilândia (MG)',1);
insert into city(name,fk_country) values('Guapiaçu (SP)',1);
insert into city(name,fk_country) values('Guapiara (SP)',1);
insert into city(name,fk_country) values('Guapimirim (RJ)',1);
insert into city(name,fk_country) values('Guapirama (PR)',1);
insert into city(name,fk_country) values('Guapó (GO)',1);
insert into city(name,fk_country) values('Guaporema (PR)',1);
insert into city(name,fk_country) values('Guaporé (RS)',1);
insert into city(name,fk_country) values('Guará (SP)',1);
insert into city(name,fk_country) values('Guarabira (PB)',1);
insert into city(name,fk_country) values('Guaraçaí (SP)',1);
insert into city(name,fk_country) values('Guaraci (PR)',1);
insert into city(name,fk_country) values('Guaraci (SP)',1);
insert into city(name,fk_country) values('Guaraciaba (MG)',1);
insert into city(name,fk_country) values('Guaraciaba (SC)',1);
insert into city(name,fk_country) values('Guaraciaba do Norte (CE)',1);
insert into city(name,fk_country) values('Guaraciama (MG)',1);
insert into city(name,fk_country) values('Guaraí (TO)',1);
insert into city(name,fk_country) values('Guaraíta (GO)',1);
insert into city(name,fk_country) values('Guaramiranga (CE)',1);
insert into city(name,fk_country) values('Guaramirim (SC)',1);
insert into city(name,fk_country) values('Guaranésia (MG)',1);
insert into city(name,fk_country) values('Guarani (MG)',1);
insert into city(name,fk_country) values('Guaraniaçu (PR)',1);
insert into city(name,fk_country) values('Guarani das Missões (RS)',1);
insert into city(name,fk_country) values('Guarani de Goiás (GO)',1);
insert into city(name,fk_country) values('Guarani d''Oeste (SP)',1);
insert into city(name,fk_country) values('Guarantã (SP)',1);
insert into city(name,fk_country) values('Guarantã do Norte (MT)',1);
insert into city(name,fk_country) values('Guarapari (ES)',1);
insert into city(name,fk_country) values('Guarapuava (PR)',1);
insert into city(name,fk_country) values('Guaraqueçaba (PR)',1);
insert into city(name,fk_country) values('Guarará (MG)',1);
insert into city(name,fk_country) values('Guararapes (SP)',1);
insert into city(name,fk_country) values('Guararema (SP)',1);
insert into city(name,fk_country) values('Guaratinga (BA)',1);
insert into city(name,fk_country) values('Guaratinguetá (SP)',1);
insert into city(name,fk_country) values('Guaratuba (PR)',1);
insert into city(name,fk_country) values('Guarda-Mor (MG)',1);
insert into city(name,fk_country) values('Guareí (SP)',1);
insert into city(name,fk_country) values('Guariba (SP)',1);
insert into city(name,fk_country) values('Guaribas (PI)',1);
insert into city(name,fk_country) values('Guarinos (GO)',1);
insert into city(name,fk_country) values('Guarujá (SP)',1);
insert into city(name,fk_country) values('Guarujá do Sul (SC)',1);
insert into city(name,fk_country) values('Guarulhos (SP)',1);
insert into city(name,fk_country) values('Guatambu (SC)',1);
insert into city(name,fk_country) values('Guatapará (SP)',1);
insert into city(name,fk_country) values('Guaxupé (MG)',1);
insert into city(name,fk_country) values('Guia Lopes da Laguna (MS)',1);
insert into city(name,fk_country) values('Guidoval (MG)',1);
insert into city(name,fk_country) values('Guimarães (MA)',1);
insert into city(name,fk_country) values('Guimarânia (MG)',1);
insert into city(name,fk_country) values('Guiratinga (MT)',1);
insert into city(name,fk_country) values('Guiricema (MG)',1);
insert into city(name,fk_country) values('Gurinhatã (MG)',1);
insert into city(name,fk_country) values('Gurinhém (PB)',1);
insert into city(name,fk_country) values('Gurjão (PB)',1);
insert into city(name,fk_country) values('Gurupá (PA)',1);
insert into city(name,fk_country) values('Gurupi (TO)',1);
insert into city(name,fk_country) values('Guzolândia (SP)',1);
insert into city(name,fk_country) values('Hortolândia (SP)',1);
insert into city(name,fk_country) values('Hugo Napoleão (PI)',1);
insert into city(name,fk_country) values('Hulha Negra (RS)',1);
insert into city(name,fk_country) values('Humaitá (AM)',1);
insert into city(name,fk_country) values('Humaitá (RS)',1);
insert into city(name,fk_country) values('Humberto de Campos (MA)',1);
insert into city(name,fk_country) values('Itajuípe (BA)',1);
insert into city(name,fk_country) values('Italva (RJ)',1);
insert into city(name,fk_country) values('Itamaraju (BA)',1);
insert into city(name,fk_country) values('Itamarandiba (MG)',1);
insert into city(name,fk_country) values('Itamarati (AM)',1);
insert into city(name,fk_country) values('Itamarati de Minas (MG)',1);
insert into city(name,fk_country) values('Itamari (BA)',1);
insert into city(name,fk_country) values('Itambacuri (MG)',1);
insert into city(name,fk_country) values('Itambaracá (PR)',1);
insert into city(name,fk_country) values('Itambé (BA)',1);
insert into city(name,fk_country) values('Itambé (PE)',1);
insert into city(name,fk_country) values('Itambé (PR)',1);
insert into city(name,fk_country) values('Itambé do Mato Dentro (MG)',1);
insert into city(name,fk_country) values('Itamogi (MG)',1);
insert into city(name,fk_country) values('Itamonte (MG)',1);
insert into city(name,fk_country) values('Itanagra (BA)',1);
insert into city(name,fk_country) values('Itanhaém (SP)',1);
insert into city(name,fk_country) values('Itanhandu (MG)',1);
insert into city(name,fk_country) values('Itanhangá (MT)',1);
insert into city(name,fk_country) values('Itanhém (BA)',1);
insert into city(name,fk_country) values('Itanhomi (MG)',1);
insert into city(name,fk_country) values('Itaobim (MG)',1);
insert into city(name,fk_country) values('Itaocara (RJ)',1);
insert into city(name,fk_country) values('Itaóca (SP)',1);
insert into city(name,fk_country) values('Itapaci (GO)',1);
insert into city(name,fk_country) values('Itapajé (CE)',1);
insert into city(name,fk_country) values('Itapagipe (MG)',1);
insert into city(name,fk_country) values('Itaparica (BA)',1);
insert into city(name,fk_country) values('Itapé (BA)',1);
insert into city(name,fk_country) values('Itapebi (BA)',1);
insert into city(name,fk_country) values('Itapecerica (MG)',1);
insert into city(name,fk_country) values('Itapecerica da Serra (SP)',1);
insert into city(name,fk_country) values('Itapecuru-Mirim (MA)',1);
insert into city(name,fk_country) values('Itapejara d''Oeste (PR)',1);
insert into city(name,fk_country) values('Itapema (SC)',1);
insert into city(name,fk_country) values('Itapemirim (ES)',1);
insert into city(name,fk_country) values('Itaperuçu (PR)',1);
insert into city(name,fk_country) values('Itaperuna (RJ)',1);
insert into city(name,fk_country) values('Itapetim (PE)',1);
insert into city(name,fk_country) values('Itapetinga (BA)',1);
insert into city(name,fk_country) values('Itapetininga (SP)',1);
insert into city(name,fk_country) values('Itapeva (MG)',1);
insert into city(name,fk_country) values('Itapeva (SP)',1);
insert into city(name,fk_country) values('Itapevi (SP)',1);
insert into city(name,fk_country) values('Itapicuru (BA)',1);
insert into city(name,fk_country) values('Itapipoca (CE)',1);
insert into city(name,fk_country) values('Itapira (SP)',1);
insert into city(name,fk_country) values('Itapiranga (AM)',1);
insert into city(name,fk_country) values('Itapiranga (SC)',1);
insert into city(name,fk_country) values('Itapirapuã (GO)',1);
insert into city(name,fk_country) values('Itapirapuã Paulista (SP)',1);
insert into city(name,fk_country) values('Itapiratins (TO)',1);
insert into city(name,fk_country) values('Itapissuma (PE)',1);
insert into city(name,fk_country) values('Itapitanga (BA)',1);
insert into city(name,fk_country) values('Itapiúna (CE)',1);
insert into city(name,fk_country) values('Itapoá (SC)',1);
insert into city(name,fk_country) values('Itápolis (SP)',1);
insert into city(name,fk_country) values('Itaporã (MS)',1);
insert into city(name,fk_country) values('Itaporã do Tocantins (TO)',1);
insert into city(name,fk_country) values('Itaporanga (PB)',1);
insert into city(name,fk_country) values('Itaporanga (SP)',1);
insert into city(name,fk_country) values('Itaporanga d''Ajuda (SE)',1);
insert into city(name,fk_country) values('Itapororoca (PB)',1);
insert into city(name,fk_country) values('Itapuã do Oeste (RO)',1);
insert into city(name,fk_country) values('Itapuca (RS)',1);
insert into city(name,fk_country) values('Itapuí (SP)',1);
insert into city(name,fk_country) values('Itapura (SP)',1);
insert into city(name,fk_country) values('Itapuranga (GO)',1);
insert into city(name,fk_country) values('Itaquaquecetuba (SP)',1);
insert into city(name,fk_country) values('Itaquara (BA)',1);
insert into city(name,fk_country) values('Itaqui (RS)',1);
insert into city(name,fk_country) values('Itaquiraí (MS)',1);
insert into city(name,fk_country) values('Itaquitinga (PE)',1);
insert into city(name,fk_country) values('Itarana (ES)',1);
insert into city(name,fk_country) values('Itarantim (BA)',1);
insert into city(name,fk_country) values('Itararé (SP)',1);
insert into city(name,fk_country) values('Itarema (CE)',1);
insert into city(name,fk_country) values('Itariri (SP)',1);
insert into city(name,fk_country) values('Itarumã (GO)',1);
insert into city(name,fk_country) values('Itati (RS)',1);
insert into city(name,fk_country) values('Itatiaia (RJ)',1);
insert into city(name,fk_country) values('Itatiaiuçu (MG)',1);
insert into city(name,fk_country) values('Itatiba (SP)',1);
insert into city(name,fk_country) values('Itatiba do Sul (RS)',1);
insert into city(name,fk_country) values('Itatim (BA)',1);
insert into city(name,fk_country) values('Itatinga (SP)',1);
insert into city(name,fk_country) values('Itatira (CE)',1);
insert into city(name,fk_country) values('Itatuba (PB)',1);
insert into city(name,fk_country) values('Itaú (RN)',1);
insert into city(name,fk_country) values('Itaubal (AP)',1);
insert into city(name,fk_country) values('Itaúba (MT)',1);
insert into city(name,fk_country) values('Itauçu (GO)',1);
insert into city(name,fk_country) values('Itaú de Minas (MG)',1);
insert into city(name,fk_country) values('Itaueira (PI)',1);
insert into city(name,fk_country) values('Itaúna (MG)',1);
insert into city(name,fk_country) values('Itaúna do Sul (PR)',1);
insert into city(name,fk_country) values('Itaverava (MG)',1);
insert into city(name,fk_country) values('Itinga (MG)',1);
insert into city(name,fk_country) values('Itinga do Maranhão (MA)',1);
insert into city(name,fk_country) values('Itiquira (MT)',1);
insert into city(name,fk_country) values('Itirapina (SP)',1);
insert into city(name,fk_country) values('Itirapuã (SP)',1);
insert into city(name,fk_country) values('Itiruçu (BA)',1);
insert into city(name,fk_country) values('Itiúba (BA)',1);
insert into city(name,fk_country) values('Itobi (SP)',1);
insert into city(name,fk_country) values('Itororó (BA)',1);
insert into city(name,fk_country) values('Itu (SP)',1);
insert into city(name,fk_country) values('Ituaçu (BA)',1);
insert into city(name,fk_country) values('Ituberá (BA)',1);
insert into city(name,fk_country) values('Itueta (MG)',1);
insert into city(name,fk_country) values('Ituiutaba (MG)',1);
insert into city(name,fk_country) values('Itumbiara (GO)',1);
insert into city(name,fk_country) values('Itumirim (MG)',1);
insert into city(name,fk_country) values('Itupeva (SP)',1);
insert into city(name,fk_country) values('Itupiranga (PA)',1);
insert into city(name,fk_country) values('Ituporanga (SC)',1);
insert into city(name,fk_country) values('Iturama (MG)',1);
insert into city(name,fk_country) values('Itutinga (MG)',1);
insert into city(name,fk_country) values('Ituverava (SP)',1);
insert into city(name,fk_country) values('Iuiú (BA)',1);
insert into city(name,fk_country) values('Iúna (ES)',1);
insert into city(name,fk_country) values('Ivaí (PR)',1);
insert into city(name,fk_country) values('Ivaiporã (PR)',1);
insert into city(name,fk_country) values('Ivaté (PR)',1);
insert into city(name,fk_country) values('Ivatuba (PR)',1);
insert into city(name,fk_country) values('Ivinhema (MS)',1);
insert into city(name,fk_country) values('Ivolândia (GO)',1);
insert into city(name,fk_country) values('Ivorá (RS)',1);
insert into city(name,fk_country) values('Ivoti (RS)',1);
insert into city(name,fk_country) values('Joaquim Nabuco (PE)',1);
insert into city(name,fk_country) values('Joaquim Pires (PI)',1);
insert into city(name,fk_country) values('Joaquim Távora (PR)',1);
insert into city(name,fk_country) values('Joca Claudino (PB)',1);
insert into city(name,fk_country) values('Joca Marques (PI)',1);
insert into city(name,fk_country) values('Jóia (RS)',1);
insert into city(name,fk_country) values('Joinville (SC)',1);
insert into city(name,fk_country) values('Jordânia (MG)',1);
insert into city(name,fk_country) values('Jordão (AC)',1);
insert into city(name,fk_country) values('José Boiteux (SC)',1);
insert into city(name,fk_country) values('José Bonifácio (SP)',1);
insert into city(name,fk_country) values('José da Penha (RN)',1);
insert into city(name,fk_country) values('José de Freitas (PI)',1);
insert into city(name,fk_country) values('José Gonçalves de Minas (MG)',1);
insert into city(name,fk_country) values('Joselândia (MA)',1);
insert into city(name,fk_country) values('Josenópolis (MG)',1);
insert into city(name,fk_country) values('José Raydan (MG)',1);
insert into city(name,fk_country) values('Joviânia (GO)',1);
insert into city(name,fk_country) values('Juara (MT)',1);
insert into city(name,fk_country) values('Juarez Távora (PB)',1);
insert into city(name,fk_country) values('Juarina (TO)',1);
insert into city(name,fk_country) values('Juatuba (MG)',1);
insert into city(name,fk_country) values('Juazeirinho (PB)',1);
insert into city(name,fk_country) values('Juazeiro (BA)',1);
insert into city(name,fk_country) values('Juazeiro do Norte (CE)',1);
insert into city(name,fk_country) values('Juazeiro do Piauí (PI)',1);
insert into city(name,fk_country) values('Jucás (CE)',1);
insert into city(name,fk_country) values('Jucati (PE)',1);
insert into city(name,fk_country) values('Jucuruçu (BA)',1);
insert into city(name,fk_country) values('Jucurutu (RN)',1);
insert into city(name,fk_country) values('Juína (MT)',1);
insert into city(name,fk_country) values('Juiz de Fora (MG)',1);
insert into city(name,fk_country) values('Júlio Borges (PI)',1);
insert into city(name,fk_country) values('Júlio de Castilhos (RS)',1);
insert into city(name,fk_country) values('Júlio Mesquita (SP)',1);
insert into city(name,fk_country) values('Jumirim (SP)',1);
insert into city(name,fk_country) values('Junco do Maranhão (MA)',1);
insert into city(name,fk_country) values('Junco do Seridó (PB)',1);
insert into city(name,fk_country) values('Jundiá (AL)',1);
insert into city(name,fk_country) values('Jundiá (RN)',1);
insert into city(name,fk_country) values('Jundiaí (SP)',1);
insert into city(name,fk_country) values('Jundiaí do Sul (PR)',1);
insert into city(name,fk_country) values('Junqueiro (AL)',1);
insert into city(name,fk_country) values('Junqueirópolis (SP)',1);
insert into city(name,fk_country) values('Jupi (PE)',1);
insert into city(name,fk_country) values('Jupiá (SC)',1);
insert into city(name,fk_country) values('Juquiá (SP)',1);
insert into city(name,fk_country) values('Juquitiba (SP)',1);
insert into city(name,fk_country) values('Juramento (MG)',1);
insert into city(name,fk_country) values('Juranda (PR)',1);
insert into city(name,fk_country) values('Jurema (PE)',1);
insert into city(name,fk_country) values('Jurema (PI)',1);
insert into city(name,fk_country) values('Juripiranga (PB)',1);
insert into city(name,fk_country) values('Juru (PB)',1);
insert into city(name,fk_country) values('Juruá (AM)',1);
insert into city(name,fk_country) values('Juruaia (MG)',1);
insert into city(name,fk_country) values('Juruena (MT)',1);
insert into city(name,fk_country) values('Juruti (PA)',1);
insert into city(name,fk_country) values('Juscimeira (MT)',1);
insert into city(name,fk_country) values('Jussara (BA)',1);
insert into city(name,fk_country) values('Jussara (GO)',1);
insert into city(name,fk_country) values('Jussara (PR)',1);
insert into city(name,fk_country) values('Jussari (BA)',1);
insert into city(name,fk_country) values('Jussiape (BA)',1);
insert into city(name,fk_country) values('Jutaí (AM)',1);
insert into city(name,fk_country) values('Juti (MS)',1);
insert into city(name,fk_country) values('Juvenília (MG)',1);
insert into city(name,fk_country) values('Limeira (SP)',1);
insert into city(name,fk_country) values('Limeira do Oeste (MG)',1);
insert into city(name,fk_country) values('Limoeiro (PE)',1);
insert into city(name,fk_country) values('Limoeiro de Anadia (AL)',1);
insert into city(name,fk_country) values('Limoeiro do Ajuru (PA)',1);
insert into city(name,fk_country) values('Limoeiro do Norte (CE)',1);
insert into city(name,fk_country) values('Lindoeste (PR)',1);
insert into city(name,fk_country) values('Lindóia (SP)',1);
insert into city(name,fk_country) values('Lindóia do Sul (SC)',1);
insert into city(name,fk_country) values('Lindolfo Collor (RS)',1);
insert into city(name,fk_country) values('Linha Nova (RS)',1);
insert into city(name,fk_country) values('Linhares (ES)',1);
insert into city(name,fk_country) values('Lins (SP)',1);
insert into city(name,fk_country) values('Livramento (PB)',1);
insert into city(name,fk_country) values('Livramento de Nossa Senhora (BA)',1);
insert into city(name,fk_country) values('Lizarda (TO)',1);
insert into city(name,fk_country) values('Loanda (PR)',1);
insert into city(name,fk_country) values('Lobato (PR)',1);
insert into city(name,fk_country) values('Logradouro (PB)',1);
insert into city(name,fk_country) values('Londrina (PR)',1);
insert into city(name,fk_country) values('Lontra (MG)',1);
insert into city(name,fk_country) values('Lontras (SC)',1);
insert into city(name,fk_country) values('Lorena (SP)',1);
insert into city(name,fk_country) values('Loreto (MA)',1);
insert into city(name,fk_country) values('Lourdes (SP)',1);
insert into city(name,fk_country) values('Louveira (SP)',1);
insert into city(name,fk_country) values('Lucas do Rio Verde (MT)',1);
insert into city(name,fk_country) values('Lucélia (SP)',1);
insert into city(name,fk_country) values('Lucena (PB)',1);
insert into city(name,fk_country) values('Lucianópolis (SP)',1);
insert into city(name,fk_country) values('Luciara (MT)',1);
insert into city(name,fk_country) values('Lucrécia (RN)',1);
insert into city(name,fk_country) values('Luís Antônio (SP)',1);
insert into city(name,fk_country) values('Luisburgo (MG)',1);
insert into city(name,fk_country) values('Luís Alves (SC)',1);
insert into city(name,fk_country) values('Luís Correia (PI)',1);
insert into city(name,fk_country) values('Luís Domingues (MA)',1);
insert into city(name,fk_country) values('Luís Eduardo Magalhães (BA)',1);
insert into city(name,fk_country) values('Luís Gomes (RN)',1);
insert into city(name,fk_country) values('Luisiana (PR)',1);
insert into city(name,fk_country) values('Luisiânia (SP)',1);
insert into city(name,fk_country) values('Luislândia (MG)',1);
insert into city(name,fk_country) values('Luminárias (MG)',1);
insert into city(name,fk_country) values('Lunardelli (PR)',1);
insert into city(name,fk_country) values('Lupércio (SP)',1);
insert into city(name,fk_country) values('Lupionópolis (PR)',1);
insert into city(name,fk_country) values('Lutécia (SP)',1);
insert into city(name,fk_country) values('Luz (MG)',1);
insert into city(name,fk_country) values('Luzerna (SC)',1);
insert into city(name,fk_country) values('Luziânia (GO)',1);
insert into city(name,fk_country) values('Luzilândia (PI)',1);
insert into city(name,fk_country) values('Luzinópolis (TO)',1);
insert into city(name,fk_country) values('Miravânia (MG)',1);
insert into city(name,fk_country) values('Mirim Doce (SC)',1);
insert into city(name,fk_country) values('Mirinzal (MA)',1);
insert into city(name,fk_country) values('Missal (PR)',1);
insert into city(name,fk_country) values('Missão Velha (CE)',1);
insert into city(name,fk_country) values('Mocajuba (PA)',1);
insert into city(name,fk_country) values('Mococa (SP)',1);
insert into city(name,fk_country) values('Modelo (SC)',1);
insert into city(name,fk_country) values('Moeda (MG)',1);
insert into city(name,fk_country) values('Moema (MG)',1);
insert into city(name,fk_country) values('Mogeiro (PB)',1);
insert into city(name,fk_country) values('Mogi das Cruzes (SP)',1);
insert into city(name,fk_country) values('Mogi Guaçu (SP)',1);
insert into city(name,fk_country) values('Mogi Mirim (SP)',1);
insert into city(name,fk_country) values('Moiporá (GO)',1);
insert into city(name,fk_country) values('Moita Bonita (SE)',1);
insert into city(name,fk_country) values('Moju (PA)',1);
insert into city(name,fk_country) values('Mojuí dos Campos (PA)',1);
insert into city(name,fk_country) values('Mombaça (CE)',1);
insert into city(name,fk_country) values('Mombuca (SP)',1);
insert into city(name,fk_country) values('Monção (MA)',1);
insert into city(name,fk_country) values('Monções (SP)',1);
insert into city(name,fk_country) values('Mondaí (SC)',1);
insert into city(name,fk_country) values('Mongaguá (SP)',1);
insert into city(name,fk_country) values('Monjolos (MG)',1);
insert into city(name,fk_country) values('Monsenhor Gil (PI)',1);
insert into city(name,fk_country) values('Monsenhor Hipólito (PI)',1);
insert into city(name,fk_country) values('Monsenhor Paulo (MG)',1);
insert into city(name,fk_country) values('Monsenhor Tabosa (CE)',1);
insert into city(name,fk_country) values('Montadas (PB)',1);
insert into city(name,fk_country) values('Montalvânia (MG)',1);
insert into city(name,fk_country) values('Montanha (ES)',1);
insert into city(name,fk_country) values('Montanhas (RN)',1);
insert into city(name,fk_country) values('Montauri (RS)',1);
insert into city(name,fk_country) values('Monte Alegre (PA)',1);
insert into city(name,fk_country) values('Monte Alegre (RN)',1);
insert into city(name,fk_country) values('Monte Alegre de Goiás (GO)',1);
insert into city(name,fk_country) values('Monte Alegre de Minas (MG)',1);
insert into city(name,fk_country) values('Monte Alegre de Sergipe (SE)',1);
insert into city(name,fk_country) values('Monte Alegre do Piauí (PI)',1);
insert into city(name,fk_country) values('Monte Alegre dos Campos (RS)',1);
insert into city(name,fk_country) values('Monte Alegre do Sul (SP)',1);
insert into city(name,fk_country) values('Monte Alto (SP)',1);
insert into city(name,fk_country) values('Monte Aprazível (SP)',1);
insert into city(name,fk_country) values('Monte Azul (MG)',1);
insert into city(name,fk_country) values('Monte Azul Paulista (SP)',1);
insert into city(name,fk_country) values('Monte Belo (MG)',1);
insert into city(name,fk_country) values('Monte Belo do Sul (RS)',1);
insert into city(name,fk_country) values('Monte Carlo (SC)',1);
insert into city(name,fk_country) values('Monte Carmelo (MG)',1);
insert into city(name,fk_country) values('Monte Castelo (SC)',1);
insert into city(name,fk_country) values('Monte Castelo (SP)',1);
insert into city(name,fk_country) values('Monte das Gameleiras (RN)',1);
insert into city(name,fk_country) values('Monte do Carmo (TO)',1);
insert into city(name,fk_country) values('Monte Formoso (MG)',1);
insert into city(name,fk_country) values('Monte Horebe (PB)',1);
insert into city(name,fk_country) values('Monteiro (PB)',1);
insert into city(name,fk_country) values('Monteiro Lobato (SP)',1);
insert into city(name,fk_country) values('Monteirópolis (AL)',1);
insert into city(name,fk_country) values('Monte Mor (SP)',1);
insert into city(name,fk_country) values('Montenegro (RS)',1);
insert into city(name,fk_country) values('Monte Negro (RO)',1);
insert into city(name,fk_country) values('Montes Altos (MA)',1);
insert into city(name,fk_country) values('Monte Santo (BA)',1);
insert into city(name,fk_country) values('Monte Santo de Minas (MG)',1);
insert into city(name,fk_country) values('Monte Santo do Tocantins (TO)',1);
insert into city(name,fk_country) values('Montes Claros (MG)',1);
insert into city(name,fk_country) values('Montes Claros de Goiás (GO)',1);
insert into city(name,fk_country) values('Monte Sião (MG)',1);
insert into city(name,fk_country) values('Montezuma (MG)',1);
insert into city(name,fk_country) values('Montividiu (GO)',1);
insert into city(name,fk_country) values('Montividiu do Norte (GO)',1);
insert into city(name,fk_country) values('Morada Nova (CE)',1);
insert into city(name,fk_country) values('Morada Nova de Minas (MG)',1);
insert into city(name,fk_country) values('Moraújo (CE)',1);
insert into city(name,fk_country) values('Moreilândia (PE)',1);
insert into city(name,fk_country) values('Moreira Sales (PR)',1);
insert into city(name,fk_country) values('Moreno (PE)',1);
insert into city(name,fk_country) values('Mormaço (RS)',1);
insert into city(name,fk_country) values('Morpará (BA)',1);
insert into city(name,fk_country) values('Morretes (PR)',1);
insert into city(name,fk_country) values('Morrinhos (CE)',1);
insert into city(name,fk_country) values('Morrinhos (GO)',1);
insert into city(name,fk_country) values('Morrinhos do Sul (RS)',1);
insert into city(name,fk_country) values('Morro Agudo (SP)',1);
insert into city(name,fk_country) values('Morro Agudo de Goiás (GO)',1);
insert into city(name,fk_country) values('Morro Cabeça no Tempo (PI)',1);
insert into city(name,fk_country) values('Morro da Fumaça (SC)',1);
insert into city(name,fk_country) values('Morro da Garça (MG)',1);
insert into city(name,fk_country) values('Morro do Chapéu (BA)',1);
insert into city(name,fk_country) values('Morro do Chapéu do Piauí (PI)',1);
insert into city(name,fk_country) values('Morro do Pilar (MG)',1);
insert into city(name,fk_country) values('Morro Grande (SC)',1);
insert into city(name,fk_country) values('Morro Redondo (RS)',1);
insert into city(name,fk_country) values('Morro Reuter (RS)',1);
insert into city(name,fk_country) values('Morros (MA)',1);
insert into city(name,fk_country) values('Mortugaba (BA)',1);
insert into city(name,fk_country) values('Morungaba (SP)',1);
insert into city(name,fk_country) values('Mossâmedes (GO)',1);
insert into city(name,fk_country) values('Mossoró (RN)',1);
insert into city(name,fk_country) values('Mostardas (RS)',1);
insert into city(name,fk_country) values('Motuca (SP)',1);
insert into city(name,fk_country) values('Mozarlândia (GO)',1);
insert into city(name,fk_country) values('Muaná (PA)',1);
insert into city(name,fk_country) values('Mucajaí (RR)',1);
insert into city(name,fk_country) values('Mucambo (CE)',1);
insert into city(name,fk_country) values('Mucugê (BA)',1);
insert into city(name,fk_country) values('Muçum (RS)',1);
insert into city(name,fk_country) values('Mucuri (BA)',1);
insert into city(name,fk_country) values('Mucurici (ES)',1);
insert into city(name,fk_country) values('Muitos Capões (RS)',1);
insert into city(name,fk_country) values('Muliterno (RS)',1);
insert into city(name,fk_country) values('Mulungu (CE)',1);
insert into city(name,fk_country) values('Mulungu (PB)',1);
insert into city(name,fk_country) values('Mulungu do Morro (BA)',1);
insert into city(name,fk_country) values('Mundo Novo (BA)',1);
insert into city(name,fk_country) values('Mundo Novo (GO)',1);
insert into city(name,fk_country) values('Mundo Novo (MS)',1);
insert into city(name,fk_country) values('Munhoz (MG)',1);
insert into city(name,fk_country) values('Munhoz de Melo (PR)',1);
insert into city(name,fk_country) values('Muniz Ferreira (BA)',1);
insert into city(name,fk_country) values('Muniz Freire (ES)',1);
insert into city(name,fk_country) values('Muquém de São Francisco (BA)',1);
insert into city(name,fk_country) values('Muqui (ES)',1);
insert into city(name,fk_country) values('Muriaé (MG)',1);
insert into city(name,fk_country) values('Muribeca (SE)',1);
insert into city(name,fk_country) values('Murici (AL)',1);
insert into city(name,fk_country) values('Murici dos Portelas (PI)',1);
insert into city(name,fk_country) values('Muricilândia (TO)',1);
insert into city(name,fk_country) values('Muritiba (BA)',1);
insert into city(name,fk_country) values('Murutinga do Sul (SP)',1);
insert into city(name,fk_country) values('Mutuípe (BA)',1);
insert into city(name,fk_country) values('Mutum (MG)',1);
insert into city(name,fk_country) values('Mutunópolis (GO)',1);
insert into city(name,fk_country) values('Muzambinho (MG)',1);
insert into city(name,fk_country) values('Nova Ponte (MG)',1);
insert into city(name,fk_country) values('Nova Porteirinha (MG)',1);
insert into city(name,fk_country) values('Nova Prata (RS)',1);
insert into city(name,fk_country) values('Nova Prata do Iguaçu (PR)',1);
insert into city(name,fk_country) values('Nova Ramada (RS)',1);
insert into city(name,fk_country) values('Nova Redenção (BA)',1);
insert into city(name,fk_country) values('Nova Resende (MG)',1);
insert into city(name,fk_country) values('Nova Roma (GO)',1);
insert into city(name,fk_country) values('Nova Roma do Sul (RS)',1);
insert into city(name,fk_country) values('Nova Rosalândia (TO)',1);
insert into city(name,fk_country) values('Nova Russas (CE)',1);
insert into city(name,fk_country) values('Nova Santa Bárbara (PR)',1);
insert into city(name,fk_country) values('Nova Santa Helena (MT)',1);
insert into city(name,fk_country) values('Nova Santa Rita (PI)',1);
insert into city(name,fk_country) values('Nova Santa Rita (RS)',1);
insert into city(name,fk_country) values('Nova Santa Rosa (PR)',1);
insert into city(name,fk_country) values('Nova Serrana (MG)',1);
insert into city(name,fk_country) values('Nova Soure (BA)',1);
insert into city(name,fk_country) values('Nova Tebas (PR)',1);
insert into city(name,fk_country) values('Nova Timboteua (PA)',1);
insert into city(name,fk_country) values('Nova Trento (SC)',1);
insert into city(name,fk_country) values('Nova Ubiratã (MT)',1);
insert into city(name,fk_country) values('Nova União (MG)',1);
insert into city(name,fk_country) values('Nova União (RO)',1);
insert into city(name,fk_country) values('Nova Venécia (ES)',1);
insert into city(name,fk_country) values('Nova Veneza (GO)',1);
insert into city(name,fk_country) values('Nova Veneza (SC)',1);
insert into city(name,fk_country) values('Nova Viçosa (BA)',1);
insert into city(name,fk_country) values('Nova Xavantina (MT)',1);
insert into city(name,fk_country) values('Novo Acordo (TO)',1);
insert into city(name,fk_country) values('Novo Alegre (TO)',1);
insert into city(name,fk_country) values('Novo Aripuanã (AM)',1);
insert into city(name,fk_country) values('Novo Airão (AM)',1);
insert into city(name,fk_country) values('Novo Barreiro (RS)',1);
insert into city(name,fk_country) values('Novo Brasil (GO)',1);
insert into city(name,fk_country) values('Novo Cabrais (RS)',1);
insert into city(name,fk_country) values('Novo Cruzeiro (MG)',1);
insert into city(name,fk_country) values('Novo Gama (GO)',1);
insert into city(name,fk_country) values('Novo Hamburgo (RS)',1);
insert into city(name,fk_country) values('Novo Horizonte (BA)',1);
insert into city(name,fk_country) values('Novo Horizonte (SC)',1);
insert into city(name,fk_country) values('Novo Horizonte (SP)',1);
insert into city(name,fk_country) values('Novo Horizonte do Norte (MT)',1);
insert into city(name,fk_country) values('Novo Horizonte do Oeste (RO)',1);
insert into city(name,fk_country) values('Novo Horizonte do Sul (MS)',1);
insert into city(name,fk_country) values('Novo Itacolomi (PR)',1);
insert into city(name,fk_country) values('Novo Jardim (TO)',1);
insert into city(name,fk_country) values('Novo Lino (AL)',1);
insert into city(name,fk_country) values('Novo Machado (RS)',1);
insert into city(name,fk_country) values('Novo Mundo (MT)',1);
insert into city(name,fk_country) values('Novo Oriente (CE)',1);
insert into city(name,fk_country) values('Novo Oriente de Minas (MG)',1);
insert into city(name,fk_country) values('Novo Oriente do Piauí (PI)',1);
insert into city(name,fk_country) values('Novo Planalto (GO)',1);
insert into city(name,fk_country) values('Novo Progresso (PA)',1);
insert into city(name,fk_country) values('Novo Repartimento (PA)',1);
insert into city(name,fk_country) values('Novorizonte (MG)',1);
insert into city(name,fk_country) values('Novo Santo Antônio (MT)',1);
insert into city(name,fk_country) values('Novo Santo Antônio (PI)',1);
insert into city(name,fk_country) values('Novo São Joaquim (MT)',1);
insert into city(name,fk_country) values('Novo Tiradentes (RS)',1);
insert into city(name,fk_country) values('Novo Triunfo (BA)',1);
insert into city(name,fk_country) values('Novo Xingu (RS)',1);
insert into city(name,fk_country) values('Nuporanga (SP)',1);
insert into city(name,fk_country) values('Ourém (PA)',1);
insert into city(name,fk_country) values('Ouriçangas (BA)',1);
insert into city(name,fk_country) values('Ouricuri (PE)',1);
insert into city(name,fk_country) values('Ourilândia do Norte (PA)',1);
insert into city(name,fk_country) values('Ourinhos (SP)',1);
insert into city(name,fk_country) values('Ourizona (PR)',1);
insert into city(name,fk_country) values('Ouro (SC)',1);
insert into city(name,fk_country) values('Ouro Branco (AL)',1);
insert into city(name,fk_country) values('Ouro Branco (MG)',1);
insert into city(name,fk_country) values('Ouro Branco (RN)',1);
insert into city(name,fk_country) values('Ouroeste (SP)',1);
insert into city(name,fk_country) values('Ouro Fino (MG)',1);
insert into city(name,fk_country) values('Ourolândia (BA)',1);
insert into city(name,fk_country) values('Ouro Preto (MG)',1);
insert into city(name,fk_country) values('Ouro Preto do Oeste (RO)',1);
insert into city(name,fk_country) values('Ouro Velho (PB)',1);
insert into city(name,fk_country) values('Ouro Verde (SC)',1);
insert into city(name,fk_country) values('Ouro Verde (SP)',1);
insert into city(name,fk_country) values('Ouro Verde de Goiás (GO)',1);
insert into city(name,fk_country) values('Ouro Verde de Minas (MG)',1);
insert into city(name,fk_country) values('Ouro Verde do Oeste (PR)',1);
insert into city(name,fk_country) values('Ouvidor (GO)',1);
insert into city(name,fk_country) values('Piúma (ES)',1);
insert into city(name,fk_country) values('Piumhi (MG)',1);
insert into city(name,fk_country) values('Placas (PA)',1);
insert into city(name,fk_country) values('Plácido de Castro (AC)',1);
insert into city(name,fk_country) values('Planaltina (GO)',1);
insert into city(name,fk_country) values('Planaltina do Paraná (PR)',1);
insert into city(name,fk_country) values('Planaltino (BA)',1);
insert into city(name,fk_country) values('Planalto (BA)',1);
insert into city(name,fk_country) values('Planalto (PR)',1);
insert into city(name,fk_country) values('Planalto (RS)',1);
insert into city(name,fk_country) values('Planalto (SP)',1);
insert into city(name,fk_country) values('Planalto Alegre (SC)',1);
insert into city(name,fk_country) values('Planalto da Serra (MT)',1);
insert into city(name,fk_country) values('Planura (MG)',1);
insert into city(name,fk_country) values('Platina (SP)',1);
insert into city(name,fk_country) values('Poá (SP)',1);
insert into city(name,fk_country) values('Poção (PE)',1);
insert into city(name,fk_country) values('Poção de Pedras (MA)',1);
insert into city(name,fk_country) values('Pocinhos (PB)',1);
insert into city(name,fk_country) values('Poço Branco (RN)',1);
insert into city(name,fk_country) values('Poço Dantas (PB)',1);
insert into city(name,fk_country) values('Poço das Antas (RS)',1);
insert into city(name,fk_country) values('Poço das Trincheiras (AL)',1);
insert into city(name,fk_country) values('Poço de José de Moura (PB)',1);
insert into city(name,fk_country) values('Poções (BA)',1);
insert into city(name,fk_country) values('Poço Fundo (MG)',1);
insert into city(name,fk_country) values('Poconé (MT)',1);
insert into city(name,fk_country) values('Poço Redondo (SE)',1);
insert into city(name,fk_country) values('Poços de Caldas (MG)',1);
insert into city(name,fk_country) values('Poço Verde (SE)',1);
insert into city(name,fk_country) values('Pocrane (MG)',1);
insert into city(name,fk_country) values('Pojuca (BA)',1);
insert into city(name,fk_country) values('Poloni (SP)',1);
insert into city(name,fk_country) values('Pombal (PB)',1);
insert into city(name,fk_country) values('Pombos (PE)',1);
insert into city(name,fk_country) values('Pomerode (SC)',1);
insert into city(name,fk_country) values('Pompeia (SP)',1);
insert into city(name,fk_country) values('Pompéu (MG)',1);
insert into city(name,fk_country) values('Pongaí (SP)',1);
insert into city(name,fk_country) values('Ponta de Pedras (PA)',1);
insert into city(name,fk_country) values('Ponta Grossa (PR)',1);
insert into city(name,fk_country) values('Pontal (SP)',1);
insert into city(name,fk_country) values('Pontal do Araguaia (MT)',1);
insert into city(name,fk_country) values('Pontal do Paraná (PR)',1);
insert into city(name,fk_country) values('Pontalina (GO)',1);
insert into city(name,fk_country) values('Pontalinda (SP)',1);
insert into city(name,fk_country) values('Pontão (RS)',1);
insert into city(name,fk_country) values('Ponta Porã (MS)',1);
insert into city(name,fk_country) values('Ponte Alta (SC)',1);
insert into city(name,fk_country) values('Ponte Alta do Bom Jesus (TO)',1);
insert into city(name,fk_country) values('Ponte Alta do Norte (SC)',1);
insert into city(name,fk_country) values('Ponte Alta do Tocantins (TO)',1);
insert into city(name,fk_country) values('Ponte Branca (MT)',1);
insert into city(name,fk_country) values('Ponte Nova (MG)',1);
insert into city(name,fk_country) values('Ponte Preta (RS)',1);
insert into city(name,fk_country) values('Pontes e Lacerda (MT)',1);
insert into city(name,fk_country) values('Ponte Serrada (SC)',1);
insert into city(name,fk_country) values('Pontes Gestal (SP)',1);
insert into city(name,fk_country) values('Ponto Belo (ES)',1);
insert into city(name,fk_country) values('Ponto Chique (MG)',1);
insert into city(name,fk_country) values('Ponto dos Volantes (MG)',1);
insert into city(name,fk_country) values('Ponto Novo (BA)',1);
insert into city(name,fk_country) values('Populina (SP)',1);
insert into city(name,fk_country) values('Porangaba (SP)',1);
insert into city(name,fk_country) values('Poranga (CE)',1);
insert into city(name,fk_country) values('Porangatu (GO)',1);
insert into city(name,fk_country) values('Porciúncula (RJ)',1);
insert into city(name,fk_country) values('Porecatu (PR)',1);
insert into city(name,fk_country) values('Portalegre (RN)',1);
insert into city(name,fk_country) values('Portão (RS)',1);
insert into city(name,fk_country) values('Porteirão (GO)',1);
insert into city(name,fk_country) values('Porteiras (CE)',1);
insert into city(name,fk_country) values('Porteirinha (MG)',1);
insert into city(name,fk_country) values('Portel (PA)',1);
insert into city(name,fk_country) values('Portelândia (GO)',1);
insert into city(name,fk_country) values('Porto (PI)',1);
insert into city(name,fk_country) values('Porto Acre (AC)',1);
insert into city(name,fk_country) values('Porto Alegre (RS)',1);
insert into city(name,fk_country) values('Porto Alegre do Norte (MT)',1);
insert into city(name,fk_country) values('Porto Alegre do Piauí (PI)',1);
insert into city(name,fk_country) values('Porto Alegre do Tocantins (TO)',1);
insert into city(name,fk_country) values('Porto Amazonas (PR)',1);
insert into city(name,fk_country) values('Porto Barreiro (PR)',1);
insert into city(name,fk_country) values('Porto Belo (SC)',1);
insert into city(name,fk_country) values('Porto Calvo (AL)',1);
insert into city(name,fk_country) values('Porto da Folha (SE)',1);
insert into city(name,fk_country) values('Porto de Moz (PA)',1);
insert into city(name,fk_country) values('Porto de Pedras (AL)',1);
insert into city(name,fk_country) values('Porto do Mangue (RN)',1);
insert into city(name,fk_country) values('Porto dos Gaúchos (MT)',1);
insert into city(name,fk_country) values('Porto Esperidião (MT)',1);
insert into city(name,fk_country) values('Porto Estrela (MT)',1);
insert into city(name,fk_country) values('Porto Feliz (SP)',1);
insert into city(name,fk_country) values('Porto Ferreira (SP)',1);
insert into city(name,fk_country) values('Porto Firme (MG)',1);
insert into city(name,fk_country) values('Porto Franco (MA)',1);
insert into city(name,fk_country) values('Porto Grande (AP)',1);
insert into city(name,fk_country) values('Porto Lucena (RS)',1);
insert into city(name,fk_country) values('Porto Mauá (RS)',1);
insert into city(name,fk_country) values('Porto Murtinho (MS)',1);
insert into city(name,fk_country) values('Porto Nacional (TO)',1);
insert into city(name,fk_country) values('Porto Real (RJ)',1);
insert into city(name,fk_country) values('Porto Real do Colégio (AL)',1);
insert into city(name,fk_country) values('Porto Rico (PR)',1);
insert into city(name,fk_country) values('Porto Rico do Maranhão (MA)',1);
insert into city(name,fk_country) values('Porto Seguro (BA)',1);
insert into city(name,fk_country) values('Porto União (SC)',1);
insert into city(name,fk_country) values('Porto Velho (RO)',1);
insert into city(name,fk_country) values('Porto Vera Cruz (RS)',1);
insert into city(name,fk_country) values('Porto Vitória (PR)',1);
insert into city(name,fk_country) values('Porto Walter (AC)',1);