insert into city(name,fk_country) values('Porto Xavier (RS)',1);
insert into city(name,fk_country) values('Posse (GO)',1);
insert into city(name,fk_country) values('Poté (MG)',1);
insert into city(name,fk_country) values('Potengi (CE)',1);
insert into city(name,fk_country) values('Potim (SP)',1);
insert into city(name,fk_country) values('Potiraguá (BA)',1);
insert into city(name,fk_country) values('Potirendaba (SP)',1);
insert into city(name,fk_country) values('Potiretama (CE)',1);
insert into city(name,fk_country) values('Pouso Alegre (MG)',1);
insert into city(name,fk_country) values('Pouso Alto (MG)',1);
insert into city(name,fk_country) values('Pouso Novo (RS)',1);
insert into city(name,fk_country) values('Pouso Redondo (SC)',1);
insert into city(name,fk_country) values('Poxoréu (MT)',1);
insert into city(name,fk_country) values('Pracinha (SP)',1);
insert into city(name,fk_country) values('Pracuuba (AP)',1);
insert into city(name,fk_country) values('Prado (BA)',1);
insert into city(name,fk_country) values('Prado Ferreira (PR)',1);
insert into city(name,fk_country) values('Pradópolis (SP)',1);
insert into city(name,fk_country) values('Prados (MG)',1);
insert into city(name,fk_country) values('Praia Grande (SC)',1);
insert into city(name,fk_country) values('Praia Grande (SP)',1);
insert into city(name,fk_country) values('Praia Norte (TO)',1);
insert into city(name,fk_country) values('Prainha (PA)',1);
insert into city(name,fk_country) values('Pranchita (PR)',1);
insert into city(name,fk_country) values('Prata (MG)',1);
insert into city(name,fk_country) values('Prata (PB)',1);
insert into city(name,fk_country) values('Prata do Piauí (PI)',1);
insert into city(name,fk_country) values('Pratânia (SP)',1);
insert into city(name,fk_country) values('Pratápolis (MG)',1);
insert into city(name,fk_country) values('Pratinha (MG)',1);
insert into city(name,fk_country) values('Presidente Alves (SP)',1);
insert into city(name,fk_country) values('Presidente Bernardes (MG)',1);
insert into city(name,fk_country) values('Presidente Bernardes (SP)',1);
insert into city(name,fk_country) values('Presidente Castelo Branco (PR)',1);
insert into city(name,fk_country) values('Presidente Castello Branco (SC)',1);
insert into city(name,fk_country) values('Presidente Dutra (BA)',1);
insert into city(name,fk_country) values('Presidente Dutra (MA)',1);
insert into city(name,fk_country) values('Presidente Epitácio (SP)',1);
insert into city(name,fk_country) values('Presidente Figueiredo (AM)',1);
insert into city(name,fk_country) values('Presidente Getúlio (SC)',1);
insert into city(name,fk_country) values('Presidente Jânio Quadros (BA)',1);
insert into city(name,fk_country) values('Presidente Juscelino (MA)',1);
insert into city(name,fk_country) values('Presidente Juscelino (MG)',1);
insert into city(name,fk_country) values('Presidente Kennedy (ES)',1);
insert into city(name,fk_country) values('Presidente Kennedy (TO)',1);
insert into city(name,fk_country) values('Presidente Kubitschek (MG)',1);
insert into city(name,fk_country) values('Presidente Lucena (RS)',1);
insert into city(name,fk_country) values('Presidente Médici (MA)',1);
insert into city(name,fk_country) values('Presidente Médici (RO)',1);
insert into city(name,fk_country) values('Presidente Nereu (SC)',1);
insert into city(name,fk_country) values('Presidente Olegário (MG)',1);
insert into city(name,fk_country) values('Presidente Prudente (SP)',1);
insert into city(name,fk_country) values('Presidente Sarney (MA)',1);
insert into city(name,fk_country) values('Presidente Tancredo Neves (BA)',1);
insert into city(name,fk_country) values('Presidente Vargas (MA)',1);
insert into city(name,fk_country) values('Presidente Venceslau (SP)',1);
insert into city(name,fk_country) values('Primavera (PA)',1);
insert into city(name,fk_country) values('Primavera (PE)',1);
insert into city(name,fk_country) values('Primavera de Rondônia (RO)',1);
insert into city(name,fk_country) values('Primavera do Leste (MT)',1);
insert into city(name,fk_country) values('Primeira Cruz (MA)',1);
insert into city(name,fk_country) values('Primeiro de Maio (PR)',1);
insert into city(name,fk_country) values('Princesa (SC)',1);
insert into city(name,fk_country) values('Princesa Isabel (PB)',1);
insert into city(name,fk_country) values('Professor Jamil (GO)',1);
insert into city(name,fk_country) values('Progresso (RS)',1);
insert into city(name,fk_country) values('Promissão (SP)',1);
insert into city(name,fk_country) values('Propriá (SE)',1);
insert into city(name,fk_country) values('Protásio Alves (RS)',1);
insert into city(name,fk_country) values('Prudente de Morais (MG)',1);
insert into city(name,fk_country) values('Prudentópolis (PR)',1);
insert into city(name,fk_country) values('Pugmil (TO)',1);
insert into city(name,fk_country) values('Pureza (RN)',1);
insert into city(name,fk_country) values('Putinga (RS)',1);
insert into city(name,fk_country) values('Puxinanã (PB)',1);
insert into city(name,fk_country) values('Quinze de Novembro (RS)',1);
insert into city(name,fk_country) values('Quipapá (PE)',1);
insert into city(name,fk_country) values('Quirinópolis (GO)',1);
insert into city(name,fk_country) values('Quissamã (RJ)',1);
insert into city(name,fk_country) values('Quitandinha (PR)',1);
insert into city(name,fk_country) values('Quiterianópolis (CE)',1);
insert into city(name,fk_country) values('Quixaba (PB)',1);
insert into city(name,fk_country) values('Quixaba (PE)',1);
insert into city(name,fk_country) values('Quixabeira (BA)',1);
insert into city(name,fk_country) values('Quixadá (CE)',1);
insert into city(name,fk_country) values('Quixelô (CE)',1);
insert into city(name,fk_country) values('Quixeramobim (CE)',1);
insert into city(name,fk_country) values('Quixeré (CE)',1);
insert into city(name,fk_country) values('Rio Negrinho (SC)',1);
insert into city(name,fk_country) values('Rio Negro (MS)',1);
insert into city(name,fk_country) values('Rio Negro (PR)',1);
insert into city(name,fk_country) values('Rio Novo (MG)',1);
insert into city(name,fk_country) values('Rio Novo do Sul (ES)',1);
insert into city(name,fk_country) values('Rio Paranaíba (MG)',1);
insert into city(name,fk_country) values('Rio Pardo (RS)',1);
insert into city(name,fk_country) values('Rio Pardo de Minas (MG)',1);
insert into city(name,fk_country) values('Rio Piracicaba (MG)',1);
insert into city(name,fk_country) values('Rio Pomba (MG)',1);
insert into city(name,fk_country) values('Rio Preto (MG)',1);
insert into city(name,fk_country) values('Rio Preto da Eva (AM)',1);
insert into city(name,fk_country) values('Rio Quente (GO)',1);
insert into city(name,fk_country) values('Rio Real (BA)',1);
insert into city(name,fk_country) values('Rio Rufino (SC)',1);
insert into city(name,fk_country) values('Rio Sono (TO)',1);
insert into city(name,fk_country) values('Rio Tinto (PB)',1);
insert into city(name,fk_country) values('Rio Verde (GO)',1);
insert into city(name,fk_country) values('Rio Verde de Mato Grosso (MS)',1);
insert into city(name,fk_country) values('Rio Vermelho (MG)',1);
insert into city(name,fk_country) values('Riozinho (RS)',1);
insert into city(name,fk_country) values('Riqueza (SC)',1);
insert into city(name,fk_country) values('Ritápolis (MG)',1);
insert into city(name,fk_country) values('Riversul (SP)',1);
insert into city(name,fk_country) values('Roca Sales (RS)',1);
insert into city(name,fk_country) values('Rochedo (MS)',1);
insert into city(name,fk_country) values('Rochedo de Minas (MG)',1);
insert into city(name,fk_country) values('Rodeio (SC)',1);
insert into city(name,fk_country) values('Rodeio Bonito (RS)',1);
insert into city(name,fk_country) values('Rodeiro (MG)',1);
insert into city(name,fk_country) values('Rodelas (BA)',1);
insert into city(name,fk_country) values('Rodolfo Fernandes (RN)',1);
insert into city(name,fk_country) values('Rodrigues Alves (AC)',1);
insert into city(name,fk_country) values('Rolador (RS)',1);
insert into city(name,fk_country) values('Rolândia (PR)',1);
insert into city(name,fk_country) values('Rolante (RS)',1);
insert into city(name,fk_country) values('Rolim de Moura (RO)',1);
insert into city(name,fk_country) values('Romaria (MG)',1);
insert into city(name,fk_country) values('Romelândia (SC)',1);
insert into city(name,fk_country) values('Roncador (PR)',1);
insert into city(name,fk_country) values('Ronda Alta (RS)',1);
insert into city(name,fk_country) values('Rondinha (RS)',1);
insert into city(name,fk_country) values('Rondolândia (MT)',1);
insert into city(name,fk_country) values('Rondon (PR)',1);
insert into city(name,fk_country) values('Rondon do Pará (PA)',1);
insert into city(name,fk_country) values('Rondonópolis (MT)',1);
insert into city(name,fk_country) values('Roque Gonzales (RS)',1);
insert into city(name,fk_country) values('Rorainópolis (RR)',1);
insert into city(name,fk_country) values('Rosana (SP)',1);
insert into city(name,fk_country) values('Rosário (MA)',1);
insert into city(name,fk_country) values('Rosário da Limeira (MG)',1);
insert into city(name,fk_country) values('Rosário do Catete (SE)',1);
insert into city(name,fk_country) values('Rosário do Ivaí (PR)',1);
insert into city(name,fk_country) values('Rosário do Sul (RS)',1);
insert into city(name,fk_country) values('Rosário Oeste (MT)',1);
insert into city(name,fk_country) values('Roseira (SP)',1);
insert into city(name,fk_country) values('Roteiro (AL)',1);
insert into city(name,fk_country) values('Rubelita (MG)',1);
insert into city(name,fk_country) values('Rubiácea (SP)',1);
insert into city(name,fk_country) values('Rubiataba (GO)',1);
insert into city(name,fk_country) values('Rubim (MG)',1);
insert into city(name,fk_country) values('Rubineia (SP)',1);
insert into city(name,fk_country) values('Rurópolis (PA)',1);
insert into city(name,fk_country) values('Russas (CE)',1);
insert into city(name,fk_country) values('Ruy Barbosa (BA)',1);
insert into city(name,fk_country) values('Ruy Barbosa (RN)',1);
insert into city(name,fk_country) values('São Miguel do Aleixo (SE)',1);
insert into city(name,fk_country) values('São Miguel do Anta (MG)',1);
insert into city(name,fk_country) values('São Miguel do Araguaia (GO)',1);
insert into city(name,fk_country) values('São Miguel do Fidalgo (PI)',1);
insert into city(name,fk_country) values('São Miguel do Gostoso (RN)',1);
insert into city(name,fk_country) values('São Miguel do Guamá (PA)',1);
insert into city(name,fk_country) values('São Miguel do Guaporé (RO)',1);
insert into city(name,fk_country) values('São Miguel do Iguaçu (PR)',1);
insert into city(name,fk_country) values('São Miguel do Oeste (SC)',1);
insert into city(name,fk_country) values('São Miguel do Passa-Quatro (GO)',1);
insert into city(name,fk_country) values('São Miguel dos Campos (AL)',1);
insert into city(name,fk_country) values('São Miguel dos Milagres (AL)',1);
insert into city(name,fk_country) values('São Miguel do Tapuio (PI)',1);
insert into city(name,fk_country) values('São Miguel do Tocantins (TO)',1);
insert into city(name,fk_country) values('São Nicolau (RS)',1);
insert into city(name,fk_country) values('São Patrício (GO)',1);
insert into city(name,fk_country) values('São Paulo (SP)',1);
insert into city(name,fk_country) values('São Paulo das Missões (RS)',1);
insert into city(name,fk_country) values('São Paulo de Olivença (AM)',1);
insert into city(name,fk_country) values('São Paulo do Potengi (RN)',1);
insert into city(name,fk_country) values('São Pedro (RN)',1);
insert into city(name,fk_country) values('São Pedro (SP)',1);
insert into city(name,fk_country) values('São Pedro da Água Branca (MA)',1);
insert into city(name,fk_country) values('São Pedro da Aldeia (RJ)',1);
insert into city(name,fk_country) values('São Pedro da Cipa (MT)',1);
insert into city(name,fk_country) values('São Pedro da Serra (RS)',1);
insert into city(name,fk_country) values('São Pedro das Missões (RS)',1);
insert into city(name,fk_country) values('São Pedro da União (MG)',1);
insert into city(name,fk_country) values('São Pedro de Alcântara (SC)',1);
insert into city(name,fk_country) values('São Pedro do Butiá (RS)',1);
insert into city(name,fk_country) values('São Pedro do Iguaçu (PR)',1);
insert into city(name,fk_country) values('São Pedro do Ivaí (PR)',1);
insert into city(name,fk_country) values('São Pedro do Paraná (PR)',1);
insert into city(name,fk_country) values('São Pedro do Piauí (PI)',1);
insert into city(name,fk_country) values('São Pedro dos Crentes (MA)',1);
insert into city(name,fk_country) values('São Pedro dos Ferros (MG)',1);
insert into city(name,fk_country) values('São Pedro do Suaçuí (MG)',1);
insert into city(name,fk_country) values('São Pedro do Sul (RS)',1);
insert into city(name,fk_country) values('São Pedro do Turvo (SP)',1);
insert into city(name,fk_country) values('São Rafael (RN)',1);
insert into city(name,fk_country) values('São Raimundo das Mangabeiras (MA)',1);
insert into city(name,fk_country) values('São Raimundo do Doca Bezerra (MA)',1);
insert into city(name,fk_country) values('São Raimundo Nonato (PI)',1);
insert into city(name,fk_country) values('São Roberto (MA)',1);
insert into city(name,fk_country) values('São Romão (MG)',1);
insert into city(name,fk_country) values('São Roque (SP)',1);
insert into city(name,fk_country) values('São Roque de Minas (MG)',1);
insert into city(name,fk_country) values('São Roque do Canaã (ES)',1);
insert into city(name,fk_country) values('São Salvador do Tocantins (TO)',1);
insert into city(name,fk_country) values('São Sebastião (AL)',1);
insert into city(name,fk_country) values('São Sebastião (SP)',1);
insert into city(name,fk_country) values('São Sebastião da Amoreira (PR)',1);
insert into city(name,fk_country) values('São Sebastião da Bela Vista (MG)',1);
insert into city(name,fk_country) values('São Sebastião da Boa Vista (PA)',1);
insert into city(name,fk_country) values('São Sebastião da Grama (SP)',1);
insert into city(name,fk_country) values('São Sebastião da Vargem Alegre (MG)',1);
insert into city(name,fk_country) values('São Sebastião de Lagoa de Roça (PB)',1);
insert into city(name,fk_country) values('São Sebastião do Alto (RJ)',1);
insert into city(name,fk_country) values('São Sebastião do Anta (MG)',1);
insert into city(name,fk_country) values('São Sebastião do Caí (RS)',1);
insert into city(name,fk_country) values('São Sebastião do Maranhão (MG)',1);
insert into city(name,fk_country) values('São Sebastião do Oeste (MG)',1);
insert into city(name,fk_country) values('São Sebastião do Paraíso (MG)',1);
insert into city(name,fk_country) values('São Sebastião do Passé (BA)',1);
insert into city(name,fk_country) values('São Sebastião do Rio Preto (MG)',1);
insert into city(name,fk_country) values('São Sebastião do Rio Verde (MG)',1);
insert into city(name,fk_country) values('São Sebastião do Tocantins (TO)',1);
insert into city(name,fk_country) values('São Sebastião do Uatumã (AM)',1);
insert into city(name,fk_country) values('São Sebastião do Umbuzeiro (PB)',1);
insert into city(name,fk_country) values('São Sepé (RS)',1);
insert into city(name,fk_country) values('São Simão (GO)',1);
insert into city(name,fk_country) values('São Simão (SP)',1);
insert into city(name,fk_country) values('São Thomé das Letras (MG)',1);
insert into city(name,fk_country) values('São Tiago (MG)',1);
insert into city(name,fk_country) values('São Tomás de Aquino (MG)',1);
insert into city(name,fk_country) values('São Tomé (PR)',1);
insert into city(name,fk_country) values('São Tomé (RN)',1);
insert into city(name,fk_country) values('São Valentim do Sul (RS)',1);
insert into city(name,fk_country) values('São Valentim (RS)',1);
insert into city(name,fk_country) values('São Valério da Natividade (TO)',1);
insert into city(name,fk_country) values('São Valério do Sul (RS)',1);
insert into city(name,fk_country) values('São Vendelino (RS)',1);
insert into city(name,fk_country) values('São Vicente (RN)',1);
insert into city(name,fk_country) values('São Vicente (SP)',1);
insert into city(name,fk_country) values('São Vicente de Minas (MG)',1);
insert into city(name,fk_country) values('São Vicente do Sul (RS)',1);
insert into city(name,fk_country) values('São Vicente Ferrer (MA)',1);
insert into city(name,fk_country) values('São Vicente Ferrer (PE)',1);
insert into city(name,fk_country) values('Sapé (PB)',1);
insert into city(name,fk_country) values('Sapeaçu (BA)',1);
insert into city(name,fk_country) values('Sapezal (MT)',1);
insert into city(name,fk_country) values('Sapiranga (RS)',1);
insert into city(name,fk_country) values('Sapopema (PR)',1);
insert into city(name,fk_country) values('Sapucaia (PA)',1);
insert into city(name,fk_country) values('Sapucaia (RJ)',1);
insert into city(name,fk_country) values('Sapucaia do Sul (RS)',1);
insert into city(name,fk_country) values('Sapucaí-Mirim (MG)',1);
insert into city(name,fk_country) values('Saquarema (RJ)',1);
insert into city(name,fk_country) values('Sarandi (PR)',1);
insert into city(name,fk_country) values('Sarandi (RS)',1);
insert into city(name,fk_country) values('Sarapuí (SP)',1);
insert into city(name,fk_country) values('Sardoá (MG)',1);
insert into city(name,fk_country) values('Sarutaiá (SP)',1);
insert into city(name,fk_country) values('Sarzedo (MG)',1);
insert into city(name,fk_country) values('Sátiro Dias (BA)',1);
insert into city(name,fk_country) values('Satuba (AL)',1);
insert into city(name,fk_country) values('Satubinha (MA)',1);
insert into city(name,fk_country) values('Saubara (BA)',1);
insert into city(name,fk_country) values('Saudade do Iguaçu (PR)',1);
insert into city(name,fk_country) values('Saudades (SC)',1);
insert into city(name,fk_country) values('Saúde (BA)',1);
insert into city(name,fk_country) values('Schroeder (SC)',1);
insert into city(name,fk_country) values('Seabra (BA)',1);
insert into city(name,fk_country) values('Seara (SC)',1);
insert into city(name,fk_country) values('Sebastianópolis do Sul (SP)',1);
insert into city(name,fk_country) values('Sebastião Barros (PI)',1);
insert into city(name,fk_country) values('Sebastião Laranjeiras (BA)',1);
insert into city(name,fk_country) values('Sebastião Leal (PI)',1);
insert into city(name,fk_country) values('Seberi (RS)',1);
insert into city(name,fk_country) values('Sede Nova (RS)',1);
insert into city(name,fk_country) values('Segredo (RS)',1);
insert into city(name,fk_country) values('Selbach (RS)',1);
insert into city(name,fk_country) values('Selvíria (MS)',1);
insert into city(name,fk_country) values('Sem-Peixe (MG)',1);
insert into city(name,fk_country) values('Senador Alexandre Costa (MA)',1);
insert into city(name,fk_country) values('Senador Amaral (MG)',1);
insert into city(name,fk_country) values('Senador Canedo (GO)',1);
insert into city(name,fk_country) values('Senador Cortes (MG)',1);
insert into city(name,fk_country) values('Senador Elói de Souza (RN)',1);
insert into city(name,fk_country) values('Senador Firmino (MG)',1);
insert into city(name,fk_country) values('Senador Georgino Avelino (RN)',1);
insert into city(name,fk_country) values('Senador Guiomard (AC)',1);
insert into city(name,fk_country) values('Senador José Bento (MG)',1);
insert into city(name,fk_country) values('Senador José Porfírio (PA)',1);
insert into city(name,fk_country) values('Senador La Rocque (MA)',1);
insert into city(name,fk_country) values('Senador Modestino Gonçalves (MG)',1);
insert into city(name,fk_country) values('Senador Pompeu (CE)',1);
insert into city(name,fk_country) values('Senador Rui Palmeira (AL)',1);
insert into city(name,fk_country) values('Senador Sá (CE)',1);
insert into city(name,fk_country) values('Senador Salgado Filho (RS)',1);
insert into city(name,fk_country) values('Sena Madureira (AC)',1);
insert into city(name,fk_country) values('Sengés (PR)',1);
insert into city(name,fk_country) values('Senhora de Oliveira (MG)',1);
insert into city(name,fk_country) values('Senhora do Porto (MG)',1);
insert into city(name,fk_country) values('Senhora dos Remédios (MG)',1);
insert into city(name,fk_country) values('Senhor do Bonfim (BA)',1);
insert into city(name,fk_country) values('Sentinela do Sul (RS)',1);
insert into city(name,fk_country) values('Sento Sé (BA)',1);
insert into city(name,fk_country) values('Serafina Corrêa (RS)',1);
insert into city(name,fk_country) values('Sericita (MG)',1);
insert into city(name,fk_country) values('Seridó (PB)',1);
insert into city(name,fk_country) values('Seringueiras (RO)',1);
insert into city(name,fk_country) values('Sério (RS)',1);
insert into city(name,fk_country) values('Seritinga (MG)',1);
insert into city(name,fk_country) values('Seropédica (RJ)',1);
insert into city(name,fk_country) values('Serra (ES)',1);
insert into city(name,fk_country) values('Serra Alta (SC)',1);
insert into city(name,fk_country) values('Serra Azul (SP)',1);
insert into city(name,fk_country) values('Serra Azul de Minas (MG)',1);
insert into city(name,fk_country) values('Serra Branca (PB)',1);
insert into city(name,fk_country) values('Serra Caiada (RN)',1);
insert into city(name,fk_country) values('Serra da Raiz (PB)',1);
insert into city(name,fk_country) values('Serra da Saudade (MG)',1);
insert into city(name,fk_country) values('Serra de São Bento (RN)',1);
insert into city(name,fk_country) values('Serra do Mel (RN)',1);
insert into city(name,fk_country) values('Serra do Navio (AP)',1);
insert into city(name,fk_country) values('Serra do Ramalho (BA)',1);
insert into city(name,fk_country) values('Serra dos Aimorés (MG)',1);
insert into city(name,fk_country) values('Serra do Salitre (MG)',1);
insert into city(name,fk_country) values('Serra Dourada (BA)',1);
insert into city(name,fk_country) values('Serra Grande (PB)',1);
insert into city(name,fk_country) values('Serrana (SP)',1);
insert into city(name,fk_country) values('Serrania (MG)',1);
insert into city(name,fk_country) values('Serra Negra (SP)',1);
insert into city(name,fk_country) values('Serra Negra do Norte (RN)',1);
insert into city(name,fk_country) values('Serrano do Maranhão (MA)',1);
insert into city(name,fk_country) values('Serranópolis (GO)',1);
insert into city(name,fk_country) values('Serranópolis de Minas (MG)',1);
insert into city(name,fk_country) values('Serranópolis do Iguaçu (PR)',1);
insert into city(name,fk_country) values('Serranos (MG)',1);
insert into city(name,fk_country) values('Serra Nova Dourada (MT)',1);
insert into city(name,fk_country) values('Serra Preta (BA)',1);
insert into city(name,fk_country) values('Serra Redonda (PB)',1);
insert into city(name,fk_country) values('Serraria (PB)',1);
insert into city(name,fk_country) values('Serra Talhada (PE)',1);
insert into city(name,fk_country) values('Serrinha (BA)',1);
insert into city(name,fk_country) values('Serrinha (RN)',1);
insert into city(name,fk_country) values('Serrinha dos Pintos (RN)',1);
insert into city(name,fk_country) values('Serrita (PE)',1);
insert into city(name,fk_country) values('Serro (MG)',1);
insert into city(name,fk_country) values('Serrolândia (BA)',1);
insert into city(name,fk_country) values('Sertaneja (PR)',1);
insert into city(name,fk_country) values('Sertânia (PE)',1);
insert into city(name,fk_country) values('Sertanópolis (PR)',1);
insert into city(name,fk_country) values('Sertão (RS)',1);
insert into city(name,fk_country) values('Sertão Santana (RS)',1);
insert into city(name,fk_country) values('Sertãozinho (PB)',1);
insert into city(name,fk_country) values('Sertãozinho (SP)',1);
insert into city(name,fk_country) values('Sete Barras (SP)',1);
insert into city(name,fk_country) values('Sete de Setembro (RS)',1);
insert into city(name,fk_country) values('Sete Lagoas (MG)',1);
insert into city(name,fk_country) values('Sete Quedas (MS)',1);
insert into city(name,fk_country) values('Setubinha (MG)',1);
insert into city(name,fk_country) values('Severiano de Almeida (RS)',1);
insert into city(name,fk_country) values('Severiano Melo (RN)',1);
insert into city(name,fk_country) values('Severínia (SP)',1);
insert into city(name,fk_country) values('Siderópolis (SC)',1);
insert into city(name,fk_country) values('Sidrolândia (MS)',1);
insert into city(name,fk_country) values('Sigefredo Pacheco (PI)',1);
insert into city(name,fk_country) values('Silva Jardim (RJ)',1);
insert into city(name,fk_country) values('Silvânia (GO)',1);
insert into city(name,fk_country) values('Silvanópolis (TO)',1);
insert into city(name,fk_country) values('Silveira Martins (RS)',1);
insert into city(name,fk_country) values('Silveirânia (MG)',1);
insert into city(name,fk_country) values('Silveiras (SP)',1);
insert into city(name,fk_country) values('Silves (AM)',1);
insert into city(name,fk_country) values('Silvianópolis (MG)',1);
insert into city(name,fk_country) values('Simão Dias (SE)',1);
insert into city(name,fk_country) values('Simão Pereira (MG)',1);
insert into city(name,fk_country) values('Simões (PI)',1);
insert into city(name,fk_country) values('Simões Filho (BA)',1);
insert into city(name,fk_country) values('Simolândia (GO)',1);
insert into city(name,fk_country) values('Simonésia (MG)',1);
insert into city(name,fk_country) values('Simplício Mendes (PI)',1);
insert into city(name,fk_country) values('Sinimbu (RS)',1);
insert into city(name,fk_country) values('Sinop (MT)',1);
insert into city(name,fk_country) values('Siqueira Campos (PR)',1);
insert into city(name,fk_country) values('Sirinhaém (PE)',1);
insert into city(name,fk_country) values('Siriri (SE)',1);
insert into city(name,fk_country) values('Sítio d''Abadia (GO)',1);
insert into city(name,fk_country) values('Sítio do Mato (BA)',1);
insert into city(name,fk_country) values('Sítio do Quinto (BA)',1);
insert into city(name,fk_country) values('Sítio Novo (MA)',1);
insert into city(name,fk_country) values('Sítio Novo (RN)',1);
insert into city(name,fk_country) values('Sítio Novo do Tocantins (TO)',1);
insert into city(name,fk_country) values('Sobradinho (BA)',1);
insert into city(name,fk_country) values('Sobradinho (RS)',1);
insert into city(name,fk_country) values('Sobrado (PB)',1);
insert into city(name,fk_country) values('Sobral (CE)',1);
insert into city(name,fk_country) values('Sobrália (MG)',1);
insert into city(name,fk_country) values('Socorro (SP)',1);
insert into city(name,fk_country) values('Socorro do Piauí (PI)',1);
insert into city(name,fk_country) values('Solânea (PB)',1);
insert into city(name,fk_country) values('Soledade (PB)',1);
insert into city(name,fk_country) values('Soledade (RS)',1);
insert into city(name,fk_country) values('Soledade de Minas (MG)',1);
insert into city(name,fk_country) values('Solidão (PE)',1);
insert into city(name,fk_country) values('Solonópole (CE)',1);
insert into city(name,fk_country) values('Sombrio (SC)',1);
insert into city(name,fk_country) values('Sonora (MS)',1);
insert into city(name,fk_country) values('Sooretama (ES)',1);
insert into city(name,fk_country) values('Sorocaba (SP)',1);
insert into city(name,fk_country) values('Sorriso (MT)',1);
insert into city(name,fk_country) values('Sossêgo (PB)',1);
insert into city(name,fk_country) values('Soure (PA)',1);
insert into city(name,fk_country) values('Sousa (PB)',1);
insert into city(name,fk_country) values('Souto Soares (BA)',1);
insert into city(name,fk_country) values('Sucupira (TO)',1);
insert into city(name,fk_country) values('Sucupira do Norte (MA)',1);
insert into city(name,fk_country) values('Sucupira do Riachão (MA)',1);
insert into city(name,fk_country) values('Sud Mennucci (SP)',1);
insert into city(name,fk_country) values('Sul Brasil (SC)',1);
insert into city(name,fk_country) values('Sulina (PR)',1);
insert into city(name,fk_country) values('Sumaré (SP)',1);
insert into city(name,fk_country) values('Sumé (PB)',1);
insert into city(name,fk_country) values('Sumidouro (RJ)',1);
insert into city(name,fk_country) values('Surubim (PE)',1);
insert into city(name,fk_country) values('Sussuapara (PI)',1);
insert into city(name,fk_country) values('Suzanápolis (SP)',1);
insert into city(name,fk_country) values('Suzano (SP)',1);
insert into city(name,fk_country) values('Touros (RN)',1);
insert into city(name,fk_country) values('Trabiju (SP)',1);
insert into city(name,fk_country) values('Tracuateua (PA)',1);
insert into city(name,fk_country) values('Tracunhaém (PE)',1);
insert into city(name,fk_country) values('Traipu (AL)',1);
insert into city(name,fk_country) values('Trairão (PA)',1);
insert into city(name,fk_country) values('Trairi (CE)',1);
insert into city(name,fk_country) values('Trajano de Moraes (RJ)',1);
insert into city(name,fk_country) values('Tramandaí (RS)',1);
insert into city(name,fk_country) values('Travesseiro (RS)',1);
insert into city(name,fk_country) values('Tremedal (BA)',1);
insert into city(name,fk_country) values('Tremembé (SP)',1);
insert into city(name,fk_country) values('Três Arroios (RS)',1);
insert into city(name,fk_country) values('Três Barras do Paraná (PR)',1);
insert into city(name,fk_country) values('Três Barras (SC)',1);
insert into city(name,fk_country) values('Três Cachoeiras (RS)',1);
insert into city(name,fk_country) values('Três Corações (MG)',1);
insert into city(name,fk_country) values('Três Coroas (RS)',1);
insert into city(name,fk_country) values('Três de Maio (RS)',1);
insert into city(name,fk_country) values('Três Forquilhas (RS)',1);
insert into city(name,fk_country) values('Três Fronteiras (SP)',1);
insert into city(name,fk_country) values('Três Lagoas (MS)',1);
insert into city(name,fk_country) values('Três Marias (MG)',1);
insert into city(name,fk_country) values('Três Palmeiras (RS)',1);
insert into city(name,fk_country) values('Três Passos (RS)',1);
insert into city(name,fk_country) values('Três Pontas (MG)',1);
insert into city(name,fk_country) values('Três Ranchos (GO)',1);
insert into city(name,fk_country) values('Três Rios (RJ)',1);
insert into city(name,fk_country) values('Treviso (SC)',1);
insert into city(name,fk_country) values('Treze de Maio (SC)',1);
insert into city(name,fk_country) values('Treze Tílias (SC)',1);
insert into city(name,fk_country) values('Trizidela do Vale (MA)',1);
insert into city(name,fk_country) values('Trindade (GO)',1);
insert into city(name,fk_country) values('Trindade (PE)',1);
insert into city(name,fk_country) values('Trindade do Sul (RS)',1);
insert into city(name,fk_country) values('Triunfo (PB)',1);
insert into city(name,fk_country) values('Triunfo (PE)',1);
insert into city(name,fk_country) values('Triunfo (RS)',1);
insert into city(name,fk_country) values('Triunfo Potiguar (RN)',1);
insert into city(name,fk_country) values('Trombas (GO)',1);
insert into city(name,fk_country) values('Trombudo Central (SC)',1);
insert into city(name,fk_country) values('Tubarão (SC)',1);
insert into city(name,fk_country) values('Tucano (BA)',1);
insert into city(name,fk_country) values('Tucumã (PA)',1);
insert into city(name,fk_country) values('Tucunduva (RS)',1);
insert into city(name,fk_country) values('Tucuruí (PA)',1);
insert into city(name,fk_country) values('Tufilândia (MA)',1);
insert into city(name,fk_country) values('Tuiuti (SP)',1);
insert into city(name,fk_country) values('Tumiritinga (MG)',1);
insert into city(name,fk_country) values('Tunápolis (SC)',1);
insert into city(name,fk_country) values('Tunas do Paraná (PR)',1);
insert into city(name,fk_country) values('Tunas (RS)',1);
insert into city(name,fk_country) values('Tuneiras do Oeste (PR)',1);
insert into city(name,fk_country) values('Tuntum (MA)',1);
insert into city(name,fk_country) values('Tupaciguara (MG)',1);
insert into city(name,fk_country) values('Tupanatinga (PE)',1);
insert into city(name,fk_country) values('Tupanci do Sul (RS)',1);
insert into city(name,fk_country) values('Tupanciretã (RS)',1);
insert into city(name,fk_country) values('Tupandi (RS)',1);
insert into city(name,fk_country) values('Tuparendi (RS)',1);
insert into city(name,fk_country) values('Tuparetama (PE)',1);
insert into city(name,fk_country) values('Tupã (SP)',1);
insert into city(name,fk_country) values('Tupãssi (PR)',1);
insert into city(name,fk_country) values('Tupi Paulista (SP)',1);
insert into city(name,fk_country) values('Tupirama (TO)',1);
insert into city(name,fk_country) values('Tupiratins (TO)',1);
insert into city(name,fk_country) values('Turiaçu (MA)',1);
insert into city(name,fk_country) values('Turilândia (MA)',1);
insert into city(name,fk_country) values('Turiúba (SP)',1);
insert into city(name,fk_country) values('Turmalina (MG)',1);
insert into city(name,fk_country) values('Turmalina (SP)',1);
insert into city(name,fk_country) values('Turuçu (RS)',1);
insert into city(name,fk_country) values('Tururu (CE)',1);
insert into city(name,fk_country) values('Turvânia (GO)',1);
insert into city(name,fk_country) values('Turvelândia (GO)',1);
insert into city(name,fk_country) values('Turvo (PR)',1);
insert into city(name,fk_country) values('Turvo (SC)',1);
insert into city(name,fk_country) values('Turvolândia (MG)',1);
insert into city(name,fk_country) values('Tutóia (MA)',1);
insert into city(name,fk_country) values('Urbano Santos (MA)',1);
insert into city(name,fk_country) values('Uru (SP)',1);
insert into city(name,fk_country) values('Uruaçu (GO)',1);
insert into city(name,fk_country) values('Uruana (GO)',1);
insert into city(name,fk_country) values('Uruana de Minas (MG)',1);
insert into city(name,fk_country) values('Uruará (PA)',1);
insert into city(name,fk_country) values('Urubici (SC)',1);
insert into city(name,fk_country) values('Uruburetama (CE)',1);
insert into city(name,fk_country) values('Urucânia (MG)',1);
insert into city(name,fk_country) values('Urucará (AM)',1);
insert into city(name,fk_country) values('Uruçuca (BA)',1);
insert into city(name,fk_country) values('Uruçuí (PI)',1);
insert into city(name,fk_country) values('Urucuia (MG)',1);
insert into city(name,fk_country) values('Urucurituba (AM)',1);
insert into city(name,fk_country) values('Uruguaiana (RS)',1);
insert into city(name,fk_country) values('Uruoca (CE)',1);
insert into city(name,fk_country) values('Urupá (RO)',1);
insert into city(name,fk_country) values('Urupema (SC)',1);
insert into city(name,fk_country) values('Urupês (SP)',1);
insert into city(name,fk_country) values('Urussanga (SC)',1);
insert into city(name,fk_country) values('Urutaí (GO)',1);
insert into city(name,fk_country) values('Utinga (BA)',1);
insert into city(name,fk_country) values('Vila Bela da Santíssima Trindade (MT)',1);
insert into city(name,fk_country) values('Vila Boa (GO)',1);
insert into city(name,fk_country) values('Vila Flores (RS)',1);
insert into city(name,fk_country) values('Vila Flor (RN)',1);
insert into city(name,fk_country) values('Vila Lângaro (RS)',1);
insert into city(name,fk_country) values('Vila Maria (RS)',1);
insert into city(name,fk_country) values('Vila Nova do Piauí (PI)',1);
insert into city(name,fk_country) values('Vila Nova dos Martírios (MA)',1);
insert into city(name,fk_country) values('Vila Nova do Sul (RS)',1);
insert into city(name,fk_country) values('Vila Pavão (ES)',1);
insert into city(name,fk_country) values('Vila Propício (GO)',1);
insert into city(name,fk_country) values('Vila Rica (MT)',1);
insert into city(name,fk_country) values('Vila Valério (ES)',1);
insert into city(name,fk_country) values('Vila Velha (ES)',1);
insert into city(name,fk_country) values('Vilhena (RO)',1);
insert into city(name,fk_country) values('Vinhedo (SP)',1);
insert into city(name,fk_country) values('Viradouro (SP)',1);
insert into city(name,fk_country) values('Virgem da Lapa (MG)',1);
insert into city(name,fk_country) values('Virgínia (MG)',1);
insert into city(name,fk_country) values('Virginópolis (MG)',1);
insert into city(name,fk_country) values('Virgolândia (MG)',1);
insert into city(name,fk_country) values('Virmond (PR)',1);
insert into city(name,fk_country) values('Visconde do Rio Branco (MG)',1);
insert into city(name,fk_country) values('Vista Alegre (RS)',1);
insert into city(name,fk_country) values('Vista Alegre do Alto (SP)',1);
insert into city(name,fk_country) values('Vista Alegre do Prata (RS)',1);
insert into city(name,fk_country) values('Vista Gaúcha (RS)',1);
insert into city(name,fk_country) values('Vista Serrana (PB)',1);
insert into city(name,fk_country) values('Vitória (ES)',1);
insert into city(name,fk_country) values('Vitória Brasil (SP)',1);
insert into city(name,fk_country) values('Vitória da Conquista (BA)',1);
insert into city(name,fk_country) values('Vitória das Missões (RS)',1);
insert into city(name,fk_country) values('Vitória de Santo Antão (PE)',1);
insert into city(name,fk_country) values('Vitória do Jari (AP)',1);
insert into city(name,fk_country) values('Vitória do Mearim (MA)',1);
insert into city(name,fk_country) values('Vitória do Xingu (PA)',1);
insert into city(name,fk_country) values('Vitorino (PR)',1);
insert into city(name,fk_country) values('Vitorino Freire (MA)',1);
insert into city(name,fk_country) values('Vitor Meireles (SC)',1);
insert into city(name,fk_country) values('Viseu (PA)',1);
insert into city(name,fk_country) values('Volta Grande (MG)',1);
insert into city(name,fk_country) values('Volta Redonda (RJ)',1);
insert into city(name,fk_country) values('Votorantim (SP)',1);
insert into city(name,fk_country) values('Votuporanga (SP)',1);
insert into city(name,fk_country) values('Wenceslau Guimarães (BA)',1);
insert into city(name,fk_country) values('Westfália (RS)',1);
insert into city(name,fk_country) values('Witmarsum (SC)',1);
insert into city(name,fk_country) values('Xexéu (PE)',1);
insert into city(name,fk_country) values('Xinguara (PA)',1);
insert into city(name,fk_country) values('Xique-Xique (BA)',1);
insert into city(name,fk_country) values('Zortéa (SC)',1);