insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', 1, 'Fuga B, Cerdeira L, Andrade F, Zaccariotto T, Esposito F, Cardoso B, Rodrigues L,Neves I, Levy CE, Lincopan N. Genome Sequences of Clinical Isolates of NDM-1-Producing Klebsiella quasipneumoniae subsp. similipneumoniae and KPC-2-Producing Klebsiella quasipneumoniae subsp. quasipneumoniae from Brazil.Microbiol Resour Announc. 2020 Mar 5;9(10). pii: e00089-20.doi:10.1128/MRA.00089-20.', 'https://www.ncbi.nlm.nih.gov/pubmed/32139569', '2020-03-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Zamparette CP, Schorner M, Campos E, Moura Q, Cerdeira L, Tartari DC, Sereia AFR, Cunha P, Fontana H, de Oliveira LFV, Grisard EC, Lincopan N, Bazzo ML, Sincero TCM. IncX4 Plasmid-Mediated mcr-1.1 in Polymyxin-Resistant Escherichia coli from Outpatients in Santa Catarina, Southern Brazil. Microb Drug Resist. 2020 Jan 31. doi: 10.1089/mdr.2019.0203.', 'https://www.ncbi.nlm.nih.gov/pubmed/32004096', '2020-01-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Fuga B, Ferreira ML, Cerdeira LT, de Campos PA, Dias VL, Rossi I, Machado LG, Lincopan N, Gontijo-Filho PP, Ribas RM. Novel small IncX3 plasmid carrying the bla KPC-2 gene in high-risk Klebsiella pneumoniae ST11/CG258. Diagn Microbiol Infect Dis. 2020 Feb;96(2):114900. doi: 10.1016/j.diagmicrobio.2019.114900.', 'https://www.ncbi.nlm.nih.gov/pubmed/31859023', '2020-02-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Valencia-Bacca J, Silva MM, Cerdeira L, Esposito F, Cardoso B, Muñoz ME, Jiménez-Villegas T, Cardenas-Arias A, Pessoa DAN, Lincopan N. Detection and Whole-Genome Analysis of a High-Risk Clone of Klebsiella pneumoniae ST340/CG258 Producing CTX-M-15 in a Companion Animal. Microb Drug Resist. 2019 Dec 6. doi: 10.1089/mdr.2019.0190.', 'https://www.ncbi.nlm.nih.gov/pubmed/31809242', '2019-12-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Fernandes MR, Sellera FP, Moura Q, Esposito F, Sabino CP, Lincopan N. Identification and genomic features of halotolerant extended-spectrum-β-lactamase (CTX-M)-producing Escherichia coli in urban-impacted coastal waters, Southeast Brazil. Mar Pollut Bull. 2020 Jan;150:110689. doi:10.1016/j.marpolbul.2019.110689.', 'https://www.ncbi.nlm.nih.gov/pubmed/31733900', '2020-01-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Sartori L, Sellera FP, Moura Q, Cardoso B, Cerdeira L, Lincopan N. Multidrug- resistant CTX-M-15-positive Klebsiella pneumoniae ST307 causing urinary tract infection in a dog in Brazil. J Glob Antimicrob Resist. 2019 Dec;19:96-97. doi: 10.1016/j.jgar.2019.09.003.', 'https://www.ncbi.nlm.nih.gov/pubmed/31520809', '2019-12-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Monte DF, Lincopan N, Berman H, Cerdeira L, Keelara S, Thakur S, Fedorka-Cray PJ, Landgraf M. Genomic Features of High-Priority Salmonella enterica Serovars Circulating in the Food Production Chain, Brazil, 2000-2016. Sci Rep. 2019 Jul 30;9(1):11058. doi: 10.1038/s41598-019-45838-0.', 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6667439/', '2019-07-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Monte DF, Lincopan N, Cerdeira L, Fedorka-Cray PJ, Landgraf M. Early Dissemination of qnrE1 in Salmonella enterica Serovar Typhimurium from Livestock in South America. Antimicrob Agents Chemother. 2019 Aug 23;63(9). pii: e00571- 19. doi: 10.1128/AAC.00571-19.', 'https://www.ncbi.nlm.nih.gov/pubmed/31235627', '2019-08-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Campos PA, Fuga B, Cerdeira LT, Ferreira ML, Dias VL, Machado LG, Rossi I, Lincopan N, Gontijo-Filho PP, Ribas RM. Early Dissemination of IncQ1 Plasmids in KPC-2-Producing Klebsiella pneumoniae CG258. Microb Drug Resist. 2019 Oct;25(8):1257-1259. doi: 10.1089/mdr.2019.0123.', 'https://www.ncbi.nlm.nih.gov/pubmed/31188044', '2019-10-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Rueda Furlan JP, Moura Q, Lima Gonzalez IH, Locosque Ramos P, Lincopan N, Guedes Stehling E. Draft genome sequence of a multidrug-resistant CTX-M-65- producing Escherichia coli ST156 colonizing a giant anteater (Myrmecophaga tridactyla) in a Zoo. J Glob Antimicrob Resist. 2019 Jun;17:19-20. doi: 10.1016/j.jgar.2019.03.005.', 'https://www.ncbi.nlm.nih.gov/pubmed/30877057', '2019-06-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Goldberg DW, Fernandes MR, Sellera FP, Costa DGC, Loureiro Bracarense AP, Lincopan N. Genetic background of CTX-M-15-producing Enterobacter hormaechei ST114 and Citrobacter freundii ST265 co-infecting a free-living green turtle (Chelonia mydas). Zoonoses Public Health. 2019 Aug;66(5):540-545. doi:10.1111/zph.12572.', 'https://www.ncbi.nlm.nih.gov/pubmed/30843359', '2019-08-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Monte DF, Sellera FP, Fernandes MR, Moura Q, Landgraf M, Lincopan N. Genome Sequencing of an Escherichia coli Sequence Type 617 Strain Isolated from Beach Ghost Shrimp (Callichirus major) from a Heavily Polluted Ecosystem Reveals a Wider Resistome against Heavy Metals and Antibiotics. Microbiol Resour Announc. 2019 Jan 17;8(3). pii: e01471-18. doi: 10.1128/MRA.01471-18.', 'https://www.ncbi.nlm.nih.gov/pubmed/30687831', '2019-01-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Cerdeira LT, Lam MMC, Wyres KL, Wick RR, Judd LM, Lopes R, Ribas RM, Morais MM, Holt KE, Lincopan N. Small IncQ1 and Col-Like Plasmids Harboring bla KPC-2 and Non-Tn4401 Elements (NTE KPC -IId) in High-Risk Lineages of Klebsiella pneumoniae CG258. Antimicrob Agents Chemother. 2019 Feb 26;63(3). pii: e02140- 18. doi: 10.1128/AAC.02140-18.', 'https://www.ncbi.nlm.nih.gov/pubmed/30602517', '2019-02-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Francisco GR, Bueno MFC, Cerdeira L, Lincopan N, Ienne S, Souza TA, de Oliveira Garcia D. Draft genome sequences of KPC-2- and CTX-M-15-producing Klebsiella pneumoniae ST437 isolated from a clinical sample and urban rivers in Sao Paulo, Brazil. J Glob Antimicrob Resist. 2019 Mar;16:74-75. doi:10.1016/j.jgar.2018.12.003.', 'https://www.ncbi.nlm.nih.gov/pubmed/30578976', '2019-03-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'de Carvalho MPN, Moura Q, Fernandes MR, Sellera FP, Pagotto AH, Stuginski DR, Castro RA, Sant&#39;Anna SS, Grego KF, Lincopan N. Genomic features of a multidrug- resistant Enterobacter cloacae ST279 producing CTX-M-15 and AAC(6&#39;)-Ib-cr isolated from fatal infectious stomatitis in a crossed pit viper (Bothrops alternatus). J Glob Antimicrob Resist. 2018 Dec;15:290-291. doi: 10.1016/j.jgar.2018.11.009.', 'https://www.ncbi.nlm.nih.gov/pubmed/30448520', '2018-12-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Silva MM, Sellera FP, Fernandes MR, Moura Q, Garino F, Azevedo SS, Lincopan N. Genomic features of a highly virulent, ceftiofur-resistant, CTX-M-8-producing Escherichia coli ST224 causing fatal infection in a domestic cat. J Glob Antimicrob Resist. 2018 Dec;15:252-253. doi: 10.1016/j.jgar.2018.10.023.', 'https://www.ncbi.nlm.nih.gov/pubmed/30404045', '2018-12-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Sacramento AG, Fernandes MR, Sellera FP, Muñoz ME, Vivas R, Dolabella SS, Lincopan N. Genomic analysis of MCR-1 and CTX-M-8 co-producing Escherichia coli ST58 isolated from a polluted mangrove ecosystem in Brazil. J Glob Antimicrob Resist. 2018 Dec;15:288-289. doi: 10.1016/j.jgar.2018.10.024.', 'https://www.ncbi.nlm.nih.gov/pubmed/30404044', '2018-12-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Sellera FP, Fernandes MR, Moura Q, Carvalho MPN, Lincopan N. Extended- spectrum-β-lactamase (CTX-M)-producing Escherichia coli in wild fishes from a polluted area in the Atlantic Coast of South America. Mar Pollut Bull. 2018 Oct;135:183-186. doi: 10.1016/j.marpolbul.2018.07.012.', 'https://www.ncbi.nlm.nih.gov/pubmed/30301029', '2018-10-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Fernandes MR, Sellera FP, Moura Q, Gaspar VC, Cerdeira L, Lincopan N. International high-risk clonal lineages of CTX-M-producing Escherichia coli F- ST648 in free-roaming cats, South America. Infect Genet Evol. 2018 Dec;66:48-51. doi: 10.1016/j.meegid.2018.09.009.', 'https://www.ncbi.nlm.nih.gov/pubmed/30227226', '2018-12-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Fernandes MR, Cerdeira L, Silva MM, Sellera FP, Muñoz M, Junior FG, Azevedo SS, Power P, Gutkind G, Lincopan N. Novel mcr-5.3 variant in a CTX-M-8- producing Escherichia coli ST711 isolated from an infected horse. J Antimicrob Chemother. 2018 Dec 1;73(12):3520-3522. doi:10.1093/jac/dky341.', 'https://www.ncbi.nlm.nih.gov/pubmed/30202925', '2018-12-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Silva MM, Fernandes MR, Sellera FP, Cerdeira L, Medeiros LKG, Garino F, Azevedo SS, Lincopan N. Multidrug-resistant CTX-M-15-producing Klebsiella pneumoniae ST231 associated with infection and persistent colonization of dog. Diagn Microbiol Infect Dis. 2018 Nov;92(3):259-261. doi: 10.1016/j.diagmicrobio.2018.06.012.', 'https://www.ncbi.nlm.nih.gov/pubmed/30025966', '2018-11-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Melo LC, Oresco C, Leigue L, Netto HM, Melville PA, Benites NR, Saras E, Haenni M, Lincopan N, Madec JY. Prevalence and molecular features of ESBL/pAmpC- producing Enterobacteriaceae in healthy and diseased companion animals in Brazil. Vet Microbiol. 2018 Jul;221:59-66. doi: 10.1016/j.vetmic.2018.05.017.', 'https://www.ncbi.nlm.nih.gov/pubmed/29981709', '2018-07-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Oliveira FA, Zaccariotto TR, Piveta C, Hofling CC, Resende MR, Levy CE, Esposito F, Fernandes MR, Cerdeira L, Lincopan N. MCR-1-positive colistin-resistant Escherichia coli in immunocompromised hospitalised patients. Int J Antimicrob Agents. 2018 Sep;52(3):438-440. doi: 10.1016/j.ijantimicag.2018.06.011.', 'https://www.ncbi.nlm.nih.gov/pubmed/29944955', '2018-09-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Sellera FP, Fernandes MR, Moura Q, Lopes RB, Souza TA, Cerdeira L, Lincopan N. Draft genome sequence of a bla CMY-2 /IncI1-harbouring Escherichia coli D:ST457 isolated from coastal benthic organisms. J Glob Antimicrob Resist. 2018 Sep;14:83- 84. doi: 10.1016/j.jgar.2018.06.010.', 'https://www.ncbi.nlm.nih.gov/pubmed/29944920', '2018-09-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Sellera FP, Fernandes MR, Ruiz R, Falleiros ACM, Rodrigues FP, Cerdeira L, Lincopan N. Identification of KPC-2-producing Escherichia coli in a companion animal: a new challenge for veterinary clinicians. J Antimicrob Chemother. 2018 Aug 1;73(8):2259-2261. doi: 10.1093/jac/dky173.', 'https://www.ncbi.nlm.nih.gov/pubmed/29800301', '2018-08-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Casella T, de Morais ABZ, de Paula Barcelos DD, Tolentino FM, Cerdeira LT, Bueno MFC, Francisco GR, de Andrade LN, da Costa Darini AL, de Oliveira Garcia D, Lincopan N, Nogueira MCL. Draft genome sequence of a KPC-2-producing Klebsiella pneumoniae ST340 carrying bla CTX-M-15 and bla CTX-M-59 genes: a rich genome of mobile genetic elements and genes encoding antibiotic resistance. J Glob Antimicrob Resist. 2018 Jun;13:35-36. doi: 10.1016/j.jgar.2018.02.011.', 'https://www.ncbi.nlm.nih.gov/pubmed/29476983', '2018-06-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Fernandes MR, Sellera FP, Moura Q, Souza TA, Lincopan N. Draft genome sequence of a CTX-M-8, CTX-M-55 and FosA3 co-producing Escherichia coli ST117/B2 isolated from an asymptomatic carrier. J Glob Antimicrob Resist. 2018 Mar;12:183-184. doi:10.1016/j.jgar.2018.01.015.', 'https://www.ncbi.nlm.nih.gov/pubmed/29412182', '2018-03-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Moura Q, Esposito F, Fernandes MR, Espinoza-Muñoz M, Souza TA, Santos SR, Cerdeira L, Cassettari V, Lincopan N. Genome sequence analysis of a hypermucoviscous/hypervirulent and MDR CTX-M-15/K19/ST29 Klebsiella pneumoniae isolated from human infection. Pathog Dis. 2017 Dec 29;75(9). doi:10.1093/femspd/ftx121.', 'https://www.ncbi.nlm.nih.gov/pubmed/29228178', '2017-12-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Sartori L, Fernandes MR, Ienne S, de Souza TA, Gregory L, Cerdeira L, Lincopan N. Draft genome sequences of two fluoroquinolone-resistant CTX-M-15-producing Escherichia coli ST90 (ST23 complex) isolated from a calf and a dairy cow in South America. J Glob Antimicrob Resist. 2017 Dec;11:145-147. doi:10.1016/j.jgar.2017.10.009.', 'https://www.ncbi.nlm.nih.gov/pubmed/29111480', '2017-12-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Cunha MPV, Davies YM, Cerdeira L, Dropa M, Lincopan N, Knöbl T. Complete DNA Sequence of an IncM1 Plasmid Bearing the Novel qnrE1 Plasmid-Mediated Quinolone Resistance Variant and bla CTX-M-8 from Klebsiella pneumoniae Sequence Type 147. Antimicrob Agents Chemother. 2017 Aug 24;61(9). pii: e00592-17. doi:10.1128/AAC.00592-17.', 'https://www.ncbi.nlm.nih.gov/pubmed/28652231', '2017-08-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Lopes R, Cerdeira LT, Fernandes MR, Pérez-Chaparro PJ, McCulloch JA, Lincopan N. Draft genome sequence of a CTX-M-15-producing endophytic Klebsiella pneumoniae ST198 isolate from commercial lettuce. J Glob Antimicrob Resist. 2017 Sep;10:19-20. doi: 10.1016/j.jgar.2017.03.005.', 'https://www.ncbi.nlm.nih.gov/pubmed/28576742', '2017-09-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Casella T, Cerdeira LT, Fernandes MR, Souza TA, Haenni M, Madec JY, Lincopan N, Nogueira MCL. Draft genome sequence of a CTX-M-15-producing Escherichia coli ST345 from commercial chicken meat in Brazil. J Glob Antimicrob Resist. 2017 Jun;9:124-125. doi: 10.1016/j.jgar.2017.04.002.', 'https://www.ncbi.nlm.nih.gov/pubmed/28559168', '2017-06-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Monte DF, Fernandes MR, Cerdeira L, de Souza TA, Mem A, Franco BDGM, Landgraf M, Lincopan N. Draft Genome Sequences of Colistin-Resistant MCR-1- Producing Escherichia coli ST1850 and ST74 Strains Isolated from Commercial Chicken Meat. Genome Announc. 2017 May 18;5(20). pii: e00329-17. doi: 10.1128/genomeA.00329-17.', 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5442378/', '2017-05-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Nascimento T, Cantamessa R, Melo L, Fernandes MR, Fraga E, Dropa M, Sato MIZ, Cerdeira L, Lincopan N. International high-risk clones of Klebsiella pneumoniae KPC-2/CC258 and Escherichia coli CTX-M-15/CC10 in urban lake waters. Sci Total Environ. 2017 Nov 15;598:910-915. doi: 10.1016/j.scitotenv.2017.03.207.', 'https://www.ncbi.nlm.nih.gov/pubmed/28458208', '2017-11-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Fernandes MR, Sellera FP, Esposito F, Sabino CP, Cerdeira L, Lincopan N. Colistin- Resistant mcr-1-Positive Escherichia coli on Public Beaches, an Infectious Threat Emerging in Recreational Waters. Antimicrob Agents Chemother. 2017 Jun 27;61(7). pii: e00234-17. doi:10.1128/AAC.00234-17.', 'https://www.ncbi.nlm.nih.gov/pubmed/28416556', '2017-06-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Monte DF, Mem A, Fernandes MR, Cerdeira L, Esposito F, Galvão JA, Franco BDGM, Lincopan N, Landgraf M. Chicken Meat as a Reservoir of Colistin-Resistant Escherichia coli Strains Carrying mcr-1 Genes in South America. Antimicrob Agents Chemother. 2017 Apr 24;61(5). pii: e02718-16. doi: 10.1128/AAC.02718-16.', 'https://www.ncbi.nlm.nih.gov/pubmed/28193665', '2017-04-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Cerdeira L, Fernandes MR, Ienne S, Souza TA, de O Garcia D, Lincopan N. Draft genome sequence of an environmental multidrug-resistant Klebsiella pneumoniae ST340/CC258 harbouring bla CTX-M-15 and bla KPC-2 genes. J Glob Antimicrob Resist. 2017 Mar;8:108-109. doi:10.1016/j.jgar.2016.12.001.', 'https://www.ncbi.nlm.nih.gov/pubmed/28082142', '2017-03-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Sellera FP, Fernandes MR, Sartori L, Carvalho MP, Esposito F, Nascimento CL, Dutra GH, Mamizuka EM, Pérez-Chaparro PJ, McCulloch JA, Lincopan N. Escherichia coli carrying IncX4 plasmid-mediated mcr-1 and bla CTX-M genes in infected migratory Magellanic penguins (Spheniscus magellanicus). J Antimicrob Chemother. 2017 Apr 1;72(4):1255-1256. doi: 10.1093/jac/dkw543.', 'https://www.ncbi.nlm.nih.gov/pubmed/28031274', '2017-04-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Moura Q, Fernandes MR, Cerdeira L, Ienne S, Souza TA, Negrão FJ, Lincopan N. Draft genome sequence of a multidrug-resistant CMY-2-producing Salmonella enterica subsp. enterica serovar Minnesota ST3088 isolated from chicken meat. J Glob Antimicrob Resist. 2017 Mar;8:67-69. doi: 10.1016/j.jgar.2016.10.011.', 'https://www.ncbi.nlm.nih.gov/pubmed/28017672', '2017-03-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Cerdeira L, Fernandes MR, Francisco GR, Bueno MF, Ienne S, Souza TA, de Oliveira Garcia D, Lincopan N. Draft Genome Sequence of a Hospital-Associated Clone of Klebsiella pneumoniae ST340/CC258 Coproducing RmtG and KPC-2 Isolated from a Pediatric Patient. Genome Announc. 2016 Nov 3;4(6). pii: e01130- 16. doi:10.1128/genomeA.01130-16.', 'https://www.ncbi.nlm.nih.gov/pubmed/27811089', '2016-11-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Cerdeira L, Silva KC, Fernandes MR, Ienne S, de Souza TA, de Oliveira Garcia D, Moreno AM, Lincopan N. Draft genome sequence of a CTX-M-15-producing Klebsiella pneumoniae sequence type 340 (clonal complex 258) isolate from a food- producing animal. J Glob Antimicrob Resist. 2016 Dec;7:67-68. doi: 10.1016/j.jgar.2016.07.012.', 'https://www.ncbi.nlm.nih.gov/pubmed/27664870', '2016-12-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Fernandes MR, McCulloch JA, Vianello MA, Moura Q, Pérez-Chaparro PJ, Esposito F, Sartori L, Dropa M, Matté MH, Lira DP, Mamizuka EM, Lincopan N. First Report of the Globally Disseminated IncX4 Plasmid Carrying the mcr-1 Gene in a Colistin- Resistant Escherichia coli Sequence Type 101 Isolate from a Human Infection in Brazil. Antimicrob Agents Chemother. 2016 Sep 23;60(10):6415-7. doi:10.1128/AAC.01325-16.', 'https://www.ncbi.nlm.nih.gov/pubmed/27503650', '2016-09-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Fernandes MR, Moura Q, Sartori L, Silva KC, Cunha MP, Esposito F, Lopes R, Otutumi LK, Gonçalves DD, Dropa M, Matté MH, Monte DF, Landgraf M, Francisco GR, Bueno MF, de Oliveira Garcia D, Knöbl T, Moreno AM, Lincopan N. Silent dissemination of colistin-resistant Escherichia coli in South America could contribute to the global spread of the mcr-1 gene. Euro Surveill. 2016 Apr 28;21(17). doi: 10.2807/1560-7917.ES.2016.21.17.30214.', 'https://www.ncbi.nlm.nih.gov/pubmed/27168587', '2016-04-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Dropa M, Lincopan N, Balsalobre LC, Oliveira DE, Moura RA, Fernandes MR, da Silva QM, Matté GR, Sato MI, Matté MH. Genetic background of novel sequence types of CTX-M-8- and CTX-M-15-producing Escherichia coli and Klebsiella pneumoniae from public wastewater treatment plants in São Paulo, Brazil. Environ Sci Pollut Res Int. 2016 Mar;23(5):4953-8. doi:10.1007/s11356-016-6079-5.', 'https://www.ncbi.nlm.nih.gov/pubmed/26782324', '2016-03-01', true);
insert into publication (type, "order", title_pt, link, date, active) VALUES('PUBLICATION', (select max("order")+1 from publication), 'Moura Q, Fernandes MR, Silva KC, Monte DF, Esposito F, Dropa M, Noronha C, Moreno AM, Landgraf M, Negrão FJ, Lincopan N. Virulent nontyphoidal Salmonella producing CTX-M and CMY-2 β-lactamases from livestock, food and human infection, Brazil. Virulence. 2018 Jan 1;9(1):281-286. doi:10.1080/21505594.2017.1279779.', 'https://www.ncbi.nlm.nih.gov/pubmed/28102761', '2018-01-01', true);

-- TECHNICAL INFO
insert into publication (type, "order", title_pt, title_en, link, active) VALUES('POP', (select max("order")+1 from publication), 'Preparo de biblioteca para sequenciamento (Illumina).', 'Library Preparation for genomic sequencing - NGS (Illumina).',
'https://doi.org/10.6084/m9.figshare.11965449.v2', true);
insert into publication (type, "order", title_pt, title_en, link, active) VALUES('POP', (select max("order")+1 from publication), 'Análise de clonalidade pela técnica ERIC-PCR.', 'Clonality analysis using the ERIC-PCR technique.',
'https://doi.org/10.6084/m9.figshare.11968452.v1', true);
insert into publication (type, "order", title_pt, title_en, link, active) VALUES('POP', (select max("order")+1 from publication), 'Extração de DNA Genômico para Sequenciamento (Illumina).', 'DNA extraction for sequencing (Illumina).',
'https://doi.org/10.6084/m9.figshare.11968509.v1', true);
insert into publication (type, "order", title_pt, title_en, link, active) VALUES('POP', (select max("order")+1 from publication), 'Extração de DNA Genômico para Sequenciamento (Nanopore).', 'DNA extraction for sequencing (Nanopore).',
'https://doi.org/10.6084/m9.figshare.11968518.v1', true);
insert into publication (type, "order", title_pt, title_en, link, active) VALUES('POP', (select max("order")+1 from publication), 'Quantificação de DNA Genômico (Nanodrop)', 'DNA quantification (Nanodrop).',
'https://doi.org/10.6084/m9.figshare.11968524.v1', true);
insert into publication (type, "order", title_pt, title_en, link, active) VALUES('POP', (select max("order")+1 from publication), 'Quantificação de DNA Genômico (Qubit)', 'DNA quantification (Qubit).',
'https://doi.org/10.6084/m9.figshare.11968539.v1', true);
insert into publication (type, "order", title_pt, title_en, link, active) VALUES('POP', (select max("order")+1 from publication), 'Reação em cadeia da polimerase (PCR).', 'Polymerase Chain Reaction (PCR).',
'https://doi.org/10.6084/m9.figshare.11968548.v1', true);
insert into publication (type, "order", title_pt, title_en, link, active) VALUES('POP', (select max("order")+1 from publication), 'Testes fenotípicos de resistência.', 'Phenotypic tests to assess bacterial resistance.',
'https://doi.org/10.6084/m9.figshare.11968554.v2', true);
insert into publication (type, "order", title_pt, title_en, link, active) VALUES('POP', (select max("order")+1 from publication), 'Teste de Susceptibilidade para Bactérias Gram-negativas.', 'Bacterial susceptibility test.',
'https://doi.org/10.6084/m9.figshare.11968587.v1', true);

-- VIDEO
insert into publication (type, "order", title_pt, title_en, active) VALUES('VIDEO', (select max("order")+1 from publication),
'Extração de DNA para sequenciamento (Illumina).', 'DNA extraction for sequencing (Illumina).', true);
insert into publication (type, "order", title_pt, title_en, active) VALUES('VIDEO', (select max("order")+1 from publication),
'Extração de DNA para sequenciamento (Nanopore).', 'DNA extraction for sequencing (Nanopore).', true);
insert into publication (type, "order", title_pt, title_en, active) VALUES('VIDEO', (select max("order")+1 from publication),
'Biblioteca e sequenciamento (Illumina).', 'Library preparation and sequencing (Illumina).', true);
insert into publication (type, "order", title_pt, title_en, active) VALUES('VIDEO', (select max("order")+1 from publication),
'Biblioteca e sequenciamento (Nanopore).', 'Library preparation and sequencing (Nanopore).', true);
