alter table antibiogram alter column mer drop not null;
alter table antibiogram alter column etp drop not null;
alter table antibiogram alter column ipm drop not null;
alter table antibiogram alter column cro drop not null;
alter table antibiogram alter column caz drop not null;
alter table antibiogram alter column cfx drop not null;
alter table antibiogram alter column cpm drop not null;
alter table antibiogram alter column ctx drop not null;
alter table antibiogram alter column nal drop not null;
alter table antibiogram alter column cip drop not null;
alter table antibiogram alter column amc drop not null;
alter table antibiogram alter column atm drop not null;
alter table antibiogram alter column ami drop not null;
alter table antibiogram alter column gen drop not null;
alter table antibiogram alter column sxt drop not null;
alter table antibiogram alter column eno drop not null;
alter table antibiogram alter column chl drop not null;
alter table antibiogram alter column fos drop not null;
alter table antibiogram alter column cep drop not null;
alter table antibiogram alter column ctf drop not null;
alter table antibiogram alter column amp drop not null;
alter table antibiogram alter column tet drop not null;
alter table antibiogram alter column col drop not null;

update antibiogram set mer = null where mer = '-';
update antibiogram set etp = null where etp = '-';
update antibiogram set ipm = null where ipm = '-';
update antibiogram set cro = null where cro = '-';
update antibiogram set caz = null where caz = '-';
update antibiogram set cfx = null where cfx = '-';
update antibiogram set cpm = null where cpm = '-';
update antibiogram set ctx = null where ctx = '-';
update antibiogram set nal = null where nal = '-';
update antibiogram set cip = null where cip = '-';
update antibiogram set amc = null where amc = '-';
update antibiogram set atm = null where atm = '-';
update antibiogram set ami = null where ami = '-';
update antibiogram set gen = null where gen = '-';
update antibiogram set sxt = null where sxt = '-';
update antibiogram set eno = null where eno = '-';
update antibiogram set chl = null where chl = '-';
update antibiogram set fos = null where fos = '-';
update antibiogram set cep = null where cep = '-';
update antibiogram set ctf = null where ctf = '-';
update antibiogram set amp = null where amp = '-';
update antibiogram set tet = null where tet = '-';
update antibiogram set col = null where col = '-';