-- region
insert into region (name_en, name_pt) VALUES('North','Norte');
insert into region (name_en, name_pt) VALUES('Northeast','Nordeste');
insert into region (name_en, name_pt) VALUES('Midwest','Centro-oeste');
insert into region (name_en, name_pt) VALUES('Southeast','Suldeste');
insert into region (name_en, name_pt) VALUES('South','Sul');

-- country
insert into country (name_en, name_pt) VALUES('Brazil','Brasil');

-- city
insert into city(name,fk_country) values('Abadia de Goiás (GO)',1);
insert into city(name,fk_country) values('Abadia dos Dourados (MG)',1);
insert into city(name,fk_country) values('Abadiânia (GO)',1);
insert into city(name,fk_country) values('Abaeté (MG)',1);
insert into city(name,fk_country) values('Abaetetuba (PA)',1);
insert into city(name,fk_country) values('Abaiara (CE)',1);
insert into city(name,fk_country) values('Abaíra (BA)',1);
insert into city(name,fk_country) values('Abaré (BA)',1);
insert into city(name,fk_country) values('Abatiá (PR)',1);
insert into city(name,fk_country) values('Abdon Batista (SC)',1);
insert into city(name,fk_country) values('Abelardo Luz (SC)',1);
insert into city(name,fk_country) values('Abel Figueiredo (PA)',1);
insert into city(name,fk_country) values('Abre-Campo (MG)',1);
insert into city(name,fk_country) values('Abreu e Lima (PE)',1);
insert into city(name,fk_country) values('Abreulândia (TO)',1);
insert into city(name,fk_country) values('Acaiaca (MG)',1);
insert into city(name,fk_country) values('Açailândia (MA)',1);
insert into city(name,fk_country) values('Acajutiba (BA)',1);
insert into city(name,fk_country) values('Acará (PA)',1);
insert into city(name,fk_country) values('Acarape (CE)',1);
insert into city(name,fk_country) values('Acaraú (CE)',1);
insert into city(name,fk_country) values('Acari (RN)',1);
insert into city(name,fk_country) values('Acauã (PI)',1);
insert into city(name,fk_country) values('Aceguá (RS)',1);
insert into city(name,fk_country) values('Acopiara (CE)',1);
insert into city(name,fk_country) values('Acorizal (MT)',1);
insert into city(name,fk_country) values('Acrelândia (AC)',1);
insert into city(name,fk_country) values('Acreúna (GO)',1);
insert into city(name,fk_country) values('Açu (RN)',1);
insert into city(name,fk_country) values('Açucena (MG)',1);
insert into city(name,fk_country) values('Adamantina (SP)',1);
insert into city(name,fk_country) values('Adelândia (GO)',1);
insert into city(name,fk_country) values('Adolfo (SP)',1);
insert into city(name,fk_country) values('Adrianópolis (PR)',1);
insert into city(name,fk_country) values('Adustina (BA)',1);
insert into city(name,fk_country) values('Afogados da Ingazeira (PE)',1);
insert into city(name,fk_country) values('Afonso Bezerra (RN)',1);
insert into city(name,fk_country) values('Afonso Cláudio (ES)',1);
insert into city(name,fk_country) values('Afonso Cunha (MA)',1);
insert into city(name,fk_country) values('Afrânio (PE)',1);
insert into city(name,fk_country) values('Afuá (PA)',1);
insert into city(name,fk_country) values('Agrestina (PE)',1);
insert into city(name,fk_country) values('Agricolândia (PI)',1);
insert into city(name,fk_country) values('Agrolândia (SC)',1);
insert into city(name,fk_country) values('Agronômica (SC)',1);
insert into city(name,fk_country) values('Água Azul do Norte (PA)',1);
insert into city(name,fk_country) values('Água Boa (MG)',1);
insert into city(name,fk_country) values('Água Boa (MT)',1);
insert into city(name,fk_country) values('Água Branca (AL)',1);
insert into city(name,fk_country) values('Água Branca (PB)',1);
insert into city(name,fk_country) values('Água Branca (PI)',1);
insert into city(name,fk_country) values('Água Clara (MS)',1);
insert into city(name,fk_country) values('Água Comprida (MG)',1);
insert into city(name,fk_country) values('Água Doce (SC)',1);
insert into city(name,fk_country) values('Água Doce do Maranhão (MA)',1);
insert into city(name,fk_country) values('Água Doce do Norte (ES)',1);
insert into city(name,fk_country) values('Água Fria (BA)',1);
insert into city(name,fk_country) values('Água Fria de Goiás (GO)',1);
insert into city(name,fk_country) values('Aguaí (SP)',1);
insert into city(name,fk_country) values('Água Limpa (GO)',1);
insert into city(name,fk_country) values('Aguanil (MG)',1);
insert into city(name,fk_country) values('Água Nova (RN)',1);
insert into city(name,fk_country) values('Água Preta (PE)',1);
insert into city(name,fk_country) values('Água Santa (RS)',1);
insert into city(name,fk_country) values('Águas Belas (PE)',1);
insert into city(name,fk_country) values('Águas da Prata (SP)',1);
insert into city(name,fk_country) values('Águas de Chapecó (SC)',1);
insert into city(name,fk_country) values('Águas de Lindóia (SP)',1);
insert into city(name,fk_country) values('Águas de Santa Bárbara (SP)',1);
insert into city(name,fk_country) values('Águas de São Pedro (SP)',1);
insert into city(name,fk_country) values('Águas Formosas (MG)',1);
insert into city(name,fk_country) values('Águas Frias (SC)',1);
insert into city(name,fk_country) values('Águas Lindas de Goiás (GO)',1);
insert into city(name,fk_country) values('Águas Mornas (SC)',1);
insert into city(name,fk_country) values('Águas Vermelhas (MG)',1);
insert into city(name,fk_country) values('Agudo (RS)',1);
insert into city(name,fk_country) values('Agudos (SP)',1);
insert into city(name,fk_country) values('Agudos do Sul (PR)',1);
insert into city(name,fk_country) values('Águia Branca (ES)',1);
insert into city(name,fk_country) values('Aguiar (PB)',1);
insert into city(name,fk_country) values('Aguiarnópolis (TO)',1);
insert into city(name,fk_country) values('Aimorés (MG)',1);
insert into city(name,fk_country) values('Aiquara (BA)',1);
insert into city(name,fk_country) values('Aiuaba (CE)',1);
insert into city(name,fk_country) values('Aiuruoca (MG)',1);
insert into city(name,fk_country) values('Ajuricaba (RS)',1);
insert into city(name,fk_country) values('Alagoa (MG)',1);
insert into city(name,fk_country) values('Alagoa Grande (PB)',1);
insert into city(name,fk_country) values('Alagoa Nova (PB)',1);
insert into city(name,fk_country) values('Alagoinha (PB)',1);
insert into city(name,fk_country) values('Alagoinha (PE)',1);
insert into city(name,fk_country) values('Alagoinha do Piauí (PI)',1);
insert into city(name,fk_country) values('Alagoinhas (BA)',1);
insert into city(name,fk_country) values('Alambari (SP)',1);
insert into city(name,fk_country) values('Albertina (MG)',1);
insert into city(name,fk_country) values('Alcântara (MA)',1);
insert into city(name,fk_country) values('Alcântaras (CE)',1);
insert into city(name,fk_country) values('Alcantil (PB)',1);
insert into city(name,fk_country) values('Alcinópolis (MS)',1);
insert into city(name,fk_country) values('Alcobaça (BA)',1);
insert into city(name,fk_country) values('Aldeias Altas (MA)',1);
insert into city(name,fk_country) values('Alecrim (RS)',1);
insert into city(name,fk_country) values('Alegre (ES)',1);
insert into city(name,fk_country) values('Alegrete (RS)',1);
insert into city(name,fk_country) values('Alegrete do Piauí (PI)',1);
insert into city(name,fk_country) values('Alegria (RS)',1);
insert into city(name,fk_country) values('Além Paraíba (MG)',1);
insert into city(name,fk_country) values('Alenquer (PA)',1);
insert into city(name,fk_country) values('Alexandria (RN)',1);
insert into city(name,fk_country) values('Alexânia (GO)',1);
insert into city(name,fk_country) values('Alfenas (MG)',1);
insert into city(name,fk_country) values('Alfredo Chaves (ES)',1);
insert into city(name,fk_country) values('Alfredo Marcondes (SP)',1);
insert into city(name,fk_country) values('Alfredo Vasconcelos (MG)',1);
insert into city(name,fk_country) values('Alfredo Wagner (SC)',1);
insert into city(name,fk_country) values('Algodão de Jandaíra (PB)',1);
insert into city(name,fk_country) values('Alhandra (PB)',1);
insert into city(name,fk_country) values('Aliança (PE)',1);
insert into city(name,fk_country) values('Aliança do Tocantins (TO)',1);
insert into city(name,fk_country) values('Almadina (BA)',1);
insert into city(name,fk_country) values('Almas (TO)',1);
insert into city(name,fk_country) values('Almenara (MG)',1);
insert into city(name,fk_country) values('Almeirim (PA)',1);
insert into city(name,fk_country) values('Almino Afonso (RN)',1);
insert into city(name,fk_country) values('Almirante Tamandaré (PR)',1);
insert into city(name,fk_country) values('Almirante Tamandaré do Sul (RS)',1);
insert into city(name,fk_country) values('Aloândia (GO)',1);
insert into city(name,fk_country) values('Alpercata (MG)',1);
insert into city(name,fk_country) values('Alpestre (RS)',1);
insert into city(name,fk_country) values('Alpinópolis (MG)',1);
insert into city(name,fk_country) values('Alta Floresta (MT)',1);
insert into city(name,fk_country) values('Alta Floresta d''Oeste (RO)',1);
insert into city(name,fk_country) values('Altair (SP)',1);
insert into city(name,fk_country) values('Altamira (PA)',1);
insert into city(name,fk_country) values('Altamira do Maranhão (MA)',1);
insert into city(name,fk_country) values('Altamira do Paraná (PR)',1);
insert into city(name,fk_country) values('Altaneira (CE)',1);
insert into city(name,fk_country) values('Alterosa (MG)',1);
insert into city(name,fk_country) values('Altinho (PE)',1);
insert into city(name,fk_country) values('Altinópolis (SP)',1);
insert into city(name,fk_country) values('Alto Alegre (RR)',1);
insert into city(name,fk_country) values('Alto Alegre (RS)',1);
insert into city(name,fk_country) values('Alto Alegre (SP)',1);
insert into city(name,fk_country) values('Alto Alegre do Maranhão (MA)',1);
insert into city(name,fk_country) values('Alto Alegre do Pindaré (MA)',1);
insert into city(name,fk_country) values('Alto Alegre dos Parecis (RO)',1);
insert into city(name,fk_country) values('Alto Araguaia (MT)',1);
insert into city(name,fk_country) values('Alto Bela Vista (SC)',1);
insert into city(name,fk_country) values('Babaçulândia (TO)',1);
insert into city(name,fk_country) values('Bacabal (MA)',1);
insert into city(name,fk_country) values('Bacabeira (MA)',1);
insert into city(name,fk_country) values('Bacuri (MA)',1);
insert into city(name,fk_country) values('Bacurituba (MA)',1);
insert into city(name,fk_country) values('Bady Bassitt (SP)',1);
insert into city(name,fk_country) values('Baependi (MG)',1);
insert into city(name,fk_country) values('Bagé (RS)',1);
insert into city(name,fk_country) values('Bagre (PA)',1);
insert into city(name,fk_country) values('Baía da Traição (PB)',1);
insert into city(name,fk_country) values('Baía Formosa (RN)',1);
insert into city(name,fk_country) values('Baianópolis (BA)',1);
insert into city(name,fk_country) values('Baião (PA)',1);
insert into city(name,fk_country) values('Baixa Grande (BA)',1);
insert into city(name,fk_country) values('Baixa Grande do Ribeiro (PI)',1);
insert into city(name,fk_country) values('Baixio (CE)',1);
insert into city(name,fk_country) values('Baixo Guandu (ES)',1);
insert into city(name,fk_country) values('Balbinos (SP)',1);
insert into city(name,fk_country) values('Baldim (MG)',1);
insert into city(name,fk_country) values('Baliza (GO)',1);
insert into city(name,fk_country) values('Balneário Arroio do Silva (SC)',1);
insert into city(name,fk_country) values('Balneário Barra do Sul (SC)',1);
insert into city(name,fk_country) values('Balneário Camboriú (SC)',1);
insert into city(name,fk_country) values('Balneário Gaivota (SC)',1);
insert into city(name,fk_country) values('Balneário Piçarras (SC)',1);
insert into city(name,fk_country) values('Balneário Pinhal (RS)',1);
insert into city(name,fk_country) values('Balneário Rincão (SC)',1);
insert into city(name,fk_country) values('Balsa Nova (PR)',1);
insert into city(name,fk_country) values('Bálsamo (SP)',1);
insert into city(name,fk_country) values('Balsas (MA)',1);
insert into city(name,fk_country) values('Bambuí (MG)',1);
insert into city(name,fk_country) values('Banabuiú (CE)',1);
insert into city(name,fk_country) values('Bananal (SP)',1);
insert into city(name,fk_country) values('Bananeiras (PB)',1);
insert into city(name,fk_country) values('Bandeira (MG)',1);
insert into city(name,fk_country) values('Bandeira do Sul (MG)',1);
insert into city(name,fk_country) values('Bandeirante (SC)',1);
insert into city(name,fk_country) values('Bandeirantes (MS)',1);
insert into city(name,fk_country) values('Bandeirantes (PR)',1);
insert into city(name,fk_country) values('Bandeirantes do Tocantins (TO)',1);
insert into city(name,fk_country) values('Bannach (PA)',1);
insert into city(name,fk_country) values('Banzaê (BA)',1);
insert into city(name,fk_country) values('Barão (RS)',1);
insert into city(name,fk_country) values('Barão de Antonina (SP)',1);
insert into city(name,fk_country) values('Barão de Cocais (MG)',1);
insert into city(name,fk_country) values('Barão de Cotegipe (RS)',1);
insert into city(name,fk_country) values('Barão de Grajaú (MA)',1);
insert into city(name,fk_country) values('Barão de Melgaço (MT)',1);
insert into city(name,fk_country) values('Barão de Monte Alto (MG)',1);
insert into city(name,fk_country) values('Barão do Triunfo (RS)',1);
insert into city(name,fk_country) values('Baraúna (PB)',1);
insert into city(name,fk_country) values('Baraúna (RN)',1);
insert into city(name,fk_country) values('Barbacena (MG)',1);
insert into city(name,fk_country) values('Barbalha (CE)',1);
insert into city(name,fk_country) values('Barbosa (SP)',1);
insert into city(name,fk_country) values('Barbosa Ferraz (PR)',1);
insert into city(name,fk_country) values('Barcarena (PA)',1);
insert into city(name,fk_country) values('Barcelona (RN)',1);
insert into city(name,fk_country) values('Barcelos (AM)',1);
insert into city(name,fk_country) values('Bariri (SP)',1);
insert into city(name,fk_country) values('Barra (BA)',1);
insert into city(name,fk_country) values('Barra Bonita (SC)',1);
insert into city(name,fk_country) values('Barra Bonita (SP)',1);
insert into city(name,fk_country) values('Barracão (PR)',1);
insert into city(name,fk_country) values('Barracão (RS)',1);
insert into city(name,fk_country) values('Barra da Estiva (BA)',1);
insert into city(name,fk_country) values('Barra d''Alcântara (PI)',1);
insert into city(name,fk_country) values('Barra de Guabiraba (PE)',1);
insert into city(name,fk_country) values('Barra de Santana (PB)',1);
insert into city(name,fk_country) values('Barra de Santa Rosa (PB)',1);
insert into city(name,fk_country) values('Barra de Santo Antônio (AL)',1);
insert into city(name,fk_country) values('Barra de São Francisco (ES)',1);
insert into city(name,fk_country) values('Barra de São Miguel (AL)',1);
insert into city(name,fk_country) values('Barra de São Miguel (PB)',1);
insert into city(name,fk_country) values('Barra do Bugres (MT)',1);
insert into city(name,fk_country) values('Barra do Chapéu (SP)',1);
insert into city(name,fk_country) values('Barra do Choça (BA)',1);
insert into city(name,fk_country) values('Barra do Corda (MA)',1);
insert into city(name,fk_country) values('Barra do Garças (MT)',1);
insert into city(name,fk_country) values('Barra do Guarita (RS)',1);
insert into city(name,fk_country) values('Barra do Jacaré (PR)',1);
insert into city(name,fk_country) values('Barra do Mendes (BA)',1);
insert into city(name,fk_country) values('Barra do Ouro (TO)',1);
insert into city(name,fk_country) values('Barra do Piraí (RJ)',1);
insert into city(name,fk_country) values('Barra do Quaraí (RS)',1);
insert into city(name,fk_country) values('Barra do Ribeiro (RS)',1);
insert into city(name,fk_country) values('Barra do Rio Azul (RS)',1);
insert into city(name,fk_country) values('Barra do Rocha (BA)',1);
insert into city(name,fk_country) values('Barra dos Coqueiros (SE)',1);
insert into city(name,fk_country) values('Barra do Turvo (SP)',1);
insert into city(name,fk_country) values('Barra Funda (RS)',1);
insert into city(name,fk_country) values('Barra Longa (MG)',1);
insert into city(name,fk_country) values('Barra Mansa (RJ)',1);
insert into city(name,fk_country) values('Barras (PI)',1);
insert into city(name,fk_country) values('Barra Velha (SC)',1);
insert into city(name,fk_country) values('Barreira (CE)',1);
insert into city(name,fk_country) values('Barreiras (BA)',1);
insert into city(name,fk_country) values('Barreiras do Piauí (PI)',1);
insert into city(name,fk_country) values('Barreirinha (AM)',1);
insert into city(name,fk_country) values('Barreirinhas (MA)',1);
insert into city(name,fk_country) values('Barreiros (PE)',1);
insert into city(name,fk_country) values('Barretos (SP)',1);
insert into city(name,fk_country) values('Barrinha (SP)',1);
insert into city(name,fk_country) values('Barro (CE)',1);
insert into city(name,fk_country) values('Barro Alto (BA)',1);
insert into city(name,fk_country) values('Barro Alto (GO)',1);
insert into city(name,fk_country) values('Barrocas (BA)',1);
insert into city(name,fk_country) values('Barro Duro (PI)',1);
insert into city(name,fk_country) values('Barrolândia (TO)',1);
insert into city(name,fk_country) values('Barro Preto (BA)',1);
insert into city(name,fk_country) values('Barroquinha (CE)',1);
insert into city(name,fk_country) values('Barros Cassal (RS)',1);
insert into city(name,fk_country) values('Barroso (MG)',1);
insert into city(name,fk_country) values('Barueri (SP)',1);
insert into city(name,fk_country) values('Bastos (SP)',1);
insert into city(name,fk_country) values('Bataguaçu (MS)',1);
insert into city(name,fk_country) values('Batalha (AL)',1);
insert into city(name,fk_country) values('Batalha (PI)',1);
insert into city(name,fk_country) values('Batatais (SP)',1);
insert into city(name,fk_country) values('Batayporã (MS)',1);
insert into city(name,fk_country) values('Baturité (CE)',1);
insert into city(name,fk_country) values('Bauru (SP)',1);
insert into city(name,fk_country) values('Bayeux (PB)',1);
insert into city(name,fk_country) values('Bebedouro (SP)',1);
insert into city(name,fk_country) values('Caapiranga (AM)',1);
insert into city(name,fk_country) values('Caaporã (PB)',1);
insert into city(name,fk_country) values('Caarapó (MS)',1);
insert into city(name,fk_country) values('Caatiba (BA)',1);
insert into city(name,fk_country) values('Cabaceiras (PB)',1);
insert into city(name,fk_country) values('Cabaceiras do Paraguaçu (BA)',1);
insert into city(name,fk_country) values('Cabeceira Grande (MG)',1);
insert into city(name,fk_country) values('Cabeceiras (GO)',1);
insert into city(name,fk_country) values('Cabeceiras do Piauí (PI)',1);
insert into city(name,fk_country) values('Cabedelo (PB)',1);
insert into city(name,fk_country) values('Cabixi (RO)',1);
insert into city(name,fk_country) values('Cabo de Santo Agostinho (PE)',1);
insert into city(name,fk_country) values('Cabo Frio (RJ)',1);
insert into city(name,fk_country) values('Cabo Verde (MG)',1);
insert into city(name,fk_country) values('Cabrália Paulista (SP)',1);
insert into city(name,fk_country) values('Cabreúva (SP)',1);
insert into city(name,fk_country) values('Cabrobó (PE)',1);
insert into city(name,fk_country) values('Caçador (SC)',1);
insert into city(name,fk_country) values('Caçapava (SP)',1);
insert into city(name,fk_country) values('Caçapava do Sul (RS)',1);
insert into city(name,fk_country) values('Cacaulândia (RO)',1);
insert into city(name,fk_country) values('Cacequi (RS)',1);
insert into city(name,fk_country) values('Cáceres (MT)',1);
insert into city(name,fk_country) values('Cachoeira (BA)',1);
insert into city(name,fk_country) values('Cachoeira Alta (GO)',1);
insert into city(name,fk_country) values('Cachoeira da Prata (MG)',1);
insert into city(name,fk_country) values('Cachoeira de Goiás (GO)',1);
insert into city(name,fk_country) values('Cachoeira de Minas (MG)',1);
insert into city(name,fk_country) values('Cachoeira de Pajeú (MG)',1);
insert into city(name,fk_country) values('Cachoeira do Arari (PA)',1);
insert into city(name,fk_country) values('Cachoeira do Piriá (PA)',1);
insert into city(name,fk_country) values('Cachoeira dos Índios (PB)',1);
insert into city(name,fk_country) values('Cachoeira do Sul (RS)',1);
insert into city(name,fk_country) values('Cachoeira Dourada (GO)',1);
insert into city(name,fk_country) values('Cachoeira Dourada (MG)',1);
insert into city(name,fk_country) values('Cachoeira Grande (MA)',1);
insert into city(name,fk_country) values('Cachoeira Paulista (SP)',1);
insert into city(name,fk_country) values('Cachoeiras de Macacu (RJ)',1);
insert into city(name,fk_country) values('Cachoeirinha (PE)',1);
insert into city(name,fk_country) values('Cachoeirinha (RS)',1);
insert into city(name,fk_country) values('Cachoeirinha (TO)',1);
insert into city(name,fk_country) values('Cachoeiro de Itapemirim (ES)',1);
insert into city(name,fk_country) values('Cacimba de Areia (PB)',1);
insert into city(name,fk_country) values('Cacimba de Dentro (PB)',1);
insert into city(name,fk_country) values('Cacimbas (PB)',1);
insert into city(name,fk_country) values('Cacimbinhas (AL)',1);
insert into city(name,fk_country) values('Cacique Doble (RS)',1);
insert into city(name,fk_country) values('Cacoal (RO)',1);
insert into city(name,fk_country) values('Caconde (SP)',1);
insert into city(name,fk_country) values('Caçu (GO)',1);
insert into city(name,fk_country) values('Caculé (BA)',1);
insert into city(name,fk_country) values('Caém (BA)',1);
insert into city(name,fk_country) values('Caetanópolis (MG)',1);
insert into city(name,fk_country) values('Caetanos (BA)',1);
insert into city(name,fk_country) values('Caeté (MG)',1);
insert into city(name,fk_country) values('Caetés (PE)',1);
insert into city(name,fk_country) values('Caetité (BA)',1);
insert into city(name,fk_country) values('Cafarnaum (BA)',1);
insert into city(name,fk_country) values('Cafeara (PR)',1);
insert into city(name,fk_country) values('Cafelândia (PR)',1);
insert into city(name,fk_country) values('Cafelândia (SP)',1);
insert into city(name,fk_country) values('Cafezal do Sul (PR)',1);
insert into city(name,fk_country) values('Caiabu (SP)',1);
insert into city(name,fk_country) values('Caiana (MG)',1);
insert into city(name,fk_country) values('Caiapônia (GO)',1);
insert into city(name,fk_country) values('Caibaté (RS)',1);
insert into city(name,fk_country) values('Caibi (SC)',1);
insert into city(name,fk_country) values('Caiçara (PB)',1);
insert into city(name,fk_country) values('Caiçara (RS)',1);
insert into city(name,fk_country) values('Caiçara do Norte (RN)',1);
insert into city(name,fk_country) values('Caiçara do Rio do Vento (RN)',1);
insert into city(name,fk_country) values('Caicó (RN)',1);
insert into city(name,fk_country) values('Caieiras (SP)',1);
insert into city(name,fk_country) values('Cairu (BA)',1);
insert into city(name,fk_country) values('Caiuá (SP)',1);
insert into city(name,fk_country) values('Cajamar (SP)',1);
insert into city(name,fk_country) values('Cajapió (MA)',1);
insert into city(name,fk_country) values('Cajari (MA)',1);
insert into city(name,fk_country) values('Cajati (SP)',1);
insert into city(name,fk_country) values('Cajazeiras (PB)',1);
insert into city(name,fk_country) values('Cajazeiras do Piauí (PI)',1);
insert into city(name,fk_country) values('Cajazeirinhas (PB)',1);
insert into city(name,fk_country) values('Cajobi (SP)',1);
insert into city(name,fk_country) values('Cajueiro (AL)',1);
insert into city(name,fk_country) values('Cajueiro da Praia (PI)',1);
insert into city(name,fk_country) values('Cajuri (MG)',1);
insert into city(name,fk_country) values('Cajuru (SP)',1);
insert into city(name,fk_country) values('Calçado (PE)',1);
insert into city(name,fk_country) values('Calçoene (AP)',1);
insert into city(name,fk_country) values('Caldas (MG)',1);
insert into city(name,fk_country) values('Caldas Brandão (PB)',1);
insert into city(name,fk_country) values('Caldas Novas (GO)',1);
insert into city(name,fk_country) values('Caldazinha (GO)',1);
insert into city(name,fk_country) values('Caldeirão Grande (BA)',1);
insert into city(name,fk_country) values('Caldeirão Grande do Piauí (PI)',1);
insert into city(name,fk_country) values('Califórnia (PR)',1);
insert into city(name,fk_country) values('Calmon (SC)',1);
insert into city(name,fk_country) values('Calumbi (PE)',1);
insert into city(name,fk_country) values('Camacan (BA)',1);
insert into city(name,fk_country) values('Camaçari (BA)',1);
insert into city(name,fk_country) values('Camacho (MG)',1);
insert into city(name,fk_country) values('Camalaú (PB)',1);
insert into city(name,fk_country) values('Camamu (BA)',1);
insert into city(name,fk_country) values('Camanducaia (MG)',1);
insert into city(name,fk_country) values('Camapuã (MS)',1);
insert into city(name,fk_country) values('Camaquã (RS)',1);
insert into city(name,fk_country) values('Camaragibe (PE)',1);
insert into city(name,fk_country) values('Camargo (RS)',1);
insert into city(name,fk_country) values('Cambará (PR)',1);
insert into city(name,fk_country) values('Cambará do Sul (RS)',1);
insert into city(name,fk_country) values('Cambé (PR)',1);
insert into city(name,fk_country) values('Cambira (PR)',1);
insert into city(name,fk_country) values('Camboriú (SC)',1);
insert into city(name,fk_country) values('Cambuci (RJ)',1);
insert into city(name,fk_country) values('Cambuí (MG)',1);
insert into city(name,fk_country) values('Cambuquira (MG)',1);
insert into city(name,fk_country) values('Cametá (PA)',1);
insert into city(name,fk_country) values('Camocim (CE)',1);
insert into city(name,fk_country) values('Camocim de São Félix (PE)',1);
insert into city(name,fk_country) values('Campanário (MG)',1);
insert into city(name,fk_country) values('Campanha (MG)',1);
insert into city(name,fk_country) values('Campestre (AL)',1);
insert into city(name,fk_country) values('Campestre (MG)',1);
insert into city(name,fk_country) values('Campestre da Serra (RS)',1);
insert into city(name,fk_country) values('Campestre de Goiás (GO)',1);
insert into city(name,fk_country) values('Campestre do Maranhão (MA)',1);
insert into city(name,fk_country) values('Campinaçu (GO)',1);
insert into city(name,fk_country) values('Campina da Lagoa (PR)',1);
insert into city(name,fk_country) values('Campina das Missões (RS)',1);
insert into city(name,fk_country) values('Campina do Monte Alegre (SP)',1);
insert into city(name,fk_country) values('Campina do Simão (PR)',1);
insert into city(name,fk_country) values('Campina Grande (PB)',1);
insert into city(name,fk_country) values('Campina Grande do Sul (PR)',1);
insert into city(name,fk_country) values('Campinápolis (MT)',1);
insert into city(name,fk_country) values('Campinas (SP)',1);
insert into city(name,fk_country) values('Campinas do Piauí (PI)',1);
insert into city(name,fk_country) values('Campinas do Sul (RS)',1);
insert into city(name,fk_country) values('Campina Verde (MG)',1);
insert into city(name,fk_country) values('Campinorte (GO)',1);
insert into city(name,fk_country) values('Campo Alegre (AL)',1);
insert into city(name,fk_country) values('Campo Alegre (SC)',1);
insert into city(name,fk_country) values('Campo Alegre de Goiás (GO)',1);
insert into city(name,fk_country) values('Campo Alegre de Lourdes (BA)',1);
insert into city(name,fk_country) values('Campo Alegre do Fidalgo (PI)',1);
insert into city(name,fk_country) values('Campo Azul (MG)',1);
insert into city(name,fk_country) values('Campo Belo (MG)',1);
insert into city(name,fk_country) values('Campo Belo do Sul (SC)',1);
insert into city(name,fk_country) values('Campo Bom (RS)',1);
insert into city(name,fk_country) values('Campo Bonito (PR)',1);
insert into city(name,fk_country) values('Campo do Brito (SE)',1);
insert into city(name,fk_country) values('Campo do Meio (MG)',1);
insert into city(name,fk_country) values('Campo do Tenente (PR)',1);
insert into city(name,fk_country) values('Campo Erê (SC)',1);
insert into city(name,fk_country) values('Campo Florido (MG)',1);
insert into city(name,fk_country) values('Campo Formoso (BA)',1);
insert into city(name,fk_country) values('Campo Grande (AL)',1);
insert into city(name,fk_country) values('Campo Grande (MS)',1);
insert into city(name,fk_country) values('Campo Grande (RN)',1);
insert into city(name,fk_country) values('Campo Grande do Piauí (PI)',1);
insert into city(name,fk_country) values('Campo Largo (PR)',1);
insert into city(name,fk_country) values('Campo Largo do Piauí (PI)',1);
insert into city(name,fk_country) values('Campo Limpo de Goiás (GO)',1);
insert into city(name,fk_country) values('Campo Limpo Paulista (SP)',1);
insert into city(name,fk_country) values('Campo Magro (PR)',1);
insert into city(name,fk_country) values('Campo Maior (PI)',1);
insert into city(name,fk_country) values('Campo Mourão (PR)',1);
insert into city(name,fk_country) values('Campo Novo (RS)',1);
insert into city(name,fk_country) values('Campo Novo de Rondônia (RO)',1);
insert into city(name,fk_country) values('Campo Novo do Parecis (MT)',1);
insert into city(name,fk_country) values('Campo Redondo (RN)',1);
insert into city(name,fk_country) values('Campos Altos (MG)',1);
insert into city(name,fk_country) values('Campos Belos (GO)',1);
insert into city(name,fk_country) values('Campos Borges (RS)',1);
insert into city(name,fk_country) values('Campos de Júlio (MT)',1);
insert into city(name,fk_country) values('Campos do Jordão (SP)',1);
insert into city(name,fk_country) values('Campos dos Goytacazes (RJ)',1);
insert into city(name,fk_country) values('Campos Gerais (MG)',1);
insert into city(name,fk_country) values('Campos Lindos (TO)',1);
insert into city(name,fk_country) values('Campos Novos (SC)',1);
insert into city(name,fk_country) values('Campos Novos Paulista (SP)',1);
insert into city(name,fk_country) values('Campos Sales (CE)',1);
insert into city(name,fk_country) values('Campos Verdes (GO)',1);
insert into city(name,fk_country) values('Campo Verde (MT)',1);
insert into city(name,fk_country) values('Camutanga (PE)',1);
insert into city(name,fk_country) values('Canaã (MG)',1);
insert into city(name,fk_country) values('Canaã dos Carajás (PA)',1);
insert into city(name,fk_country) values('Canabrava do Norte (MT)',1);
insert into city(name,fk_country) values('Cananeia (SP)',1);
insert into city(name,fk_country) values('Canapi (AL)',1);
insert into city(name,fk_country) values('Canápolis (BA)',1);
insert into city(name,fk_country) values('Canápolis (MG)',1);
insert into city(name,fk_country) values('Canarana (BA)',1);
insert into city(name,fk_country) values('Canarana (MT)',1);
insert into city(name,fk_country) values('Canas (SP)',1);
insert into city(name,fk_country) values('Cana Verde (MG)',1);
insert into city(name,fk_country) values('Canavieira (PI)',1);
insert into city(name,fk_country) values('Canavieiras (BA)',1);
insert into city(name,fk_country) values('Candeal (BA)',1);
insert into city(name,fk_country) values('Candeias (BA)',1);
insert into city(name,fk_country) values('Candeias (MG)',1);
insert into city(name,fk_country) values('Candeias do Jamari (RO)',1);
insert into city(name,fk_country) values('Candelária (RS)',1);
insert into city(name,fk_country) values('Candiba (BA)',1);
insert into city(name,fk_country) values('Cândido de Abreu (PR)',1);
insert into city(name,fk_country) values('Cândido Godói (RS)',1);
insert into city(name,fk_country) values('Cândido Mendes (MA)',1);
insert into city(name,fk_country) values('Cândido Mota (SP)',1);
insert into city(name,fk_country) values('Cândido Rodrigues (SP)',1);
insert into city(name,fk_country) values('Cândido Sales (BA)',1);
insert into city(name,fk_country) values('Candiota (RS)',1);
insert into city(name,fk_country) values('Candói (PR)',1);
insert into city(name,fk_country) values('Canela (RS)',1);
insert into city(name,fk_country) values('Canelinha (SC)',1);
insert into city(name,fk_country) values('Canguaretama (RN)',1);
insert into city(name,fk_country) values('Canguçu (RS)',1);
insert into city(name,fk_country) values('Canhoba (SE)',1);
insert into city(name,fk_country) values('Canhotinho (PE)',1);
insert into city(name,fk_country) values('Canindé (CE)',1);
insert into city(name,fk_country) values('Canindé de São Francisco (SE)',1);
insert into city(name,fk_country) values('Canitar (SP)',1);
insert into city(name,fk_country) values('Canoas (RS)',1);
insert into city(name,fk_country) values('Canoinhas (SC)',1);
insert into city(name,fk_country) values('Cansanção (BA)',1);
insert into city(name,fk_country) values('Cantagalo (MG)',1);
insert into city(name,fk_country) values('Cantagalo (PR)',1);
insert into city(name,fk_country) values('Cantagalo (RJ)',1);
insert into city(name,fk_country) values('Cantanhede (MA)',1);
insert into city(name,fk_country) values('Cantá (RR)',1);
insert into city(name,fk_country) values('Canto do Buriti (PI)',1);
insert into city(name,fk_country) values('Canudos (BA)',1);
insert into city(name,fk_country) values('Canudos do Vale (RS)',1);
insert into city(name,fk_country) values('Canutama (AM)',1);
insert into city(name,fk_country) values('Capanema (PA)',1);
insert into city(name,fk_country) values('Capanema (PR)',1);
insert into city(name,fk_country) values('Capão Alto (SC)',1);
insert into city(name,fk_country) values('Capão Bonito (SP)',1);
insert into city(name,fk_country) values('Capão Bonito do Sul (RS)',1);
insert into city(name,fk_country) values('Damianópolis (GO)',1);
insert into city(name,fk_country) values('Damião (PB)',1);
insert into city(name,fk_country) values('Damolândia (GO)',1);
insert into city(name,fk_country) values('Darcinópolis (TO)',1);
insert into city(name,fk_country) values('Dário Meira (BA)',1);
insert into city(name,fk_country) values('Datas (MG)',1);
insert into city(name,fk_country) values('David Canabarro (RS)',1);
insert into city(name,fk_country) values('Davinópolis (GO)',1);
insert into city(name,fk_country) values('Davinópolis (MA)',1);
insert into city(name,fk_country) values('Delfim Moreira (MG)',1);
insert into city(name,fk_country) values('Delfinópolis (MG)',1);
insert into city(name,fk_country) values('Delmiro Gouveia (AL)',1);
insert into city(name,fk_country) values('Delta (MG)',1);
insert into city(name,fk_country) values('Demerval Lobão (PI)',1);
insert into city(name,fk_country) values('Denise (MT)',1);
insert into city(name,fk_country) values('Deodápolis (MS)',1);
insert into city(name,fk_country) values('Deputado Irapuan Pinheiro (CE)',1);
insert into city(name,fk_country) values('Derrubadas (RS)',1);
insert into city(name,fk_country) values('Descalvado (SP)',1);
insert into city(name,fk_country) values('Descanso (SC)',1);
insert into city(name,fk_country) values('Descoberto (MG)',1);
insert into city(name,fk_country) values('Desterro (PB)',1);
insert into city(name,fk_country) values('Desterro de Entre Rios (MG)',1);
insert into city(name,fk_country) values('Desterro do Melo (MG)',1);
insert into city(name,fk_country) values('Dezesseis de Novembro (RS)',1);
insert into city(name,fk_country) values('Diadema (SP)',1);
insert into city(name,fk_country) values('Diamante (PB)',1);
insert into city(name,fk_country) values('Diamante d''Oeste (PR)',1);
insert into city(name,fk_country) values('Diamante do Norte (PR)',1);
insert into city(name,fk_country) values('Diamante do Sul (PR)',1);
insert into city(name,fk_country) values('Diamantina (MG)',1);
insert into city(name,fk_country) values('Diamantino (MT)',1);
insert into city(name,fk_country) values('Dianópolis (TO)',1);
insert into city(name,fk_country) values('Dias d''Ávila (BA)',1);
insert into city(name,fk_country) values('Dilermando de Aguiar (RS)',1);
insert into city(name,fk_country) values('Diogo de Vasconcelos (MG)',1);
insert into city(name,fk_country) values('Dionísio (MG)',1);
insert into city(name,fk_country) values('Dionísio Cerqueira (SC)',1);
insert into city(name,fk_country) values('Echaporã (SP)',1);
insert into city(name,fk_country) values('Ecoporanga (ES)',1);
insert into city(name,fk_country) values('Edealina (GO)',1);
insert into city(name,fk_country) values('Edeia (GO)',1);
insert into city(name,fk_country) values('Eirunepé (AM)',1);
insert into city(name,fk_country) values('Eldorado (MS)',1);
insert into city(name,fk_country) values('Eldorado (SP)',1);
insert into city(name,fk_country) values('Eldorado dos Carajás (PA)',1);
insert into city(name,fk_country) values('Eldorado do Sul (RS)',1);
insert into city(name,fk_country) values('Elesbão Veloso (PI)',1);
insert into city(name,fk_country) values('Elias Fausto (SP)',1);
insert into city(name,fk_country) values('Eliseu Martins (PI)',1);
insert into city(name,fk_country) values('Elisiário (SP)',1);
insert into city(name,fk_country) values('Elísio Medrado (BA)',1);
insert into city(name,fk_country) values('Elói Mendes (MG)',1);
insert into city(name,fk_country) values('Emas (PB)',1);
insert into city(name,fk_country) values('Embaúba (SP)',1);
insert into city(name,fk_country) values('Embu das Artes (SP)',1);
insert into city(name,fk_country) values('Embu-Guaçu (SP)',1);
insert into city(name,fk_country) values('Emilianópolis (SP)',1);
insert into city(name,fk_country) values('Encantado (RS)',1);
insert into city(name,fk_country) values('Encanto (RN)',1);
insert into city(name,fk_country) values('Encruzilhada (BA)',1);
insert into city(name,fk_country) values('Encruzilhada do Sul (RS)',1);
insert into city(name,fk_country) values('Enéas Marques (PR)',1);
insert into city(name,fk_country) values('Engenheiro Beltrão (PR)',1);
insert into city(name,fk_country) values('Engenheiro Caldas (MG)',1);
insert into city(name,fk_country) values('Engenheiro Coelho (SP)',1);
insert into city(name,fk_country) values('Engenheiro Navarro (MG)',1);
insert into city(name,fk_country) values('Engenheiro Paulo de Frontin (RJ)',1);
insert into city(name,fk_country) values('Engenho Velho (RS)',1);
insert into city(name,fk_country) values('Entre Folhas (MG)',1);
insert into city(name,fk_country) values('Fagundes (PB)',1);
insert into city(name,fk_country) values('Fagundes Varela (RS)',1);
insert into city(name,fk_country) values('Faina (GO)',1);
insert into city(name,fk_country) values('Fama (MG)',1);
insert into city(name,fk_country) values('Faria Lemos (MG)',1);
insert into city(name,fk_country) values('Farias Brito (CE)',1);
insert into city(name,fk_country) values('Faro (PA)',1);
insert into city(name,fk_country) values('Farol (PR)',1);
insert into city(name,fk_country) values('Farroupilha (RS)',1);
insert into city(name,fk_country) values('Fartura (SP)',1);
insert into city(name,fk_country) values('Fartura do Piauí (PI)',1);
insert into city(name,fk_country) values('Fátima (BA)',1);
insert into city(name,fk_country) values('Fátima (TO)',1);
insert into city(name,fk_country) values('Fátima do Sul (MS)',1);
insert into city(name,fk_country) values('Faxinal (PR)',1);
insert into city(name,fk_country) values('Faxinal dos Guedes (SC)',1);
insert into city(name,fk_country) values('Faxinal do Soturno (RS)',1);
insert into city(name,fk_country) values('Faxinalzinho (RS)',1);
insert into city(name,fk_country) values('Fazenda Nova (GO)',1);
insert into city(name,fk_country) values('Fazenda Rio Grande (PR)',1);
insert into city(name,fk_country) values('Fazenda Vilanova (RS)',1);
insert into city(name,fk_country) values('Feijó (AC)',1);
insert into city(name,fk_country) values('Feira da Mata (BA)',1);
insert into city(name,fk_country) values('Feira de Santana (BA)',1);
insert into city(name,fk_country) values('Feira Grande (AL)',1);
insert into city(name,fk_country) values('Feira Nova (PE)',1);
insert into city(name,fk_country) values('Feira Nova (SE)',1);
insert into city(name,fk_country) values('Feira Nova do Maranhão (MA)',1);
insert into city(name,fk_country) values('Felício dos Santos (MG)',1);
insert into city(name,fk_country) values('Felipe Guerra (RN)',1);
insert into city(name,fk_country) values('Felisburgo (MG)',1);
insert into city(name,fk_country) values('Felixlândia (MG)',1);
insert into city(name,fk_country) values('Feliz (RS)',1);
insert into city(name,fk_country) values('Feliz Deserto (AL)',1);
insert into city(name,fk_country) values('Feliz Natal (MT)',1);
insert into city(name,fk_country) values('Fênix (PR)',1);
insert into city(name,fk_country) values('Fernandes Pinheiro (PR)',1);
insert into city(name,fk_country) values('Fernandes Tourinho (MG)',1);
insert into city(name,fk_country) values('Fernando Falcão (MA)',1);
insert into city(name,fk_country) values('Fernando Pedroza (RN)',1);
insert into city(name,fk_country) values('Fernandópolis (SP)',1);
insert into city(name,fk_country) values('Fernando Prestes (SP)',1);
insert into city(name,fk_country) values('Fernão (SP)',1);
insert into city(name,fk_country) values('Ferraz de Vasconcelos (SP)',1);
insert into city(name,fk_country) values('Ferreira Gomes (AP)',1);
insert into city(name,fk_country) values('Gabriel Monteiro (SP)',1);
insert into city(name,fk_country) values('Gado Bravo (PB)',1);
insert into city(name,fk_country) values('Gália (SP)',1);
insert into city(name,fk_country) values('Galileia (MG)',1);
insert into city(name,fk_country) values('Galinhos (RN)',1);
insert into city(name,fk_country) values('Galvão (SC)',1);
insert into city(name,fk_country) values('Gameleira (PE)',1);
insert into city(name,fk_country) values('Gameleira de Goiás (GO)',1);
insert into city(name,fk_country) values('Gameleiras (MG)',1);
insert into city(name,fk_country) values('Gandu (BA)',1);
insert into city(name,fk_country) values('Garanhuns (PE)',1);
insert into city(name,fk_country) values('Gararu (SE)',1);
insert into city(name,fk_country) values('Garça (SP)',1);
insert into city(name,fk_country) values('Garibaldi (RS)',1);
insert into city(name,fk_country) values('Garopaba (SC)',1);
insert into city(name,fk_country) values('Garrafão do Norte (PA)',1);
insert into city(name,fk_country) values('Garruchos (RS)',1);
insert into city(name,fk_country) values('Garuva (SC)',1);
insert into city(name,fk_country) values('Gaspar (SC)',1);
insert into city(name,fk_country) values('Gastão Vidigal (SP)',1);
insert into city(name,fk_country) values('Gaúcha do Norte (MT)',1);
insert into city(name,fk_country) values('Gaurama (RS)',1);
insert into city(name,fk_country) values('Gavião (BA)',1);
insert into city(name,fk_country) values('Gavião Peixoto (SP)',1);
insert into city(name,fk_country) values('Geminiano (PI)',1);
insert into city(name,fk_country) values('General Câmara (RS)',1);
insert into city(name,fk_country) values('General Carneiro (MT)',1);
insert into city(name,fk_country) values('General Carneiro (PR)',1);
insert into city(name,fk_country) values('General Maynard (SE)',1);
insert into city(name,fk_country) values('General Salgado (SP)',1);
insert into city(name,fk_country) values('General Sampaio (CE)',1);
insert into city(name,fk_country) values('Gentil (RS)',1);
insert into city(name,fk_country) values('Gentio do Ouro (BA)',1);
insert into city(name,fk_country) values('Getulina (SP)',1);
insert into city(name,fk_country) values('Getúlio Vargas (RS)',1);
insert into city(name,fk_country) values('Gilbués (PI)',1);
insert into city(name,fk_country) values('Girau do Ponciano (AL)',1);
insert into city(name,fk_country) values('Giruá (RS)',1);
insert into city(name,fk_country) values('Glaucilândia (MG)',1);
insert into city(name,fk_country) values('Glicério (SP)',1);
insert into city(name,fk_country) values('Glória (BA)',1);
insert into city(name,fk_country) values('Glória de Dourados (MS)',1);
insert into city(name,fk_country) values('Glória d''Oeste (MT)',1);
insert into city(name,fk_country) values('Glória do Goitá (PE)',1);
insert into city(name,fk_country) values('Glorinha (RS)',1);
insert into city(name,fk_country) values('Godofredo Viana (MA)',1);
insert into city(name,fk_country) values('Godoy Moreira (PR)',1);
insert into city(name,fk_country) values('Goiabeira (MG)',1);
insert into city(name,fk_country) values('Goiana (PE)',1);
insert into city(name,fk_country) values('Goianá (MG)',1);
insert into city(name,fk_country) values('Goianápolis (GO)',1);
insert into city(name,fk_country) values('Goiandira (GO)',1);
insert into city(name,fk_country) values('Goianésia (GO)',1);
insert into city(name,fk_country) values('Goianésia do Pará (PA)',1);
insert into city(name,fk_country) values('Goiânia (GO)',1);
insert into city(name,fk_country) values('Goianinha (RN)',1);
insert into city(name,fk_country) values('Goianira (GO)',1);
insert into city(name,fk_country) values('Goianorte (TO)',1);
insert into city(name,fk_country) values('Goiás (GO)',1);
insert into city(name,fk_country) values('Goiatins (TO)',1);
insert into city(name,fk_country) values('Harmonia (RS)',1);
insert into city(name,fk_country) values('Heitoraí (GO)',1);
insert into city(name,fk_country) values('Heliodora (MG)',1);
insert into city(name,fk_country) values('Heliópolis (BA)',1);
insert into city(name,fk_country) values('Herculândia (SP)',1);
insert into city(name,fk_country) values('Herval (RS)',1);
insert into city(name,fk_country) values('Herval d''Oeste (SC)',1);
insert into city(name,fk_country) values('Herveiras (RS)',1);
insert into city(name,fk_country) values('Iacanga (SP)',1);
insert into city(name,fk_country) values('Iaciara (GO)',1);
insert into city(name,fk_country) values('Iacri (SP)',1);
insert into city(name,fk_country) values('Iaçu (BA)',1);
insert into city(name,fk_country) values('Iapu (MG)',1);
insert into city(name,fk_country) values('Iaras (SP)',1);
insert into city(name,fk_country) values('Iati (PE)',1);
insert into city(name,fk_country) values('Ibaiti (PR)',1);
insert into city(name,fk_country) values('Ibarama (RS)',1);
insert into city(name,fk_country) values('Ibaté (SP)',1);
insert into city(name,fk_country) values('Ibaretama (CE)',1);
insert into city(name,fk_country) values('Ibateguara (AL)',1);
insert into city(name,fk_country) values('Ibatiba (ES)',1);
insert into city(name,fk_country) values('Ibema (PR)',1);
insert into city(name,fk_country) values('Ibertioga (MG)',1);
insert into city(name,fk_country) values('Ibiá (MG)',1);
insert into city(name,fk_country) values('Ibiaçá (RS)',1);
insert into city(name,fk_country) values('Ibiaí (MG)',1);
insert into city(name,fk_country) values('Ibiam (SC)',1);
insert into city(name,fk_country) values('Ibiapina (CE)',1);
insert into city(name,fk_country) values('Ibiara (PB)',1);
insert into city(name,fk_country) values('Ibiassucê (BA)',1);
insert into city(name,fk_country) values('Ibicaraí (BA)',1);
insert into city(name,fk_country) values('Ibicaré (SC)',1);
insert into city(name,fk_country) values('Ibicoara (BA)',1);
insert into city(name,fk_country) values('Ibicuí (BA)',1);
insert into city(name,fk_country) values('Ibicuitinga (CE)',1);
insert into city(name,fk_country) values('Ibimirim (PE)',1);
insert into city(name,fk_country) values('Ibipeba (BA)',1);
insert into city(name,fk_country) values('Ibipitanga (BA)',1);
insert into city(name,fk_country) values('Ibiporã (PR)',1);
insert into city(name,fk_country) values('Ibiquera (BA)',1);
insert into city(name,fk_country) values('Ibirá (SP)',1);
insert into city(name,fk_country) values('Ibiracatu (MG)',1);
insert into city(name,fk_country) values('Ibiraci (MG)',1);
insert into city(name,fk_country) values('Ibiraçu (ES)',1);
insert into city(name,fk_country) values('Ibiraiaras (RS)',1);
insert into city(name,fk_country) values('Ibirajuba (PE)',1);
insert into city(name,fk_country) values('Ibirama (SC)',1);
insert into city(name,fk_country) values('Ibirapitanga (BA)',1);
insert into city(name,fk_country) values('Ibirapuã (BA)',1);
insert into city(name,fk_country) values('Ibirapuitã (RS)',1);
insert into city(name,fk_country) values('Ibirarema (SP)',1);
insert into city(name,fk_country) values('Ibirataia (BA)',1);
insert into city(name,fk_country) values('Ibirité (MG)',1);
insert into city(name,fk_country) values('Ibirubá (RS)',1);
insert into city(name,fk_country) values('Ibitiara (BA)',1);
insert into city(name,fk_country) values('Ibitinga (SP)',1);
insert into city(name,fk_country) values('Ibitirama (ES)',1);
insert into city(name,fk_country) values('Ibititá (BA)',1);
insert into city(name,fk_country) values('Ibitiúra de Minas (MG)',1);
insert into city(name,fk_country) values('Ibituruna (MG)',1);
insert into city(name,fk_country) values('Ibiúna (SP)',1);
insert into city(name,fk_country) values('Ibotirama (BA)',1);
insert into city(name,fk_country) values('Icapuí (CE)',1);
insert into city(name,fk_country) values('Içara (SC)',1);
insert into city(name,fk_country) values('Icaraí de Minas (MG)',1);
insert into city(name,fk_country) values('Icaraíma (PR)',1);
insert into city(name,fk_country) values('Icatu (MA)',1);
insert into city(name,fk_country) values('Icém (SP)',1);
insert into city(name,fk_country) values('Ichu (BA)',1);
insert into city(name,fk_country) values('Icó (CE)',1);
insert into city(name,fk_country) values('Iconha (ES)',1);
insert into city(name,fk_country) values('Ielmo Marinho (RN)',1);
insert into city(name,fk_country) values('Iepê (SP)',1);
insert into city(name,fk_country) values('Igaci (AL)',1);
insert into city(name,fk_country) values('Igaporã (BA)',1);
insert into city(name,fk_country) values('Igaraçu do Tietê (SP)',1);
insert into city(name,fk_country) values('Igaracy (PB)',1);
insert into city(name,fk_country) values('Igarapava (SP)',1);
insert into city(name,fk_country) values('Igarapé (MG)',1);
insert into city(name,fk_country) values('Igarapé-Açu (PA)',1);
insert into city(name,fk_country) values('Igarapé do Meio (MA)',1);
insert into city(name,fk_country) values('Igarapé Grande (MA)',1);
insert into city(name,fk_country) values('Igarapé-Miri (PA)',1);
insert into city(name,fk_country) values('Igarassu (PE)',1);
insert into city(name,fk_country) values('Igaratá (SP)',1);
insert into city(name,fk_country) values('Igaratinga (MG)',1);
insert into city(name,fk_country) values('Igrapiúna (BA)',1);
insert into city(name,fk_country) values('Igreja Nova (AL)',1);
insert into city(name,fk_country) values('Igrejinha (RS)',1);
insert into city(name,fk_country) values('Iguaba Grande (RJ)',1);
insert into city(name,fk_country) values('Iguaí (BA)',1);
insert into city(name,fk_country) values('Iguape (SP)',1);
insert into city(name,fk_country) values('Iguaraci (PE)',1);
insert into city(name,fk_country) values('Iguaraçu (PR)',1);
insert into city(name,fk_country) values('Iguatama (MG)',1);
insert into city(name,fk_country) values('Iguatemi (MS)',1);
insert into city(name,fk_country) values('Iguatu (CE)',1);
insert into city(name,fk_country) values('Iguatu (PR)',1);
insert into city(name,fk_country) values('Ijaci (MG)',1);
insert into city(name,fk_country) values('Ijuí (RS)',1);
insert into city(name,fk_country) values('Ilhabela (SP)',1);
insert into city(name,fk_country) values('Ilha Comprida (SP)',1);
insert into city(name,fk_country) values('Ilha das Flores (SE)',1);
insert into city(name,fk_country) values('Ilha de Itamaracá (PE)',1);
insert into city(name,fk_country) values('Ilha Grande (PI)',1);
insert into city(name,fk_country) values('Ilha Solteira (SP)',1);
insert into city(name,fk_country) values('Ilhéus (BA)',1);
insert into city(name,fk_country) values('Ilhota (SC)',1);
insert into city(name,fk_country) values('Ilicínea (MG)',1);
insert into city(name,fk_country) values('Ilópolis (RS)',1);
insert into city(name,fk_country) values('Imaculada (PB)',1);
insert into city(name,fk_country) values('Imaruí (SC)',1);
insert into city(name,fk_country) values('Imbaú (PR)',1);
insert into city(name,fk_country) values('Imbé (RS)',1);
insert into city(name,fk_country) values('Imbé de Minas (MG)',1);
insert into city(name,fk_country) values('Imbituba (SC)',1);
insert into city(name,fk_country) values('Imbituva (PR)',1);
insert into city(name,fk_country) values('Imbuia (SC)',1);
insert into city(name,fk_country) values('Imigrante (RS)',1);
insert into city(name,fk_country) values('Imperatriz (MA)',1);
insert into city(name,fk_country) values('Inaciolândia (GO)',1);
insert into city(name,fk_country) values('Inácio Martins (PR)',1);
insert into city(name,fk_country) values('Inajá (PE)',1);
insert into city(name,fk_country) values('Inajá (PR)',1);
insert into city(name,fk_country) values('Inconfidentes (MG)',1);
insert into city(name,fk_country) values('Indaiabira (MG)',1);
insert into city(name,fk_country) values('Indaial (SC)',1);
insert into city(name,fk_country) values('Indaiatuba (SP)',1);
insert into city(name,fk_country) values('Independência (CE)',1);
insert into city(name,fk_country) values('Independência (RS)',1);
insert into city(name,fk_country) values('Indiana (SP)',1);
insert into city(name,fk_country) values('Indianópolis (MG)',1);
insert into city(name,fk_country) values('Indianópolis (PR)',1);
insert into city(name,fk_country) values('Indiaporã (SP)',1);
insert into city(name,fk_country) values('Indiara (GO)',1);
insert into city(name,fk_country) values('Indiaroba (SE)',1);
insert into city(name,fk_country) values('Indiavaí (MT)',1);
insert into city(name,fk_country) values('Ingá (PB)',1);
insert into city(name,fk_country) values('Jaboatão dos Guararapes (PE)',1);
insert into city(name,fk_country) values('Jaborá (SC)',1);
insert into city(name,fk_country) values('Jaborandi (BA)',1);
insert into city(name,fk_country) values('Jaborandi (SP)',1);
insert into city(name,fk_country) values('Jaboticaba (RS)',1);
insert into city(name,fk_country) values('Jaboticabal (SP)',1);
insert into city(name,fk_country) values('Jaboticatubas (MG)',1);
insert into city(name,fk_country) values('Jaboti (PR)',1);
insert into city(name,fk_country) values('Jaçanã (RN)',1);
insert into city(name,fk_country) values('Jacaraci (BA)',1);
insert into city(name,fk_country) values('Jacaraú (PB)',1);
insert into city(name,fk_country) values('Jacareacanga (PA)',1);
insert into city(name,fk_country) values('Jacaré dos Homens (AL)',1);
insert into city(name,fk_country) values('Jacareí (SP)',1);
insert into city(name,fk_country) values('Jacarezinho (PR)',1);
insert into city(name,fk_country) values('Jaci (SP)',1);
insert into city(name,fk_country) values('Jaciara (MT)',1);
insert into city(name,fk_country) values('Jacinto (MG)',1);
insert into city(name,fk_country) values('Jacinto Machado (SC)',1);
insert into city(name,fk_country) values('Jacobina (BA)',1);
insert into city(name,fk_country) values('Jacobina do Piauí (PI)',1);
insert into city(name,fk_country) values('Jacuí (MG)',1);
insert into city(name,fk_country) values('Jacuípe (AL)',1);
insert into city(name,fk_country) values('Jacuizinho (RS)',1);
insert into city(name,fk_country) values('Jacundá (PA)',1);
insert into city(name,fk_country) values('Jacupiranga (SP)',1);
insert into city(name,fk_country) values('Jacutinga (MG)',1);
insert into city(name,fk_country) values('Jacutinga (RS)',1);
insert into city(name,fk_country) values('Jaguapitã (PR)',1);
insert into city(name,fk_country) values('Jaguaquara (BA)',1);
insert into city(name,fk_country) values('Jaguaraçu (MG)',1);
insert into city(name,fk_country) values('Jaguarão (RS)',1);
insert into city(name,fk_country) values('Jaguarari (BA)',1);
insert into city(name,fk_country) values('Jaguaré (ES)',1);
insert into city(name,fk_country) values('Jaguaretama (CE)',1);
insert into city(name,fk_country) values('Jaguari (RS)',1);
insert into city(name,fk_country) values('Jaguariaíva (PR)',1);
insert into city(name,fk_country) values('Jaguaribara (CE)',1);
insert into city(name,fk_country) values('Jaguaribe (CE)',1);
insert into city(name,fk_country) values('Jaguaripe (BA)',1);
insert into city(name,fk_country) values('Jaguariúna (SP)',1);
insert into city(name,fk_country) values('Jaguaruana (CE)',1);
insert into city(name,fk_country) values('Jaguaruna (SC)',1);
insert into city(name,fk_country) values('Jaíba (MG)',1);
insert into city(name,fk_country) values('Jaicós (PI)',1);
insert into city(name,fk_country) values('Jales (SP)',1);
insert into city(name,fk_country) values('Jambeiro (SP)',1);
insert into city(name,fk_country) values('Jampruca (MG)',1);
insert into city(name,fk_country) values('Janaúba (MG)',1);
insert into city(name,fk_country) values('Jandaia (GO)',1);
insert into city(name,fk_country) values('Jandaia do Sul (PR)',1);
insert into city(name,fk_country) values('Jandaíra (BA)',1);
insert into city(name,fk_country) values('Jandaíra (RN)',1);
insert into city(name,fk_country) values('Jandira (SP)',1);
insert into city(name,fk_country) values('Janduís (RN)',1);
insert into city(name,fk_country) values('Jangada (MT)',1);
insert into city(name,fk_country) values('Janiópolis (PR)',1);
insert into city(name,fk_country) values('Januária (MG)',1);
insert into city(name,fk_country) values('Japaraíba (MG)',1);
insert into city(name,fk_country) values('Japaratinga (AL)',1);
insert into city(name,fk_country) values('Japaratuba (SE)',1);
insert into city(name,fk_country) values('Japeri (RJ)',1);
insert into city(name,fk_country) values('Japi (RN)',1);
insert into city(name,fk_country) values('Japira (PR)',1);
insert into city(name,fk_country) values('Japoatã (SE)',1);
insert into city(name,fk_country) values('Japonvar (MG)',1);
insert into city(name,fk_country) values('Japorã (MS)',1);
insert into city(name,fk_country) values('Japurá (AM)',1);
insert into city(name,fk_country) values('Japurá (PR)',1);
insert into city(name,fk_country) values('Kaloré (PR)',1);
insert into city(name,fk_country) values('Lábrea (AM)',1);
insert into city(name,fk_country) values('Lacerdópolis (SC)',1);
insert into city(name,fk_country) values('Ladainha (MG)',1);
insert into city(name,fk_country) values('Ladário (MS)',1);
insert into city(name,fk_country) values('Lafaiete Coutinho (BA)',1);
insert into city(name,fk_country) values('Lagamar (MG)',1);
insert into city(name,fk_country) values('Lagarto (SE)',1);
insert into city(name,fk_country) values('Lages (SC)',1);
insert into city(name,fk_country) values('Lagoa (PB)',1);
insert into city(name,fk_country) values('Lagoa Alegre (PI)',1);
insert into city(name,fk_country) values('Lagoa Bonita do Sul (RS)',1);
insert into city(name,fk_country) values('Lagoa da Canoa (AL)',1);
insert into city(name,fk_country) values('Lagoa da Confusão (TO)',1);
insert into city(name,fk_country) values('Lagoa d''Anta (RN)',1);
insert into city(name,fk_country) values('Lagoa da Prata (MG)',1);
insert into city(name,fk_country) values('Lagoa de Dentro (PB)',1);
insert into city(name,fk_country) values('Lagoa de Itaenga (PE)',1);
insert into city(name,fk_country) values('Lagoa de Pedras (RN)',1);
insert into city(name,fk_country) values('Lagoa de São Francisco (PI)',1);
insert into city(name,fk_country) values('Lagoa de Velhos (RN)',1);
insert into city(name,fk_country) values('Lagoa do Barro do Piauí (PI)',1);
insert into city(name,fk_country) values('Lagoa do Carro (PE)',1);
insert into city(name,fk_country) values('Lagoa do Mato (MA)',1);
insert into city(name,fk_country) values('Lagoa do Ouro (PE)',1);
insert into city(name,fk_country) values('Lagoa do Piauí (PI)',1);
insert into city(name,fk_country) values('Lagoa dos Gatos (PE)',1);
insert into city(name,fk_country) values('Lagoa do Sítio (PI)',1);
insert into city(name,fk_country) values('Lagoa dos Patos (MG)',1);
insert into city(name,fk_country) values('Lagoa dos Três Cantos (RS)',1);
insert into city(name,fk_country) values('Lagoa do Tocantins (TO)',1);
insert into city(name,fk_country) values('Lagoa Dourada (MG)',1);
insert into city(name,fk_country) values('Lagoa Formosa (MG)',1);
insert into city(name,fk_country) values('Lagoa Grande (MG)',1);
insert into city(name,fk_country) values('Lagoa Grande (PE)',1);
insert into city(name,fk_country) values('Lagoa Grande do Maranhão (MA)',1);
insert into city(name,fk_country) values('Lagoa Nova (RN)',1);
insert into city(name,fk_country) values('Lagoão (RS)',1);
insert into city(name,fk_country) values('Lagoa Real (BA)',1);
insert into city(name,fk_country) values('Lagoa Salgada (RN)',1);
insert into city(name,fk_country) values('Lagoa Santa (GO)',1);
insert into city(name,fk_country) values('Lagoa Santa (MG)',1);
insert into city(name,fk_country) values('Lagoa Seca (PB)',1);
insert into city(name,fk_country) values('Lagoa Vermelha (RS)',1);
insert into city(name,fk_country) values('Lago da Pedra (MA)',1);
insert into city(name,fk_country) values('Lago do Junco (MA)',1);
insert into city(name,fk_country) values('Lago dos Rodrigues (MA)',1);
insert into city(name,fk_country) values('Lagoinha (SP)',1);
insert into city(name,fk_country) values('Lagoinha do Piauí (PI)',1);
insert into city(name,fk_country) values('Lago Verde (MA)',1);
insert into city(name,fk_country) values('Laguna (SC)',1);
insert into city(name,fk_country) values('Laguna Carapã (MS)',1);
insert into city(name,fk_country) values('Laje (BA)',1);
insert into city(name,fk_country) values('Lajeado (RS)',1);
insert into city(name,fk_country) values('Macaé (RJ)',1);
insert into city(name,fk_country) values('Macaíba (RN)',1);
insert into city(name,fk_country) values('Macajuba (BA)',1);
insert into city(name,fk_country) values('Maçambará (RS)',1);
insert into city(name,fk_country) values('Macambira (SE)',1);
insert into city(name,fk_country) values('Macapá (AP)',1);
insert into city(name,fk_country) values('Macaparana (PE)',1);
insert into city(name,fk_country) values('Macarani (BA)',1);
insert into city(name,fk_country) values('Macatuba (SP)',1);
insert into city(name,fk_country) values('Macau (RN)',1);
insert into city(name,fk_country) values('Macaubal (SP)',1);
insert into city(name,fk_country) values('Macaúbas (BA)',1);
insert into city(name,fk_country) values('Macedônia (SP)',1);
insert into city(name,fk_country) values('Maceió (AL)',1);
insert into city(name,fk_country) values('Machacalis (MG)',1);
insert into city(name,fk_country) values('Machadinho (RS)',1);
insert into city(name,fk_country) values('Machadinho d''Oeste (RO)',1);
insert into city(name,fk_country) values('Machado (MG)',1);
insert into city(name,fk_country) values('Machados (PE)',1);
insert into city(name,fk_country) values('Macieira (SC)',1);
insert into city(name,fk_country) values('Macuco (RJ)',1);
insert into city(name,fk_country) values('Macururé (BA)',1);
insert into city(name,fk_country) values('Madalena (CE)',1);
insert into city(name,fk_country) values('Madeiro (PI)',1);
insert into city(name,fk_country) values('Madre de Deus (BA)',1);
insert into city(name,fk_country) values('Madre de Deus de Minas (MG)',1);
insert into city(name,fk_country) values('Mãe d''Água (PB)',1);
insert into city(name,fk_country) values('Mãe do Rio (PA)',1);
insert into city(name,fk_country) values('Maetinga (BA)',1);
insert into city(name,fk_country) values('Mafra (SC)',1);
insert into city(name,fk_country) values('Magalhães Barata (PA)',1);
insert into city(name,fk_country) values('Magalhães de Almeida (MA)',1);
insert into city(name,fk_country) values('Magda (SP)',1);
insert into city(name,fk_country) values('Magé (RJ)',1);
insert into city(name,fk_country) values('Maiquinique (BA)',1);
insert into city(name,fk_country) values('Mairi (BA)',1);
insert into city(name,fk_country) values('Mairinque (SP)',1);
insert into city(name,fk_country) values('Mairiporã (SP)',1);
insert into city(name,fk_country) values('Mairipotaba (GO)',1);
insert into city(name,fk_country) values('Major Gercino (SC)',1);
insert into city(name,fk_country) values('Major Isidoro (AL)',1);
insert into city(name,fk_country) values('Major Sales (RN)',1);
insert into city(name,fk_country) values('Major Vieira (SC)',1);
insert into city(name,fk_country) values('Malacacheta (MG)',1);