insert into city(name,fk_country) values('Malhada (BA)',1);
insert into city(name,fk_country) values('Malhada de Pedras (BA)',1);
insert into city(name,fk_country) values('Malhada dos Bois (SE)',1);
insert into city(name,fk_country) values('Malhador (SE)',1);
insert into city(name,fk_country) values('Mallet (PR)',1);
insert into city(name,fk_country) values('Malta (PB)',1);
insert into city(name,fk_country) values('Mamanguape (PB)',1);
insert into city(name,fk_country) values('Mambaí (GO)',1);
insert into city(name,fk_country) values('Mamborê (PR)',1);
insert into city(name,fk_country) values('Mamonas (MG)',1);
insert into city(name,fk_country) values('Mampituba (RS)',1);
insert into city(name,fk_country) values('Manacapuru (AM)',1);
insert into city(name,fk_country) values('Manaíra (PB)',1);
insert into city(name,fk_country) values('Manaquiri (AM)',1);
insert into city(name,fk_country) values('Manari (PE)',1);
insert into city(name,fk_country) values('Manaus (AM)',1);
insert into city(name,fk_country) values('Mâncio Lima (AC)',1);
insert into city(name,fk_country) values('Mandaguaçu (PR)',1);
insert into city(name,fk_country) values('Mandaguari (PR)',1);
insert into city(name,fk_country) values('Mandirituba (PR)',1);
insert into city(name,fk_country) values('Manduri (SP)',1);
insert into city(name,fk_country) values('Manfrinópolis (PR)',1);
insert into city(name,fk_country) values('Manga (MG)',1);
insert into city(name,fk_country) values('Mangaratiba (RJ)',1);
insert into city(name,fk_country) values('Mangueirinha (PR)',1);
insert into city(name,fk_country) values('Manhuaçu (MG)',1);
insert into city(name,fk_country) values('Manhumirim (MG)',1);
insert into city(name,fk_country) values('Manicoré (AM)',1);
insert into city(name,fk_country) values('Manoel Emídio (PI)',1);
insert into city(name,fk_country) values('Manoel Ribas (PR)',1);
insert into city(name,fk_country) values('Manoel Urbano (AC)',1);
insert into city(name,fk_country) values('Manoel Viana (RS)',1);
insert into city(name,fk_country) values('Manoel Vitorino (BA)',1);
insert into city(name,fk_country) values('Mansidão (BA)',1);
insert into city(name,fk_country) values('Mantena (MG)',1);
insert into city(name,fk_country) values('Mantenópolis (ES)',1);
insert into city(name,fk_country) values('Maquiné (RS)',1);
insert into city(name,fk_country) values('Maraã (AM)',1);
insert into city(name,fk_country) values('Marabá (PA)',1);
insert into city(name,fk_country) values('Marabá Paulista (SP)',1);
insert into city(name,fk_country) values('Maracaçumé (MA)',1);
insert into city(name,fk_country) values('Maracaí (SP)',1);
insert into city(name,fk_country) values('Maracajá (SC)',1);
insert into city(name,fk_country) values('Maracaju (MS)',1);
insert into city(name,fk_country) values('Maracanã (PA)',1);
insert into city(name,fk_country) values('Maracanaú (CE)',1);
insert into city(name,fk_country) values('Maracás (BA)',1);
insert into city(name,fk_country) values('Maragogi (AL)',1);
insert into city(name,fk_country) values('Maragogipe (BA)',1);
insert into city(name,fk_country) values('Maraial (PE)',1);
insert into city(name,fk_country) values('Marajá do Sena (MA)',1);
insert into city(name,fk_country) values('Maranguape (CE)',1);
insert into city(name,fk_country) values('Maranhãozinho (MA)',1);
insert into city(name,fk_country) values('Marapanim (PA)',1);
insert into city(name,fk_country) values('Marapoama (SP)',1);
insert into city(name,fk_country) values('Mara Rosa (GO)',1);
insert into city(name,fk_country) values('Maratá (RS)',1);
insert into city(name,fk_country) values('Marataízes (ES)',1);
insert into city(name,fk_country) values('Maraú (BA)',1);
insert into city(name,fk_country) values('Marau (RS)',1);
insert into city(name,fk_country) values('Maravilha (AL)',1);
insert into city(name,fk_country) values('Maravilha (SC)',1);
insert into city(name,fk_country) values('Maravilhas (MG)',1);
insert into city(name,fk_country) values('Marcação (PB)',1);
insert into city(name,fk_country) values('Marcelândia (MT)',1);
insert into city(name,fk_country) values('Marcelino Ramos (RS)',1);
insert into city(name,fk_country) values('Marcelino Vieira (RN)',1);
insert into city(name,fk_country) values('Marcionílio Souza (BA)',1);
insert into city(name,fk_country) values('Marco (CE)',1);
insert into city(name,fk_country) values('Marcolândia (PI)',1);
insert into city(name,fk_country) values('Marcos Parente (PI)',1);
insert into city(name,fk_country) values('Mar de Espanha (MG)',1);
insert into city(name,fk_country) values('Marechal Cândido Rondon (PR)',1);
insert into city(name,fk_country) values('Marechal Deodoro (AL)',1);
insert into city(name,fk_country) values('Marechal Floriano (ES)',1);
insert into city(name,fk_country) values('Marechal Thaumaturgo (AC)',1);
insert into city(name,fk_country) values('Marema (SC)',1);
insert into city(name,fk_country) values('Mari (PB)',1);
insert into city(name,fk_country) values('Maria da Fé (MG)',1);
insert into city(name,fk_country) values('Maria Helena (PR)',1);
insert into city(name,fk_country) values('Marialva (PR)',1);
insert into city(name,fk_country) values('Mariana (MG)',1);
insert into city(name,fk_country) values('Mariana Pimentel (RS)',1);
insert into city(name,fk_country) values('Mariano Moro (RS)',1);
insert into city(name,fk_country) values('Marianópolis do Tocantins (TO)',1);
insert into city(name,fk_country) values('Mariápolis (SP)',1);
insert into city(name,fk_country) values('Maribondo (AL)',1);
insert into city(name,fk_country) values('Maricá (RJ)',1);
insert into city(name,fk_country) values('Marilac (MG)',1);
insert into city(name,fk_country) values('Marilândia (ES)',1);
insert into city(name,fk_country) values('Marilândia do Sul (PR)',1);
insert into city(name,fk_country) values('Marilena (PR)',1);
insert into city(name,fk_country) values('Nacip Raydan (MG)',1);
insert into city(name,fk_country) values('Nantes (SP)',1);
insert into city(name,fk_country) values('Nanuque (MG)',1);
insert into city(name,fk_country) values('Não-Me-Toque (RS)',1);
insert into city(name,fk_country) values('Naque (MG)',1);
insert into city(name,fk_country) values('Narandiba (SP)',1);
insert into city(name,fk_country) values('Natal (RN)',1);
insert into city(name,fk_country) values('Natalândia (MG)',1);
insert into city(name,fk_country) values('Natércia (MG)',1);
insert into city(name,fk_country) values('Natividade (RJ)',1);
insert into city(name,fk_country) values('Natividade (TO)',1);
insert into city(name,fk_country) values('Natividade da Serra (SP)',1);
insert into city(name,fk_country) values('Natuba (PB)',1);
insert into city(name,fk_country) values('Navegantes (SC)',1);
insert into city(name,fk_country) values('Naviraí (MS)',1);
insert into city(name,fk_country) values('Nazaré (BA)',1);
insert into city(name,fk_country) values('Nazaré (TO)',1);
insert into city(name,fk_country) values('Nazaré da Mata (PE)',1);
insert into city(name,fk_country) values('Nazaré do Piauí (PI)',1);
insert into city(name,fk_country) values('Nazareno (MG)',1);
insert into city(name,fk_country) values('Nazaré Paulista (SP)',1);
insert into city(name,fk_country) values('Nazarezinho (PB)',1);
insert into city(name,fk_country) values('Nazária (PI)',1);
insert into city(name,fk_country) values('Nazário (GO)',1);
insert into city(name,fk_country) values('Neópolis (SE)',1);
insert into city(name,fk_country) values('Nepomuceno (MG)',1);
insert into city(name,fk_country) values('Nerópolis (GO)',1);
insert into city(name,fk_country) values('Neves Paulista (SP)',1);
insert into city(name,fk_country) values('Nhamundá (AM)',1);
insert into city(name,fk_country) values('Nhandeara (SP)',1);
insert into city(name,fk_country) values('Nicolau Vergueiro (RS)',1);
insert into city(name,fk_country) values('Nilo Peçanha (BA)',1);
insert into city(name,fk_country) values('Nilópolis (RJ)',1);
insert into city(name,fk_country) values('Nina Rodrigues (MA)',1);
insert into city(name,fk_country) values('Ninheira (MG)',1);
insert into city(name,fk_country) values('Nioaque (MS)',1);
insert into city(name,fk_country) values('Nipoã (SP)',1);
insert into city(name,fk_country) values('Niquelândia (GO)',1);
insert into city(name,fk_country) values('Nísia Floresta (RN)',1);
insert into city(name,fk_country) values('Niterói (RJ)',1);
insert into city(name,fk_country) values('Nobres (MT)',1);
insert into city(name,fk_country) values('Nonoai (RS)',1);
insert into city(name,fk_country) values('Nordestina (BA)',1);
insert into city(name,fk_country) values('Normandia (RR)',1);
insert into city(name,fk_country) values('Nortelândia (MT)',1);
insert into city(name,fk_country) values('Nossa Senhora Aparecida (SE)',1);
insert into city(name,fk_country) values('Nossa Senhora da Glória (SE)',1);
insert into city(name,fk_country) values('Nossa Senhora das Dores (SE)',1);
insert into city(name,fk_country) values('Nossa Senhora das Graças (PR)',1);
insert into city(name,fk_country) values('Nossa Senhora de Lourdes (SE)',1);
insert into city(name,fk_country) values('Nossa Senhora de Nazaré (PI)',1);
insert into city(name,fk_country) values('Nossa Senhora do Livramento (MT)',1);
insert into city(name,fk_country) values('Nossa Senhora do Socorro (SE)',1);
insert into city(name,fk_country) values('Nossa Senhora dos Remédios (PI)',1);
insert into city(name,fk_country) values('Nova Aliança (SP)',1);
insert into city(name,fk_country) values('Nova Aliança do Ivaí (PR)',1);
insert into city(name,fk_country) values('Nova Alvorada (RS)',1);
insert into city(name,fk_country) values('Nova Alvorada do Sul (MS)',1);
insert into city(name,fk_country) values('Nova América (GO)',1);
insert into city(name,fk_country) values('Nova América da Colina (PR)',1);
insert into city(name,fk_country) values('Nova Andradina (MS)',1);
insert into city(name,fk_country) values('Nova Araçá (RS)',1);
insert into city(name,fk_country) values('Nova Aurora (GO)',1);
insert into city(name,fk_country) values('Nova Aurora (PR)',1);
insert into city(name,fk_country) values('Nova Bandeirantes (MT)',1);
insert into city(name,fk_country) values('Nova Bassano (RS)',1);
insert into city(name,fk_country) values('Óbidos (PA)',1);
insert into city(name,fk_country) values('Ocara (CE)',1);
insert into city(name,fk_country) values('Ocauçu (SP)',1);
insert into city(name,fk_country) values('Oeiras (PI)',1);
insert into city(name,fk_country) values('Oeiras do Pará (PA)',1);
insert into city(name,fk_country) values('Oiapoque (AP)',1);
insert into city(name,fk_country) values('Olaria (MG)',1);
insert into city(name,fk_country) values('Óleo (SP)',1);
insert into city(name,fk_country) values('Olho d''Água (PB)',1);
insert into city(name,fk_country) values('Olho d''Água das Cunhãs (MA)',1);
insert into city(name,fk_country) values('Olho d''Água das Flores (AL)',1);
insert into city(name,fk_country) values('Olho d''Água do Borges (RN)',1);
insert into city(name,fk_country) values('Olho d''Água do Casado (AL)',1);
insert into city(name,fk_country) values('Olho d''Água do Piauí (PI)',1);
insert into city(name,fk_country) values('Olho d''Água Grande (AL)',1);
insert into city(name,fk_country) values('Olhos-d''Água (MG)',1);
insert into city(name,fk_country) values('Olímpia (SP)',1);
insert into city(name,fk_country) values('Olímpio Noronha (MG)',1);
insert into city(name,fk_country) values('Olinda (PE)',1);
insert into city(name,fk_country) values('Olinda Nova do Maranhão (MA)',1);
insert into city(name,fk_country) values('Olindina (BA)',1);
insert into city(name,fk_country) values('Olivedos (PB)',1);
insert into city(name,fk_country) values('Oliveira (MG)',1);
insert into city(name,fk_country) values('Pacaembu (SP)',1);
insert into city(name,fk_country) values('Pacajá (PA)',1);
insert into city(name,fk_country) values('Pacajus (CE)',1);
insert into city(name,fk_country) values('Pacaraima (RR)',1);
insert into city(name,fk_country) values('Pacatuba (CE)',1);
insert into city(name,fk_country) values('Pacatuba (SE)',1);
insert into city(name,fk_country) values('Paço do Lumiar (MA)',1);
insert into city(name,fk_country) values('Pacoti (CE)',1);
insert into city(name,fk_country) values('Pacujá (CE)',1);
insert into city(name,fk_country) values('Padre Bernardo (GO)',1);
insert into city(name,fk_country) values('Padre Carvalho (MG)',1);
insert into city(name,fk_country) values('Padre Marcos (PI)',1);
insert into city(name,fk_country) values('Padre Paraíso (MG)',1);
insert into city(name,fk_country) values('Paes Landim (PI)',1);
insert into city(name,fk_country) values('Paial (SC)',1);
insert into city(name,fk_country) values('Paiçandu (PR)',1);
insert into city(name,fk_country) values('Paim Filho (RS)',1);
insert into city(name,fk_country) values('Paineiras (MG)',1);
insert into city(name,fk_country) values('Painel (SC)',1);
insert into city(name,fk_country) values('Pains (MG)',1);
insert into city(name,fk_country) values('Pai Pedro (MG)',1);
insert into city(name,fk_country) values('Paiva (MG)',1);
insert into city(name,fk_country) values('Pajeú do Piauí (PI)',1);
insert into city(name,fk_country) values('Palestina (AL)',1);
insert into city(name,fk_country) values('Palestina (SP)',1);
insert into city(name,fk_country) values('Palestina de Goiás (GO)',1);
insert into city(name,fk_country) values('Palestina do Pará (PA)',1);
insert into city(name,fk_country) values('Palhano (CE)',1);
insert into city(name,fk_country) values('Palhoça (SC)',1);
insert into city(name,fk_country) values('Palma (MG)',1);
insert into city(name,fk_country) values('Palmácia (CE)',1);
insert into city(name,fk_country) values('Palmares (PE)',1);
insert into city(name,fk_country) values('Palmares do Sul (RS)',1);
insert into city(name,fk_country) values('Palmares Paulista (SP)',1);
insert into city(name,fk_country) values('Palmas (PR)',1);
insert into city(name,fk_country) values('Palmas (TO)',1);
insert into city(name,fk_country) values('Palmas de Monte Alto (BA)',1);
insert into city(name,fk_country) values('Palma Sola (SC)',1);
insert into city(name,fk_country) values('Palmeira (PR)',1);
insert into city(name,fk_country) values('Palmeira (SC)',1);
insert into city(name,fk_country) values('Palmeira das Missões (RS)',1);
insert into city(name,fk_country) values('Palmeira d''Oeste (SP)',1);
insert into city(name,fk_country) values('Palmeira do Piauí (PI)',1);
insert into city(name,fk_country) values('Palmeira dos Índios (AL)',1);
insert into city(name,fk_country) values('Palmeirais (PI)',1);
insert into city(name,fk_country) values('Palmeirândia (MA)',1);
insert into city(name,fk_country) values('Palmeirante (TO)',1);
insert into city(name,fk_country) values('Palmeiras (BA)',1);
insert into city(name,fk_country) values('Palmeiras de Goiás (GO)',1);
insert into city(name,fk_country) values('Palmeiras do Tocantins (TO)',1);
insert into city(name,fk_country) values('Palmeirina (PE)',1);
insert into city(name,fk_country) values('Palmeirópolis (TO)',1);
insert into city(name,fk_country) values('Palmelo (GO)',1);
insert into city(name,fk_country) values('Palminópolis (GO)',1);
insert into city(name,fk_country) values('Palmital (PR)',1);
insert into city(name,fk_country) values('Palmital (SP)',1);
insert into city(name,fk_country) values('Palmitinho (RS)',1);
insert into city(name,fk_country) values('Palmitos (SC)',1);
insert into city(name,fk_country) values('Palmópolis (MG)',1);
insert into city(name,fk_country) values('Palotina (PR)',1);
insert into city(name,fk_country) values('Panamá (GO)',1);
insert into city(name,fk_country) values('Panambi (RS)',1);
insert into city(name,fk_country) values('Pancas (ES)',1);
insert into city(name,fk_country) values('Panelas (PE)',1);
insert into city(name,fk_country) values('Panorama (SP)',1);
insert into city(name,fk_country) values('Pantano Grande (RS)',1);
insert into city(name,fk_country) values('Pão de Açúcar (AL)',1);
insert into city(name,fk_country) values('Papagaios (MG)',1);
insert into city(name,fk_country) values('Papanduva (SC)',1);
insert into city(name,fk_country) values('Paquetá (PI)',1);
insert into city(name,fk_country) values('Paracambi (RJ)',1);
insert into city(name,fk_country) values('Paracatu (MG)',1);
insert into city(name,fk_country) values('Paracuru (CE)',1);
insert into city(name,fk_country) values('Pará de Minas (MG)',1);
insert into city(name,fk_country) values('Paragominas (PA)',1);
insert into city(name,fk_country) values('Paraguaçu (MG)',1);
insert into city(name,fk_country) values('Paraguaçu Paulista (SP)',1);
insert into city(name,fk_country) values('Paraí (RS)',1);
insert into city(name,fk_country) values('Paraíba do Sul (RJ)',1);
insert into city(name,fk_country) values('Paraibano (MA)',1);
insert into city(name,fk_country) values('Paraibuna (SP)',1);
insert into city(name,fk_country) values('Paraipaba (CE)',1);
insert into city(name,fk_country) values('Paraíso (SC)',1);
insert into city(name,fk_country) values('Paraíso (SP)',1);
insert into city(name,fk_country) values('Paraíso das Águas (MS)',1);
insert into city(name,fk_country) values('Paraíso do Norte (PR)',1);
insert into city(name,fk_country) values('Paraíso do Sul (RS)',1);
insert into city(name,fk_country) values('Paraíso do Tocantins (TO)',1);
insert into city(name,fk_country) values('Paraisópolis (MG)',1);
insert into city(name,fk_country) values('Parambu (CE)',1);
insert into city(name,fk_country) values('Paramirim (BA)',1);
insert into city(name,fk_country) values('Paramoti (CE)',1);
insert into city(name,fk_country) values('Paraná (RN)',1);
insert into city(name,fk_country) values('Paranã (TO)',1);
insert into city(name,fk_country) values('Paranacity (PR)',1);
insert into city(name,fk_country) values('Paranaguá (PR)',1);
insert into city(name,fk_country) values('Paranaíba (MS)',1);
insert into city(name,fk_country) values('Paranaiguara (GO)',1);
insert into city(name,fk_country) values('Paranaíta (MT)',1);
insert into city(name,fk_country) values('Paranapanema (SP)',1);
insert into city(name,fk_country) values('Paranapoema (PR)',1);
insert into city(name,fk_country) values('Paranapuã (SP)',1);
insert into city(name,fk_country) values('Paranatama (PE)',1);
insert into city(name,fk_country) values('Paranatinga (MT)',1);
insert into city(name,fk_country) values('Paranavaí (PR)',1);
insert into city(name,fk_country) values('Paranhos (MS)',1);
insert into city(name,fk_country) values('Paraopeba (MG)',1);
insert into city(name,fk_country) values('Parapuã (SP)',1);
insert into city(name,fk_country) values('Parari (PB)',1);
insert into city(name,fk_country) values('Paratinga (BA)',1);
insert into city(name,fk_country) values('Paraty (RJ)',1);
insert into city(name,fk_country) values('Paraú (RN)',1);
insert into city(name,fk_country) values('Parauapebas (PA)',1);
insert into city(name,fk_country) values('Paraúna (GO)',1);
insert into city(name,fk_country) values('Parazinho (RN)',1);
insert into city(name,fk_country) values('Pardinho (SP)',1);
insert into city(name,fk_country) values('Pareci Novo (RS)',1);
insert into city(name,fk_country) values('Parecis (RO)',1);
insert into city(name,fk_country) values('Parelhas (RN)',1);
insert into city(name,fk_country) values('Pariconha (AL)',1);
insert into city(name,fk_country) values('Parintins (AM)',1);
insert into city(name,fk_country) values('Paripiranga (BA)',1);
insert into city(name,fk_country) values('Paripueira (AL)',1);
insert into city(name,fk_country) values('Pariquera-Açu (SP)',1);
insert into city(name,fk_country) values('Parisi (SP)',1);
insert into city(name,fk_country) values('Parnaguá (PI)',1);
insert into city(name,fk_country) values('Parnaíba (PI)',1);
insert into city(name,fk_country) values('Parnamirim (PE)',1);
insert into city(name,fk_country) values('Parnamirim (RN)',1);
insert into city(name,fk_country) values('Parnarama (MA)',1);
insert into city(name,fk_country) values('Parobé (RS)',1);
insert into city(name,fk_country) values('Passabém (MG)',1);
insert into city(name,fk_country) values('Passa-e-Fica (RN)',1);
insert into city(name,fk_country) values('Passagem (PB)',1);
insert into city(name,fk_country) values('Passagem (RN)',1);
insert into city(name,fk_country) values('Passagem Franca (MA)',1);
insert into city(name,fk_country) values('Passagem Franca do Piauí (PI)',1);
insert into city(name,fk_country) values('Passa-Quatro (MG)',1);
insert into city(name,fk_country) values('Passa-Sete (RS)',1);
insert into city(name,fk_country) values('Passa Tempo (MG)',1);
insert into city(name,fk_country) values('Passa Vinte (MG)',1);
insert into city(name,fk_country) values('Passira (PE)',1);
insert into city(name,fk_country) values('Passo de Camaragibe (AL)',1);
insert into city(name,fk_country) values('Passo de Torres (SC)',1);
insert into city(name,fk_country) values('Passo do Sobrado (RS)',1);
insert into city(name,fk_country) values('Passo Fundo (RS)',1);
insert into city(name,fk_country) values('Passos (MG)',1);
insert into city(name,fk_country) values('Passos Maia (SC)',1);
insert into city(name,fk_country) values('Pastos Bons (MA)',1);
insert into city(name,fk_country) values('Patis (MG)',1);
insert into city(name,fk_country) values('Pato Bragado (PR)',1);
insert into city(name,fk_country) values('Pato Branco (PR)',1);
insert into city(name,fk_country) values('Patos (PB)',1);
insert into city(name,fk_country) values('Patos de Minas (MG)',1);
insert into city(name,fk_country) values('Patos do Piauí (PI)',1);
insert into city(name,fk_country) values('Patrocínio (MG)',1);
insert into city(name,fk_country) values('Patrocínio do Muriaé (MG)',1);
insert into city(name,fk_country) values('Patrocínio Paulista (SP)',1);
insert into city(name,fk_country) values('Patu (RN)',1);
insert into city(name,fk_country) values('Paty do Alferes (RJ)',1);
insert into city(name,fk_country) values('Pau Brasil (BA)',1);
insert into city(name,fk_country) values('Paudalho (PE)',1);
insert into city(name,fk_country) values('Pau-d''Arco (PA)',1);
insert into city(name,fk_country) values('Pau-d''Arco (TO)',1);
insert into city(name,fk_country) values('Pau-d''Arco do Piauí (PI)',1);
insert into city(name,fk_country) values('Pau dos Ferros (RN)',1);
insert into city(name,fk_country) values('Pauini (AM)',1);
insert into city(name,fk_country) values('Paula Cândido (MG)',1);
insert into city(name,fk_country) values('Paula Freitas (PR)',1);
insert into city(name,fk_country) values('Pauliceia (SP)',1);
insert into city(name,fk_country) values('Paulínia (SP)',1);
insert into city(name,fk_country) values('Paulino Neves (MA)',1);
insert into city(name,fk_country) values('Paulista (PB)',1);
insert into city(name,fk_country) values('Paulista (PE)',1);
insert into city(name,fk_country) values('Paulistana (PI)',1);
insert into city(name,fk_country) values('Paulistânia (SP)',1);
insert into city(name,fk_country) values('Paulistas (MG)',1);
insert into city(name,fk_country) values('Paulo Afonso (BA)',1);
insert into city(name,fk_country) values('Paulo Bento (RS)',1);
insert into city(name,fk_country) values('Paulo de Faria (SP)',1);
insert into city(name,fk_country) values('Paulo Frontin (PR)',1);
insert into city(name,fk_country) values('Paulo Jacinto (AL)',1);
insert into city(name,fk_country) values('Paulo Lopes (SC)',1);
insert into city(name,fk_country) values('Paulo Ramos (MA)',1);
insert into city(name,fk_country) values('Pavão (MG)',1);
insert into city(name,fk_country) values('Paverama (RS)',1);
insert into city(name,fk_country) values('Pavussu (PI)',1);
insert into city(name,fk_country) values('Quadra (SP)',1);
insert into city(name,fk_country) values('Quaraí (RS)',1);
insert into city(name,fk_country) values('Quartel Geral (MG)',1);
insert into city(name,fk_country) values('Quarto Centenário (PR)',1);
insert into city(name,fk_country) values('Quatá (SP)',1);
insert into city(name,fk_country) values('Quatiguá (PR)',1);
insert into city(name,fk_country) values('Quatipuru (PA)',1);
insert into city(name,fk_country) values('Quatis (RJ)',1);
insert into city(name,fk_country) values('Quatro Barras (PR)',1);
insert into city(name,fk_country) values('Quatro Irmãos (RS)',1);
insert into city(name,fk_country) values('Quatro Pontes (PR)',1);
insert into city(name,fk_country) values('Quebrangulo (AL)',1);
insert into city(name,fk_country) values('Quedas do Iguaçu (PR)',1);
insert into city(name,fk_country) values('Queimada Nova (PI)',1);
insert into city(name,fk_country) values('Rafael Fernandes (RN)',1);
insert into city(name,fk_country) values('Rafael Godeiro (RN)',1);
insert into city(name,fk_country) values('Rafael Jambeiro (BA)',1);
insert into city(name,fk_country) values('Rafard (SP)',1);
insert into city(name,fk_country) values('Ramilândia (PR)',1);
insert into city(name,fk_country) values('Rancharia (SP)',1);
insert into city(name,fk_country) values('Rancho Alegre d''Oeste (PR)',1);
insert into city(name,fk_country) values('Rancho Alegre (PR)',1);
insert into city(name,fk_country) values('Rancho Queimado (SC)',1);
insert into city(name,fk_country) values('Raposa (MA)',1);
insert into city(name,fk_country) values('Raposos (MG)',1);
insert into city(name,fk_country) values('Raul Soares (MG)',1);
insert into city(name,fk_country) values('Realeza (PR)',1);
insert into city(name,fk_country) values('Rebouças (PR)',1);
insert into city(name,fk_country) values('Recife (PE)',1);
insert into city(name,fk_country) values('Recreio (MG)',1);
insert into city(name,fk_country) values('Recursolândia (TO)',1);
insert into city(name,fk_country) values('Redenção (CE)',1);
insert into city(name,fk_country) values('Redenção (PA)',1);
insert into city(name,fk_country) values('Redenção da Serra (SP)',1);
insert into city(name,fk_country) values('Redenção do Gurgueia (PI)',1);
insert into city(name,fk_country) values('Redentora (RS)',1);
insert into city(name,fk_country) values('Reduto (MG)',1);
insert into city(name,fk_country) values('Regeneração (PI)',1);
insert into city(name,fk_country) values('Regente Feijó (SP)',1);
insert into city(name,fk_country) values('Reginópolis (SP)',1);
insert into city(name,fk_country) values('Registro (SP)',1);
insert into city(name,fk_country) values('Relvado (RS)',1);
insert into city(name,fk_country) values('Remanso (BA)',1);
insert into city(name,fk_country) values('Remígio (PB)',1);
insert into city(name,fk_country) values('Renascença (PR)',1);
insert into city(name,fk_country) values('Reriutaba (CE)',1);
insert into city(name,fk_country) values('Resende (RJ)',1);
insert into city(name,fk_country) values('Resende Costa (MG)',1);
insert into city(name,fk_country) values('Reserva do Cabaçal (MT)',1);
insert into city(name,fk_country) values('Reserva do Iguaçu (PR)',1);
insert into city(name,fk_country) values('Reserva (PR)',1);
insert into city(name,fk_country) values('Resplendor (MG)',1);
insert into city(name,fk_country) values('Ressaquinha (MG)',1);
insert into city(name,fk_country) values('Restinga (SP)',1);
insert into city(name,fk_country) values('Restinga Seca (RS)',1);
insert into city(name,fk_country) values('Retirolândia (BA)',1);
insert into city(name,fk_country) values('Riachão (MA)',1);
insert into city(name,fk_country) values('Riachão (PB)',1);
insert into city(name,fk_country) values('Riachão das Neves (BA)',1);
insert into city(name,fk_country) values('Riachão do Bacamarte (PB)',1);
insert into city(name,fk_country) values('Riachão do Dantas (SE)',1);
insert into city(name,fk_country) values('Riachão do Jacuípe (BA)',1);
insert into city(name,fk_country) values('Riachão do Poço (PB)',1);
insert into city(name,fk_country) values('Riachinho (MG)',1);
insert into city(name,fk_country) values('Riachinho (TO)',1);
insert into city(name,fk_country) values('Riacho da Cruz (RN)',1);
insert into city(name,fk_country) values('Riacho das Almas (PE)',1);
insert into city(name,fk_country) values('Riacho de Santana (BA)',1);
insert into city(name,fk_country) values('Riacho de Santana (RN)',1);
insert into city(name,fk_country) values('Riacho de Santo Antônio (PB)',1);
insert into city(name,fk_country) values('Riacho dos Cavalos (PB)',1);
insert into city(name,fk_country) values('Riacho dos Machados (MG)',1);
insert into city(name,fk_country) values('Riacho Frio (PI)',1);
insert into city(name,fk_country) values('Riachuelo (RN)',1);
insert into city(name,fk_country) values('Riachuelo (SE)',1);
insert into city(name,fk_country) values('Rialma (GO)',1);
insert into city(name,fk_country) values('Rianápolis (GO)',1);
insert into city(name,fk_country) values('Ribamar Fiquene (MA)',1);
insert into city(name,fk_country) values('Ribas do Rio Pardo (MS)',1);
insert into city(name,fk_country) values('Ribeira (SP)',1);
insert into city(name,fk_country) values('Sabará (MG)',1);
insert into city(name,fk_country) values('Sabáudia (PR)',1);
insert into city(name,fk_country) values('Sabinópolis (MG)',1);
insert into city(name,fk_country) values('Sabino (SP)',1);
insert into city(name,fk_country) values('Saboeiro (CE)',1);
insert into city(name,fk_country) values('Sacramento (MG)',1);
insert into city(name,fk_country) values('Sagrada Família (RS)',1);
insert into city(name,fk_country) values('Sagres (SP)',1);
insert into city(name,fk_country) values('Sairé (PE)',1);
insert into city(name,fk_country) values('Saldanha Marinho (RS)',1);
insert into city(name,fk_country) values('Sales (SP)',1);
insert into city(name,fk_country) values('Sales Oliveira (SP)',1);
insert into city(name,fk_country) values('Salesópolis (SP)',1);
insert into city(name,fk_country) values('Salete (SC)',1);
insert into city(name,fk_country) values('Salgadinho (PB)',1);
insert into city(name,fk_country) values('Salgadinho (PE)',1);
insert into city(name,fk_country) values('Salgado (SE)',1);
insert into city(name,fk_country) values('Salgado de São Félix (PB)',1);
insert into city(name,fk_country) values('Salgado Filho (PR)',1);
insert into city(name,fk_country) values('Salgueiro (PE)',1);
insert into city(name,fk_country) values('Salinas (MG)',1);
insert into city(name,fk_country) values('Salinas da Margarida (BA)',1);
insert into city(name,fk_country) values('Salinópolis (PA)',1);
insert into city(name,fk_country) values('Salitre (CE)',1);
insert into city(name,fk_country) values('Salmourão (SP)',1);
insert into city(name,fk_country) values('Saloá (PE)',1);
insert into city(name,fk_country) values('Saltinho (SC)',1);
insert into city(name,fk_country) values('Saltinho (SP)',1);
insert into city(name,fk_country) values('Salto (SP)',1);
insert into city(name,fk_country) values('Salto da Divisa (MG)',1);
insert into city(name,fk_country) values('Salto de Pirapora (SP)',1);
insert into city(name,fk_country) values('Salto do Céu (MT)',1);
insert into city(name,fk_country) values('Salto do Itararé (PR)',1);
insert into city(name,fk_country) values('Salto do Jacuí (RS)',1);
insert into city(name,fk_country) values('Salto do Lontra (PR)',1);
insert into city(name,fk_country) values('Salto Grande (SP)',1);
insert into city(name,fk_country) values('Salto Veloso (SC)',1);
insert into city(name,fk_country) values('Salvador (BA)',1);
insert into city(name,fk_country) values('Salvador das Missões (RS)',1);
insert into city(name,fk_country) values('Salvador do Sul (RS)',1);
insert into city(name,fk_country) values('Salvaterra (PA)',1);
insert into city(name,fk_country) values('Sambaíba (MA)',1);
insert into city(name,fk_country) values('Sampaio (TO)',1);
insert into city(name,fk_country) values('Sananduva (RS)',1);
insert into city(name,fk_country) values('Sanclerlândia (GO)',1);
insert into city(name,fk_country) values('Sandolândia (TO)',1);
insert into city(name,fk_country) values('Sandovalina (SP)',1);
insert into city(name,fk_country) values('Sangão (SC)',1);
insert into city(name,fk_country) values('Sanharó (PE)',1);
insert into city(name,fk_country) values('Santa Adélia (SP)',1);
insert into city(name,fk_country) values('Santa Albertina (SP)',1);
insert into city(name,fk_country) values('Santa Amélia (PR)',1);
insert into city(name,fk_country) values('Santa Bárbara (BA)',1);
insert into city(name,fk_country) values('Santa Bárbara (MG)',1);
insert into city(name,fk_country) values('Santa Bárbara de Goiás (GO)',1);
insert into city(name,fk_country) values('Santa Bárbara d''Oeste (SP)',1);
insert into city(name,fk_country) values('Santa Bárbara do Leste (MG)',1);
insert into city(name,fk_country) values('Santa Bárbara do Monte Verde (MG)',1);
insert into city(name,fk_country) values('Santa Bárbara do Pará (PA)',1);
insert into city(name,fk_country) values('Santa Bárbara do Sul (RS)',1);
insert into city(name,fk_country) values('Santa Bárbara do Tugúrio (MG)',1);
insert into city(name,fk_country) values('Santa Branca (SP)',1);
insert into city(name,fk_country) values('Santa Brígida (BA)',1);
insert into city(name,fk_country) values('Santa Carmem (MT)',1);
insert into city(name,fk_country) values('Santa Cecília (PB)',1);
insert into city(name,fk_country) values('Santa Cecília (SC)',1);
insert into city(name,fk_country) values('Santa Cecília do Pavão (PR)',1);
insert into city(name,fk_country) values('Santa Cecília do Sul (RS)',1);
insert into city(name,fk_country) values('Santa Clara d''Oeste (SP)',1);
insert into city(name,fk_country) values('Santa Clara do Sul (RS)',1);
insert into city(name,fk_country) values('Santa Cruz (PB)',1);
insert into city(name,fk_country) values('Santa Cruz (PE)',1);
insert into city(name,fk_country) values('Santa Cruz (RN)',1);
insert into city(name,fk_country) values('Santa Cruz Cabrália (BA)',1);
insert into city(name,fk_country) values('Santa Cruz da Baixa Verde (PE)',1);
insert into city(name,fk_country) values('Santa Cruz da Conceição (SP)',1);
insert into city(name,fk_country) values('Santa Cruz da Esperança (SP)',1);
insert into city(name,fk_country) values('Santa Cruz da Vitória (BA)',1);
insert into city(name,fk_country) values('Santa Cruz das Palmeiras (SP)',1);
insert into city(name,fk_country) values('Santa Cruz de Goiás (GO)',1);
insert into city(name,fk_country) values('Santa Cruz de Minas (MG)',1);
insert into city(name,fk_country) values('Santa Cruz de Monte Castelo (PR)',1);
insert into city(name,fk_country) values('Santa Cruz de Salinas (MG)',1);
insert into city(name,fk_country) values('Santa Cruz do Arari (PA)',1);
insert into city(name,fk_country) values('Santa Cruz do Capibaribe (PE)',1);
insert into city(name,fk_country) values('Santa Cruz do Escalvado (MG)',1);
insert into city(name,fk_country) values('Santa Cruz do Piauí (PI)',1);
insert into city(name,fk_country) values('Santa Cruz do Rio Pardo (SP)',1);
insert into city(name,fk_country) values('Santa Cruz do Sul (RS)',1);
insert into city(name,fk_country) values('Santa Cruz do Xingu (MT)',1);
insert into city(name,fk_country) values('Santa Cruz dos Milagres (PI)',1);
insert into city(name,fk_country) values('Santa Efigênia de Minas (MG)',1);
insert into city(name,fk_country) values('Santa Ernestina (SP)',1);
insert into city(name,fk_country) values('Santa Fé (PR)',1);
insert into city(name,fk_country) values('Santa Fé de Goiás (GO)',1);
insert into city(name,fk_country) values('Santa Fé de Minas (MG)',1);
insert into city(name,fk_country) values('Santa Fé do Araguaia (TO)',1);
insert into city(name,fk_country) values('Santa Fé do Sul (SP)',1);
insert into city(name,fk_country) values('Santa Filomena (PE)',1);
insert into city(name,fk_country) values('Santa Filomena (PI)',1);
insert into city(name,fk_country) values('Santa Filomena do Maranhão (MA)',1);
insert into city(name,fk_country) values('Santa Gertrudes (SP)',1);
insert into city(name,fk_country) values('Santa Helena (MA)',1);
insert into city(name,fk_country) values('Santa Helena (PB)',1);
insert into city(name,fk_country) values('Santa Helena (PR)',1);
insert into city(name,fk_country) values('Santa Helena (SC)',1);
insert into city(name,fk_country) values('Santa Helena de Goiás (GO)',1);
insert into city(name,fk_country) values('Santa Helena de Minas (MG)',1);
insert into city(name,fk_country) values('Santa Inês (BA)',1);
insert into city(name,fk_country) values('Santa Inês (MA)',1);
insert into city(name,fk_country) values('Santa Inês (PB)',1);
insert into city(name,fk_country) values('Santa Inês (PR)',1);
insert into city(name,fk_country) values('Santa Isabel (GO)',1);
insert into city(name,fk_country) values('Santa Isabel (SP)',1);
insert into city(name,fk_country) values('Santa Isabel do Ivaí (PR)',1);
insert into city(name,fk_country) values('Santa Isabel do Pará (PA)',1);
insert into city(name,fk_country) values('Santa Isabel do Rio Negro (AM)',1);
insert into city(name,fk_country) values('Santa Izabel do Oeste (PR)',1);
insert into city(name,fk_country) values('Santa Juliana (MG)',1);
insert into city(name,fk_country) values('Santa Leopoldina (ES)',1);
insert into city(name,fk_country) values('Santa Lúcia (PR)',1);
insert into city(name,fk_country) values('Santa Lúcia (SP)',1);
insert into city(name,fk_country) values('Santaluz (BA)',1);
insert into city(name,fk_country) values('Santa Luz (PI)',1);
insert into city(name,fk_country) values('Santa Luzia (BA)',1);
insert into city(name,fk_country) values('Santa Luzia (MA)',1);
insert into city(name,fk_country) values('Santa Luzia (MG)',1);
insert into city(name,fk_country) values('Santa Luzia (PB)',1);
insert into city(name,fk_country) values('Santa Luzia d''Oeste (RO)',1);
insert into city(name,fk_country) values('Santa Luzia do Itanhy (SE)',1);
insert into city(name,fk_country) values('Santa Luzia do Norte (AL)',1);
insert into city(name,fk_country) values('Santa Luzia do Pará (PA)',1);
insert into city(name,fk_country) values('Santa Luzia do Paruá (MA)',1);
insert into city(name,fk_country) values('Santa Margarida (MG)',1);
insert into city(name,fk_country) values('Santa Margarida do Sul (RS)',1);
insert into city(name,fk_country) values('Santa Maria (RN)',1);
insert into city(name,fk_country) values('Santa Maria (RS)',1);
insert into city(name,fk_country) values('Santa Maria da Boa Vista (PE)',1);
insert into city(name,fk_country) values('Santa Maria das Barreiras (PA)',1);
insert into city(name,fk_country) values('Santa Maria da Serra (SP)',1);
insert into city(name,fk_country) values('Santa Maria da Vitória (BA)',1);
insert into city(name,fk_country) values('Santa Maria de Itabira (MG)',1);
insert into city(name,fk_country) values('Santa Maria do Cambucá (PE)',1);
insert into city(name,fk_country) values('Santa Maria do Herval (RS)',1);
insert into city(name,fk_country) values('Santa Maria de Jetibá (ES)',1);
insert into city(name,fk_country) values('Santa Maria do Oeste (PR)',1);
insert into city(name,fk_country) values('Santa Maria do Pará (PA)',1);
insert into city(name,fk_country) values('Santa Maria do Salto (MG)',1);
insert into city(name,fk_country) values('Santa Maria do Suaçuí (MG)',1);
insert into city(name,fk_country) values('Santa Maria do Tocantins (TO)',1);
insert into city(name,fk_country) values('Santa Maria Madalena (RJ)',1);
insert into city(name,fk_country) values('Santa Mariana (PR)',1);
insert into city(name,fk_country) values('Santa Mercedes (SP)',1);
insert into city(name,fk_country) values('Santa Mônica (PR)',1);
insert into city(name,fk_country) values('Santana (AP)',1);
insert into city(name,fk_country) values('Santana (BA)',1);
insert into city(name,fk_country) values('Santana da Boa Vista (RS)',1);
insert into city(name,fk_country) values('Santana da Ponte Pensa (SP)',1);
insert into city(name,fk_country) values('Santana da Vargem (MG)',1);
insert into city(name,fk_country) values('Santana de Cataguases (MG)',1);
insert into city(name,fk_country) values('Santana de Mangueira (PB)',1);
insert into city(name,fk_country) values('Santana de Parnaíba (SP)',1);
insert into city(name,fk_country) values('Santana de Pirapama (MG)',1);
insert into city(name,fk_country) values('Santana do Acaraú (CE)',1);
insert into city(name,fk_country) values('Santana do Araguaia (PA)',1);
insert into city(name,fk_country) values('Santana do Cariri (CE)',1);
insert into city(name,fk_country) values('Santana do Deserto (MG)',1);
insert into city(name,fk_country) values('Santana do Garambéu (MG)',1);
insert into city(name,fk_country) values('Santana do Ipanema (AL)',1);
insert into city(name,fk_country) values('Santana do Itararé (PR)',1);
insert into city(name,fk_country) values('Santana do Jacaré (MG)',1);
insert into city(name,fk_country) values('Santana do Livramento (RS)',1);
insert into city(name,fk_country) values('Santana do Manhuaçu (MG)',1);
insert into city(name,fk_country) values('Santana do Maranhão (MA)',1);
insert into city(name,fk_country) values('Santana do Matos (RN)',1);
insert into city(name,fk_country) values('Santana do Mundaú (AL)',1);
insert into city(name,fk_country) values('Santana do Paraíso (MG)',1);
insert into city(name,fk_country) values('Santana do Piauí (PI)',1);
insert into city(name,fk_country) values('Santana do Riacho (MG)',1);
insert into city(name,fk_country) values('Santana do São Francisco (SE)',1);
insert into city(name,fk_country) values('Santana do Seridó (RN)',1);
insert into city(name,fk_country) values('Santana dos Garrotes (PB)',1);
insert into city(name,fk_country) values('Santana dos Montes (MG)',1);
insert into city(name,fk_country) values('Santanópolis (BA)',1);
insert into city(name,fk_country) values('Santa Quitéria (CE)',1);
insert into city(name,fk_country) values('Santa Quitéria do Maranhão (MA)',1);
insert into city(name,fk_country) values('Santarém (PA)',1);
insert into city(name,fk_country) values('Santarém Novo (PA)',1);
insert into city(name,fk_country) values('Santa Rita (MA)',1);
insert into city(name,fk_country) values('Santa Rita (PB)',1);
insert into city(name,fk_country) values('Santa Rita de Caldas (MG)',1);
insert into city(name,fk_country) values('Santa Rita de Cássia (BA)',1);
insert into city(name,fk_country) values('Santa Rita de Jacutinga (MG)',1);
insert into city(name,fk_country) values('Santa Rita de Minas (MG)',1);
insert into city(name,fk_country) values('Santa Rita do Araguaia (GO)',1);
insert into city(name,fk_country) values('Santa Rita d''Oeste (SP)',1);
insert into city(name,fk_country) values('Santa Rita de Ibitipoca (MG)',1);
insert into city(name,fk_country) values('Santa Rita do Itueto (MG)',1);
insert into city(name,fk_country) values('Santa Rita do Novo Destino (GO)',1);
insert into city(name,fk_country) values('Santa Rita do Pardo (MS)',1);
insert into city(name,fk_country) values('Santa Rita do Passa Quatro (SP)',1);
insert into city(name,fk_country) values('Santa Rita do Sapucaí (MG)',1);
insert into city(name,fk_country) values('Santa Rita do Tocantins (TO)',1);
insert into city(name,fk_country) values('Santa Rita do Trivelato (MT)',1);
insert into city(name,fk_country) values('Santa Rosa (RS)',1);
insert into city(name,fk_country) values('Santa Rosa da Serra (MG)',1);
insert into city(name,fk_country) values('Santa Rosa de Goiás (GO)',1);
insert into city(name,fk_country) values('Santa Rosa de Lima (SC)',1);
insert into city(name,fk_country) values('Santa Rosa de Lima (SE)',1);
insert into city(name,fk_country) values('Santa Rosa de Viterbo (SP)',1);
insert into city(name,fk_country) values('Santa Rosa do Piauí (PI)',1);
insert into city(name,fk_country) values('Santa Rosa do Purus (AC)',1);
insert into city(name,fk_country) values('Santa Rosa do Sul (SC)',1);
insert into city(name,fk_country) values('Santa Rosa do Tocantins (TO)',1);
insert into city(name,fk_country) values('Santa Salete (SP)',1);
insert into city(name,fk_country) values('Santa Teresa (ES)',1);
insert into city(name,fk_country) values('Santa Teresinha (BA)',1);
insert into city(name,fk_country) values('Santa Teresinha (PB)',1);
insert into city(name,fk_country) values('Santa Tereza (RS)',1);
insert into city(name,fk_country) values('Santa Tereza de Goiás (GO)',1);
insert into city(name,fk_country) values('Santa Tereza do Oeste (PR)',1);
insert into city(name,fk_country) values('Santa Tereza do Tocantins (TO)',1);
insert into city(name,fk_country) values('Santa Terezinha (MT)',1);
insert into city(name,fk_country) values('Santa Terezinha (PE)',1);
insert into city(name,fk_country) values('Santa Terezinha (SC)',1);
insert into city(name,fk_country) values('Santa Terezinha de Goiás (GO)',1);
insert into city(name,fk_country) values('Santa Terezinha de Itaipu (PR)',1);
insert into city(name,fk_country) values('Santa Terezinha do Progresso (SC)',1);
insert into city(name,fk_country) values('Santa Terezinha do Tocantins (TO)',1);
insert into city(name,fk_country) values('Santa Vitória (MG)',1);
insert into city(name,fk_country) values('Santa Vitória do Palmar (RS)',1);
insert into city(name,fk_country) values('Santiago (RS)',1);
insert into city(name,fk_country) values('Santiago do Sul (SC)',1);
insert into city(name,fk_country) values('Santo Afonso (MT)',1);
insert into city(name,fk_country) values('Santo Amaro (BA)',1);
insert into city(name,fk_country) values('Santo Amaro da Imperatriz (SC)',1);
insert into city(name,fk_country) values('Santo Amaro das Brotas (SE)',1);
insert into city(name,fk_country) values('Santo Amaro do Maranhão (MA)',1);
insert into city(name,fk_country) values('Santo Anastácio (SP)',1);
insert into city(name,fk_country) values('Santo André (PB)',1);
insert into city(name,fk_country) values('Santo André (SP)',1);
insert into city(name,fk_country) values('Santo Ângelo (RS)',1);
insert into city(name,fk_country) values('Santo Antônio (RN)',1);
insert into city(name,fk_country) values('Santo Antônio da Alegria (SP)',1);
insert into city(name,fk_country) values('Santo Antônio da Barra (GO)',1);
insert into city(name,fk_country) values('Santo Antônio da Patrulha (RS)',1);
insert into city(name,fk_country) values('Santo Antônio da Platina (PR)',1);
insert into city(name,fk_country) values('Santo Antônio das Missões (RS)',1);
insert into city(name,fk_country) values('Santo Antônio de Goiás (GO)',1);
insert into city(name,fk_country) values('Santo Antônio de Jesus (BA)',1);
insert into city(name,fk_country) values('Santo Antônio de Lisboa (PI)',1);
insert into city(name,fk_country) values('Santo Antônio de Pádua (RJ)',1);
insert into city(name,fk_country) values('Santo Antônio de Posse (SP)',1);
insert into city(name,fk_country) values('Santo Antônio do Amparo (MG)',1);
insert into city(name,fk_country) values('Santo Antônio do Aracanguá (SP)',1);
insert into city(name,fk_country) values('Santo Antônio do Aventureiro (MG)',1);
insert into city(name,fk_country) values('Santo Antônio do Caiuá (PR)',1);
insert into city(name,fk_country) values('Santo Antônio do Descoberto (GO)',1);
insert into city(name,fk_country) values('Santo Antônio do Grama (MG)',1);
insert into city(name,fk_country) values('Santo Antônio do Içá (AM)',1);
insert into city(name,fk_country) values('Santo Antônio do Itambé (MG)',1);
insert into city(name,fk_country) values('Santo Antônio do Jacinto (MG)',1);
insert into city(name,fk_country) values('Santo Antônio do Jardim (SP)',1);
insert into city(name,fk_country) values('Santo Antônio do Leste (MT)',1);
insert into city(name,fk_country) values('Santo Antônio do Leverger (MT)',1);
insert into city(name,fk_country) values('Santo Antônio do Monte (MG)',1);
insert into city(name,fk_country) values('Santo Antônio do Palma (RS)',1);
insert into city(name,fk_country) values('Santo Antônio do Paraíso (PR)',1);
insert into city(name,fk_country) values('Santo Antônio do Pinhal (SP)',1);
insert into city(name,fk_country) values('Santo Antônio do Planalto (RS)',1);
insert into city(name,fk_country) values('Santo Antônio do Retiro (MG)',1);
insert into city(name,fk_country) values('Tabaí (RS)',1);
insert into city(name,fk_country) values('Tabaporã (MT)',1);
insert into city(name,fk_country) values('Tabapuã (SP)',1);
insert into city(name,fk_country) values('Tabatinga (AM)',1);
insert into city(name,fk_country) values('Tabatinga (SP)',1);
insert into city(name,fk_country) values('Tabira (PE)',1);
insert into city(name,fk_country) values('Taboão da Serra (SP)',1);
insert into city(name,fk_country) values('Tabocas do Brejo Velho (BA)',1);
insert into city(name,fk_country) values('Taboleiro Grande (RN)',1);
insert into city(name,fk_country) values('Tabuleiro do Norte (CE)',1);
insert into city(name,fk_country) values('Tabuleiro (MG)',1);
insert into city(name,fk_country) values('Tacaimbó (PE)',1);
insert into city(name,fk_country) values('Tacaratu (PE)',1);
insert into city(name,fk_country) values('Taciba (SP)',1);
insert into city(name,fk_country) values('Tacima (PB)',1);
insert into city(name,fk_country) values('Tacuru (MS)',1);
insert into city(name,fk_country) values('Taguaí (SP)',1);
insert into city(name,fk_country) values('Taguatinga (TO)',1);
insert into city(name,fk_country) values('Taiaçu (SP)',1);
insert into city(name,fk_country) values('Tailândia (PA)',1);
insert into city(name,fk_country) values('Taiobeiras (MG)',1);
insert into city(name,fk_country) values('Taió (SC)',1);
insert into city(name,fk_country) values('Taipas do Tocantins (TO)',1);
insert into city(name,fk_country) values('Taipu (RN)',1);
insert into city(name,fk_country) values('Taiuva (SP)',1);
insert into city(name,fk_country) values('Talismã (TO)',1);
insert into city(name,fk_country) values('Tamandaré (PE)',1);
insert into city(name,fk_country) values('Tamarana (PR)',1);
insert into city(name,fk_country) values('Tambaú (SP)',1);
insert into city(name,fk_country) values('Tamboara (PR)',1);
insert into city(name,fk_country) values('Tamboril (CE)',1);
insert into city(name,fk_country) values('Tamboril do Piauí (PI)',1);
insert into city(name,fk_country) values('Tanabi (SP)',1);
insert into city(name,fk_country) values('Tangará (RN)',1);
insert into city(name,fk_country) values('Tangará (SC)',1);
insert into city(name,fk_country) values('Tangará da Serra (MT)',1);
insert into city(name,fk_country) values('Tanguá (RJ)',1);
insert into city(name,fk_country) values('Tanhaçu (BA)',1);
insert into city(name,fk_country) values('Tanque d''Arca (AL)',1);
insert into city(name,fk_country) values('Tanque do Piauí (PI)',1);
insert into city(name,fk_country) values('Tanque Novo (BA)',1);
insert into city(name,fk_country) values('Tanquinho (BA)',1);
insert into city(name,fk_country) values('Taparuba (MG)',1);
insert into city(name,fk_country) values('Tapauá (AM)',1);
insert into city(name,fk_country) values('Tapejara (PR)',1);
insert into city(name,fk_country) values('Tapejara (RS)',1);
insert into city(name,fk_country) values('Tapera (RS)',1);
insert into city(name,fk_country) values('Taperoá (BA)',1);
insert into city(name,fk_country) values('Taperoá (PB)',1);
insert into city(name,fk_country) values('Tapes (RS)',1);
insert into city(name,fk_country) values('Tapira (MG)',1);
insert into city(name,fk_country) values('Tapira (PR)',1);
insert into city(name,fk_country) values('Tapiraí (MG)',1);
insert into city(name,fk_country) values('Tapiraí (SP)',1);
insert into city(name,fk_country) values('Tapiramutá (BA)',1);
insert into city(name,fk_country) values('Tapiratiba (SP)',1);
insert into city(name,fk_country) values('Tapurah (MT)',1);
insert into city(name,fk_country) values('Taquara (RS)',1);
insert into city(name,fk_country) values('Taquaraçu de Minas (MG)',1);
insert into city(name,fk_country) values('Taquaral (SP)',1);
insert into city(name,fk_country) values('Taquaral de Goiás (GO)',1);
insert into city(name,fk_country) values('Taquarana (AL)',1);
insert into city(name,fk_country) values('Taquari (RS)',1);
insert into city(name,fk_country) values('Taquaritinga (SP)',1);
insert into city(name,fk_country) values('Taquaritinga do Norte (PE)',1);
insert into city(name,fk_country) values('Taquarituba (SP)',1);
insert into city(name,fk_country) values('Taquarivaí (SP)',1);
insert into city(name,fk_country) values('Taquaruçu do Sul (RS)',1);
insert into city(name,fk_country) values('Taquarussu (MS)',1);
insert into city(name,fk_country) values('Tarabai (SP)',1);
insert into city(name,fk_country) values('Tarauacá (AC)',1);
insert into city(name,fk_country) values('Tarrafas (CE)',1);
insert into city(name,fk_country) values('Tartarugalzinho (AP)',1);
insert into city(name,fk_country) values('Tarumã (SP)',1);
insert into city(name,fk_country) values('Tarumirim (MG)',1);
insert into city(name,fk_country) values('Tasso Fragoso (MA)',1);
insert into city(name,fk_country) values('Tatuí (SP)',1);
insert into city(name,fk_country) values('Tauá (CE)',1);
insert into city(name,fk_country) values('Taubaté (SP)',1);
insert into city(name,fk_country) values('Tavares (PB)',1);
insert into city(name,fk_country) values('Uarini (AM)',1);
insert into city(name,fk_country) values('Uauá (BA)',1);
insert into city(name,fk_country) values('Ubá (MG)',1);
insert into city(name,fk_country) values('Ubaí (MG)',1);
insert into city(name,fk_country) values('Ubaíra (BA)',1);
insert into city(name,fk_country) values('Ubaitaba (BA)',1);
insert into city(name,fk_country) values('Ubajara (CE)',1);
insert into city(name,fk_country) values('Ubaporanga (MG)',1);
insert into city(name,fk_country) values('Ubarana (SP)',1);
insert into city(name,fk_country) values('Ubatã (BA)',1);
insert into city(name,fk_country) values('Ubatuba (SP)',1);
insert into city(name,fk_country) values('Uberaba (MG)',1);
insert into city(name,fk_country) values('Uberlândia (MG)',1);
insert into city(name,fk_country) values('Ubirajara (SP)',1);
insert into city(name,fk_country) values('Ubiratã (PR)',1);
insert into city(name,fk_country) values('Ubiretama (RS)',1);
insert into city(name,fk_country) values('Uchoa (SP)',1);
insert into city(name,fk_country) values('Uibaí (BA)',1);
insert into city(name,fk_country) values('Uiramutã (RR)',1);
insert into city(name,fk_country) values('Uirapuru (GO)',1);
insert into city(name,fk_country) values('Uiraúna (PB)',1);
insert into city(name,fk_country) values('Ulianópolis (PA)',1);
insert into city(name,fk_country) values('Umari (CE)',1);
insert into city(name,fk_country) values('Vacaria (RS)',1);
insert into city(name,fk_country) values('Vale de São Domingos (MT)',1);
insert into city(name,fk_country) values('Vale do Anari (RO)',1);
insert into city(name,fk_country) values('Vale do Paraíso (RO)',1);
insert into city(name,fk_country) values('Vale do Sol (RS)',1);
insert into city(name,fk_country) values('Valença (BA)',1);
insert into city(name,fk_country) values('Valença (RJ)',1);
insert into city(name,fk_country) values('Valença do Piauí (PI)',1);
insert into city(name,fk_country) values('Valente (BA)',1);
insert into city(name,fk_country) values('Valentim Gentil (SP)',1);
insert into city(name,fk_country) values('Vale Real (RS)',1);
insert into city(name,fk_country) values('Vale Verde (RS)',1);
insert into city(name,fk_country) values('Valinhos (SP)',1);
insert into city(name,fk_country) values('Valparaíso (SP)',1);
insert into city(name,fk_country) values('Valparaíso de Goiás (GO)',1);
insert into city(name,fk_country) values('Vanini (RS)',1);
insert into city(name,fk_country) values('Vargeão (SC)',1);
insert into city(name,fk_country) values('Vargem (SC)',1);
insert into city(name,fk_country) values('Vargem (SP)',1);
insert into city(name,fk_country) values('Vargem Alegre (MG)',1);
insert into city(name,fk_country) values('Vargem Alta (ES)',1);
insert into city(name,fk_country) values('Vargem Bonita (MG)',1);
insert into city(name,fk_country) values('Vargem Bonita (SC)',1);
insert into city(name,fk_country) values('Vargem Grande (MA)',1);
insert into city(name,fk_country) values('Vargem Grande do Rio Pardo (MG)',1);
insert into city(name,fk_country) values('Vargem Grande do Sul (SP)',1);
insert into city(name,fk_country) values('Vargem Grande Paulista (SP)',1);
insert into city(name,fk_country) values('Varginha (MG)',1);
insert into city(name,fk_country) values('Varjão (GO)',1);
insert into city(name,fk_country) values('Varjão de Minas (MG)',1);
insert into city(name,fk_country) values('Varjota (CE)',1);
insert into city(name,fk_country) values('Varre-Sai (RJ)',1);
insert into city(name,fk_country) values('Várzea (PB)',1);
insert into city(name,fk_country) values('Várzea (RN)',1);
insert into city(name,fk_country) values('Várzea Alegre (CE)',1);
insert into city(name,fk_country) values('Várzea Branca (PI)',1);
insert into city(name,fk_country) values('Várzea da Palma (MG)',1);
insert into city(name,fk_country) values('Várzea da Roça (BA)',1);
insert into city(name,fk_country) values('Várzea do Poço (BA)',1);
insert into city(name,fk_country) values('Várzea Grande (MT)',1);
insert into city(name,fk_country) values('Várzea Grande (PI)',1);
insert into city(name,fk_country) values('Várzea Nova (BA)',1);
insert into city(name,fk_country) values('Várzea Paulista (SP)',1);
insert into city(name,fk_country) values('Varzedo (BA)',1);
insert into city(name,fk_country) values('Varzelândia (MG)',1);
insert into city(name,fk_country) values('Wagner (BA)',1);
insert into city(name,fk_country) values('Wall Ferraz (PI)',1);
insert into city(name,fk_country) values('Wanderlândia (TO)',1);
insert into city(name,fk_country) values('Xambioá (TO)',1);
insert into city(name,fk_country) values('Xambrê (PR)',1);
insert into city(name,fk_country) values('Xangri-lá (RS)',1);
insert into city(name,fk_country) values('Xanxerê (SC)',1);
insert into city(name,fk_country) values('Zabelê (PB)',1);
insert into city(name,fk_country) values('Zacarias (SP)',1);
insert into city(name,fk_country) values('Alto Caparaó (MG)',1);
insert into city(name,fk_country) values('Alto da Boa Vista (MT)',1);
insert into city(name,fk_country) values('Alto do Rodrigues (RN)',1);
insert into city(name,fk_country) values('Alto Feliz (RS)',1);
insert into city(name,fk_country) values('Alto Garças (MT)',1);
insert into city(name,fk_country) values('Alto Horizonte (GO)',1);
insert into city(name,fk_country) values('Alto Jequitibá (MG)',1);
insert into city(name,fk_country) values('Alto Longá (PI)',1);
insert into city(name,fk_country) values('Altônia (PR)',1);
insert into city(name,fk_country) values('Alto Paraguai (MT)',1);
insert into city(name,fk_country) values('Alto Paraíso (PR)',1);
insert into city(name,fk_country) values('Alto Paraíso (RO)',1);
insert into city(name,fk_country) values('Alto Paraíso de Goiás (GO)',1);
insert into city(name,fk_country) values('Alto Paraná (PR)',1);
insert into city(name,fk_country) values('Alto Parnaíba (MA)',1);
insert into city(name,fk_country) values('Alto Piquiri (PR)',1);
insert into city(name,fk_country) values('Alto Rio Doce (MG)',1);
insert into city(name,fk_country) values('Alto Rio Novo (ES)',1);
insert into city(name,fk_country) values('Altos (PI)',1);
insert into city(name,fk_country) values('Alto Santo (CE)',1);
insert into city(name,fk_country) values('Alto Taquari (MT)',1);
insert into city(name,fk_country) values('Alumínio (SP)',1);
insert into city(name,fk_country) values('Alvarães (AM)',1);
insert into city(name,fk_country) values('Alvarenga (MG)',1);
insert into city(name,fk_country) values('Álvares Florence (SP)',1);
insert into city(name,fk_country) values('Álvares Machado (SP)',1);
insert into city(name,fk_country) values('Álvaro de Carvalho (SP)',1);
insert into city(name,fk_country) values('Alvinlândia (SP)',1);
insert into city(name,fk_country) values('Alvinópolis (MG)',1);
insert into city(name,fk_country) values('Alvorada (RS)',1);
insert into city(name,fk_country) values('Alvorada (TO)',1);
insert into city(name,fk_country) values('Alvorada de Minas (MG)',1);
insert into city(name,fk_country) values('Alvorada d''Oeste (RO)',1);
insert into city(name,fk_country) values('Alvorada do Gurgueia (PI)',1);
insert into city(name,fk_country) values('Alvorada do Norte (GO)',1);
insert into city(name,fk_country) values('Alvorada do Sul (PR)',1);
insert into city(name,fk_country) values('Amajari (RR)',1);
insert into city(name,fk_country) values('Amambai (MS)',1);
insert into city(name,fk_country) values('Amapá (AP)',1);
insert into city(name,fk_country) values('Amapá do Maranhão (MA)',1);
insert into city(name,fk_country) values('Amaporã (PR)',1);
insert into city(name,fk_country) values('Amaraji (PE)',1);
insert into city(name,fk_country) values('Amaral Ferrador (RS)',1);
insert into city(name,fk_country) values('Amaralina (GO)',1);
insert into city(name,fk_country) values('Amarante (PI)',1);
insert into city(name,fk_country) values('Amarante do Maranhão (MA)',1);
insert into city(name,fk_country) values('Amargosa (BA)',1);
insert into city(name,fk_country) values('Amaturá (AM)',1);
insert into city(name,fk_country) values('Amélia Rodrigues (BA)',1);
insert into city(name,fk_country) values('América Dourada (BA)',1);
insert into city(name,fk_country) values('Americana (SP)',1);
insert into city(name,fk_country) values('Americano do Brasil (GO)',1);
insert into city(name,fk_country) values('Américo Brasiliense (SP)',1);
insert into city(name,fk_country) values('Américo de Campos (SP)',1);
insert into city(name,fk_country) values('Ametista do Sul (RS)',1);
insert into city(name,fk_country) values('Amontada (CE)',1);
insert into city(name,fk_country) values('Amorinópolis (GO)',1);
insert into city(name,fk_country) values('Amparo (PB)',1);
insert into city(name,fk_country) values('Amparo (SP)',1);
insert into city(name,fk_country) values('Amparo da Serra (MG)',1);
insert into city(name,fk_country) values('Amparo de São Francisco (SE)',1);
insert into city(name,fk_country) values('Ampére (PR)',1);
insert into city(name,fk_country) values('Anadia (AL)',1);
insert into city(name,fk_country) values('Anagé (BA)',1);
insert into city(name,fk_country) values('Anahy (PR)',1);
insert into city(name,fk_country) values('Anajás (PA)',1);
insert into city(name,fk_country) values('Anajatuba (MA)',1);
insert into city(name,fk_country) values('Analândia (SP)',1);
insert into city(name,fk_country) values('Anamã (AM)',1);
insert into city(name,fk_country) values('Ananás (TO)',1);
insert into city(name,fk_country) values('Ananindeua (PA)',1);
insert into city(name,fk_country) values('Anápolis (GO)',1);
insert into city(name,fk_country) values('Anapu (PA)',1);
insert into city(name,fk_country) values('Anapurus (MA)',1);
insert into city(name,fk_country) values('Anastácio (MS)',1);
insert into city(name,fk_country) values('Anaurilândia (MS)',1);
insert into city(name,fk_country) values('Anchieta (ES)',1);
insert into city(name,fk_country) values('Anchieta (SC)',1);
insert into city(name,fk_country) values('Andaraí (BA)',1);
insert into city(name,fk_country) values('Andirá (PR)',1);
insert into city(name,fk_country) values('Andorinha (BA)',1);
insert into city(name,fk_country) values('Andradas (MG)',1);
insert into city(name,fk_country) values('Andradina (SP)',1);
insert into city(name,fk_country) values('André da Rocha (RS)',1);
insert into city(name,fk_country) values('Andrelândia (MG)',1);
insert into city(name,fk_country) values('Angatuba (SP)',1);
insert into city(name,fk_country) values('Angelândia (MG)',1);
insert into city(name,fk_country) values('Angélica (MS)',1);
insert into city(name,fk_country) values('Angelim (PE)',1);
insert into city(name,fk_country) values('Angelina (SC)',1);
insert into city(name,fk_country) values('Angical (BA)',1);
insert into city(name,fk_country) values('Angical do Piauí (PI)',1);
insert into city(name,fk_country) values('Angico (TO)',1);
insert into city(name,fk_country) values('Angicos (RN)',1);
insert into city(name,fk_country) values('Angra dos Reis (RJ)',1);
insert into city(name,fk_country) values('Anguera (BA)',1);
insert into city(name,fk_country) values('Ângulo (PR)',1);
insert into city(name,fk_country) values('Anhanguera (GO)',1);
insert into city(name,fk_country) values('Anhembi (SP)',1);
insert into city(name,fk_country) values('Anhumas (SP)',1);
insert into city(name,fk_country) values('Anicuns (GO)',1);
insert into city(name,fk_country) values('Anísio de Abreu (PI)',1);
insert into city(name,fk_country) values('Anita Garibaldi (SC)',1);
insert into city(name,fk_country) values('Anitápolis (SC)',1);
insert into city(name,fk_country) values('Anori (AM)',1);
insert into city(name,fk_country) values('Anta Gorda (RS)',1);
insert into city(name,fk_country) values('Antas (BA)',1);
insert into city(name,fk_country) values('Antonina (PR)',1);
insert into city(name,fk_country) values('Antonina do Norte (CE)',1);
insert into city(name,fk_country) values('Antônio Almeida (PI)',1);
insert into city(name,fk_country) values('Antônio Cardoso (BA)',1);
insert into city(name,fk_country) values('Antônio Carlos (MG)',1);
insert into city(name,fk_country) values('Antônio Carlos (SC)',1);
insert into city(name,fk_country) values('Antônio Dias (MG)',1);
insert into city(name,fk_country) values('Antônio Gonçalves (BA)',1);
insert into city(name,fk_country) values('Antônio João (MS)',1);
insert into city(name,fk_country) values('Antônio Martins (RN)',1);
insert into city(name,fk_country) values('Antônio Olinto (PR)',1);
insert into city(name,fk_country) values('Antônio Prado (RS)',1);
insert into city(name,fk_country) values('Antônio Prado de Minas (MG)',1);
insert into city(name,fk_country) values('Aparecida (PB)',1);
insert into city(name,fk_country) values('Aparecida (SP)',1);
insert into city(name,fk_country) values('Aparecida de Goiânia (GO)',1);
insert into city(name,fk_country) values('Aparecida d''Oeste (SP)',1);