insert into city(name,fk_country) values('Aparecida do Rio Doce (GO)',1);
insert into city(name,fk_country) values('Aparecida do Rio Negro (TO)',1);
insert into city(name,fk_country) values('Aparecida do Taboado (MS)',1);
insert into city(name,fk_country) values('Aperibé (RJ)',1);
insert into city(name,fk_country) values('Apiacá (ES)',1);
insert into city(name,fk_country) values('Apiacás (MT)',1);
insert into city(name,fk_country) values('Apiaí (SP)',1);
insert into city(name,fk_country) values('Apicum-Açu (MA)',1);
insert into city(name,fk_country) values('Apiúna (SC)',1);
insert into city(name,fk_country) values('Apodi (RN)',1);
insert into city(name,fk_country) values('Aporá (BA)',1);
insert into city(name,fk_country) values('Aporé (GO)',1);
insert into city(name,fk_country) values('Apuarema (BA)',1);
insert into city(name,fk_country) values('Apucarana (PR)',1);
insert into city(name,fk_country) values('Apuí (AM)',1);
insert into city(name,fk_country) values('Apuiarés (CE)',1);
insert into city(name,fk_country) values('Aquidabã (SE)',1);
insert into city(name,fk_country) values('Aquidauana (MS)',1);
insert into city(name,fk_country) values('Aquiraz (CE)',1);
insert into city(name,fk_country) values('Arabutã (SC)',1);
insert into city(name,fk_country) values('Araçagi (PB)',1);
insert into city(name,fk_country) values('Araçaí (MG)',1);
insert into city(name,fk_country) values('Aracaju (SE)',1);
insert into city(name,fk_country) values('Beberibe (CE)',1);
insert into city(name,fk_country) values('Bela Cruz (CE)',1);
insert into city(name,fk_country) values('Belágua (MA)',1);
insert into city(name,fk_country) values('Bela Vista (MS)',1);
insert into city(name,fk_country) values('Bela Vista da Caroba (PR)',1);
insert into city(name,fk_country) values('Bela Vista de Goiás (GO)',1);
insert into city(name,fk_country) values('Bela Vista de Minas (MG)',1);
insert into city(name,fk_country) values('Bela Vista do Maranhão (MA)',1);
insert into city(name,fk_country) values('Bela Vista do Paraíso (PR)',1);
insert into city(name,fk_country) values('Bela Vista do Piauí (PI)',1);
insert into city(name,fk_country) values('Bela Vista do Toldo (SC)',1);
insert into city(name,fk_country) values('Belém (AL)',1);
insert into city(name,fk_country) values('Belém (PA)',1);
insert into city(name,fk_country) values('Belém (PB)',1);
insert into city(name,fk_country) values('Belém de Maria (PE)',1);
insert into city(name,fk_country) values('Belém do Brejo do Cruz (PB)',1);
insert into city(name,fk_country) values('Belém do Piauí (PI)',1);
insert into city(name,fk_country) values('Belém do São Francisco (PE)',1);
insert into city(name,fk_country) values('Belford Roxo (RJ)',1);
insert into city(name,fk_country) values('Belmiro Braga (MG)',1);
insert into city(name,fk_country) values('Belmonte (BA)',1);
insert into city(name,fk_country) values('Belmonte (SC)',1);
insert into city(name,fk_country) values('Belo Campo (BA)',1);
insert into city(name,fk_country) values('Belo Horizonte (MG)',1);
insert into city(name,fk_country) values('Belo Jardim (PE)',1);
insert into city(name,fk_country) values('Belo Monte (AL)',1);
insert into city(name,fk_country) values('Belo Oriente (MG)',1);
insert into city(name,fk_country) values('Belo Vale (MG)',1);
insert into city(name,fk_country) values('Belterra (PA)',1);
insert into city(name,fk_country) values('Beneditinos (PI)',1);
insert into city(name,fk_country) values('Benedito Leite (MA)',1);
insert into city(name,fk_country) values('Benedito Novo (SC)',1);
insert into city(name,fk_country) values('Benevides (PA)',1);
insert into city(name,fk_country) values('Benjamin Constant (AM)',1);
insert into city(name,fk_country) values('Benjamin Constant do Sul (RS)',1);
insert into city(name,fk_country) values('Bento de Abreu (SP)',1);
insert into city(name,fk_country) values('Bento Fernandes (RN)',1);
insert into city(name,fk_country) values('Bento Gonçalves (RS)',1);
insert into city(name,fk_country) values('Bequimão (MA)',1);
insert into city(name,fk_country) values('Berilo (MG)',1);
insert into city(name,fk_country) values('Berizal (MG)',1);
insert into city(name,fk_country) values('Bernardino Batista (PB)',1);
insert into city(name,fk_country) values('Bernardino de Campos (SP)',1);
insert into city(name,fk_country) values('Bernardo do Mearim (MA)',1);
insert into city(name,fk_country) values('Bernardo Sayão (TO)',1);
insert into city(name,fk_country) values('Bertioga (SP)',1);
insert into city(name,fk_country) values('Bertolínia (PI)',1);
insert into city(name,fk_country) values('Bertópolis (MG)',1);
insert into city(name,fk_country) values('Beruri (AM)',1);
insert into city(name,fk_country) values('Betânia (PE)',1);
insert into city(name,fk_country) values('Betânia do Piauí (PI)',1);
insert into city(name,fk_country) values('Betim (MG)',1);
insert into city(name,fk_country) values('Bezerros (PE)',1);
insert into city(name,fk_country) values('Bias Fortes (MG)',1);
insert into city(name,fk_country) values('Bicas (MG)',1);
insert into city(name,fk_country) values('Biguaçu (SC)',1);
insert into city(name,fk_country) values('Bilac (SP)',1);
insert into city(name,fk_country) values('Biquinhas (MG)',1);
insert into city(name,fk_country) values('Birigui (SP)',1);
insert into city(name,fk_country) values('Biritiba Mirim (SP)',1);
insert into city(name,fk_country) values('Biritinga (BA)',1);
insert into city(name,fk_country) values('Bituruna (PR)',1);
insert into city(name,fk_country) values('Blumenau (SC)',1);
insert into city(name,fk_country) values('Boa Esperança (ES)',1);
insert into city(name,fk_country) values('Boa Esperança (MG)',1);
insert into city(name,fk_country) values('Boa Esperança (PR)',1);
insert into city(name,fk_country) values('Boa Esperança do Iguaçu (PR)',1);
insert into city(name,fk_country) values('Boa Esperança do Sul (SP)',1);
insert into city(name,fk_country) values('Boa Hora (PI)',1);
insert into city(name,fk_country) values('Boa Nova (BA)',1);
insert into city(name,fk_country) values('Boa Saúde (RN)',1);
insert into city(name,fk_country) values('Boa Ventura (PB)',1);
insert into city(name,fk_country) values('Boa Ventura de São Roque (PR)',1);
insert into city(name,fk_country) values('Boa Viagem (CE)',1);
insert into city(name,fk_country) values('Boa Vista (PB)',1);
insert into city(name,fk_country) values('Boa Vista (RR)',1);
insert into city(name,fk_country) values('Boa Vista da Aparecida (PR)',1);
insert into city(name,fk_country) values('Boa Vista das Missões (RS)',1);
insert into city(name,fk_country) values('Boa Vista do Buricá (RS)',1);
insert into city(name,fk_country) values('Boa Vista do Cadeado (RS)',1);
insert into city(name,fk_country) values('Boa Vista do Gurupi (MA)',1);
insert into city(name,fk_country) values('Boa Vista do Incra (RS)',1);
insert into city(name,fk_country) values('Boa Vista do Ramos (AM)',1);
insert into city(name,fk_country) values('Boa Vista do Sul (RS)',1);
insert into city(name,fk_country) values('Boa Vista do Tupim (BA)',1);
insert into city(name,fk_country) values('Boca da Mata (AL)',1);
insert into city(name,fk_country) values('Boca do Acre (AM)',1);
insert into city(name,fk_country) values('Bocaina (PI)',1);
insert into city(name,fk_country) values('Bocaina (SP)',1);
insert into city(name,fk_country) values('Bocaina de Minas (MG)',1);
insert into city(name,fk_country) values('Bocaina do Sul (SC)',1);
insert into city(name,fk_country) values('Bocaiuva (MG)',1);
insert into city(name,fk_country) values('Bocaiuva do Sul (PR)',1);
insert into city(name,fk_country) values('Bodó (RN)',1);
insert into city(name,fk_country) values('Bodocó (PE)',1);
insert into city(name,fk_country) values('Bodoquena (MS)',1);
insert into city(name,fk_country) values('Bofete (SP)',1);
insert into city(name,fk_country) values('Boituva (SP)',1);
insert into city(name,fk_country) values('Bombinhas (SC)',1);
insert into city(name,fk_country) values('Bom Conselho (PE)',1);
insert into city(name,fk_country) values('Bom Despacho (MG)',1);
insert into city(name,fk_country) values('Bom Jardim (MA)',1);
insert into city(name,fk_country) values('Bom Jardim (PE)',1);
insert into city(name,fk_country) values('Bom Jardim (RJ)',1);
insert into city(name,fk_country) values('Bom Jardim da Serra (SC)',1);
insert into city(name,fk_country) values('Bom Jardim de Goiás (GO)',1);
insert into city(name,fk_country) values('Bom Jardim de Minas (MG)',1);
insert into city(name,fk_country) values('Bom Jesus (PB)',1);
insert into city(name,fk_country) values('Bom Jesus (PI)',1);
insert into city(name,fk_country) values('Bom Jesus (RN)',1);
insert into city(name,fk_country) values('Bom Jesus (RS)',1);
insert into city(name,fk_country) values('Bom Jesus (SC)',1);
insert into city(name,fk_country) values('Bom Jesus da Lapa (BA)',1);
insert into city(name,fk_country) values('Bom Jesus da Penha (MG)',1);
insert into city(name,fk_country) values('Bom Jesus da Serra (BA)',1);
insert into city(name,fk_country) values('Bom Jesus das Selvas (MA)',1);
insert into city(name,fk_country) values('Bom Jesus de Goiás (GO)',1);
insert into city(name,fk_country) values('Bom Jesus do Amparo (MG)',1);
insert into city(name,fk_country) values('Bom Jesus do Araguaia (MT)',1);
insert into city(name,fk_country) values('Bom Jesus do Galho (MG)',1);
insert into city(name,fk_country) values('Bom Jesus do Itabapoana (RJ)',1);
insert into city(name,fk_country) values('Bom Jesus do Norte (ES)',1);
insert into city(name,fk_country) values('Bom Jesus do Oeste (SC)',1);
insert into city(name,fk_country) values('Bom Jesus dos Perdões (SP)',1);
insert into city(name,fk_country) values('Capão da Canoa (RS)',1);
insert into city(name,fk_country) values('Capão do Cipó (RS)',1);
insert into city(name,fk_country) values('Capão do Leão (RS)',1);
insert into city(name,fk_country) values('Caparaó (MG)',1);
insert into city(name,fk_country) values('Capela (AL)',1);
insert into city(name,fk_country) values('Capela (SE)',1);
insert into city(name,fk_country) values('Capela de Santana (RS)',1);
insert into city(name,fk_country) values('Capela do Alto (SP)',1);
insert into city(name,fk_country) values('Capela do Alto Alegre (BA)',1);
insert into city(name,fk_country) values('Capela Nova (MG)',1);
insert into city(name,fk_country) values('Capelinha (MG)',1);
insert into city(name,fk_country) values('Capetinga (MG)',1);
insert into city(name,fk_country) values('Capim (PB)',1);
insert into city(name,fk_country) values('Capim Branco (MG)',1);
insert into city(name,fk_country) values('Capim Grosso (BA)',1);
insert into city(name,fk_country) values('Capinópolis (MG)',1);
insert into city(name,fk_country) values('Capinzal (SC)',1);
insert into city(name,fk_country) values('Capinzal do Norte (MA)',1);
insert into city(name,fk_country) values('Capistrano (CE)',1);
insert into city(name,fk_country) values('Capitão (RS)',1);
insert into city(name,fk_country) values('Capitão Andrade (MG)',1);
insert into city(name,fk_country) values('Capitão de Campos (PI)',1);
insert into city(name,fk_country) values('Capitão Enéas (MG)',1);
insert into city(name,fk_country) values('Capitão Gervásio Oliveira (PI)',1);
insert into city(name,fk_country) values('Capitão Leônidas Marques (PR)',1);
insert into city(name,fk_country) values('Capitão Poço (PA)',1);
insert into city(name,fk_country) values('Capitólio (MG)',1);
insert into city(name,fk_country) values('Capivari (SP)',1);
insert into city(name,fk_country) values('Capivari de Baixo (SC)',1);
insert into city(name,fk_country) values('Capivari do Sul (RS)',1);
insert into city(name,fk_country) values('Capixaba (AC)',1);
insert into city(name,fk_country) values('Capoeiras (PE)',1);
insert into city(name,fk_country) values('Caputira (MG)',1);
insert into city(name,fk_country) values('Caraá (RS)',1);
insert into city(name,fk_country) values('Caracaraí (RR)',1);
insert into city(name,fk_country) values('Caracol (MS)',1);
insert into city(name,fk_country) values('Caracol (PI)',1);
insert into city(name,fk_country) values('Caraguatatuba (SP)',1);
insert into city(name,fk_country) values('Caraí (MG)',1);
insert into city(name,fk_country) values('Caraíbas (BA)',1);
insert into city(name,fk_country) values('Carambeí (PR)',1);
insert into city(name,fk_country) values('Caranaíba (MG)',1);
insert into city(name,fk_country) values('Carandaí (MG)',1);
insert into city(name,fk_country) values('Carangola (MG)',1);
insert into city(name,fk_country) values('Carapebus (RJ)',1);
insert into city(name,fk_country) values('Carapicuíba (SP)',1);
insert into city(name,fk_country) values('Caratinga (MG)',1);
insert into city(name,fk_country) values('Carauari (AM)',1);
insert into city(name,fk_country) values('Caraúbas (PB)',1);
insert into city(name,fk_country) values('Caraúbas (RN)',1);
insert into city(name,fk_country) values('Caraúbas do Piauí (PI)',1);
insert into city(name,fk_country) values('Caravelas (BA)',1);
insert into city(name,fk_country) values('Carazinho (RS)',1);
insert into city(name,fk_country) values('Carbonita (MG)',1);
insert into city(name,fk_country) values('Cardeal da Silva (BA)',1);
insert into city(name,fk_country) values('Cardoso (SP)',1);
insert into city(name,fk_country) values('Cardoso Moreira (RJ)',1);
insert into city(name,fk_country) values('Careaçu (MG)',1);
insert into city(name,fk_country) values('Careiro (AM)',1);
insert into city(name,fk_country) values('Careiro da Várzea (AM)',1);
insert into city(name,fk_country) values('Cariacica (ES)',1);
insert into city(name,fk_country) values('Caridade (CE)',1);
insert into city(name,fk_country) values('Caridade do Piauí (PI)',1);
insert into city(name,fk_country) values('Carinhanha (BA)',1);
insert into city(name,fk_country) values('Carira (SE)',1);
insert into city(name,fk_country) values('Cariré (CE)',1);
insert into city(name,fk_country) values('Caririaçu (CE)',1);
insert into city(name,fk_country) values('Cariri do Tocantins (TO)',1);
insert into city(name,fk_country) values('Cariús (CE)',1);
insert into city(name,fk_country) values('Carlinda (MT)',1);
insert into city(name,fk_country) values('Carlópolis (PR)',1);
insert into city(name,fk_country) values('Carlos Barbosa (RS)',1);
insert into city(name,fk_country) values('Carlos Chagas (MG)',1);
insert into city(name,fk_country) values('Carlos Gomes (RS)',1);
insert into city(name,fk_country) values('Carmésia (MG)',1);
insert into city(name,fk_country) values('Carmo (RJ)',1);
insert into city(name,fk_country) values('Carmo da Cachoeira (MG)',1);
insert into city(name,fk_country) values('Carmo da Mata (MG)',1);
insert into city(name,fk_country) values('Carmo de Minas (MG)',1);
insert into city(name,fk_country) values('Carmo do Cajuru (MG)',1);
insert into city(name,fk_country) values('Carmo do Paranaíba (MG)',1);
insert into city(name,fk_country) values('Carmo do Rio Claro (MG)',1);
insert into city(name,fk_country) values('Carmo do Rio Verde (GO)',1);
insert into city(name,fk_country) values('Carmolândia (TO)',1);
insert into city(name,fk_country) values('Carmópolis (SE)',1);
insert into city(name,fk_country) values('Carmópolis de Minas (MG)',1);
insert into city(name,fk_country) values('Carnaíba (PE)',1);
insert into city(name,fk_country) values('Carnaúba dos Dantas (RN)',1);
insert into city(name,fk_country) values('Carnaubais (RN)',1);
insert into city(name,fk_country) values('Carnaubal (CE)',1);
insert into city(name,fk_country) values('Carnaubeira da Penha (PE)',1);
insert into city(name,fk_country) values('Carneirinho (MG)',1);
insert into city(name,fk_country) values('Carneiros (AL)',1);
insert into city(name,fk_country) values('Caroebe (RR)',1);
insert into city(name,fk_country) values('Carolina (MA)',1);
insert into city(name,fk_country) values('Carpina (PE)',1);
insert into city(name,fk_country) values('Carrancas (MG)',1);
insert into city(name,fk_country) values('Carrapateira (PB)',1);
insert into city(name,fk_country) values('Carrasco Bonito (TO)',1);
insert into city(name,fk_country) values('Caruaru (PE)',1);
insert into city(name,fk_country) values('Carutapera (MA)',1);
insert into city(name,fk_country) values('Carvalhópolis (MG)',1);
insert into city(name,fk_country) values('Carvalhos (MG)',1);
insert into city(name,fk_country) values('Casa Branca (SP)',1);
insert into city(name,fk_country) values('Casa Grande (MG)',1);
insert into city(name,fk_country) values('Casa Nova (BA)',1);
insert into city(name,fk_country) values('Casca (RS)',1);
insert into city(name,fk_country) values('Cascalho Rico (MG)',1);
insert into city(name,fk_country) values('Cascavel (CE)',1);
insert into city(name,fk_country) values('Cascavel (PR)',1);
insert into city(name,fk_country) values('Caseara (TO)',1);
insert into city(name,fk_country) values('Caseiros (RS)',1);
insert into city(name,fk_country) values('Casimiro de Abreu (RJ)',1);
insert into city(name,fk_country) values('Casinhas (PE)',1);
insert into city(name,fk_country) values('Casserengue (PB)',1);
insert into city(name,fk_country) values('Cássia (MG)',1);
insert into city(name,fk_country) values('Cássia dos Coqueiros (SP)',1);
insert into city(name,fk_country) values('Cassilândia (MS)',1);
insert into city(name,fk_country) values('Castanhal (PA)',1);
insert into city(name,fk_country) values('Castanheira (MT)',1);
insert into city(name,fk_country) values('Castanheiras (RO)',1);
insert into city(name,fk_country) values('Castelândia (GO)',1);
insert into city(name,fk_country) values('Castelo (ES)',1);
insert into city(name,fk_country) values('Castelo do Piauí (PI)',1);
insert into city(name,fk_country) values('Castilho (SP)',1);
insert into city(name,fk_country) values('Castro (PR)',1);
insert into city(name,fk_country) values('Castro Alves (BA)',1);
insert into city(name,fk_country) values('Cataguases (MG)',1);
insert into city(name,fk_country) values('Catalão (GO)',1);
insert into city(name,fk_country) values('Catanduva (SP)',1);
insert into city(name,fk_country) values('Catanduvas (PR)',1);
insert into city(name,fk_country) values('Catanduvas (SC)',1);
insert into city(name,fk_country) values('Catarina (CE)',1);
insert into city(name,fk_country) values('Catas Altas (MG)',1);
insert into city(name,fk_country) values('Catas Altas da Noruega (MG)',1);
insert into city(name,fk_country) values('Catende (PE)',1);
insert into city(name,fk_country) values('Catiguá (SP)',1);
insert into city(name,fk_country) values('Catingueira (PB)',1);
insert into city(name,fk_country) values('Catolândia (BA)',1);
insert into city(name,fk_country) values('Catolé do Rocha (PB)',1);
insert into city(name,fk_country) values('Catu (BA)',1);
insert into city(name,fk_country) values('Catuípe (RS)',1);
insert into city(name,fk_country) values('Catuji (MG)',1);
insert into city(name,fk_country) values('Catunda (CE)',1);
insert into city(name,fk_country) values('Caturaí (GO)',1);
insert into city(name,fk_country) values('Caturama (BA)',1);
insert into city(name,fk_country) values('Caturité (PB)',1);
insert into city(name,fk_country) values('Catuti (MG)',1);
insert into city(name,fk_country) values('Caucaia (CE)',1);
insert into city(name,fk_country) values('Cavalcante (GO)',1);
insert into city(name,fk_country) values('Caxambu (MG)',1);
insert into city(name,fk_country) values('Caxambu do Sul (SC)',1);
insert into city(name,fk_country) values('Caxias (MA)',1);
insert into city(name,fk_country) values('Caxias do Sul (RS)',1);
insert into city(name,fk_country) values('Caxingó (PI)',1);
insert into city(name,fk_country) values('Ceará-Mirim (RN)',1);
insert into city(name,fk_country) values('Cedral (MA)',1);
insert into city(name,fk_country) values('Cedral (SP)',1);
insert into city(name,fk_country) values('Cedro (CE)',1);
insert into city(name,fk_country) values('Cedro (PE)',1);
insert into city(name,fk_country) values('Cedro de São João (SE)',1);
insert into city(name,fk_country) values('Cedro do Abaeté (MG)',1);
insert into city(name,fk_country) values('Celso Ramos (SC)',1);
insert into city(name,fk_country) values('Centenário (RS)',1);
insert into city(name,fk_country) values('Centenário (TO)',1);
insert into city(name,fk_country) values('Centenário do Sul (PR)',1);
insert into city(name,fk_country) values('Central (BA)',1);
insert into city(name,fk_country) values('Central de Minas (MG)',1);
insert into city(name,fk_country) values('Central do Maranhão (MA)',1);
insert into city(name,fk_country) values('Centralina (MG)',1);
insert into city(name,fk_country) values('Centro do Guilherme (MA)',1);
insert into city(name,fk_country) values('Centro Novo do Maranhão (MA)',1);
insert into city(name,fk_country) values('Cerejeiras (RO)',1);
insert into city(name,fk_country) values('Ceres (GO)',1);
insert into city(name,fk_country) values('Cerqueira César (SP)',1);
insert into city(name,fk_country) values('Cerquilho (SP)',1);
insert into city(name,fk_country) values('Cerrito (RS)',1);
insert into city(name,fk_country) values('Cerro Azul (PR)',1);
insert into city(name,fk_country) values('Cerro Branco (RS)',1);
insert into city(name,fk_country) values('Cerro Corá (RN)',1);
insert into city(name,fk_country) values('Cerro Grande (RS)',1);
insert into city(name,fk_country) values('Cerro Grande do Sul (RS)',1);
insert into city(name,fk_country) values('Cerro Largo (RS)',1);
insert into city(name,fk_country) values('Cerro Negro (SC)',1);
insert into city(name,fk_country) values('Cesário Lange (SP)',1);
insert into city(name,fk_country) values('Céu Azul (PR)',1);
insert into city(name,fk_country) values('Cezarina (GO)',1);
insert into city(name,fk_country) values('Chácara (MG)',1);
insert into city(name,fk_country) values('Chã de Alegria (PE)',1);
insert into city(name,fk_country) values('Chã Grande (PE)',1);
insert into city(name,fk_country) values('Chalé (MG)',1);
insert into city(name,fk_country) values('Chapada (RS)',1);
insert into city(name,fk_country) values('Chapada de Areia (TO)',1);
insert into city(name,fk_country) values('Chapada da Natividade (TO)',1);
insert into city(name,fk_country) values('Chapada do Norte (MG)',1);
insert into city(name,fk_country) values('Chapada dos Guimarães (MT)',1);
insert into city(name,fk_country) values('Chapada Gaúcha (MG)',1);
insert into city(name,fk_country) values('Chapadão do Céu (GO)',1);
insert into city(name,fk_country) values('Chapadão do Lageado (SC)',1);
insert into city(name,fk_country) values('Chapadão do Sul (MS)',1);
insert into city(name,fk_country) values('Chapadinha (MA)',1);
insert into city(name,fk_country) values('Chapecó (SC)',1);
insert into city(name,fk_country) values('Chã Preta (AL)',1);
insert into city(name,fk_country) values('Charqueada (SP)',1);
insert into city(name,fk_country) values('Charqueadas (RS)',1);
insert into city(name,fk_country) values('Charrua (RS)',1);
insert into city(name,fk_country) values('Chaval (CE)',1);
insert into city(name,fk_country) values('Chavantes (SP)',1);
insert into city(name,fk_country) values('Chaves (PA)',1);
insert into city(name,fk_country) values('Chiador (MG)',1);
insert into city(name,fk_country) values('Chiapetta (RS)',1);
insert into city(name,fk_country) values('Chopinzinho (PR)',1);
insert into city(name,fk_country) values('Choró (CE)',1);
insert into city(name,fk_country) values('Chorozinho (CE)',1);
insert into city(name,fk_country) values('Chorrochó (BA)',1);
insert into city(name,fk_country) values('Chuí (RS)',1);
insert into city(name,fk_country) values('Chupinguaia (RO)',1);
insert into city(name,fk_country) values('Chuvisca (RS)',1);
insert into city(name,fk_country) values('Cianorte (PR)',1);
insert into city(name,fk_country) values('Cícero Dantas (BA)',1);
insert into city(name,fk_country) values('Cidade Gaúcha (PR)',1);
insert into city(name,fk_country) values('Cidade Ocidental (GO)',1);
insert into city(name,fk_country) values('Cidelândia (MA)',1);
insert into city(name,fk_country) values('Cidreira (RS)',1);
insert into city(name,fk_country) values('Cipó (BA)',1);
insert into city(name,fk_country) values('Cipotânea (MG)',1);
insert into city(name,fk_country) values('Ciríaco (RS)',1);
insert into city(name,fk_country) values('Claraval (MG)',1);
insert into city(name,fk_country) values('Claro dos Poções (MG)',1);
insert into city(name,fk_country) values('Cláudia (MT)',1);
insert into city(name,fk_country) values('Cláudio (MG)',1);
insert into city(name,fk_country) values('Clementina (SP)',1);
insert into city(name,fk_country) values('Clevelândia (PR)',1);
insert into city(name,fk_country) values('Coaraci (BA)',1);
insert into city(name,fk_country) values('Coari (AM)',1);
insert into city(name,fk_country) values('Cocal (PI)',1);
insert into city(name,fk_country) values('Cocal de Telha (PI)',1);
insert into city(name,fk_country) values('Diorama (GO)',1);
insert into city(name,fk_country) values('Dirce Reis (SP)',1);
insert into city(name,fk_country) values('Dirceu Arcoverde (PI)',1);
insert into city(name,fk_country) values('Divina Pastora (SE)',1);
insert into city(name,fk_country) values('Divinésia (MG)',1);
insert into city(name,fk_country) values('Divino (MG)',1);
insert into city(name,fk_country) values('Divino das Laranjeiras (MG)',1);
insert into city(name,fk_country) values('Divino de São Lourenço (ES)',1);
insert into city(name,fk_country) values('Divinolândia (SP)',1);
insert into city(name,fk_country) values('Divinolândia de Minas (MG)',1);
insert into city(name,fk_country) values('Divinópolis (MG)',1);
insert into city(name,fk_country) values('Divinópolis de Goiás (GO)',1);
insert into city(name,fk_country) values('Divinópolis do Tocantins (TO)',1);
insert into city(name,fk_country) values('Divisa Alegre (MG)',1);
insert into city(name,fk_country) values('Divisa Nova (MG)',1);
insert into city(name,fk_country) values('Divisópolis (MG)',1);
insert into city(name,fk_country) values('Dobrada (SP)',1);
insert into city(name,fk_country) values('Dois Córregos (SP)',1);
insert into city(name,fk_country) values('Dois Irmãos (RS)',1);
insert into city(name,fk_country) values('Dois Irmãos das Missões (RS)',1);
insert into city(name,fk_country) values('Dois Irmãos do Buriti (MS)',1);
insert into city(name,fk_country) values('Dois Irmãos do Tocantins (TO)',1);
insert into city(name,fk_country) values('Dois Lajeados (RS)',1);
insert into city(name,fk_country) values('Dois Riachos (AL)',1);
insert into city(name,fk_country) values('Dois Vizinhos (PR)',1);
insert into city(name,fk_country) values('Dolcinópolis (SP)',1);
insert into city(name,fk_country) values('Dom Aquino (MT)',1);
insert into city(name,fk_country) values('Dom Basílio (BA)',1);
insert into city(name,fk_country) values('Dom Bosco (MG)',1);
insert into city(name,fk_country) values('Dom Cavati (MG)',1);
insert into city(name,fk_country) values('Dom Eliseu (PA)',1);
insert into city(name,fk_country) values('Dom Expedito Lopes (PI)',1);
insert into city(name,fk_country) values('Dom Feliciano (RS)',1);
insert into city(name,fk_country) values('Domingos Martins (ES)',1);
insert into city(name,fk_country) values('Domingos Mourão (PI)',1);
insert into city(name,fk_country) values('Dom Inocêncio (PI)',1);
insert into city(name,fk_country) values('Dom Joaquim (MG)',1);
insert into city(name,fk_country) values('Dom Macedo Costa (BA)',1);
insert into city(name,fk_country) values('Entre Ijuís (RS)',1);
insert into city(name,fk_country) values('Entre Rios (BA)',1);
insert into city(name,fk_country) values('Entre Rios (SC)',1);
insert into city(name,fk_country) values('Entre Rios de Minas (MG)',1);
insert into city(name,fk_country) values('Entre Rios do Oeste (PR)',1);
insert into city(name,fk_country) values('Entre Rios do Sul (RS)',1);
insert into city(name,fk_country) values('Envira (AM)',1);
insert into city(name,fk_country) values('Epitaciolândia (AC)',1);
insert into city(name,fk_country) values('Equador (RN)',1);
insert into city(name,fk_country) values('Erebango (RS)',1);
insert into city(name,fk_country) values('Erechim (RS)',1);
insert into city(name,fk_country) values('Ererê (CE)',1);
insert into city(name,fk_country) values('Érico Cardoso (BA)',1);
insert into city(name,fk_country) values('Ermo (SC)',1);
insert into city(name,fk_country) values('Ernestina (RS)',1);
insert into city(name,fk_country) values('Erval Grande (RS)',1);
insert into city(name,fk_country) values('Ervália (MG)',1);
insert into city(name,fk_country) values('Erval Seco (RS)',1);
insert into city(name,fk_country) values('Erval Velho (SC)',1);
insert into city(name,fk_country) values('Escada (PE)',1);
insert into city(name,fk_country) values('Esmeralda (RS)',1);
insert into city(name,fk_country) values('Esmeraldas (MG)',1);
insert into city(name,fk_country) values('Espera Feliz (MG)',1);
insert into city(name,fk_country) values('Esperança (PB)',1);
insert into city(name,fk_country) values('Esperança do Sul (RS)',1);
insert into city(name,fk_country) values('Esperança Nova (PR)',1);
insert into city(name,fk_country) values('Esperantina (PI)',1);
insert into city(name,fk_country) values('Esperantina (TO)',1);
insert into city(name,fk_country) values('Esperantinópolis (MA)',1);
insert into city(name,fk_country) values('Espigão Alto do Iguaçu (PR)',1);
insert into city(name,fk_country) values('Espigão d''Oeste (RO)',1);
insert into city(name,fk_country) values('Espinosa (MG)',1);
insert into city(name,fk_country) values('Ferreiros (PE)',1);
insert into city(name,fk_country) values('Ferros (MG)',1);
insert into city(name,fk_country) values('Fervedouro (MG)',1);
insert into city(name,fk_country) values('Figueira (PR)',1);
insert into city(name,fk_country) values('Figueirão (MS)',1);
insert into city(name,fk_country) values('Figueirópolis (TO)',1);
insert into city(name,fk_country) values('Figueirópolis d''Oeste (MT)',1);
insert into city(name,fk_country) values('Filadélfia (BA)',1);
insert into city(name,fk_country) values('Filadélfia (TO)',1);
insert into city(name,fk_country) values('Firmino Alves (BA)',1);
insert into city(name,fk_country) values('Firminópolis (GO)',1);
insert into city(name,fk_country) values('Flexeiras (AL)',1);
insert into city(name,fk_country) values('Floraí (PR)',1);
insert into city(name,fk_country) values('Florânia (RN)',1);
insert into city(name,fk_country) values('Flora Rica (SP)',1);
insert into city(name,fk_country) values('Flor da Serra do Sul (PR)',1);
insert into city(name,fk_country) values('Flor do Sertão (SC)',1);
insert into city(name,fk_country) values('Floreal (SP)',1);
insert into city(name,fk_country) values('Flores (PE)',1);
insert into city(name,fk_country) values('Flores da Cunha (RS)',1);
insert into city(name,fk_country) values('Flores de Goiás (GO)',1);
insert into city(name,fk_country) values('Flores do Piauí (PI)',1);
insert into city(name,fk_country) values('Floresta (PE)',1);
insert into city(name,fk_country) values('Floresta (PR)',1);
insert into city(name,fk_country) values('Floresta Azul (BA)',1);
insert into city(name,fk_country) values('Floresta do Araguaia (PA)',1);
insert into city(name,fk_country) values('Floresta do Piauí (PI)',1);
insert into city(name,fk_country) values('Florestal (MG)',1);
insert into city(name,fk_country) values('Florestópolis (PR)',1);
insert into city(name,fk_country) values('Floriano (PI)',1);
insert into city(name,fk_country) values('Floriano Peixoto (RS)',1);
insert into city(name,fk_country) values('Florianópolis (SC)',1);
insert into city(name,fk_country) values('Flórida (PR)',1);
insert into city(name,fk_country) values('Flórida Paulista (SP)',1);
insert into city(name,fk_country) values('Florínea (SP)',1);
insert into city(name,fk_country) values('Fonte Boa (AM)',1);
insert into city(name,fk_country) values('Fontoura Xavier (RS)',1);
insert into city(name,fk_country) values('Formiga (MG)',1);
insert into city(name,fk_country) values('Formigueiro (RS)',1);
insert into city(name,fk_country) values('Formosa (GO)',1);
insert into city(name,fk_country) values('Formosa da Serra Negra (MA)',1);
insert into city(name,fk_country) values('Formosa do Oeste (PR)',1);
insert into city(name,fk_country) values('Formosa do Rio Preto (BA)',1);
insert into city(name,fk_country) values('Formosa do Sul (SC)',1);
insert into city(name,fk_country) values('Formoso (GO)',1);
insert into city(name,fk_country) values('Formoso (MG)',1);
insert into city(name,fk_country) values('Goiatuba (GO)',1);
insert into city(name,fk_country) values('Goioerê (PR)',1);
insert into city(name,fk_country) values('Goioxim (PR)',1);
insert into city(name,fk_country) values('Gonçalves (MG)',1);
insert into city(name,fk_country) values('Gonçalves Dias (MA)',1);
insert into city(name,fk_country) values('Gongogi (BA)',1);
insert into city(name,fk_country) values('Gonzaga (MG)',1);
insert into city(name,fk_country) values('Gouvêia (MG)',1);
insert into city(name,fk_country) values('Gouvelândia (GO)',1);
insert into city(name,fk_country) values('Governador Archer (MA)',1);
insert into city(name,fk_country) values('Governador Celso Ramos (SC)',1);
insert into city(name,fk_country) values('Governador Dix-Sept Rosado (RN)',1);
insert into city(name,fk_country) values('Governador Edison Lobão (MA)',1);
insert into city(name,fk_country) values('Governador Eugênio Barros (MA)',1);
insert into city(name,fk_country) values('Governador Jorge Teixeira (RO)',1);
insert into city(name,fk_country) values('Governador Lindenberg (ES)',1);
insert into city(name,fk_country) values('Governador Luiz Rocha (MA)',1);
insert into city(name,fk_country) values('Governador Mangabeira (BA)',1);
insert into city(name,fk_country) values('Governador Newton Bello (MA)',1);
insert into city(name,fk_country) values('Governador Nunes Freire (MA)',1);
insert into city(name,fk_country) values('Governador Valadares (MG)',1);
insert into city(name,fk_country) values('Graça (CE)',1);
insert into city(name,fk_country) values('Graça Aranha (MA)',1);
insert into city(name,fk_country) values('Graccho Cardoso (SE)',1);
insert into city(name,fk_country) values('Grajaú (MA)',1);
insert into city(name,fk_country) values('Gramado (RS)',1);
insert into city(name,fk_country) values('Gramado dos Loureiros (RS)',1);
insert into city(name,fk_country) values('Gramado Xavier (RS)',1);
insert into city(name,fk_country) values('Grandes Rios (PR)',1);
insert into city(name,fk_country) values('Granito (PE)',1);
insert into city(name,fk_country) values('Granja (CE)',1);
insert into city(name,fk_country) values('Granjeiro (CE)',1);
insert into city(name,fk_country) values('Grão Mogol (MG)',1);
insert into city(name,fk_country) values('Grão-Pará (SC)',1);
insert into city(name,fk_country) values('Gravatá (PE)',1);
insert into city(name,fk_country) values('Gravataí (RS)',1);
insert into city(name,fk_country) values('Gravatal (SC)',1);
insert into city(name,fk_country) values('Groaíras (CE)',1);
insert into city(name,fk_country) values('Grossos (RN)',1);
insert into city(name,fk_country) values('Grupiara (MG)',1);
insert into city(name,fk_country) values('Guabiju (RS)',1);
insert into city(name,fk_country) values('Guabiruba (SC)',1);
insert into city(name,fk_country) values('Guaçuí (ES)',1);
insert into city(name,fk_country) values('Guadalupe (PI)',1);
insert into city(name,fk_country) values('Guaíba (RS)',1);
insert into city(name,fk_country) values('Guaiçara (SP)',1);
insert into city(name,fk_country) values('Guaimbê (SP)',1);
insert into city(name,fk_country) values('Guaíra (PR)',1);
insert into city(name,fk_country) values('Guaíra (SP)',1);
insert into city(name,fk_country) values('Guairaçá (PR)',1);
insert into city(name,fk_country) values('Guaiúba (CE)',1);
insert into city(name,fk_country) values('Guajará (AM)',1);
insert into city(name,fk_country) values('Guajará-Mirim (RO)',1);
insert into city(name,fk_country) values('Guajeru (BA)',1);
insert into city(name,fk_country) values('Guamaré (RN)',1);
insert into city(name,fk_country) values('Guamiranga (PR)',1);
insert into city(name,fk_country) values('Guanambi (BA)',1);
insert into city(name,fk_country) values('Guanhães (MG)',1);
insert into city(name,fk_country) values('Guapé (MG)',1);
insert into city(name,fk_country) values('Hidrolândia (CE)',1);
insert into city(name,fk_country) values('Hidrolândia (GO)',1);
insert into city(name,fk_country) values('Hidrolina (GO)',1);
insert into city(name,fk_country) values('Holambra (SP)',1);
insert into city(name,fk_country) values('Honório Serpa (PR)',1);
insert into city(name,fk_country) values('Horizonte (CE)',1);
insert into city(name,fk_country) values('Horizontina (RS)',1);
insert into city(name,fk_country) values('Ingaí (MG)',1);
insert into city(name,fk_country) values('Ingazeira (PE)',1);
insert into city(name,fk_country) values('Inhacorá (RS)',1);
insert into city(name,fk_country) values('Inhambupe (BA)',1);
insert into city(name,fk_country) values('Inhangapi (PA)',1);
insert into city(name,fk_country) values('Inhapi (AL)',1);
insert into city(name,fk_country) values('Inhapim (MG)',1);
insert into city(name,fk_country) values('Inhaúma (MG)',1);
insert into city(name,fk_country) values('Inhuma (PI)',1);
insert into city(name,fk_country) values('Inhumas (GO)',1);
insert into city(name,fk_country) values('Inimutaba (MG)',1);
insert into city(name,fk_country) values('Inocência (MS)',1);
insert into city(name,fk_country) values('Inúbia Paulista (SP)',1);
insert into city(name,fk_country) values('Iomerê (SC)',1);
insert into city(name,fk_country) values('Ipaba (MG)',1);
insert into city(name,fk_country) values('Ipameri (GO)',1);
insert into city(name,fk_country) values('Ipanema (MG)',1);
insert into city(name,fk_country) values('Ipanguaçu (RN)',1);
insert into city(name,fk_country) values('Ipaporanga (CE)',1);
insert into city(name,fk_country) values('Ipatinga (MG)',1);
insert into city(name,fk_country) values('Ipaussu (SP)',1);
insert into city(name,fk_country) values('Ipaumirim (CE)',1);
insert into city(name,fk_country) values('Ipê (RS)',1);
insert into city(name,fk_country) values('Ipecaetá (BA)',1);
insert into city(name,fk_country) values('Iperó (SP)',1);
insert into city(name,fk_country) values('Ipeúna (SP)',1);
insert into city(name,fk_country) values('Ipiaçu (MG)',1);
insert into city(name,fk_country) values('Ipiaú (BA)',1);
insert into city(name,fk_country) values('Ipiguá (SP)',1);
insert into city(name,fk_country) values('Ipirá (BA)',1);
insert into city(name,fk_country) values('Ipiranga (PR)',1);
insert into city(name,fk_country) values('Ipiranga de Goiás (GO)',1);
insert into city(name,fk_country) values('Ipiranga do Norte (MT)',1);
insert into city(name,fk_country) values('Ipiranga do Piauí (PI)',1);
insert into city(name,fk_country) values('Ipiranga do Sul (RS)',1);
insert into city(name,fk_country) values('Ipira (SC)',1);
insert into city(name,fk_country) values('Ipixuna (AM)',1);
insert into city(name,fk_country) values('Ipixuna do Pará (PA)',1);
insert into city(name,fk_country) values('Ipojuca (PE)',1);
insert into city(name,fk_country) values('Iporá (GO)',1);
insert into city(name,fk_country) values('Iporã (PR)',1);
insert into city(name,fk_country) values('Iporã do Oeste (SC)',1);
insert into city(name,fk_country) values('Iporanga (SP)',1);
insert into city(name,fk_country) values('Ipu (CE)',1);
insert into city(name,fk_country) values('Ipuã (SP)',1);
insert into city(name,fk_country) values('Ipuaçu (SC)',1);
insert into city(name,fk_country) values('Ipubi (PE)',1);
insert into city(name,fk_country) values('Ipueira (RN)',1);
insert into city(name,fk_country) values('Ipueiras (CE)',1);
insert into city(name,fk_country) values('Ipueiras (TO)',1);
insert into city(name,fk_country) values('Ipuiuna (MG)',1);
insert into city(name,fk_country) values('Ipumirim (SC)',1);
insert into city(name,fk_country) values('Ipupiara (BA)',1);
insert into city(name,fk_country) values('Iracema (CE)',1);
insert into city(name,fk_country) values('Iracema (RR)',1);
insert into city(name,fk_country) values('Iracema do Oeste (PR)',1);
insert into city(name,fk_country) values('Iracemápolis (SP)',1);
insert into city(name,fk_country) values('Iraceminha (SC)',1);
insert into city(name,fk_country) values('Iraí (RS)',1);
insert into city(name,fk_country) values('Iraí de Minas (MG)',1);
insert into city(name,fk_country) values('Irajuba (BA)',1);
insert into city(name,fk_country) values('Iramaia (BA)',1);
insert into city(name,fk_country) values('Iranduba (AM)',1);
insert into city(name,fk_country) values('Irani (SC)',1);
insert into city(name,fk_country) values('Irapuã (SP)',1);
insert into city(name,fk_country) values('Irapuru (SP)',1);
insert into city(name,fk_country) values('Iraquara (BA)',1);
insert into city(name,fk_country) values('Irará (BA)',1);
insert into city(name,fk_country) values('Irati (PR)',1);
insert into city(name,fk_country) values('Irati (SC)',1);
insert into city(name,fk_country) values('Irauçuba (CE)',1);
insert into city(name,fk_country) values('Irecê (BA)',1);
insert into city(name,fk_country) values('Iretama (PR)',1);
insert into city(name,fk_country) values('Irineópolis (SC)',1);
insert into city(name,fk_country) values('Irituia (PA)',1);
insert into city(name,fk_country) values('Irupi (ES)',1);
insert into city(name,fk_country) values('Isaías Coelho (PI)',1);
insert into city(name,fk_country) values('Israelândia (GO)',1);
insert into city(name,fk_country) values('Itá (SC)',1);
insert into city(name,fk_country) values('Itaara (RS)',1);
insert into city(name,fk_country) values('Itabaiana (PB)',1);
insert into city(name,fk_country) values('Itabaiana (SE)',1);
insert into city(name,fk_country) values('Itabaianinha (SE)',1);
insert into city(name,fk_country) values('Itabela (BA)',1);
insert into city(name,fk_country) values('Itaberaba (BA)',1);
insert into city(name,fk_country) values('Itaberá (SP)',1);
insert into city(name,fk_country) values('Itaberaí (GO)',1);
insert into city(name,fk_country) values('Itabi (SE)',1);
insert into city(name,fk_country) values('Itabira (MG)',1);
insert into city(name,fk_country) values('Itabirinha (MG)',1);
insert into city(name,fk_country) values('Itabirito (MG)',1);
insert into city(name,fk_country) values('Itaboraí (RJ)',1);
insert into city(name,fk_country) values('Itabuna (BA)',1);
insert into city(name,fk_country) values('Itacajá (TO)',1);
insert into city(name,fk_country) values('Itacambira (MG)',1);
insert into city(name,fk_country) values('Itacarambi (MG)',1);
insert into city(name,fk_country) values('Itacaré (BA)',1);
insert into city(name,fk_country) values('Itacoatiara (AM)',1);
insert into city(name,fk_country) values('Itacuruba (PE)',1);
insert into city(name,fk_country) values('Itacurubi (RS)',1);
insert into city(name,fk_country) values('Itaetê (BA)',1);
insert into city(name,fk_country) values('Itagi (BA)',1);
insert into city(name,fk_country) values('Itagibá (BA)',1);
insert into city(name,fk_country) values('Itagimirim (BA)',1);
insert into city(name,fk_country) values('Itaguaçu da Bahia (BA)',1);
insert into city(name,fk_country) values('Itaguaçu (ES)',1);
insert into city(name,fk_country) values('Itaguaí (RJ)',1);
insert into city(name,fk_country) values('Itaguajé (PR)',1);
insert into city(name,fk_country) values('Itaguara (MG)',1);
insert into city(name,fk_country) values('Itaguari (GO)',1);
insert into city(name,fk_country) values('Itaguaru (GO)',1);
insert into city(name,fk_country) values('Itaguatins (TO)',1);
insert into city(name,fk_country) values('Itaí (SP)',1);
insert into city(name,fk_country) values('Itaíba (PE)',1);
insert into city(name,fk_country) values('Itaiçaba (CE)',1);
insert into city(name,fk_country) values('Itainópolis (PI)',1);
insert into city(name,fk_country) values('Itaiópolis (SC)',1);
insert into city(name,fk_country) values('Itaipava do Grajaú (MA)',1);
insert into city(name,fk_country) values('Itaipé (MG)',1);
insert into city(name,fk_country) values('Itaipulândia (PR)',1);
insert into city(name,fk_country) values('Itaitinga (CE)',1);
insert into city(name,fk_country) values('Itaituba (PA)',1);
insert into city(name,fk_country) values('Itajá (GO)',1);
insert into city(name,fk_country) values('Itajá (RN)',1);
insert into city(name,fk_country) values('Itajaí (SC)',1);
insert into city(name,fk_country) values('Itajobi (SP)',1);
insert into city(name,fk_country) values('Itaju (SP)',1);
insert into city(name,fk_country) values('Itajubá (MG)',1);
insert into city(name,fk_country) values('Itaju do Colônia (BA)',1);
insert into city(name,fk_country) values('Jaqueira (PE)',1);
insert into city(name,fk_country) values('Jaquirana (RS)',1);
insert into city(name,fk_country) values('Jaraguá (GO)',1);
insert into city(name,fk_country) values('Jaraguá do Sul (SC)',1);
insert into city(name,fk_country) values('Jaraguari (MS)',1);
insert into city(name,fk_country) values('Jaramataia (AL)',1);
insert into city(name,fk_country) values('Jardim (CE)',1);
insert into city(name,fk_country) values('Jardim (MS)',1);
insert into city(name,fk_country) values('Jardim Alegre (PR)',1);
insert into city(name,fk_country) values('Jardim de Angicos (RN)',1);
insert into city(name,fk_country) values('Jardim de Piranhas (RN)',1);
insert into city(name,fk_country) values('Jardim do Mulato (PI)',1);
insert into city(name,fk_country) values('Jardim do Seridó (RN)',1);
insert into city(name,fk_country) values('Jardim Olinda (PR)',1);
insert into city(name,fk_country) values('Jardinópolis (SC)',1);
insert into city(name,fk_country) values('Jardinópolis (SP)',1);
insert into city(name,fk_country) values('Jari (RS)',1);
insert into city(name,fk_country) values('Jarinu (SP)',1);
insert into city(name,fk_country) values('Jaru (RO)',1);
insert into city(name,fk_country) values('Jataí (GO)',1);
insert into city(name,fk_country) values('Jataizinho (PR)',1);
insert into city(name,fk_country) values('Jataúba (PE)',1);
insert into city(name,fk_country) values('Jateí (MS)',1);
insert into city(name,fk_country) values('Jati (CE)',1);
insert into city(name,fk_country) values('Jatobá (MA)',1);
insert into city(name,fk_country) values('Jatobá (PE)',1);
insert into city(name,fk_country) values('Jatobá do Piauí (PI)',1);
insert into city(name,fk_country) values('Jaú (SP)',1);
insert into city(name,fk_country) values('Jaú do Tocantins (TO)',1);
insert into city(name,fk_country) values('Jaupaci (GO)',1);
insert into city(name,fk_country) values('Jauru (MT)',1);
insert into city(name,fk_country) values('Jeceaba (MG)',1);
insert into city(name,fk_country) values('Jenipapo de Minas (MG)',1);
insert into city(name,fk_country) values('Jenipapo dos Vieiras (MA)',1);
insert into city(name,fk_country) values('Jequeri (MG)',1);
insert into city(name,fk_country) values('Jequiá da Praia (AL)',1);
insert into city(name,fk_country) values('Jequié (BA)',1);
insert into city(name,fk_country) values('Jequitaí (MG)',1);
insert into city(name,fk_country) values('Jequitibá (MG)',1);
insert into city(name,fk_country) values('Jequitinhonha (MG)',1);
insert into city(name,fk_country) values('Jeremoabo (BA)',1);
insert into city(name,fk_country) values('Jericó (PB)',1);
insert into city(name,fk_country) values('Jeriquara (SP)',1);
insert into city(name,fk_country) values('Jerônimo Monteiro (ES)',1);
insert into city(name,fk_country) values('Jerumenha (PI)',1);
insert into city(name,fk_country) values('Jesuânia (MG)',1);
insert into city(name,fk_country) values('Jesuítas (PR)',1);
insert into city(name,fk_country) values('Jesúpolis (GO)',1);
insert into city(name,fk_country) values('Jijoca de Jericoacoara (CE)',1);
insert into city(name,fk_country) values('Ji-Paraná (RO)',1);
insert into city(name,fk_country) values('Jiquiriçá (BA)',1);
insert into city(name,fk_country) values('Jitaúna (BA)',1);
insert into city(name,fk_country) values('Joaçaba (SC)',1);
insert into city(name,fk_country) values('Joaíma (MG)',1);
insert into city(name,fk_country) values('Joanésia (MG)',1);
insert into city(name,fk_country) values('Joanópolis (SP)',1);
insert into city(name,fk_country) values('João Alfredo (PE)',1);
insert into city(name,fk_country) values('João Câmara (RN)',1);
insert into city(name,fk_country) values('João Costa (PI)',1);
insert into city(name,fk_country) values('João Dias (RN)',1);
insert into city(name,fk_country) values('João Dourado (BA)',1);
insert into city(name,fk_country) values('João Lisboa (MA)',1);
insert into city(name,fk_country) values('João Monlevade (MG)',1);
insert into city(name,fk_country) values('João Neiva (ES)',1);
insert into city(name,fk_country) values('João Pessoa (PB)',1);
insert into city(name,fk_country) values('João Pinheiro (MG)',1);
insert into city(name,fk_country) values('João Ramalho (SP)',1);
insert into city(name,fk_country) values('Joaquim Felício (MG)',1);
insert into city(name,fk_country) values('Joaquim Gomes (AL)',1);
insert into city(name,fk_country) values('Lajeado (TO)',1);
insert into city(name,fk_country) values('Lajeado do Bugre (RS)',1);
insert into city(name,fk_country) values('Lajeado Grande (SC)',1);
insert into city(name,fk_country) values('Lajeado Novo (MA)',1);
insert into city(name,fk_country) values('Lajedão (BA)',1);
insert into city(name,fk_country) values('Lajedinho (BA)',1);
insert into city(name,fk_country) values('Lajedo (PE)',1);
insert into city(name,fk_country) values('Lajedo do Tabocal (BA)',1);
insert into city(name,fk_country) values('Laje do Muriaé (RJ)',1);
insert into city(name,fk_country) values('Lajes (RN)',1);
insert into city(name,fk_country) values('Lajes Pintadas (RN)',1);
insert into city(name,fk_country) values('Lajinha (MG)',1);
insert into city(name,fk_country) values('Lamarão (BA)',1);
insert into city(name,fk_country) values('Lambari (MG)',1);
insert into city(name,fk_country) values('Lambari d''Oeste (MT)',1);
insert into city(name,fk_country) values('Lamim (MG)',1);
insert into city(name,fk_country) values('Landri Sales (PI)',1);
insert into city(name,fk_country) values('Lapa (PR)',1);
insert into city(name,fk_country) values('Lapão (BA)',1);
insert into city(name,fk_country) values('Laranja da Terra (ES)',1);
insert into city(name,fk_country) values('Laranjal (MG)',1);
insert into city(name,fk_country) values('Laranjal (PR)',1);
insert into city(name,fk_country) values('Laranjal do Jari (AP)',1);
insert into city(name,fk_country) values('Laranjal Paulista (SP)',1);
insert into city(name,fk_country) values('Laranjeiras (SE)',1);
insert into city(name,fk_country) values('Laranjeiras do Sul (PR)',1);
insert into city(name,fk_country) values('Lassance (MG)',1);
insert into city(name,fk_country) values('Lastro (PB)',1);
insert into city(name,fk_country) values('Laurentino (SC)',1);
insert into city(name,fk_country) values('Lauro de Freitas (BA)',1);
insert into city(name,fk_country) values('Lauro Müller (SC)',1);
insert into city(name,fk_country) values('Lavandeira (TO)',1);
insert into city(name,fk_country) values('Lavínia (SP)',1);
insert into city(name,fk_country) values('Lavras (MG)',1);
insert into city(name,fk_country) values('Lavras da Mangabeira (CE)',1);
insert into city(name,fk_country) values('Lavras do Sul (RS)',1);
insert into city(name,fk_country) values('Lavrinhas (SP)',1);
insert into city(name,fk_country) values('Leandro Ferreira (MG)',1);
insert into city(name,fk_country) values('Lebon Régis (SC)',1);
insert into city(name,fk_country) values('Leme (SP)',1);
insert into city(name,fk_country) values('Leme do Prado (MG)',1);
insert into city(name,fk_country) values('Lençóis (BA)',1);
insert into city(name,fk_country) values('Lençóis Paulista (SP)',1);
insert into city(name,fk_country) values('Leoberto Leal (SC)',1);
insert into city(name,fk_country) values('Leopoldina (MG)',1);
insert into city(name,fk_country) values('Leopoldo de Bulhões (GO)',1);
insert into city(name,fk_country) values('Leópolis (PR)',1);
insert into city(name,fk_country) values('Liberato Salzano (RS)',1);
insert into city(name,fk_country) values('Liberdade (MG)',1);
insert into city(name,fk_country) values('Licínio de Almeida (BA)',1);
insert into city(name,fk_country) values('Lidianópolis (PR)',1);
insert into city(name,fk_country) values('Lima Campos (MA)',1);
insert into city(name,fk_country) values('Lima Duarte (MG)',1);
insert into city(name,fk_country) values('Marília (SP)',1);
insert into city(name,fk_country) values('Mariluz (PR)',1);
insert into city(name,fk_country) values('Maringá (PR)',1);
insert into city(name,fk_country) values('Marinópolis (SP)',1);
insert into city(name,fk_country) values('Mário Campos (MG)',1);
insert into city(name,fk_country) values('Mariópolis (PR)',1);
insert into city(name,fk_country) values('Maripá (PR)',1);
insert into city(name,fk_country) values('Maripá de Minas (MG)',1);
insert into city(name,fk_country) values('Marituba (PA)',1);
insert into city(name,fk_country) values('Marizópolis (PB)',1);
insert into city(name,fk_country) values('Marliéria (MG)',1);
insert into city(name,fk_country) values('Marmeleiro (PR)',1);
insert into city(name,fk_country) values('Marmelópolis (MG)',1);
insert into city(name,fk_country) values('Marques de Souza (RS)',1);
insert into city(name,fk_country) values('Marquinho (PR)',1);
insert into city(name,fk_country) values('Martinho Campos (MG)',1);
insert into city(name,fk_country) values('Martinópole (CE)',1);
insert into city(name,fk_country) values('Martinópolis (SP)',1);
insert into city(name,fk_country) values('Martins (RN)',1);
insert into city(name,fk_country) values('Martins Soares (MG)',1);
insert into city(name,fk_country) values('Maruim (SE)',1);
insert into city(name,fk_country) values('Marumbi (PR)',1);
insert into city(name,fk_country) values('Mar Vermelho (AL)',1);
insert into city(name,fk_country) values('Marzagão (GO)',1);
insert into city(name,fk_country) values('Mascote (BA)',1);
insert into city(name,fk_country) values('Massapê (CE)',1);
insert into city(name,fk_country) values('Massapê do Piauí (PI)',1);
insert into city(name,fk_country) values('Massaranduba (PB)',1);
insert into city(name,fk_country) values('Massaranduba (SC)',1);
insert into city(name,fk_country) values('Mata (RS)',1);
insert into city(name,fk_country) values('Mata de São João (BA)',1);
insert into city(name,fk_country) values('Mata Grande (AL)',1);
insert into city(name,fk_country) values('Matão (SP)',1);
insert into city(name,fk_country) values('Mataraca (PB)',1);
insert into city(name,fk_country) values('Mata Roma (MA)',1);
insert into city(name,fk_country) values('Mata Verde (MG)',1);
insert into city(name,fk_country) values('Mateiros (TO)',1);
insert into city(name,fk_country) values('Matelândia (PR)',1);
insert into city(name,fk_country) values('Materlândia (MG)',1);
insert into city(name,fk_country) values('Mateus Leme (MG)',1);
insert into city(name,fk_country) values('Mathias Lobato (MG)',1);
insert into city(name,fk_country) values('Matias Barbosa (MG)',1);
insert into city(name,fk_country) values('Matias Cardoso (MG)',1);
insert into city(name,fk_country) values('Matias Olímpio (PI)',1);
insert into city(name,fk_country) values('Matina (BA)',1);
insert into city(name,fk_country) values('Matinha (MA)',1);
insert into city(name,fk_country) values('Matinhas (PB)',1);
insert into city(name,fk_country) values('Matinhos (PR)',1);
insert into city(name,fk_country) values('Matipó (MG)',1);
insert into city(name,fk_country) values('Mato Castelhano (RS)',1);
insert into city(name,fk_country) values('Matões (MA)',1);
insert into city(name,fk_country) values('Matões do Norte (MA)',1);
insert into city(name,fk_country) values('Mato Grosso (PB)',1);
insert into city(name,fk_country) values('Mato Leitão (RS)',1);
insert into city(name,fk_country) values('Mato Queimado (RS)',1);
insert into city(name,fk_country) values('Mato Rico (PR)',1);
insert into city(name,fk_country) values('Matos Costa (SC)',1);
insert into city(name,fk_country) values('Mato Verde (MG)',1);
insert into city(name,fk_country) values('Matozinhos (MG)',1);
insert into city(name,fk_country) values('Matrinchã (GO)',1);
insert into city(name,fk_country) values('Matriz de Camaragibe (AL)',1);
insert into city(name,fk_country) values('Matupá (MT)',1);
insert into city(name,fk_country) values('Matureia (PB)',1);
insert into city(name,fk_country) values('Matutina (MG)',1);
insert into city(name,fk_country) values('Mauá (SP)',1);
insert into city(name,fk_country) values('Mauá da Serra (PR)',1);
insert into city(name,fk_country) values('Maués (AM)',1);
insert into city(name,fk_country) values('Maurilândia (GO)',1);
insert into city(name,fk_country) values('Maurilândia do Tocantins (TO)',1);
insert into city(name,fk_country) values('Mauriti (CE)',1);
insert into city(name,fk_country) values('Maxaranguape (RN)',1);
insert into city(name,fk_country) values('Maximiliano de Almeida (RS)',1);
insert into city(name,fk_country) values('Mazagão (AP)',1);
insert into city(name,fk_country) values('Medeiros (MG)',1);
insert into city(name,fk_country) values('Medeiros Neto (BA)',1);
insert into city(name,fk_country) values('Medianeira (PR)',1);
insert into city(name,fk_country) values('Medicilândia (PA)',1);
insert into city(name,fk_country) values('Medina (MG)',1);
insert into city(name,fk_country) values('Meleiro (SC)',1);
insert into city(name,fk_country) values('Melgaço (PA)',1);
insert into city(name,fk_country) values('Mendes (RJ)',1);
insert into city(name,fk_country) values('Mendes Pimentel (MG)',1);
insert into city(name,fk_country) values('Mendonça (SP)',1);
insert into city(name,fk_country) values('Mercedes (PR)',1);
insert into city(name,fk_country) values('Mercês (MG)',1);
insert into city(name,fk_country) values('Meridiano (SP)',1);
insert into city(name,fk_country) values('Meruoca (CE)',1);
insert into city(name,fk_country) values('Mesópolis (SP)',1);
insert into city(name,fk_country) values('Mesquita (MG)',1);
insert into city(name,fk_country) values('Mesquita (RJ)',1);
insert into city(name,fk_country) values('Messias (AL)',1);
insert into city(name,fk_country) values('Messias Targino (RN)',1);
insert into city(name,fk_country) values('Miguel Alves (PI)',1);
insert into city(name,fk_country) values('Miguel Calmon (BA)',1);
insert into city(name,fk_country) values('Miguel Leão (PI)',1);
insert into city(name,fk_country) values('Miguelópolis (SP)',1);
insert into city(name,fk_country) values('Miguel Pereira (RJ)',1);
insert into city(name,fk_country) values('Milagres (BA)',1);
insert into city(name,fk_country) values('Milagres (CE)',1);
insert into city(name,fk_country) values('Milagres do Maranhão (MA)',1);
insert into city(name,fk_country) values('Milhã (CE)',1);
insert into city(name,fk_country) values('Milton Brandão (PI)',1);
insert into city(name,fk_country) values('Mimoso de Goiás (GO)',1);
insert into city(name,fk_country) values('Mimoso do Sul (ES)',1);
insert into city(name,fk_country) values('Minaçu (GO)',1);
insert into city(name,fk_country) values('Minador do Negrão (AL)',1);
insert into city(name,fk_country) values('Minas do Leão (RS)',1);
insert into city(name,fk_country) values('Minas Novas (MG)',1);
insert into city(name,fk_country) values('Minduri (MG)',1);
insert into city(name,fk_country) values('Mineiros (GO)',1);
insert into city(name,fk_country) values('Mineiros do Tietê (SP)',1);
insert into city(name,fk_country) values('Ministro Andreazza (RO)',1);
insert into city(name,fk_country) values('Mirabela (MG)',1);
insert into city(name,fk_country) values('Miracatu (SP)',1);
insert into city(name,fk_country) values('Miracema (RJ)',1);
insert into city(name,fk_country) values('Miracema do Tocantins (TO)',1);
insert into city(name,fk_country) values('Mirador (MA)',1);
insert into city(name,fk_country) values('Mirador (PR)',1);
insert into city(name,fk_country) values('Miradouro (MG)',1);
insert into city(name,fk_country) values('Mira Estrela (SP)',1);
insert into city(name,fk_country) values('Miraguaí (RS)',1);
insert into city(name,fk_country) values('Miraí (MG)',1);
insert into city(name,fk_country) values('Miraíma (CE)',1);
insert into city(name,fk_country) values('Miranda (MS)',1);
insert into city(name,fk_country) values('Miranda do Norte (MA)',1);
insert into city(name,fk_country) values('Mirandiba (PE)',1);
insert into city(name,fk_country) values('Mirandópolis (SP)',1);
insert into city(name,fk_country) values('Mirangaba (BA)',1);
insert into city(name,fk_country) values('Miranorte (TO)',1);
insert into city(name,fk_country) values('Mirante (BA)',1);
insert into city(name,fk_country) values('Mirante da Serra (RO)',1);
insert into city(name,fk_country) values('Mirante do Paranapanema (SP)',1);
insert into city(name,fk_country) values('Miraselva (PR)',1);
insert into city(name,fk_country) values('Mirassol (SP)',1);
insert into city(name,fk_country) values('Mirassolândia (SP)',1);
insert into city(name,fk_country) values('Mirassol d''Oeste (MT)',1);
insert into city(name,fk_country) values('Nova Belém (MG)',1);
insert into city(name,fk_country) values('Nova Boa Vista (RS)',1);
insert into city(name,fk_country) values('Nova Brasilândia (MT)',1);
insert into city(name,fk_country) values('Nova Brasilândia d''Oeste (RO)',1);
insert into city(name,fk_country) values('Nova Bréscia (RS)',1);
insert into city(name,fk_country) values('Nova Campina (SP)',1);
insert into city(name,fk_country) values('Nova Canaã (BA)',1);
insert into city(name,fk_country) values('Nova Canaã do Norte (MT)',1);
insert into city(name,fk_country) values('Nova Canaã Paulista (SP)',1);
insert into city(name,fk_country) values('Nova Candelária (RS)',1);
insert into city(name,fk_country) values('Nova Cantu (PR)',1);
insert into city(name,fk_country) values('Nova Castilho (SP)',1);
insert into city(name,fk_country) values('Nova Colinas (MA)',1);
insert into city(name,fk_country) values('Nova Crixás (GO)',1);
insert into city(name,fk_country) values('Nova Cruz (RN)',1);
insert into city(name,fk_country) values('Nova Era (MG)',1);
insert into city(name,fk_country) values('Nova Erechim (SC)',1);
insert into city(name,fk_country) values('Nova Esperança (PR)',1);
insert into city(name,fk_country) values('Nova Esperança do Piriá (PA)',1);
insert into city(name,fk_country) values('Nova Esperança do Sudoeste (PR)',1);
insert into city(name,fk_country) values('Nova Esperança do Sul (RS)',1);
insert into city(name,fk_country) values('Nova Europa (SP)',1);
insert into city(name,fk_country) values('Nova Fátima (BA)',1);
insert into city(name,fk_country) values('Nova Fátima (PR)',1);
insert into city(name,fk_country) values('Nova Floresta (PB)',1);
insert into city(name,fk_country) values('Nova Friburgo (RJ)',1);
insert into city(name,fk_country) values('Nova Glória (GO)',1);
insert into city(name,fk_country) values('Nova Granada (SP)',1);
insert into city(name,fk_country) values('Nova Guarita (MT)',1);
insert into city(name,fk_country) values('Nova Guataporanga (SP)',1);
insert into city(name,fk_country) values('Nova Hartz (RS)',1);
insert into city(name,fk_country) values('Nova Ibiá (BA)',1);
insert into city(name,fk_country) values('Nova Iguaçu (RJ)',1);
insert into city(name,fk_country) values('Nova Iguaçu de Goiás (GO)',1);
insert into city(name,fk_country) values('Nova Independência (SP)',1);
insert into city(name,fk_country) values('Nova Iorque (MA)',1);
insert into city(name,fk_country) values('Nova Ipixuna (PA)',1);
insert into city(name,fk_country) values('Novais (SP)',1);
insert into city(name,fk_country) values('Nova Itaberaba (SC)',1);
insert into city(name,fk_country) values('Nova Itarana (BA)',1);
insert into city(name,fk_country) values('Nova Lacerda (MT)',1);
insert into city(name,fk_country) values('Nova Laranjeiras (PR)',1);
insert into city(name,fk_country) values('Nova Lima (MG)',1);
insert into city(name,fk_country) values('Nova Londrina (PR)',1);
insert into city(name,fk_country) values('Nova Luzitânia (SP)',1);
insert into city(name,fk_country) values('Nova Mamoré (RO)',1);
insert into city(name,fk_country) values('Nova Marilândia (MT)',1);