insert into city(name,fk_country) values('Nova Maringá (MT)',1);
insert into city(name,fk_country) values('Nova Módica (MG)',1);
insert into city(name,fk_country) values('Nova Monte Verde (MT)',1);
insert into city(name,fk_country) values('Nova Mutum (MT)',1);
insert into city(name,fk_country) values('Nova Nazaré (MT)',1);
insert into city(name,fk_country) values('Nova Odessa (SP)',1);
insert into city(name,fk_country) values('Nova Olímpia (MT)',1);
insert into city(name,fk_country) values('Nova Olímpia (PR)',1);
insert into city(name,fk_country) values('Nova Olinda (CE)',1);
insert into city(name,fk_country) values('Nova Olinda (PB)',1);
insert into city(name,fk_country) values('Nova Olinda (TO)',1);
insert into city(name,fk_country) values('Nova Olinda do Maranhão (MA)',1);
insert into city(name,fk_country) values('Nova Olinda do Norte (AM)',1);
insert into city(name,fk_country) values('Nova Pádua (RS)',1);
insert into city(name,fk_country) values('Nova Palma (RS)',1);
insert into city(name,fk_country) values('Nova Palmeira (PB)',1);
insert into city(name,fk_country) values('Nova Petrópolis (RS)',1);
insert into city(name,fk_country) values('Oliveira de Fátima (TO)',1);
insert into city(name,fk_country) values('Oliveira dos Brejinhos (BA)',1);
insert into city(name,fk_country) values('Oliveira Fortes (MG)',1);
insert into city(name,fk_country) values('Olivença (AL)',1);
insert into city(name,fk_country) values('Onça de Pitangui (MG)',1);
insert into city(name,fk_country) values('Onda Verde (SP)',1);
insert into city(name,fk_country) values('Oratórios (MG)',1);
insert into city(name,fk_country) values('Oriente (SP)',1);
insert into city(name,fk_country) values('Orindiúva (SP)',1);
insert into city(name,fk_country) values('Oriximiná (PA)',1);
insert into city(name,fk_country) values('Orizânia (MG)',1);
insert into city(name,fk_country) values('Orizona (GO)',1);
insert into city(name,fk_country) values('Orlândia (SP)',1);
insert into city(name,fk_country) values('Orleans (SC)',1);
insert into city(name,fk_country) values('Orobó (PE)',1);
insert into city(name,fk_country) values('Orocó (PE)',1);
insert into city(name,fk_country) values('Orós (CE)',1);
insert into city(name,fk_country) values('Ortigueira (PR)',1);
insert into city(name,fk_country) values('Osasco (SP)',1);
insert into city(name,fk_country) values('Oscar Bressane (SP)',1);
insert into city(name,fk_country) values('Osório (RS)',1);
insert into city(name,fk_country) values('Osvaldo Cruz (SP)',1);
insert into city(name,fk_country) values('Otacílio Costa (SC)',1);
insert into city(name,fk_country) values('Peabiru (PR)',1);
insert into city(name,fk_country) values('Peçanha (MG)',1);
insert into city(name,fk_country) values('Pederneiras (SP)',1);
insert into city(name,fk_country) values('Pé de Serra (BA)',1);
insert into city(name,fk_country) values('Pedra (PE)',1);
insert into city(name,fk_country) values('Pedra Azul (MG)',1);
insert into city(name,fk_country) values('Pedra Bela (SP)',1);
insert into city(name,fk_country) values('Pedra Bonita (MG)',1);
insert into city(name,fk_country) values('Pedra Branca (CE)',1);
insert into city(name,fk_country) values('Pedra Branca (PB)',1);
insert into city(name,fk_country) values('Pedra Branca do Amapari (AP)',1);
insert into city(name,fk_country) values('Pedra do Anta (MG)',1);
insert into city(name,fk_country) values('Pedra do Indaiá (MG)',1);
insert into city(name,fk_country) values('Pedra Dourada (MG)',1);
insert into city(name,fk_country) values('Pedra Grande (RN)',1);
insert into city(name,fk_country) values('Pedra Lavrada (PB)',1);
insert into city(name,fk_country) values('Pedralva (MG)',1);
insert into city(name,fk_country) values('Pedra Mole (SE)',1);
insert into city(name,fk_country) values('Pedranópolis (SP)',1);
insert into city(name,fk_country) values('Pedrão (BA)',1);
insert into city(name,fk_country) values('Pedra Preta (MT)',1);
insert into city(name,fk_country) values('Pedra Preta (RN)',1);
insert into city(name,fk_country) values('Pedras Altas (RS)',1);
insert into city(name,fk_country) values('Pedras de Fogo (PB)',1);
insert into city(name,fk_country) values('Pedras de Maria da Cruz (MG)',1);
insert into city(name,fk_country) values('Pedras Grandes (SC)',1);
insert into city(name,fk_country) values('Pedregulho (SP)',1);
insert into city(name,fk_country) values('Pedreira (SP)',1);
insert into city(name,fk_country) values('Pedreiras (MA)',1);
insert into city(name,fk_country) values('Pedrinhas (SE)',1);
insert into city(name,fk_country) values('Pedrinhas Paulista (SP)',1);
insert into city(name,fk_country) values('Pedrinópolis (MG)',1);
insert into city(name,fk_country) values('Pedro Afonso (TO)',1);
insert into city(name,fk_country) values('Pedro Alexandre (BA)',1);
insert into city(name,fk_country) values('Pedro Avelino (RN)',1);
insert into city(name,fk_country) values('Pedro Canário (ES)',1);
insert into city(name,fk_country) values('Pedro de Toledo (SP)',1);
insert into city(name,fk_country) values('Pedro do Rosário (MA)',1);
insert into city(name,fk_country) values('Pedro Gomes (MS)',1);
insert into city(name,fk_country) values('Pedro II (PI)',1);
insert into city(name,fk_country) values('Pedro Laurentino (PI)',1);
insert into city(name,fk_country) values('Pedro Leopoldo (MG)',1);
insert into city(name,fk_country) values('Pedro Osório (RS)',1);
insert into city(name,fk_country) values('Pedro Régis (PB)',1);
insert into city(name,fk_country) values('Pedro Teixeira (MG)',1);
insert into city(name,fk_country) values('Pedro Velho (RN)',1);
insert into city(name,fk_country) values('Peixe (TO)',1);
insert into city(name,fk_country) values('Peixe-Boi (PA)',1);
insert into city(name,fk_country) values('Peixoto de Azevedo (MT)',1);
insert into city(name,fk_country) values('Pejuçara (RS)',1);
insert into city(name,fk_country) values('Pelotas (RS)',1);
insert into city(name,fk_country) values('Penaforte (CE)',1);
insert into city(name,fk_country) values('Penalva (MA)',1);
insert into city(name,fk_country) values('Penápolis (SP)',1);
insert into city(name,fk_country) values('Pendências (RN)',1);
insert into city(name,fk_country) values('Penedo (AL)',1);
insert into city(name,fk_country) values('Penha (SC)',1);
insert into city(name,fk_country) values('Pentecoste (CE)',1);
insert into city(name,fk_country) values('Pequeri (MG)',1);
insert into city(name,fk_country) values('Pequi (MG)',1);
insert into city(name,fk_country) values('Pequizeiro (TO)',1);
insert into city(name,fk_country) values('Perdigão (MG)',1);
insert into city(name,fk_country) values('Perdizes (MG)',1);
insert into city(name,fk_country) values('Perdões (MG)',1);
insert into city(name,fk_country) values('Pereira Barreto (SP)',1);
insert into city(name,fk_country) values('Pereiras (SP)',1);
insert into city(name,fk_country) values('Pereiro (CE)',1);
insert into city(name,fk_country) values('Peri Mirim (MA)',1);
insert into city(name,fk_country) values('Periquito (MG)',1);
insert into city(name,fk_country) values('Peritiba (SC)',1);
insert into city(name,fk_country) values('Peritoró (MA)',1);
insert into city(name,fk_country) values('Perobal (PR)',1);
insert into city(name,fk_country) values('Pérola (PR)',1);
insert into city(name,fk_country) values('Pérola d''Oeste (PR)',1);
insert into city(name,fk_country) values('Perolândia (GO)',1);
insert into city(name,fk_country) values('Peruíbe (SP)',1);
insert into city(name,fk_country) values('Pescador (MG)',1);
insert into city(name,fk_country) values('Pescaria Brava (SC)',1);
insert into city(name,fk_country) values('Pesqueira (PE)',1);
insert into city(name,fk_country) values('Petrolândia (PE)',1);
insert into city(name,fk_country) values('Petrolândia (SC)',1);
insert into city(name,fk_country) values('Petrolina (PE)',1);
insert into city(name,fk_country) values('Petrolina de Goiás (GO)',1);
insert into city(name,fk_country) values('Petrópolis (RJ)',1);
insert into city(name,fk_country) values('Piaçabuçu (AL)',1);
insert into city(name,fk_country) values('Piacatu (SP)',1);
insert into city(name,fk_country) values('Piancó (PB)',1);
insert into city(name,fk_country) values('Piatã (BA)',1);
insert into city(name,fk_country) values('Piau (MG)',1);
insert into city(name,fk_country) values('Picada Café (RS)',1);
insert into city(name,fk_country) values('Piçarra (PA)',1);
insert into city(name,fk_country) values('Picos (PI)',1);
insert into city(name,fk_country) values('Picuí (PB)',1);
insert into city(name,fk_country) values('Piedade (SP)',1);
insert into city(name,fk_country) values('Piedade de Caratinga (MG)',1);
insert into city(name,fk_country) values('Piedade de Ponte Nova (MG)',1);
insert into city(name,fk_country) values('Piedade do Rio Grande (MG)',1);
insert into city(name,fk_country) values('Piedade dos Gerais (MG)',1);
insert into city(name,fk_country) values('Piên (PR)',1);
insert into city(name,fk_country) values('Pilão Arcado (BA)',1);
insert into city(name,fk_country) values('Pilar (AL)',1);
insert into city(name,fk_country) values('Pilar (PB)',1);
insert into city(name,fk_country) values('Pilar de Goiás (GO)',1);
insert into city(name,fk_country) values('Pilar do Sul (SP)',1);
insert into city(name,fk_country) values('Pilões (PB)',1);
insert into city(name,fk_country) values('Pilões (RN)',1);
insert into city(name,fk_country) values('Pilõezinhos (PB)',1);
insert into city(name,fk_country) values('Pimenta (MG)',1);
insert into city(name,fk_country) values('Pimenta Bueno (RO)',1);
insert into city(name,fk_country) values('Pimenteiras (PI)',1);
insert into city(name,fk_country) values('Pimenteiras do Oeste (RO)',1);
insert into city(name,fk_country) values('Pindaí (BA)',1);
insert into city(name,fk_country) values('Pindamonhangaba (SP)',1);
insert into city(name,fk_country) values('Pindaré-Mirim (MA)',1);
insert into city(name,fk_country) values('Pindoba (AL)',1);
insert into city(name,fk_country) values('Pindobaçu (BA)',1);
insert into city(name,fk_country) values('Pindorama (SP)',1);
insert into city(name,fk_country) values('Pindorama do Tocantins (TO)',1);
insert into city(name,fk_country) values('Pindoretama (CE)',1);
insert into city(name,fk_country) values('Pingo d''Água (MG)',1);
insert into city(name,fk_country) values('Pinhais (PR)',1);
insert into city(name,fk_country) values('Pinhal (RS)',1);
insert into city(name,fk_country) values('Pinhalão (PR)',1);
insert into city(name,fk_country) values('Pinhal da Serra (RS)',1);
insert into city(name,fk_country) values('Pinhal de São Bento (PR)',1);
insert into city(name,fk_country) values('Pinhal Grande (RS)',1);
insert into city(name,fk_country) values('Pinhalzinho (SC)',1);
insert into city(name,fk_country) values('Pinhalzinho (SP)',1);
insert into city(name,fk_country) values('Pinhão (PR)',1);
insert into city(name,fk_country) values('Pinhão (SE)',1);
insert into city(name,fk_country) values('Pinheiral (RJ)',1);
insert into city(name,fk_country) values('Pinheirinho do Vale (RS)',1);
insert into city(name,fk_country) values('Pinheiro (MA)',1);
insert into city(name,fk_country) values('Pinheiro Machado (RS)',1);
insert into city(name,fk_country) values('Pinheiro Preto (SC)',1);
insert into city(name,fk_country) values('Pinheiros (ES)',1);
insert into city(name,fk_country) values('Pintadas (BA)',1);
insert into city(name,fk_country) values('Pinto Bandeira (RS)',1);
insert into city(name,fk_country) values('Pintópolis (MG)',1);
insert into city(name,fk_country) values('Pio IX (PI)',1);
insert into city(name,fk_country) values('Pio XII (MA)',1);
insert into city(name,fk_country) values('Piquerobi (SP)',1);
insert into city(name,fk_country) values('Piquet Carneiro (CE)',1);
insert into city(name,fk_country) values('Piquete (SP)',1);
insert into city(name,fk_country) values('Piracaia (SP)',1);
insert into city(name,fk_country) values('Piracanjuba (GO)',1);
insert into city(name,fk_country) values('Piracema (MG)',1);
insert into city(name,fk_country) values('Piracicaba (SP)',1);
insert into city(name,fk_country) values('Piracuruca (PI)',1);
insert into city(name,fk_country) values('Piraí (RJ)',1);
insert into city(name,fk_country) values('Piraí do Norte (BA)',1);
insert into city(name,fk_country) values('Piraí do Sul (PR)',1);
insert into city(name,fk_country) values('Piraju (SP)',1);
insert into city(name,fk_country) values('Pirajuba (MG)',1);
insert into city(name,fk_country) values('Pirajuí (SP)',1);
insert into city(name,fk_country) values('Pirambu (SE)',1);
insert into city(name,fk_country) values('Piranga (MG)',1);
insert into city(name,fk_country) values('Pirangi (SP)',1);
insert into city(name,fk_country) values('Piranguçu (MG)',1);
insert into city(name,fk_country) values('Piranguinho (MG)',1);
insert into city(name,fk_country) values('Piranhas (AL)',1);
insert into city(name,fk_country) values('Piranhas (GO)',1);
insert into city(name,fk_country) values('Pirapemas (MA)',1);
insert into city(name,fk_country) values('Pirapetinga (MG)',1);
insert into city(name,fk_country) values('Pirapó (RS)',1);
insert into city(name,fk_country) values('Pirapora (MG)',1);
insert into city(name,fk_country) values('Pirapora do Bom Jesus (SP)',1);
insert into city(name,fk_country) values('Pirapozinho (SP)',1);
insert into city(name,fk_country) values('Piraquara (PR)',1);
insert into city(name,fk_country) values('Piraquê (TO)',1);
insert into city(name,fk_country) values('Pirassununga (SP)',1);
insert into city(name,fk_country) values('Piratini (RS)',1);
insert into city(name,fk_country) values('Piratininga (SP)',1);
insert into city(name,fk_country) values('Piratuba (SC)',1);
insert into city(name,fk_country) values('Piraúba (MG)',1);
insert into city(name,fk_country) values('Pirenópolis (GO)',1);
insert into city(name,fk_country) values('Pires do Rio (GO)',1);
insert into city(name,fk_country) values('Pires Ferreira (CE)',1);
insert into city(name,fk_country) values('Piripá (BA)',1);
insert into city(name,fk_country) values('Piripiri (PI)',1);
insert into city(name,fk_country) values('Piritiba (BA)',1);
insert into city(name,fk_country) values('Pirpirituba (PB)',1);
insert into city(name,fk_country) values('Pitanga (PR)',1);
insert into city(name,fk_country) values('Pitangueiras (PR)',1);
insert into city(name,fk_country) values('Pitangueiras (SP)',1);
insert into city(name,fk_country) values('Pitangui (MG)',1);
insert into city(name,fk_country) values('Pitimbu (PB)',1);
insert into city(name,fk_country) values('Queimadas (BA)',1);
insert into city(name,fk_country) values('Queimadas (PB)',1);
insert into city(name,fk_country) values('Queimados (RJ)',1);
insert into city(name,fk_country) values('Queiroz (SP)',1);
insert into city(name,fk_country) values('Queluzito (MG)',1);
insert into city(name,fk_country) values('Queluz (SP)',1);
insert into city(name,fk_country) values('Querência do Norte (PR)',1);
insert into city(name,fk_country) values('Querência (MT)',1);
insert into city(name,fk_country) values('Quevedos (RS)',1);
insert into city(name,fk_country) values('Quijingue (BA)',1);
insert into city(name,fk_country) values('Quilombo (SC)',1);
insert into city(name,fk_country) values('Quinta do Sol (PR)',1);
insert into city(name,fk_country) values('Quintana (SP)',1);
insert into city(name,fk_country) values('Ribeira do Amparo (BA)',1);
insert into city(name,fk_country) values('Ribeira do Piauí (PI)',1);
insert into city(name,fk_country) values('Ribeira do Pombal (BA)',1);
insert into city(name,fk_country) values('Ribeirão (PE)',1);
insert into city(name,fk_country) values('Ribeirão Bonito (SP)',1);
insert into city(name,fk_country) values('Ribeirão Branco (SP)',1);
insert into city(name,fk_country) values('Ribeirão Cascalheira (MT)',1);
insert into city(name,fk_country) values('Ribeirão Claro (PR)',1);
insert into city(name,fk_country) values('Ribeirão Corrente (SP)',1);
insert into city(name,fk_country) values('Ribeirão das Neves (MG)',1);
insert into city(name,fk_country) values('Ribeirão do Largo (BA)',1);
insert into city(name,fk_country) values('Ribeirão do Pinhal (PR)',1);
insert into city(name,fk_country) values('Ribeirão dos Índios (SP)',1);
insert into city(name,fk_country) values('Ribeirão do Sul (SP)',1);
insert into city(name,fk_country) values('Ribeirão Grande (SP)',1);
insert into city(name,fk_country) values('Ribeirão Pires (SP)',1);
insert into city(name,fk_country) values('Ribeirão Preto (SP)',1);
insert into city(name,fk_country) values('Ribeirão Vermelho (MG)',1);
insert into city(name,fk_country) values('Ribeirãozinho (MT)',1);
insert into city(name,fk_country) values('Ribeiro Gonçalves (PI)',1);
insert into city(name,fk_country) values('Ribeirópolis (SE)',1);
insert into city(name,fk_country) values('Rifaina (SP)',1);
insert into city(name,fk_country) values('Rincão (SP)',1);
insert into city(name,fk_country) values('Rinópolis (SP)',1);
insert into city(name,fk_country) values('Rio Acima (MG)',1);
insert into city(name,fk_country) values('Rio Azul (PR)',1);
insert into city(name,fk_country) values('Rio Bananal (ES)',1);
insert into city(name,fk_country) values('Rio Bom (PR)',1);
insert into city(name,fk_country) values('Rio Bonito (RJ)',1);
insert into city(name,fk_country) values('Rio Bonito do Iguaçu (PR)',1);
insert into city(name,fk_country) values('Rio Branco (AC)',1);
insert into city(name,fk_country) values('Rio Branco (MT)',1);
insert into city(name,fk_country) values('Rio Branco do Ivaí (PR)',1);
insert into city(name,fk_country) values('Rio Branco do Sul (PR)',1);
insert into city(name,fk_country) values('Rio Brilhante (MS)',1);
insert into city(name,fk_country) values('Rio Casca (MG)',1);
insert into city(name,fk_country) values('Rio Claro (RJ)',1);
insert into city(name,fk_country) values('Rio Claro (SP)',1);
insert into city(name,fk_country) values('Rio Crespo (RO)',1);
insert into city(name,fk_country) values('Rio da Conceição (TO)',1);
insert into city(name,fk_country) values('Rio das Antas (SC)',1);
insert into city(name,fk_country) values('Rio das Flores (RJ)',1);
insert into city(name,fk_country) values('Rio das Ostras (RJ)',1);
insert into city(name,fk_country) values('Rio das Pedras (SP)',1);
insert into city(name,fk_country) values('Rio de Contas (BA)',1);
insert into city(name,fk_country) values('Rio de Janeiro (RJ)',1);
insert into city(name,fk_country) values('Rio do Antônio (BA)',1);
insert into city(name,fk_country) values('Rio do Campo (SC)',1);
insert into city(name,fk_country) values('Rio Doce (MG)',1);
insert into city(name,fk_country) values('Rio do Fogo (RN)',1);
insert into city(name,fk_country) values('Rio do Oeste (SC)',1);
insert into city(name,fk_country) values('Rio do Pires (BA)',1);
insert into city(name,fk_country) values('Rio do Prado (MG)',1);
insert into city(name,fk_country) values('Rio dos Bois (TO)',1);
insert into city(name,fk_country) values('Rio dos Cedros (SC)',1);
insert into city(name,fk_country) values('Rio dos Índios (RS)',1);
insert into city(name,fk_country) values('Rio do Sul (SC)',1);
insert into city(name,fk_country) values('Rio Espera (MG)',1);
insert into city(name,fk_country) values('Rio Formoso (PE)',1);
insert into city(name,fk_country) values('Rio Fortuna (SC)',1);
insert into city(name,fk_country) values('Rio Grande (RS)',1);
insert into city(name,fk_country) values('Rio Grande da Serra (SP)',1);
insert into city(name,fk_country) values('Rio Grande do Piauí (PI)',1);
insert into city(name,fk_country) values('Riolândia (SP)',1);
insert into city(name,fk_country) values('Rio Largo (AL)',1);
insert into city(name,fk_country) values('Rio Manso (MG)',1);
insert into city(name,fk_country) values('Santo Antônio do Rio Abaixo (MG)',1);
insert into city(name,fk_country) values('Santo Antônio dos Lopes (MA)',1);
insert into city(name,fk_country) values('Santo Antônio dos Milagres (PI)',1);
insert into city(name,fk_country) values('Santo Antônio do Sudoeste (PR)',1);
insert into city(name,fk_country) values('Santo Antônio do Tauá (PA)',1);
insert into city(name,fk_country) values('Santo Augusto (RS)',1);
insert into city(name,fk_country) values('Santo Cristo (RS)',1);
insert into city(name,fk_country) values('Santo Estêvão (BA)',1);
insert into city(name,fk_country) values('Santo Expedito (SP)',1);
insert into city(name,fk_country) values('Santo Expedito do Sul (RS)',1);
insert into city(name,fk_country) values('Santo Hipólito (MG)',1);
insert into city(name,fk_country) values('Santo Inácio (PR)',1);
insert into city(name,fk_country) values('Santo Inácio do Piauí (PI)',1);
insert into city(name,fk_country) values('Santópolis do Aguapeí (SP)',1);
insert into city(name,fk_country) values('Santos (SP)',1);
insert into city(name,fk_country) values('Santos Dumont (MG)',1);
insert into city(name,fk_country) values('São Benedito (CE)',1);
insert into city(name,fk_country) values('São Benedito do Rio Preto (MA)',1);
insert into city(name,fk_country) values('São Benedito do Sul (PE)',1);
insert into city(name,fk_country) values('São Bento (MA)',1);
insert into city(name,fk_country) values('São Bento (PB)',1);
insert into city(name,fk_country) values('São Bento Abade (MG)',1);
insert into city(name,fk_country) values('São Bento de Pombal (PB)',1);
insert into city(name,fk_country) values('São Bento do Norte (RN)',1);
insert into city(name,fk_country) values('São Bento do Sapucaí (SP)',1);
insert into city(name,fk_country) values('São Bento do Sul (SC)',1);
insert into city(name,fk_country) values('São Bento do Tocantins (TO)',1);
insert into city(name,fk_country) values('São Bento do Trairi (RN)',1);
insert into city(name,fk_country) values('São Bento do Una (PE)',1);
insert into city(name,fk_country) values('São Bernardino (SC)',1);
insert into city(name,fk_country) values('São Bernardo (MA)',1);
insert into city(name,fk_country) values('São Bernardo do Campo (SP)',1);
insert into city(name,fk_country) values('São Bonifácio (SC)',1);
insert into city(name,fk_country) values('São Borja (RS)',1);
insert into city(name,fk_country) values('São Brás (AL)',1);
insert into city(name,fk_country) values('São Brás do Suaçuí (MG)',1);
insert into city(name,fk_country) values('São Braz do Piauí (PI)',1);
insert into city(name,fk_country) values('São Caetano (PE)',1);
insert into city(name,fk_country) values('São Caetano de Odivelas (PA)',1);
insert into city(name,fk_country) values('São Caetano do Sul (SP)',1);
insert into city(name,fk_country) values('São Carlos (SC)',1);
insert into city(name,fk_country) values('São Carlos (SP)',1);
insert into city(name,fk_country) values('São Carlos do Ivaí (PR)',1);
insert into city(name,fk_country) values('São Cristóvão (SE)',1);
insert into city(name,fk_country) values('São Cristóvão do Sul (SC)',1);
insert into city(name,fk_country) values('São Desidério (BA)',1);
insert into city(name,fk_country) values('São Domingos (BA)',1);
insert into city(name,fk_country) values('São Domingos (GO)',1);
insert into city(name,fk_country) values('São Domingos (PB)',1);
insert into city(name,fk_country) values('São Domingos (SC)',1);
insert into city(name,fk_country) values('São Domingos (SE)',1);
insert into city(name,fk_country) values('São Domingos das Dores (MG)',1);
insert into city(name,fk_country) values('São Domingos do Araguaia (PA)',1);
insert into city(name,fk_country) values('São Domingos do Azeitão (MA)',1);
insert into city(name,fk_country) values('São Domingos do Capim (PA)',1);
insert into city(name,fk_country) values('São Domingos do Cariri (PB)',1);
insert into city(name,fk_country) values('São Domingos do Maranhão (MA)',1);
insert into city(name,fk_country) values('São Domingos do Norte (ES)',1);
insert into city(name,fk_country) values('São Domingos do Prata (MG)',1);
insert into city(name,fk_country) values('São Domingos do Sul (RS)',1);
insert into city(name,fk_country) values('São Felipe (BA)',1);
insert into city(name,fk_country) values('São Felipe d''Oeste (RO)',1);
insert into city(name,fk_country) values('São Félix (BA)',1);
insert into city(name,fk_country) values('São Félix de Balsas (MA)',1);
insert into city(name,fk_country) values('São Félix de Minas (MG)',1);
insert into city(name,fk_country) values('São Félix do Araguaia (MT)',1);
insert into city(name,fk_country) values('São Félix do Coribe (BA)',1);
insert into city(name,fk_country) values('São Félix do Piauí (PI)',1);
insert into city(name,fk_country) values('São Félix do Tocantins (TO)',1);
insert into city(name,fk_country) values('São Félix do Xingu (PA)',1);
insert into city(name,fk_country) values('São Fernando (RN)',1);
insert into city(name,fk_country) values('São Fidélis (RJ)',1);
insert into city(name,fk_country) values('São Francisco (MG)',1);
insert into city(name,fk_country) values('São Francisco (PB)',1);
insert into city(name,fk_country) values('São Francisco (SE)',1);
insert into city(name,fk_country) values('São Francisco (SP)',1);
insert into city(name,fk_country) values('São Francisco de Assis (RS)',1);
insert into city(name,fk_country) values('São Francisco de Assis do Piauí (PI)',1);
insert into city(name,fk_country) values('São Francisco de Goiás (GO)',1);
insert into city(name,fk_country) values('São Francisco de Itabapoana (RJ)',1);
insert into city(name,fk_country) values('São Francisco de Paula (MG)',1);
insert into city(name,fk_country) values('São Francisco de Paula (RS)',1);
insert into city(name,fk_country) values('São Francisco de Sales (MG)',1);
insert into city(name,fk_country) values('São Francisco do Brejão (MA)',1);
insert into city(name,fk_country) values('São Francisco do Conde (BA)',1);
insert into city(name,fk_country) values('São Francisco do Glória (MG)',1);
insert into city(name,fk_country) values('São Francisco do Guaporé (RO)',1);
insert into city(name,fk_country) values('São Francisco do Maranhão (MA)',1);
insert into city(name,fk_country) values('São Francisco do Oeste (RN)',1);
insert into city(name,fk_country) values('São Francisco do Pará (PA)',1);
insert into city(name,fk_country) values('São Francisco do Piauí (PI)',1);
insert into city(name,fk_country) values('São Francisco do Sul (SC)',1);
insert into city(name,fk_country) values('São Gabriel (BA)',1);
insert into city(name,fk_country) values('São Gabriel (RS)',1);
insert into city(name,fk_country) values('São Gabriel da Cachoeira (AM)',1);
insert into city(name,fk_country) values('São Gabriel da Palha (ES)',1);
insert into city(name,fk_country) values('São Gabriel do Oeste (MS)',1);
insert into city(name,fk_country) values('São Geraldo (MG)',1);
insert into city(name,fk_country) values('São Geraldo da Piedade (MG)',1);
insert into city(name,fk_country) values('São Geraldo do Araguaia (PA)',1);
insert into city(name,fk_country) values('São Geraldo do Baixio (MG)',1);
insert into city(name,fk_country) values('São Gonçalo (RJ)',1);
insert into city(name,fk_country) values('São Gonçalo do Abaeté (MG)',1);
insert into city(name,fk_country) values('São Gonçalo do Amarante (CE)',1);
insert into city(name,fk_country) values('São Gonçalo do Amarante (RN)',1);
insert into city(name,fk_country) values('São Gonçalo do Gurgueia (PI)',1);
insert into city(name,fk_country) values('São Gonçalo do Pará (MG)',1);
insert into city(name,fk_country) values('São Gonçalo do Piauí (PI)',1);
insert into city(name,fk_country) values('São Gonçalo do Rio Abaixo (MG)',1);
insert into city(name,fk_country) values('São Gonçalo do Rio Preto (MG)',1);
insert into city(name,fk_country) values('São Gonçalo do Sapucaí (MG)',1);
insert into city(name,fk_country) values('São Gonçalo dos Campos (BA)',1);
insert into city(name,fk_country) values('São Gotardo (MG)',1);
insert into city(name,fk_country) values('São Jerônimo (RS)',1);
insert into city(name,fk_country) values('São Jerônimo da Serra (PR)',1);
insert into city(name,fk_country) values('São João (PE)',1);
insert into city(name,fk_country) values('São João (PR)',1);
insert into city(name,fk_country) values('São João Batista (MA)',1);
insert into city(name,fk_country) values('São João Batista (SC)',1);
insert into city(name,fk_country) values('São João Batista do Glória (MG)',1);
insert into city(name,fk_country) values('São João da Baliza (RR)',1);
insert into city(name,fk_country) values('São João da Barra (RJ)',1);
insert into city(name,fk_country) values('São João da Boa Vista (SP)',1);
insert into city(name,fk_country) values('São João da Canabrava (PI)',1);
insert into city(name,fk_country) values('São João da Fronteira (PI)',1);
insert into city(name,fk_country) values('São João da Lagoa (MG)',1);
insert into city(name,fk_country) values('São João d''Aliança (GO)',1);
insert into city(name,fk_country) values('São João da Mata (MG)',1);
insert into city(name,fk_country) values('São João da Paraúna (GO)',1);
insert into city(name,fk_country) values('São João da Ponta (PA)',1);
insert into city(name,fk_country) values('São João da Ponte (MG)',1);
insert into city(name,fk_country) values('São João das Duas Pontes (SP)',1);
insert into city(name,fk_country) values('São João da Serra (PI)',1);
insert into city(name,fk_country) values('São João das Missões (MG)',1);
insert into city(name,fk_country) values('São João da Urtiga (RS)',1);
insert into city(name,fk_country) values('São João da Varjota (PI)',1);
insert into city(name,fk_country) values('São João de Iracema (SP)',1);
insert into city(name,fk_country) values('São João del-Rei (MG)',1);
insert into city(name,fk_country) values('São João de Meriti (RJ)',1);
insert into city(name,fk_country) values('São João de Pirabas (PA)',1);
insert into city(name,fk_country) values('São João do Araguaia (PA)',1);
insert into city(name,fk_country) values('São João do Arraial (PI)',1);
insert into city(name,fk_country) values('São João do Caiuá (PR)',1);
insert into city(name,fk_country) values('São João do Cariri (PB)',1);
insert into city(name,fk_country) values('São João do Caru (MA)',1);
insert into city(name,fk_country) values('São João do Itaperiú (SC)',1);
insert into city(name,fk_country) values('São João do Ivaí (PR)',1);
insert into city(name,fk_country) values('São João do Jaguaribe (CE)',1);
insert into city(name,fk_country) values('São João do Manhuaçu (MG)',1);
insert into city(name,fk_country) values('São João do Manteninha (MG)',1);
insert into city(name,fk_country) values('São João do Oeste (SC)',1);
insert into city(name,fk_country) values('São João do Oriente (MG)',1);
insert into city(name,fk_country) values('São João do Pacuí (MG)',1);
insert into city(name,fk_country) values('São João do Paraíso (MA)',1);
insert into city(name,fk_country) values('São João do Paraíso (MG)',1);
insert into city(name,fk_country) values('São João do Pau-d''Alho (SP)',1);
insert into city(name,fk_country) values('São João do Piauí (PI)',1);
insert into city(name,fk_country) values('São João do Polêsine (RS)',1);
insert into city(name,fk_country) values('São João do Rio do Peixe (PB)',1);
insert into city(name,fk_country) values('São João do Sabugi (RN)',1);
insert into city(name,fk_country) values('São João do Soter (MA)',1);
insert into city(name,fk_country) values('São João dos Patos (MA)',1);
insert into city(name,fk_country) values('São João do Sul (SC)',1);
insert into city(name,fk_country) values('São João do Tigre (PB)',1);
insert into city(name,fk_country) values('São João do Triunfo (PR)',1);
insert into city(name,fk_country) values('São João Evangelista (MG)',1);
insert into city(name,fk_country) values('São João Nepomuceno (MG)',1);
insert into city(name,fk_country) values('São Joaquim (SC)',1);
insert into city(name,fk_country) values('São Joaquim da Barra (SP)',1);
insert into city(name,fk_country) values('São Joaquim de Bicas (MG)',1);
insert into city(name,fk_country) values('São Joaquim do Monte (PE)',1);
insert into city(name,fk_country) values('São Jorge (RS)',1);
insert into city(name,fk_country) values('São Jorge d''Oeste (PR)',1);
insert into city(name,fk_country) values('São Jorge do Ivaí (PR)',1);
insert into city(name,fk_country) values('São Jorge do Patrocínio (PR)',1);
insert into city(name,fk_country) values('São José (SC)',1);
insert into city(name,fk_country) values('São José da Barra (MG)',1);
insert into city(name,fk_country) values('São José da Bela Vista (SP)',1);
insert into city(name,fk_country) values('São José da Boa Vista (PR)',1);
insert into city(name,fk_country) values('São José da Coroa Grande (PE)',1);
insert into city(name,fk_country) values('São José da Lagoa Tapada (PB)',1);
insert into city(name,fk_country) values('São José da Laje (AL)',1);
insert into city(name,fk_country) values('São José da Lapa (MG)',1);
insert into city(name,fk_country) values('São José da Safira (MG)',1);
insert into city(name,fk_country) values('São José das Missões (RS)',1);
insert into city(name,fk_country) values('São José das Palmeiras (PR)',1);
insert into city(name,fk_country) values('São José da Tapera (AL)',1);
insert into city(name,fk_country) values('São José da Varginha (MG)',1);
insert into city(name,fk_country) values('São José da Vitória (BA)',1);
insert into city(name,fk_country) values('São José de Caiana (PB)',1);
insert into city(name,fk_country) values('São José de Espinharas (PB)',1);
insert into city(name,fk_country) values('São José de Mipibu (RN)',1);
insert into city(name,fk_country) values('São José de Piranhas (PB)',1);
insert into city(name,fk_country) values('São José de Princesa (PB)',1);
insert into city(name,fk_country) values('São José de Ribamar (MA)',1);
insert into city(name,fk_country) values('São José de Ubá (RJ)',1);
insert into city(name,fk_country) values('São José do Alegre (MG)',1);
insert into city(name,fk_country) values('São José do Barreiro (SP)',1);
insert into city(name,fk_country) values('São José do Belmonte (PE)',1);
insert into city(name,fk_country) values('São José do Bonfim (PB)',1);
insert into city(name,fk_country) values('São José do Brejo do Cruz (PB)',1);
insert into city(name,fk_country) values('São José do Calçado (ES)',1);
insert into city(name,fk_country) values('São José do Campestre (RN)',1);
insert into city(name,fk_country) values('São José do Cedro (SC)',1);
insert into city(name,fk_country) values('São José do Cerrito (SC)',1);
insert into city(name,fk_country) values('São José do Divino (MG)',1);
insert into city(name,fk_country) values('São José do Divino (PI)',1);
insert into city(name,fk_country) values('São José do Egito (PE)',1);
insert into city(name,fk_country) values('São José do Goiabal (MG)',1);
insert into city(name,fk_country) values('São José do Herval (RS)',1);
insert into city(name,fk_country) values('São José do Hortêncio (RS)',1);
insert into city(name,fk_country) values('São José do Inhacorá (RS)',1);
insert into city(name,fk_country) values('São José do Jacuípe (BA)',1);
insert into city(name,fk_country) values('São José do Jacuri (MG)',1);
insert into city(name,fk_country) values('São José do Mantimento (MG)',1);
insert into city(name,fk_country) values('São José do Norte (RS)',1);
insert into city(name,fk_country) values('São José do Ouro (RS)',1);
insert into city(name,fk_country) values('São José do Peixe (PI)',1);
insert into city(name,fk_country) values('São José do Piauí (PI)',1);
insert into city(name,fk_country) values('São José do Povo (MT)',1);
insert into city(name,fk_country) values('São José do Rio Claro (MT)',1);
insert into city(name,fk_country) values('São José do Rio Pardo (SP)',1);
insert into city(name,fk_country) values('São José do Rio Preto (SP)',1);
insert into city(name,fk_country) values('São José do Sabugi (PB)',1);
insert into city(name,fk_country) values('São José dos Ausentes (RS)',1);
insert into city(name,fk_country) values('São José dos Basílios (MA)',1);
insert into city(name,fk_country) values('São José dos Campos (SP)',1);
insert into city(name,fk_country) values('São José dos Cordeiros (PB)',1);
insert into city(name,fk_country) values('São José do Seridó (RN)',1);
insert into city(name,fk_country) values('São José dos Pinhais (PR)',1);
insert into city(name,fk_country) values('São José dos Quatro Marcos (MT)',1);
insert into city(name,fk_country) values('São José dos Ramos (PB)',1);
insert into city(name,fk_country) values('São José do Sul (RS)',1);
insert into city(name,fk_country) values('São José do Vale do Rio Preto (RJ)',1);
insert into city(name,fk_country) values('São José do Xingu (MT)',1);
insert into city(name,fk_country) values('São Julião (PI)',1);
insert into city(name,fk_country) values('São Leopoldo (RS)',1);
insert into city(name,fk_country) values('São Lourenço (MG)',1);
insert into city(name,fk_country) values('São Lourenço da Mata (PE)',1);
insert into city(name,fk_country) values('São Lourenço da Serra (SP)',1);
insert into city(name,fk_country) values('São Lourenço do Oeste (SC)',1);
insert into city(name,fk_country) values('São Lourenço do Piauí (PI)',1);
insert into city(name,fk_country) values('São Lourenço do Sul (RS)',1);
insert into city(name,fk_country) values('São Ludgero (SC)',1);
insert into city(name,fk_country) values('São Luís (MA)',1);
insert into city(name,fk_country) values('São Luís de Montes Belos (GO)',1);
insert into city(name,fk_country) values('São Luís do Curu (CE)',1);
insert into city(name,fk_country) values('São Luís do Norte (GO)',1);
insert into city(name,fk_country) values('São Luís do Piauí (PI)',1);
insert into city(name,fk_country) values('São Luís do Quitunde (AL)',1);
insert into city(name,fk_country) values('São Luiz (RR)',1);
insert into city(name,fk_country) values('São Luiz do Paraitinga (SP)',1);
insert into city(name,fk_country) values('São Luiz Gonzaga (RS)',1);
insert into city(name,fk_country) values('São Luís Gonzaga do Maranhão (MA)',1);
insert into city(name,fk_country) values('São Mamede (PB)',1);
insert into city(name,fk_country) values('São Manoel do Paraná (PR)',1);
insert into city(name,fk_country) values('São Manuel (SP)',1);
insert into city(name,fk_country) values('São Marcos (RS)',1);
insert into city(name,fk_country) values('São Martinho (RS)',1);
insert into city(name,fk_country) values('São Martinho (SC)',1);
insert into city(name,fk_country) values('São Martinho da Serra (RS)',1);
insert into city(name,fk_country) values('São Mateus (ES)',1);
insert into city(name,fk_country) values('São Mateus do Maranhão (MA)',1);
insert into city(name,fk_country) values('São Mateus do Sul (PR)',1);
insert into city(name,fk_country) values('São Miguel (RN)',1);
insert into city(name,fk_country) values('São Miguel Arcanjo (SP)',1);
insert into city(name,fk_country) values('São Miguel da Baixa Grande (PI)',1);
insert into city(name,fk_country) values('São Miguel da Boa Vista (SC)',1);
insert into city(name,fk_country) values('São Miguel das Matas (BA)',1);
insert into city(name,fk_country) values('São Miguel das Missões (RS)',1);
insert into city(name,fk_country) values('São Miguel de Taipu (PB)',1);
insert into city(name,fk_country) values('Tavares (RS)',1);
insert into city(name,fk_country) values('Tefé (AM)',1);
insert into city(name,fk_country) values('Teixeira (PB)',1);
insert into city(name,fk_country) values('Teixeira de Freitas (BA)',1);
insert into city(name,fk_country) values('Teixeira Soares (PR)',1);
insert into city(name,fk_country) values('Teixeiras (MG)',1);
insert into city(name,fk_country) values('Teixeirópolis (RO)',1);
insert into city(name,fk_country) values('Tejuçuoca (CE)',1);
insert into city(name,fk_country) values('Tejupá (SP)',1);
insert into city(name,fk_country) values('Telêmaco Borba (PR)',1);
insert into city(name,fk_country) values('Telha (SE)',1);
insert into city(name,fk_country) values('Tenente Ananias (RN)',1);
insert into city(name,fk_country) values('Tenente Laurentino Cruz (RN)',1);
insert into city(name,fk_country) values('Tenente Portela (RS)',1);
insert into city(name,fk_country) values('Tenório (PB)',1);
insert into city(name,fk_country) values('Teodoro Sampaio (BA)',1);
insert into city(name,fk_country) values('Teodoro Sampaio (SP)',1);
insert into city(name,fk_country) values('Teofilândia (BA)',1);
insert into city(name,fk_country) values('Teófilo Otoni (MG)',1);
insert into city(name,fk_country) values('Teolândia (BA)',1);
insert into city(name,fk_country) values('Teotônio Vilela (AL)',1);
insert into city(name,fk_country) values('Terenos (MS)',1);
insert into city(name,fk_country) values('Teresina (PI)',1);
insert into city(name,fk_country) values('Teresina de Goiás (GO)',1);
insert into city(name,fk_country) values('Teresópolis (RJ)',1);
insert into city(name,fk_country) values('Terezinha (PE)',1);
insert into city(name,fk_country) values('Terezópolis de Goiás (GO)',1);
insert into city(name,fk_country) values('Terra Alta (PA)',1);
insert into city(name,fk_country) values('Terra Boa (PR)',1);
insert into city(name,fk_country) values('Terra de Areia (RS)',1);
insert into city(name,fk_country) values('Terra Nova (BA)',1);
insert into city(name,fk_country) values('Terra Nova (PE)',1);
insert into city(name,fk_country) values('Terra Nova do Norte (MT)',1);
insert into city(name,fk_country) values('Terra Rica (PR)',1);
insert into city(name,fk_country) values('Terra Roxa (PR)',1);
insert into city(name,fk_country) values('Terra Roxa (SP)',1);
insert into city(name,fk_country) values('Terra Santa (PA)',1);
insert into city(name,fk_country) values('Tesouro (MT)',1);
insert into city(name,fk_country) values('Teutônia (RS)',1);
insert into city(name,fk_country) values('Theobroma (RO)',1);
insert into city(name,fk_country) values('Tianguá (CE)',1);
insert into city(name,fk_country) values('Tibagi (PR)',1);
insert into city(name,fk_country) values('Tibau do Sul (RN)',1);
insert into city(name,fk_country) values('Tibau (RN)',1);
insert into city(name,fk_country) values('Tietê (SP)',1);
insert into city(name,fk_country) values('Tigrinhos (SC)',1);
insert into city(name,fk_country) values('Tijucas (SC)',1);
insert into city(name,fk_country) values('Tijucas do Sul (PR)',1);
insert into city(name,fk_country) values('Timbaúba (PE)',1);
insert into city(name,fk_country) values('Timbaúba dos Batistas (RN)',1);
insert into city(name,fk_country) values('Timbé do Sul (SC)',1);
insert into city(name,fk_country) values('Timbiras (MA)',1);
insert into city(name,fk_country) values('Timbó (SC)',1);
insert into city(name,fk_country) values('Timbó Grande (SC)',1);
insert into city(name,fk_country) values('Timburi (SP)',1);
insert into city(name,fk_country) values('Timon (MA)',1);
insert into city(name,fk_country) values('Timóteo (MG)',1);
insert into city(name,fk_country) values('Tio Hugo (RS)',1);
insert into city(name,fk_country) values('Tiradentes (MG)',1);
insert into city(name,fk_country) values('Tiradentes do Sul (RS)',1);
insert into city(name,fk_country) values('Tiros (MG)',1);
insert into city(name,fk_country) values('Tobias Barreto (SE)',1);
insert into city(name,fk_country) values('Tocantínia (TO)',1);
insert into city(name,fk_country) values('Tocantinópolis (TO)',1);
insert into city(name,fk_country) values('Tocantins (MG)',1);
insert into city(name,fk_country) values('Tocos do Moji (MG)',1);
insert into city(name,fk_country) values('Toledo (MG)',1);
insert into city(name,fk_country) values('Toledo (PR)',1);
insert into city(name,fk_country) values('Tomar do Geru (SE)',1);
insert into city(name,fk_country) values('Tomazina (PR)',1);
insert into city(name,fk_country) values('Tombos (MG)',1);
insert into city(name,fk_country) values('Tomé-Açu (PA)',1);
insert into city(name,fk_country) values('Tonantins (AM)',1);
insert into city(name,fk_country) values('Toritama (PE)',1);
insert into city(name,fk_country) values('Torixoréu (MT)',1);
insert into city(name,fk_country) values('Toropi (RS)',1);
insert into city(name,fk_country) values('Torre de Pedra (SP)',1);
insert into city(name,fk_country) values('Torres (RS)',1);
insert into city(name,fk_country) values('Torrinha (SP)',1);
insert into city(name,fk_country) values('Umarizal (RN)',1);
insert into city(name,fk_country) values('Umbaúba (SE)',1);
insert into city(name,fk_country) values('Umburanas (BA)',1);
insert into city(name,fk_country) values('Umburatiba (MG)',1);
insert into city(name,fk_country) values('Umbuzeiro (PB)',1);
insert into city(name,fk_country) values('Umirim (CE)',1);
insert into city(name,fk_country) values('Umuarama (PR)',1);
insert into city(name,fk_country) values('Una (BA)',1);
insert into city(name,fk_country) values('Unaí (MG)',1);
insert into city(name,fk_country) values('União (PI)',1);
insert into city(name,fk_country) values('União da Serra (RS)',1);
insert into city(name,fk_country) values('União da Vitória (PR)',1);
insert into city(name,fk_country) values('União de Minas (MG)',1);
insert into city(name,fk_country) values('União do Oeste (SC)',1);
insert into city(name,fk_country) values('União dos Palmares (AL)',1);
insert into city(name,fk_country) values('União do Sul (MT)',1);
insert into city(name,fk_country) values('União Paulista (SP)',1);
insert into city(name,fk_country) values('Uniflor (PR)',1);
insert into city(name,fk_country) values('Unistalda (RS)',1);
insert into city(name,fk_country) values('Upanema (RN)',1);
insert into city(name,fk_country) values('Uraí (PR)',1);
insert into city(name,fk_country) values('Urandi (BA)',1);
insert into city(name,fk_country) values('Urânia (SP)',1);
insert into city(name,fk_country) values('Vassouras (RJ)',1);
insert into city(name,fk_country) values('Vazante (MG)',1);
insert into city(name,fk_country) values('Venâncio Aires (RS)',1);
insert into city(name,fk_country) values('Venda Nova do Imigrante (ES)',1);
insert into city(name,fk_country) values('Venha-Ver (RN)',1);
insert into city(name,fk_country) values('Ventania (PR)',1);
insert into city(name,fk_country) values('Venturosa (PE)',1);
insert into city(name,fk_country) values('Vera (MT)',1);
insert into city(name,fk_country) values('Vera Cruz (BA)',1);
insert into city(name,fk_country) values('Vera Cruz (RN)',1);
insert into city(name,fk_country) values('Vera Cruz (RS)',1);
insert into city(name,fk_country) values('Vera Cruz (SP)',1);
insert into city(name,fk_country) values('Vera Cruz do Oeste (PR)',1);
insert into city(name,fk_country) values('Vera Mendes (PI)',1);
insert into city(name,fk_country) values('Veranópolis (RS)',1);
insert into city(name,fk_country) values('Verdejante (PE)',1);
insert into city(name,fk_country) values('Verdelândia (MG)',1);
insert into city(name,fk_country) values('Verê (PR)',1);
insert into city(name,fk_country) values('Vereda (BA)',1);
insert into city(name,fk_country) values('Veredinha (MG)',1);
insert into city(name,fk_country) values('Veríssimo (MG)',1);
insert into city(name,fk_country) values('Vermelho Novo (MG)',1);
insert into city(name,fk_country) values('Vertente do Lério (PE)',1);
insert into city(name,fk_country) values('Vertentes (PE)',1);
insert into city(name,fk_country) values('Vespasiano (MG)',1);
insert into city(name,fk_country) values('Vespasiano Corrêa (RS)',1);
insert into city(name,fk_country) values('Viadutos (RS)',1);
insert into city(name,fk_country) values('Viamão (RS)',1);
insert into city(name,fk_country) values('Viana (ES)',1);
insert into city(name,fk_country) values('Viana (MA)',1);
insert into city(name,fk_country) values('Vianópolis (GO)',1);
insert into city(name,fk_country) values('Vicência (PE)',1);
insert into city(name,fk_country) values('Vicente Dutra (RS)',1);
insert into city(name,fk_country) values('Vicentina (MS)',1);
insert into city(name,fk_country) values('Vicentinópolis (GO)',1);
insert into city(name,fk_country) values('Viçosa (AL)',1);
insert into city(name,fk_country) values('Viçosa (MG)',1);
insert into city(name,fk_country) values('Viçosa (RN)',1);
insert into city(name,fk_country) values('Viçosa do Ceará (CE)',1);
insert into city(name,fk_country) values('Victor Graeff (RS)',1);
insert into city(name,fk_country) values('Vidal Ramos (SC)',1);
insert into city(name,fk_country) values('Videira (SC)',1);
insert into city(name,fk_country) values('Vieiras (MG)',1);
insert into city(name,fk_country) values('Vieirópolis (PB)',1);
insert into city(name,fk_country) values('Vigia (PA)',1);
insert into city(name,fk_country) values('Wanderley (BA)',1);
insert into city(name,fk_country) values('Wenceslau Braz (MG)',1);
insert into city(name,fk_country) values('Wenceslau Braz (PR)',1);
insert into city(name,fk_country) values('Xapuri (AC)',1);
insert into city(name,fk_country) values('Xavantina (SC)',1);
insert into city(name,fk_country) values('Xaxim (SC)',1);
insert into city(name,fk_country) values('Zé Doca (MA)',1);
insert into city(name,fk_country) values('Araçariguama (SP)',1);
insert into city(name,fk_country) values('Araçás (BA)',1);
insert into city(name,fk_country) values('Aracati (CE)',1);
insert into city(name,fk_country) values('Aracatu (BA)',1);
insert into city(name,fk_country) values('Araçatuba (SP)',1);
insert into city(name,fk_country) values('Araci (BA)',1);
insert into city(name,fk_country) values('Aracitaba (MG)',1);
insert into city(name,fk_country) values('Aracoiaba (CE)',1);
insert into city(name,fk_country) values('Araçoiaba (PE)',1);
insert into city(name,fk_country) values('Araçoiaba da Serra (SP)',1);
insert into city(name,fk_country) values('Aracruz (ES)',1);
insert into city(name,fk_country) values('Araçu (GO)',1);
insert into city(name,fk_country) values('Araçuaí (MG)',1);
insert into city(name,fk_country) values('Aragarças (GO)',1);
insert into city(name,fk_country) values('Aragoiânia (GO)',1);
insert into city(name,fk_country) values('Aragominas (TO)',1);
insert into city(name,fk_country) values('Araguacema (TO)',1);
insert into city(name,fk_country) values('Araguaçu (TO)',1);
insert into city(name,fk_country) values('Araguaiana (MT)',1);
insert into city(name,fk_country) values('Araguaína (TO)',1);
insert into city(name,fk_country) values('Araguainha (MT)',1);
insert into city(name,fk_country) values('Araguanã (MA)',1);
insert into city(name,fk_country) values('Araguanã (TO)',1);
insert into city(name,fk_country) values('Araguapaz (GO)',1);
insert into city(name,fk_country) values('Araguari (MG)',1);
insert into city(name,fk_country) values('Araguatins (TO)',1);
insert into city(name,fk_country) values('Araioses (MA)',1);
insert into city(name,fk_country) values('Aral Moreira (MS)',1);
insert into city(name,fk_country) values('Aramari (BA)',1);
insert into city(name,fk_country) values('Arambaré (RS)',1);
insert into city(name,fk_country) values('Arame (MA)',1);
insert into city(name,fk_country) values('Aramina (SP)',1);
insert into city(name,fk_country) values('Arandu (SP)',1);
insert into city(name,fk_country) values('Arantina (MG)',1);
insert into city(name,fk_country) values('Arapeí (SP)',1);
insert into city(name,fk_country) values('Arapiraca (AL)',1);
insert into city(name,fk_country) values('Arapoema (TO)',1);
insert into city(name,fk_country) values('Araponga (MG)',1);
insert into city(name,fk_country) values('Arapongas (PR)',1);
insert into city(name,fk_country) values('Araporã (MG)',1);
insert into city(name,fk_country) values('Arapoti (PR)',1);
insert into city(name,fk_country) values('Arapuá (MG)',1);
insert into city(name,fk_country) values('Arapuã (PR)',1);
insert into city(name,fk_country) values('Araputanga (MT)',1);
insert into city(name,fk_country) values('Araquari (SC)',1);
insert into city(name,fk_country) values('Arara (PB)',1);
insert into city(name,fk_country) values('Araranguá (SC)',1);
insert into city(name,fk_country) values('Araraquara (SP)',1);
insert into city(name,fk_country) values('Araras (SP)',1);
insert into city(name,fk_country) values('Ararendá (CE)',1);
insert into city(name,fk_country) values('Arari (MA)',1);
insert into city(name,fk_country) values('Araricá (RS)',1);
insert into city(name,fk_country) values('Araripe (CE)',1);
insert into city(name,fk_country) values('Araripina (PE)',1);
insert into city(name,fk_country) values('Araruama (RJ)',1);
insert into city(name,fk_country) values('Araruna (PB)',1);
insert into city(name,fk_country) values('Araruna (PR)',1);
insert into city(name,fk_country) values('Arataca (BA)',1);
insert into city(name,fk_country) values('Aratiba (RS)',1);
insert into city(name,fk_country) values('Aratuba (CE)',1);
insert into city(name,fk_country) values('Aratuípe (BA)',1);
insert into city(name,fk_country) values('Arauá (SE)',1);
insert into city(name,fk_country) values('Araucária (PR)',1);
insert into city(name,fk_country) values('Araújos (MG)',1);
insert into city(name,fk_country) values('Araxá (MG)',1);
insert into city(name,fk_country) values('Arceburgo (MG)',1);
insert into city(name,fk_country) values('Arco-Íris (SP)',1);
insert into city(name,fk_country) values('Arcos (MG)',1);
insert into city(name,fk_country) values('Arcoverde (PE)',1);
insert into city(name,fk_country) values('Areado (MG)',1);
insert into city(name,fk_country) values('Areal (RJ)',1);
insert into city(name,fk_country) values('Arealva (SP)',1);
insert into city(name,fk_country) values('Areia (PB)',1);
insert into city(name,fk_country) values('Areia Branca (RN)',1);
insert into city(name,fk_country) values('Areia Branca (SE)',1);
insert into city(name,fk_country) values('Areia de Baraúnas (PB)',1);
insert into city(name,fk_country) values('Areial (PB)',1);
insert into city(name,fk_country) values('Areias (SP)',1);
insert into city(name,fk_country) values('Areiópolis (SP)',1);
insert into city(name,fk_country) values('Arenápolis (MT)',1);
insert into city(name,fk_country) values('Arenópolis (GO)',1);
insert into city(name,fk_country) values('Arês (RN)',1);
insert into city(name,fk_country) values('Argirita (MG)',1);
insert into city(name,fk_country) values('Aricanduva (MG)',1);
insert into city(name,fk_country) values('Arinos (MG)',1);
insert into city(name,fk_country) values('Aripuanã (MT)',1);
insert into city(name,fk_country) values('Ariquemes (RO)',1);
insert into city(name,fk_country) values('Ariranha (SP)',1);
insert into city(name,fk_country) values('Ariranha do Ivaí (PR)',1);
insert into city(name,fk_country) values('Armação dos Búzios (RJ)',1);
insert into city(name,fk_country) values('Armazém (SC)',1);
insert into city(name,fk_country) values('Arneiroz (CE)',1);
insert into city(name,fk_country) values('Aroazes (PI)',1);
insert into city(name,fk_country) values('Aroeiras (PB)',1);
insert into city(name,fk_country) values('Aroeiras do Itaim (PI)',1);
insert into city(name,fk_country) values('Arraial (PI)',1);
insert into city(name,fk_country) values('Arraial do Cabo (RJ)',1);
insert into city(name,fk_country) values('Arraias (TO)',1);
insert into city(name,fk_country) values('Arroio do Meio (RS)',1);
insert into city(name,fk_country) values('Arroio do Padre (RS)',1);
insert into city(name,fk_country) values('Arroio do Sal (RS)',1);
insert into city(name,fk_country) values('Arroio dos Ratos (RS)',1);
insert into city(name,fk_country) values('Arroio do Tigre (RS)',1);
insert into city(name,fk_country) values('Arroio Grande (RS)',1);
insert into city(name,fk_country) values('Arroio Trinta (SC)',1);
insert into city(name,fk_country) values('Artur Nogueira (SP)',1);
insert into city(name,fk_country) values('Aruanã (GO)',1);
insert into city(name,fk_country) values('Arujá (SP)',1);
insert into city(name,fk_country) values('Arvoredo (SC)',1);
insert into city(name,fk_country) values('Arvorezinha (RS)',1);
insert into city(name,fk_country) values('Ascurra (SC)',1);
insert into city(name,fk_country) values('Aspásia (SP)',1);
insert into city(name,fk_country) values('Assaí (PR)',1);
insert into city(name,fk_country) values('Assaré (CE)',1);
insert into city(name,fk_country) values('Assis (SP)',1);
insert into city(name,fk_country) values('Assis Brasil (AC)',1);
insert into city(name,fk_country) values('Assis Chateaubriand (PR)',1);
insert into city(name,fk_country) values('Assunção do Piauí (PI)',1);
insert into city(name,fk_country) values('Assunção (PB)',1);
insert into city(name,fk_country) values('Astolfo Dutra (MG)',1);
insert into city(name,fk_country) values('Astorga (PR)',1);
insert into city(name,fk_country) values('Atalaia (AL)',1);
insert into city(name,fk_country) values('Atalaia (PR)',1);
insert into city(name,fk_country) values('Atalaia do Norte (AM)',1);
insert into city(name,fk_country) values('Atalanta (SC)',1);
insert into city(name,fk_country) values('Ataleia (MG)',1);
insert into city(name,fk_country) values('Atibaia (SP)',1);
insert into city(name,fk_country) values('Atílio Vivácqua (ES)',1);
insert into city(name,fk_country) values('Augustinópolis (TO)',1);
insert into city(name,fk_country) values('Augusto Corrêa (PA)',1);
insert into city(name,fk_country) values('Augusto de Lima (MG)',1);
insert into city(name,fk_country) values('Augusto Pestana (RS)',1);
insert into city(name,fk_country) values('Áurea (RS)',1);
insert into city(name,fk_country) values('Aurelino Leal (BA)',1);
insert into city(name,fk_country) values('Auriflama (SP)',1);
insert into city(name,fk_country) values('Aurilândia (GO)',1);
insert into city(name,fk_country) values('Aurora (CE)',1);
insert into city(name,fk_country) values('Aurora (SC)',1);
insert into city(name,fk_country) values('Aurora do Pará (PA)',1);
insert into city(name,fk_country) values('Aurora do Tocantins (TO)',1);
insert into city(name,fk_country) values('Autazes (AM)',1);
insert into city(name,fk_country) values('Avaí (SP)',1);
insert into city(name,fk_country) values('Avanhandava (SP)',1);
insert into city(name,fk_country) values('Avaré (SP)',1);
insert into city(name,fk_country) values('Aveiro (PA)',1);
insert into city(name,fk_country) values('Avelino Lopes (PI)',1);
insert into city(name,fk_country) values('Avelinópolis (GO)',1);
insert into city(name,fk_country) values('Axixá (MA)',1);
insert into city(name,fk_country) values('Bom Jesus do Sul (PR)',1);
insert into city(name,fk_country) values('Bom Jesus do Tocantins (PA)',1);
insert into city(name,fk_country) values('Bom Jesus do Tocantins (TO)',1);
insert into city(name,fk_country) values('Bom Lugar (MA)',1);
insert into city(name,fk_country) values('Bom Princípio (RS)',1);
insert into city(name,fk_country) values('Bom Princípio do Piauí (PI)',1);
insert into city(name,fk_country) values('Bom Progresso (RS)',1);
insert into city(name,fk_country) values('Bom Repouso (MG)',1);
insert into city(name,fk_country) values('Bom Retiro (SC)',1);
insert into city(name,fk_country) values('Bom Retiro do Sul (RS)',1);
insert into city(name,fk_country) values('Bom Sucesso (MG)',1);
insert into city(name,fk_country) values('Bom Sucesso (PB)',1);
insert into city(name,fk_country) values('Bom Sucesso (PR)',1);
insert into city(name,fk_country) values('Bom Sucesso de Itararé (SP)',1);
insert into city(name,fk_country) values('Bom Sucesso do Sul (PR)',1);
insert into city(name,fk_country) values('Bonfim (MG)',1);
insert into city(name,fk_country) values('Bonfim (RR)',1);
insert into city(name,fk_country) values('Bonfim do Piauí (PI)',1);
insert into city(name,fk_country) values('Bonfinópolis (GO)',1);
insert into city(name,fk_country) values('Bonfinópolis de Minas (MG)',1);
insert into city(name,fk_country) values('Boninal (BA)',1);
insert into city(name,fk_country) values('Bonito (BA)',1);
insert into city(name,fk_country) values('Bonito (MS)',1);
insert into city(name,fk_country) values('Bonito (PA)',1);
insert into city(name,fk_country) values('Bonito (PE)',1);
insert into city(name,fk_country) values('Bonito de Minas (MG)',1);
insert into city(name,fk_country) values('Bonito de Santa Fé (PB)',1);
insert into city(name,fk_country) values('Bonópolis (GO)',1);
insert into city(name,fk_country) values('Boqueirão (PB)',1);
insert into city(name,fk_country) values('Boqueirão do Leão (RS)',1);
insert into city(name,fk_country) values('Boqueirão do Piauí (PI)',1);
insert into city(name,fk_country) values('Boquim (SE)',1);
insert into city(name,fk_country) values('Boquira (BA)',1);
insert into city(name,fk_country) values('Borá (SP)',1);
insert into city(name,fk_country) values('Boraceia (SP)',1);
insert into city(name,fk_country) values('Borba (AM)',1);
insert into city(name,fk_country) values('Borborema (PB)',1);
insert into city(name,fk_country) values('Borborema (SP)',1);
insert into city(name,fk_country) values('Borda da Mata (MG)',1);
insert into city(name,fk_country) values('Borebi (SP)',1);
insert into city(name,fk_country) values('Borrazópolis (PR)',1);
insert into city(name,fk_country) values('Bossoroca (RS)',1);
insert into city(name,fk_country) values('Botelhos (MG)',1);
insert into city(name,fk_country) values('Botucatu (SP)',1);
insert into city(name,fk_country) values('Botumirim (MG)',1);
insert into city(name,fk_country) values('Botuporã (BA)',1);
insert into city(name,fk_country) values('Botuverá (SC)',1);
insert into city(name,fk_country) values('Bozano (RS)',1);
insert into city(name,fk_country) values('Braço do Norte (SC)',1);
insert into city(name,fk_country) values('Braço do Trombudo (SC)',1);
insert into city(name,fk_country) values('Braga (RS)',1);
insert into city(name,fk_country) values('Bragança (PA)',1);
insert into city(name,fk_country) values('Bragança Paulista (SP)',1);
insert into city(name,fk_country) values('Braganey (PR)',1);
insert into city(name,fk_country) values('Branquinha (AL)',1);
insert into city(name,fk_country) values('Brasilândia (MS)',1);
insert into city(name,fk_country) values('Brasilândia de Minas (MG)',1);
insert into city(name,fk_country) values('Brasilândia do Sul (PR)',1);
insert into city(name,fk_country) values('Brasilândia do Tocantins (TO)',1);
insert into city(name,fk_country) values('Brasileia (AC)',1);
insert into city(name,fk_country) values('Brasileira (PI)',1);
insert into city(name,fk_country) values('Brasília de Minas (MG)',1);
insert into city(name,fk_country) values('Brasil Novo (PA)',1);
insert into city(name,fk_country) values('Brasnorte (MT)',1);
insert into city(name,fk_country) values('Brasópolis (MG)',1);
insert into city(name,fk_country) values('Brás Pires (MG)',1);
insert into city(name,fk_country) values('Braúna (SP)',1);
insert into city(name,fk_country) values('Braúnas (MG)',1);
insert into city(name,fk_country) values('Brazabrantes (GO)',1);
insert into city(name,fk_country) values('Brejão (PE)',1);
insert into city(name,fk_country) values('Brejetuba (ES)',1);
insert into city(name,fk_country) values('Brejinho (PE)',1);
insert into city(name,fk_country) values('Brejinho (RN)',1);
insert into city(name,fk_country) values('Brejinho de Nazaré (TO)',1);
insert into city(name,fk_country) values('Brejo (MA)',1);
insert into city(name,fk_country) values('Brejo Alegre (SP)',1);
insert into city(name,fk_country) values('Brejo da Madre de Deus (PE)',1);
insert into city(name,fk_country) values('Brejo de Areia (MA)',1);
insert into city(name,fk_country) values('Brejo do Cruz (PB)',1);
insert into city(name,fk_country) values('Brejo do Piauí (PI)',1);
insert into city(name,fk_country) values('Brejo dos Santos (PB)',1);
insert into city(name,fk_country) values('Brejões (BA)',1);
insert into city(name,fk_country) values('Brejo Grande (SE)',1);
insert into city(name,fk_country) values('Brejo Grande do Araguaia (PA)',1);
insert into city(name,fk_country) values('Brejolândia (BA)',1);
insert into city(name,fk_country) values('Brejo Santo (CE)',1);
insert into city(name,fk_country) values('Breu Branco (PA)',1);
insert into city(name,fk_country) values('Breves (PA)',1);
insert into city(name,fk_country) values('Britânia (GO)',1);
insert into city(name,fk_country) values('Brochier (RS)',1);
insert into city(name,fk_country) values('Brodowski (SP)',1);
insert into city(name,fk_country) values('Brotas (SP)',1);
insert into city(name,fk_country) values('Brotas de Macaúbas (BA)',1);
insert into city(name,fk_country) values('Brumadinho (MG)',1);
insert into city(name,fk_country) values('Brumado (BA)',1);
insert into city(name,fk_country) values('Brunópolis (SC)',1);
insert into city(name,fk_country) values('Brusque (SC)',1);
insert into city(name,fk_country) values('Bueno Brandão (MG)',1);
insert into city(name,fk_country) values('Buenópolis (MG)',1);
insert into city(name,fk_country) values('Buenos Aires (PE)',1);
insert into city(name,fk_country) values('Buerarema (BA)',1);
insert into city(name,fk_country) values('Bugre (MG)',1);
insert into city(name,fk_country) values('Buíque (PE)',1);
insert into city(name,fk_country) values('Bujari (AC)',1);
insert into city(name,fk_country) values('Bujaru (PA)',1);
insert into city(name,fk_country) values('Buri (SP)',1);
insert into city(name,fk_country) values('Buritama (SP)',1);
insert into city(name,fk_country) values('Buriti (MA)',1);
insert into city(name,fk_country) values('Buriti Alegre (GO)',1);
insert into city(name,fk_country) values('Buriti Bravo (MA)',1);
insert into city(name,fk_country) values('Buriticupu (MA)',1);
insert into city(name,fk_country) values('Buriti de Goiás (GO)',1);
insert into city(name,fk_country) values('Buriti dos Lopes (PI)',1);
insert into city(name,fk_country) values('Buriti dos Montes (PI)',1);
insert into city(name,fk_country) values('Buriti do Tocantins (TO)',1);
insert into city(name,fk_country) values('Buritinópolis (GO)',1);
insert into city(name,fk_country) values('Buritirama (BA)',1);
insert into city(name,fk_country) values('Buritirana (MA)',1);
insert into city(name,fk_country) values('Buritis (MG)',1);
insert into city(name,fk_country) values('Buritis (RO)',1);
insert into city(name,fk_country) values('Buritizal (SP)',1);